---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/complete-preparation-for-upgrade.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 'Configurez et gérez Storage Encryption, gérez les clés d"authentification et mettez fin aux relations SnapMirror lorsque vous utilisez ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Finalisez la préparation de la mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les licences ONTAP et la gestion du chiffrement du stockage à l'aide du gestionnaire de clés intégré (OKM). Vous pouvez également mettre en veille les relations SnapMirror.



== Découvrez les licences ONTAP

Chaque nœud du cluster doit avoir son propre fichier de licence NetApp (NLF).

Si vous ne disposez pas de NLF, les fonctions sous licence du cluster sont disponibles pour le nouveau contrôleur. Cependant, l'utilisation de fonctions sans licence sur le contrôleur peut vous mettre hors conformité avec votre contrat de licence. Vous devez donc installer le NLF pour le nouveau contrôleur une fois la mise à niveau terminée.

Consultez link:other-references.html["Références"] pour accéder au _NetApp Support Site_ où vous pouvez obtenir votre NLF. Les NLF sont disponibles dans la section _My Support_ sous _Software licenses_. Si le site ne propose pas les NLF dont vous avez besoin, contactez votre NetApp sales representative.

Pour des informations détaillées sur les licences ONTAP, consultez link:other-references.html["Références"] pour accéder au _System Administration Reference_.



== Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré

Utilisez le Gestionnaire de clés intégré (OKM) pour gérer les clés de chiffrement. Si l'OKM est configuré, vous devez enregistrer la phrase de passe et les données de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Notez la phrase de passe à l'échelle du cluster.
+
Il s'agit de la phrase secrète saisie lorsque le gestionnaire de clés intégré OKM a été configuré ou mis à jour via l'interface de ligne de commandes ou l'API REST.

. Vérifiez la phrase de passe et le fonctionnement du key-manager :
+
`security key-manager onboard sync`

+
Lorsque vous y êtes invité, saisissez la phrase secrète OKM à l'échelle du cluster que vous avez enregistrée à l'étape précédente.

. Vérifiez que cc-mode est activé en consultant le résultat de la commande suivante :
+
`security key-manager config show`

. Sauvegardez les informations du key-manager :
+
`security key-manager onboard show-backup`





== Facultativement, mettre en pause les relations SnapMirror

Avant de poursuivre l'opération, vous devez confirmer que toutes les relations SnapMirror sont suspendues. Lorsqu'une relation SnapMirror est mise en veille, elle reste suspension sur l'ensemble des redémarrages et basculements.

.Étapes
. Vérifier l'état de la relation SnapMirror sur le cluster destination :
+
`snapmirror show`

+
[NOTE]
====
Si l'état est « transfert », vous devez annuler ces transferts :
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'annulation échoue si la relation SnapMirror n'est pas à l'état « Transferring ».

. Arrêter toutes les relations entre le cluster :
+
`snapmirror quiesce -destination-vserver *`



.Et la suite ?
Après avoir préparé la mise à niveau, link:relocate-non-root-aggr-and-nas-data-lifs-node1-node2.html["déplacer les agrégats non racines et les LIF de données NAS appartenant au nœud1 vers le nœud2"].
