---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 'Déterminez si vous pouvez utiliser l"ARL, en conservant l"ancien châssis et les anciens disques du système pour la configuration de la mise à niveau.' 
---
= Instructions de mise à niveau des contrôleurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour savoir si vous pouvez utiliser le transfert d'agrégats (ARL), le conservation des anciens châssis et disques du système dépend de la configuration de la mise à niveau du système et de la version de ONTAP.



== Mises à niveau prises en charge pour l'ARL

La mise à niveau du contrôleur est prise en charge pour certaines configurations système. Consultez la link:decide-to-use-the-aggregate-relocation-guide.html#supported-systems["combinaisons de mise à niveau système prises en charge"] pour obtenir la liste des systèmes pris en charge et la version minimale d'ONTAP.

Si vous avez reçu un nouveau AFF A30, AFF A50, AFF A70, AFF A90, AFF A150, AFF A900, AFF C30, AFF C60, AFF C80, FAS2820 ou FAS9500 en tant que système complet, y compris un nouveau châssis, reportez-vous à link:other-references.html["Références"] pour accéder à _Utilisez les commandes « system controller replace » pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.8 ou une version ultérieure_.

La mise à niveau du contrôleur avec l'ARL est prise en charge sur les systèmes configurés avec les volumes SnapLock Enterprise et SnapLock Compliance.



== Clusters à 2 nœuds sans commutateur

Si vous mettez à niveau des nœuds dans un cluster sans commutateur à 2 nœuds, vous pouvez quitter le cluster sans commutateur tout en effectuant la mise à niveau. Il n'est pas nécessaire de les convertir en cluster commuté.



== Commutateurs connectés aux clusters

Si vous mettez à niveau des nœuds d'un cluster connecté à un commutateur de cluster, vous devez vérifier que la marque, le modèle, la version du firmware, le fichier RCF et la version de ONTAP exécutés sur le commutateur sont identiques à ceux exécutés sur le contrôleur de remplacement après la mise à niveau. Si nécessaire, vous devez effectuer la mise à niveau du commutateur avant de mettre à niveau les contrôleurs à l'aide de l'ARL.

Pour plus d'informations, voir link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Se connecter à un cluster relié par un commutateur"].



== Résoudre les problèmes

Vous pouvez être confronté à une défaillance lors de la mise à niveau de la paire de nœuds. Il est possible que le nœud tombe en panne, mais que les agrégats ne soient pas transférés ou que les LIF ne migrent pas. La cause de l'échec et sa solution dépendent du moment où l'échec s'est produit pendant la procédure de mise à niveau.

En cas de problème, reportez-vous à la link:aggregate-relocation-failures.html["Résoudre les problèmes"] section à la fin de la procédure pour plus d'informations et des solutions possibles. Les informations concernant les défaillances possibles sont répertoriées par phase de la procédure dans le link:overview-of-the-arl-upgrade.html["Séquence de mise à niveau ARL"].

Si vous ne trouvez pas de solution au problème rencontré, contactez le support technique.
