---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 'Vous pouvez mettre à niveau le matériel du contrôleur en convertissant un ancien système en un système de remplacement, en conservant l"ancien châssis et les anciens disques du système.' 
---
= En savoir plus sur cette procédure de mise à niveau ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs méthodes de relocalisation agrégée (ARL) pour mettre à niveau le matériel du contrôleur. Cette procédure décrit comment mettre à niveau les contrôleurs de stockage d'une paire HA en convertissant le système existant en système de remplacement, tout en conservant le châssis et les disques existants.

Le transfert d'agrégats tire parti de la configuration haute disponibilité et des communications d'interconnexion de cluster. Vous pouvez ainsi déplacer la propriété d'agrégats non racines d'un nœud vers un autre s'ils partagent le stockage au sein du même cluster.

Pendant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, délocalisant ainsi la propriété des agrégats non racines. Vous migrez les agrégats non racine entre les anciens nœuds de contrôleur. Une fois les nœuds de remplacement installés, vous migrez les agrégats non racines des anciens nœuds de contrôleur vers les nœuds de contrôleur de remplacement. Les données hébergées sur les nœuds que vous mettez à niveau sont accessibles lors de la procédure de mise à niveau. Vous migrez également les LIF de données entre les nœuds du cluster lorsque vous continuez.

Le matériel du contrôleur que vous remplacez dépend du type de modèle de système existant :

[cols="30,70"]
|===
| Si votre système existant est... | Alors... 


| AFF A250, AFF C250 | Remplacez les deux contrôleurs AFF A250 ou AFF C250 par les nouveaux contrôleurs et modules d'E/S. 


| AFF A800, AFF C800 | Remplacez les deux contrôleurs AFF A800 ou AFF C800 par les nouveaux contrôleurs et modules d'E/S. 


| AFF A220, AFF A200, AFF C190, FAS2620 ou FAS2720 | Remplacez le module de contrôleur de chaque nœud de l'ancien contrôleur par le nouveau. 


| AFF A700 OU FAS9000 | Remplacez le contrôleur et les modules NVRAM de chaque nœud de l'ancien contrôleur par les nouveaux modules. *Remarque* : vous n'avez pas besoin de déplacer, déconnecter ou reconnecter les cartes E/S, les câbles de données, les tiroirs disques et les disques. 
|===

NOTE: Les termes *node1* et *node2* sont utilisés uniquement comme référence aux noms de noeud dans ce document. Lorsque vous suivez la procédure, vous devez remplacer les noms réels de vos nœuds.



== Exigences et restrictions

Vous devez prendre en compte des facteurs importants avant de commencer votre procédure de mise à niveau.


NOTE: Vous devez vérifier toutes les informations importantes suivantes avant de commencer la procédure de mise à niveau.

* Cette procédure est complexe et suppose que vous avez des compétences avancées en administration de ONTAP. Vous devez également lire et comprendre le link:guidelines_for_upgrading_controllers_with_arl.html["directives pour la mise à niveau des contrôleurs"] et link:overview_of_the_arl_upgrade.html["Séquence de mise à niveau ARL"] avant de commencer la mise à niveau.
* Cette procédure suppose que le matériel de remplacement du contrôleur est nouveau et qu'il n'a pas été utilisé dans un autre système. Étapes requises pour préparer les contrôleurs utilisés avec le `wipeconfig` la commande n'est pas incluse dans cette procédure. Vous devez contacter le support technique si le matériel de remplacement de contrôleur était précédemment utilisé dans un autre cluster ONTAP ou en tant que système à un seul nœud autonome.
* Vous pouvez suivre cette procédure pour mettre à niveau le matériel du contrôleur dans des clusters de plus de deux nœuds. Cependant, il est nécessaire d'effectuer séparément la procédure pour chaque paire haute disponibilité du cluster.
* Si vous disposez d'un commutateur qui n'est pas pris en charge par la version ONTAP et le système de remplacement vers lequel vous effectuez la mise à niveau, reportez-vous à la section link:other_references.html["Références"] Pour accéder au _Hardware Universe_.
* Les systèmes AFF A250 et AFF C250 utilisent des ports 10/25 GbE embarqués pour l'interconnexion des clusters. Pour migrer des clusters sans commutateur à deux nœuds d'un système AFF A250 ou AFF C250 vers un système AFF A50, AFF A30, AFF C60 ou AFF C30, vous devez utiliser une carte X60132A 4 ports 10/25 GbE dans l'emplacement 1 des deux nœuds. Cela permet l'interconnexion des LIF de cluster vers un port temporaire de la plateforme cible.
* Les systèmes AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70 et FAS90 partagent des ports réseau 100 GbE pour les connexions au cluster et haute disponibilité. Ces systèmes peuvent prendre en charge des connexions de cluster 10 GbE ou 25 GbE avec les anciens switchs de cluster. Cependant, NetApp recommande de mettre à jour les vitesses de cluster 100 GbE lorsque les switchs 10 GbE et 25 GbE ne sont plus nécessaires. Pour plus d'informations, consultez les articles suivants de la base de connaissances :
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Comment configurer les ports de cluster 10G ou 25G dans une nouvelle configuration de cluster"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Comment convertir les ports de cluster 10G ou 25G existants en ports de cluster 40G ou 100G"^]


--
+
Si vous ne pouvez pas lier les ports e0a ou e0b du nœud existant aux ports de cluster du nouveau nœud, consultez les documents suivants pour plus d'informations :

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["Bugs NetApp ID de bug en ligne CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["Code de bogue en ligne de NetApp Bugs 1127315"^]


* Les systèmes ASA A900, AFF A900 et FAS9500 prennent uniquement en charge une alimentation haut de gamme (200 V à 240 V). Si votre système AFF A700 ou FAS9000 fonctionne avec une alimentation à faible consommation électrique (100 V à 120 V), vous devez convertir l'alimentation d'entrée AFF A700 ou FAS9000 avant d'utiliser cette procédure.
* Si vous effectuez une mise à niveau à partir d'un système existant avec interruption de service incluse dans lelink:decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["matrice des systèmes pris en charge"] Vous pouvez mettre à niveau le matériel du contrôleur en déplaçant le stockage ou en contactant le support technique.  Se référer àlink:other_references.html["Références"] pour accéder à _Mise à niveau par déplacement de volumes ou de stockage_.




== Automatisation du processus de mise à niveau des contrôleurs

Cette procédure fournit les étapes de la procédure automatisée, qui utilise l'affectation automatique des disques et les vérifications d'accessibilité des ports réseau pour simplifier l'expérience de mise à niveau du contrôleur.
