---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 'Installez les modules système de remplacement sur le nœud 2 lors d"une mise à niveau ARL des modèles de contrôleurs du même châssis.' 
---
= Installez le module AFF A30, AFF A50, AFF C30 ou AFF C60 dans le nœud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Installez le module de contrôleur de remplacement que vous avez reçu pour la mise à niveau sur le node2. Le nœud 2 est le contrôleur B situé dans la moitié inférieure du châssis lorsque l'on regarde les contrôleurs depuis l'arrière du système.

.Étapes
. Positionnez le système de stockage sur les rails au milieu de l'armoire ou du rack de télécommunications, puis soutenez le système de stockage par le bas et faites-le glisser pour le mettre en place.
+

NOTE: N'insérez pas complètement le module de contrôleur dans le châssis avant d'y être invité plus tard dans la procédure.

. Reliez les ports de gestion et de console au module de contrôleur node2.
+

NOTE: Étant donné que le châssis est déjà sous tension, le nœud 2 démarre l'initialisation du BIOS suivie du démarrage automatique dès qu'il est complètement installé.  Pour interrompre le démarrage du node2, avant d'insérer complètement le module de contrôleur dans l'emplacement, il est recommandé de connecter la console série et les câbles de gestion au module de contrôleur node2.

. Avec la poignée de came en position ouverte, poussez fermement le module de contrôleur jusqu'à ce qu'il rencontre le fond de panier central et qu'il soit bien en place. Le loquet de verrouillage s'élève lorsque le module de contrôleur est bien en place. Fermer la poignée de came en position verrouillée.
+

NOTE: Pour éviter d'endommager les connecteurs, ne forcez pas trop lorsque vous faites glisser le module de contrôleur dans le châssis.

. Connectez la console série dès que le module est installé et soyez prêt à interrompre l'AUTOBOOT du node2.
. Après l'interruption DE L'AUTOBOOT, le nœud 2 s'arrête à l'invite DU CHARGEUR. Si vous n'interrompez pas LE démarrage AUTOMATIQUE à temps et que le démarrage du nœud 2 commence, attendez l'invite et appuyez sur Ctrl-C pour accéder au menu de démarrage. Une fois que le nœud s'arrête au menu de démarrage, utilisez l'option `8` pour redémarrer le nœud et interrompre le DÉMARRAGE AUTOMATIQUE pendant le redémarrage.
. À l'invite LOADER> du nœud 2, définissez les variables d'environnement par défaut :
+
[source, cli]
----
set-defaults
----
. Enregistrez les paramètres des variables d'environnement par défaut :
+
[source, cli]
----
saveenv
----
. Pour les configurations sans commutateur à deux nœuds, vérifiez que vous disposez d'une carte X60132A 4 ports 10/25 GbE dans l'emplacement 1 du nœud 2. La carte X60132A est requise pour l'interconnexion du cluster lors de la mise à niveau.

