---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-asa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 'Installez les modules système de remplacement sur le nœud 2 lors d"une mise à niveau ARL des modèles de contrôleurs du même châssis.' 
---
= Installez le module de contrôleur ASA A150, AFF A150 ou FAS2820 sur le nœud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Installez le module de contrôleur ASA A150, AFF A150 ou FAS2820 que vous avez reçu pour la mise à niveau sur le node2. Le nœud 2 est le contrôleur B situé sur le côté droit du châssis, lorsque vous regardez les contrôleurs depuis l'arrière du système.

.Avant de commencer
* Si vous n'êtes pas déjà mis à la terre, mettez-vous à la terre correctement.
* Déconnectez tous les câbles, y compris les câbles de la console, de la gestion, du stockage SAS et du réseau de données, du contrôleur à retirer.


.Étapes
. Alignez l'extrémité du module de contrôleur avec la baie B du châssis, puis poussez doucement le module de contrôleur à mi-course dans le système.
+

TIP: La baie B est située sur le côté droit du châssis.

+

WARNING: N'insérez pas complètement le module de contrôleur dans le châssis tant que vous n'y êtes pas invité plus tard dans la procédure.

. Reliez les ports de gestion et de console au module de contrôleur node2.
+

NOTE: Comme le châssis est déjà sous tension, le nœud 2 démarre dès qu'il est complètement inséré.  Pour empêcher le démarrage du nœud 2, connectez les câbles de la console et de gestion avant d'insérer complètement le module de contrôleur.

. Poussez fermement le module de contrôleur dans le châssis jusqu'à ce qu'il rencontre le fond de panier central et qu'il soit bien en place.
+
Le loquet de verrouillage s'élève lorsque le module de contrôleur est bien en place.

+

NOTE: Pour éviter d'endommager les connecteurs, ne forcez pas trop lorsque vous faites glisser le module de contrôleur dans le châssis.

. Connectez la console série dès que le module est installé et soyez prêt à interrompre l'AUTOBOOT du node2.
. Après l'interruption DE L'AUTOBOOT, le nœud 2 s'arrête à l'invite DU CHARGEUR. Si vous n'interrompez pas LE démarrage AUTOMATIQUE à temps et que le démarrage du nœud 2 commence, attendez l'invite et appuyez sur Ctrl-C pour accéder au menu de démarrage. Une fois que le nœud s'arrête au menu de démarrage, utilisez l'option `8` pour redémarrer le nœud et interrompre le DÉMARRAGE AUTOMATIQUE pendant le redémarrage.

