---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/manage-storage-encryption-using-okm.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 'Configurez et gérez Storage Encryption, gérez les clés d"authentification et mettez fin aux relations SnapMirror lorsque vous utilisez ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le gestionnaire de clés intégré (OKM) pour gérer les clés de chiffrement. Si vous avez configuré le gestionnaire de clés intégré OKM, vous devez enregistrer la phrase de passe et les éléments de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Notez la phrase de passe à l'échelle du cluster.
+
Il s'agit de la phrase secrète saisie lorsque le gestionnaire de clés intégré OKM a été configuré ou mis à jour via l'interface de ligne de commandes ou l'API REST.

. Vérifiez la phrase de passe et le fonctionnement du key-manager :
+
`security key-manager onboard sync`

+
Lorsque vous y êtes invité, saisissez la phrase secrète OKM à l'échelle du cluster que vous avez enregistrée à l'étape précédente.

. Vérifiez que cc-mode est activé en consultant le résultat de la commande suivante :
+
`security key-manager config show`

. Sauvegardez les informations du key-manager :
+
`security key-manager onboard show-backup`





== Suspendre les relations SnapMirror (facultatif)

Avant de poursuivre l'opération, vous devez confirmer que toutes les relations SnapMirror sont suspendues. Lorsqu'une relation SnapMirror est mise en veille, elle reste suspension sur l'ensemble des redémarrages et basculements.

.Étapes
. Vérifier l'état de la relation SnapMirror sur le cluster destination :
+
`snapmirror show`

+
[NOTE]
====
Si l'état est « transfert », vous devez annuler ces transferts :
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'annulation échoue si la relation SnapMirror n'est pas à l'état « Transferring ».

. Arrêter toutes les relations entre le cluster :
+
`snapmirror quiesce -destination-vserver *`


