---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 'Vérifiez que les LIF de données NAS du nœud 2 sur le nœud 1 sont déplacées du nœud 1 vers le nœud 2 lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Déplacement des agrégats non racines et des LIF de données NAS vers le nœud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Après avoir vérifié la configuration réseau sur le nœud 2, vous devez déplacer les LIF de données NAS appartenant au nœud 2 du nœud 1 vers le nœud 2 et confirmer que les LIF SAN existent sur le nœud 2.

.Description de la tâche
Les LIF distantes gèrent le trafic vers les LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour le bon fonctionnement du cluster ou du service pendant la mise à niveau. Les interfaces logiques SAN ne sont déplacées que lorsqu'elles doivent être mappées sur de nouveaux ports.

Vous vérifiez que les LIF sont en bon état et situées sur les ports appropriés après avoir mis le nœud 2 en ligne.

.Étapes
. Reprendre l'opération de relocalisation :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les tâches suivantes :

+
--
** Vérification du quorum du cluster
** Vérification de l'ID système
** Vérification de la version d'image
** Vérification de la plate-forme cible
** Vérification de l'accessibilité du réseau


--
+
Le système interrompt l'opération à ce stade de la vérification de la connectivité du réseau

. Reprendre l'opération de relocalisation :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
--
** Vérification de l'état du cluster
** Vérification de l'état de la LIF de cluster


--
+
Après ces vérifications, le système replace les agrégats non racines et les LIF de données NAS sur le nœud 2, qui s'exécute désormais sur le contrôleur de remplacement.

+
L'opération de remplacement du contrôleur s'interrompt une fois le transfert de ressources terminé.

. Vérifier le statut du transfert d'agrégats et du déplacement des LIF de données NAS :
+
[source, cli]
----
system controller replace show-details
----
+
Si la procédure de remplacement du contrôleur est suspendue, vérifiez et corrigez l'erreur, le cas échéant, puis faites-la `resume` pour poursuivre l'opération.

. Si nécessaire, restaurez et rétablissez les LIF déplacées ou migrez et modifiez manuellement les LIF du nœud 2 qui n'ont pas pu être déplacées automatiquement vers le nœud 2.
+
[role="tabbed-block"]
====
.Restaurez et rétablissez les LIF déplacés
--
.. Veuillez indiquer les LIF déplacés :
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Si des LIF sont déplacées, restaurez le nœud de rattachement vers le nœud 2 :
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migration et modification manuelles des LIF
--
.. Migrer vers le nœud 2 les LIF qui n'ont pas pu être déplacés automatiquement :
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. Modifiez le nœud d'origine et le port d'origine pour les LIF migrées :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. Reprenez l'opération pour demander au système d'effectuer les vérifications post-requises :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
** Vérification du quorum du cluster
** Vérification de l'état du cluster
** Vérification de la reconstruction d'agrégats
** Vérification de l'état de l'agrégat
** Vérification de l'état du disque
** Vérification de l'état de la LIF de cluster
** Vérification du volume



