---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 'Vérifiez que les LIF de données NAS du nœud 1 sur le nœud 2 sont déplacées du nœud 2 vers le nœud 1 lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Déplacez les agrégats non racines du nœud 1 et les LIF de données NAS du nœud 2 vers le nœud mis à niveau 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Après avoir vérifié la configuration réseau sur le nœud 1, vous devez déplacer les LIF de données NAS appartenant au nœud 1 du nœud 2 vers le nœud 1 et confirmer que les LIF SAN existent sur le nœud 1.

.Description de la tâche
Les LIF distantes gèrent le trafic vers les LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour le bon fonctionnement du cluster ou du service pendant la mise à niveau. Les interfaces logiques SAN ne sont déplacées que lorsqu'elles doivent être mappées sur de nouveaux ports.

Vous vérifiez que les LIF sont en bon état et situées sur les ports appropriés après avoir mis le nœud 1 en ligne.

.Étapes
. Reprendre l'opération de relocalisation :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les tâches suivantes :

+
--
** Vérification du quorum du cluster
** Vérification de l'ID système
** Vérification de la version d'image
** Vérification de la plate-forme cible
** Vérification de l'accessibilité du réseau


--
+
Le système interrompt l'opération à ce stade de la vérification de la connectivité du réseau

. Effectuez une vérification de l'accessibilité du réseau :
+
[source, cli]
----
network port reachability show -node node1
----
+
Vérifiez que tous les ports connectés, y compris le groupe d'interfaces et les ports VLAN, affichent leur état comme `OK`.

. Pour les mises à niveau suivantes, vous devez réaffecter les LIFs SAN FCP.
+
[cols="35,65"]
|===
| Système existant | Système de remplacement 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | AFF C80 
|===
+
Pour toutes les autres mises à niveau du système, passez à <<resume_relocation_step4,Étape 4>>l' .

+
.. Réaffectez les LIF SAN FCP utilisées pour l'accès aux données FCP ou FC-NVMe aux ports de base appropriés :
+
[source, cli]
----
network interface show -vserver <vserver_hosting_fcp_lifs>
----
.. Pour les LIF avec le nœud actuel comme nœud mis à niveau 1 et le port actuel signale « status oper » comme « - » (car le port existait sur le nœud AFF A800 mais n'existe pas sur le nœud AFF A90), modifiez le port actuel avant de pouvoir le mettre en ligne.
+
Vérifier que la connectivité physique est établie sur le port FC target où le LIF FC doit être déplacé :

+
--
... Définir le statut de la LIF sur « down » :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down
----
... Modifier le home port de la LIF :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>
----
... Régler le statut de la LIF sur « UP » :
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up
----


--
+
Répétez les sous-étapes a et b pour chaque LIF FC SAN qui est home sur le node1.



. [[resume_relocation_step4]]reprendre l'opération de déplacement :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
--
** Vérification de l'état du cluster
** Vérification de l'état de la LIF de cluster


--
+
Après ces vérifications, le système replace les agrégats non-racine et les LIF de données NAS qui appartiennent au nœud1 sur le nouveau nœud 1.

+
L'opération de remplacement du contrôleur s'interrompt une fois le transfert de ressources terminé.

. Vérifier le statut du transfert d'agrégats et du déplacement des LIF de données NAS :
+
[source, cli]
----
system controller replace show-details
----
+
Si la procédure de remplacement du contrôleur est suspendue, vérifiez et corrigez l'erreur, le cas échéant, puis faites-la `resume` pour poursuivre l'opération.

. Si nécessaire, restaurez et rétablissez les LIF déplacées ou migrez et modifiez manuellement les LIF du nœud 1 qui n'ont pas pu être déplacées automatiquement vers le nœud 1.
+
[role="tabbed-block"]
====
.Restaurez et rétablissez les LIF déplacés
--
.. Veuillez indiquer les LIF déplacés :
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Si des LIF sont déplacées, restaurer le nœud de rattachement vers le nœud 1 :
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node1_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migration et modification manuelles des LIF
--
.. Migrer vers le nœud 1 les LIF qui n'ont pas pu être déplacés automatiquement :
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node1_nodename> -destination-port <port_on_node1>
----
.. Modifiez le nœud d'origine et le port d'origine pour les LIF migrées :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node1_nodename> -home-port <home_port>
----


--
====
. Reprenez l'opération pour demander au système d'effectuer les vérifications post-requises :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
** Vérification du quorum du cluster
** Vérification de l'état du cluster
** Vérification de la reconstruction d'agrégats
** Vérification de l'état de l'agrégat
** Vérification de l'état du disque
** Vérification de l'état de la LIF de cluster
** Vérification du volume



