---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/retire-node2.html 
keywords: retire, node2, retiring, node 
summary: 'Arrêtez le nœud 2 et retirez-le du rack ou du châssis lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Retrait du nœud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour retirer le nœud 2, arrêtez-le correctement, puis retirez-le du rack ou du châssis.

.Étapes
. Reprendre l'opération :
+
`system controller replace resume`

+
Le nœud s'arrête automatiquement.



.Et la suite ?
Après la mise hors service du nœud 2, choisissez l'une des procédures de remplacement de contrôleur suivantes en fonction de votre configuration de mise à niveau :

* link:replace-node2-affa250-affc250.html["Remplacez le module contrôleur node2 AFF A250 ou AFF C250"]
* link:replace-node2-affa800-affc800.html["Remplacez le module contrôleur node2 AFF A800 ou AFF C800"]
* link:replace-node2-affa220-affa200-affc190-fas2620-fas2720.html["Remplacez le module de contrôleur node2 AFF A220, AFF A200, AFF C190, FAS2620 ou FAS2720"]
* link:replace-node2-aff700-fas900.html["Remplacez le contrôleur node2 AFF A700 ou FAS9000 et les modules NVRAM"]

