---
permalink: upgrade/convert-node1-to-drive-shelf.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Convertissez node1 en une étagère de disques et connectez-le à node3 avant de réaffecter les disques de node1 à node3. 
---
= Convertissez le nœud 1 en tiroir disque et connectez-vous au nœud 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Convertissez node1 en une étagère de disques et connectez-le à node3 avant de réaffecter les disques de node1 à node3.

.Étapes
. Déconnectez tous les câbles réseau du nœud 1.
. Retirez le nœud 1 du châssis AFF A150, AFF A220 ou FAS2820.
. Insérez le module IOM12 ou IOM12B dans la baie du nœud 1.
. Connectez le port SAS du nœud 3 à un port disponible du module IOM12 ou IOM12B. Consultez la link:https://hwu.netapp.com["Hardware Universe"^] pour vérifier les ports SAS de votre système.
. Créez des connexions de cluster temporaires en connectant les ports de cluster node4 à n’importe quel port de cluster sur node3.
+

NOTE: Si le nœud 3 prend uniquement en charge les connexions de cluster 10 GbE, vous devez disposer d'un câblage 10 GbE pour créer des connexions de cluster temporaires.



.Et la suite ?
link:reassign-node1-drives.html["Réaffectez des lecteurs du nœud 1 au nœud 3"]
