---
permalink: upgrade/convert-node2-to-drive-shelf.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Convertissez node2 en un support de disque et connectez-le à node4 avant de réaffecter les disques de node2 à node4. 
---
= Convertissez le nœud 2 en tiroir disque et connectez-vous au nœud 4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Convertissez node2 en baie de disques et connectez-le à node4 avant de réaffecter les disques de node2 à node4. Node1 et node2 sont les contrôleurs à l'intérieur de la baie de disques.

.Étapes
. Déconnectez tous les câbles réseau du nœud 2.
. Retirez le nœud2 du châssis AFF A150, AFF A220 ou FAS2820.
. Insérez le module IOM12 ou IOM12B dans la baie du node2.
. Connectez le port SCSI série (SAS) du node4 à un port disponible sur le module IOM12 ou IOM12B.  Voir lelink:https://hwu.netapp.com["Hardware Universe"^] pour vérifier les ports SAS de votre système.
. Créez des connexions de cluster temporaires en connectant les ports e0a et e0b du nœud 1 à deux ports 25 GbE sur le nœud 4.
+

NOTE: Si node4 prend uniquement en charge les connexions de cluster 10 GbE, vous devez disposer d'un câblage 10 GbE pour créer des connexions de cluster temporaires.



.Et la suite ?
link:reassign-node2-drives.html["Réaffectez des lecteurs du nœud 2 au nœud 4"]
