---
permalink: upgrade/migrate-fas2820-aggregates-epsilon-lifs.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 'Migrez les agrégats de données, epsilon et les interfaces logiques (LIF) du nœud 1 vers le nœud 4.' 
---
= Migrer les agrégats de données, epsilon et LIF du nœud 1 vers le nœud 4 de FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Migrez les agrégats de données, epsilon et les interfaces logiques (LIF) du nœud 1 FAS2820 vers le nœud 4.

.Description de la tâche
Effectuez les étapes suivantes sur node4.

.Étapes
. À l'invite LOADER pour node4, définissez l'ID du système partenaire :
+
[source, cli]
----
setenv partner-sysid <system_ID_of_node1>
----
. Vérifiez l'ID du système partenaire :
+
[source, cli]
----
printenv partner-sysid
----
. Enregistrer les modifications :
+
[source, cli]
----
saveenv
----
. Démarrez le nœud dans le menu de démarrage :
+
[source, cli]
----
boot_ontap menu
----
. Dans le menu de démarrage, sélectionnez l'option `6 Update flash from backup config` pour restaurer le système de fichiers /var sur node4.
+
Cette opération remplace toute configuration Flash par la dernière sauvegarde sur disque.

. Entrez `y` pour continuer.
+
[NOTE]
====
Le nœud redémarre automatiquement pour charger la nouvelle copie du système de fichiers /var.

Le nœud signale un avertissement de non-concordance d'ID système. Entrez `y` Pour remplacer l'ID système.

====
. Migrer les LIFs du cluster :
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
+
[NOTE]
====
Si les ports du cluster système ne sont pas similaires lors de la mise à niveau d'un FAS2820 vers un contrôleur de remplacement, vous devrez peut-être modifier temporairement les interfaces sur node4 en ports de cluster :

[source, cli]
----
network port modify -node <node4> -port <port_name> -mtu 9000 -ipspace Cluster
----
====
+
[source, cli]
----
network interface migrate -vserver Cluster -lif <cluster_LIF>  -destination-node <node4> -destination-port <port_name>
----
. Attendez que le cluster atteigne le quorum, puis vérifiez que les nœuds du cluster sont sains :
+
[source, cli]
----
– cluster show
----
+

NOTE: La paire haute disponibilité et le basculement du stockage restent désactivés dans l'état actuel.

. Déplacer les LIFs du cluster sur les ports de cluster 25G temporaires du node4 :
+
[source, cli]
----
network interface modify -vserver Cluster -lif <cluster_LIF> -home-node <node4> -home-port <port_name>
----
. Effectuez cette étape uniquement si des groupes d’interfaces et des VLAN de données sont utilisés sur le cluster FAS2820 que vous mettez à niveau. Sinon, allez à<<migrate_node1_nod4,Étape 11>> .
+
Les noms des ports réseau physiques sur le contrôleur de remplacement diffèrent de ceux du FAS2820.  Cela peut entraîner des VLAN déplacés et des groupes d'interfaces mal configurés sur le nœud 4.

+
.. Afficher les VLAN déplacés :
+
[source, cli]
----
cluster controller-replacement network displaced-vlans show
----
.. Restaurer les VLAN déplacés :
+
[source, cli]
----
cluster controller-replacement network displaced-vlans restore
----
.. Corrigez les groupes d’interfaces mal configurés.  Les noms de port entre le FAS2820 et les contrôleurs que vous mettez à niveau peuvent être différents.  Mettez à jour les groupes d’interface avec les ports membres corrects :
+
[source, cli]
----
ifgrp remove-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----
+
[source, cli]
----
ifgrp add-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----




[[migrate_node1_nod4]]
. Migrer les agrégats de données du nœud 1 vers le nœud 4 :
+
[source, cli]
----
storage aggregate relocation start -aggregate-list <aggregate_list_name> -node <node1> -destination <node4> -ndo-controller-upgrade true -override-destination-checks true
----
. Afficher l'état agrégé des données :
+
[source, cli]
----
storage aggregate show
----
. Migrez l'epsilon en le supprimant du nœud 1 et en le déplaçant vers le nœud 4.
+
.. Supprimer epsilon du nœud 1 :
+
[source, cli]
----
cluster modify -epsilon false -node <node1>
----
.. Déplacer epsilon vers NODE4 :
+
[source, cli]
----
cluster modify -epsilon true -node <node4>
----


. Afficher l'état du cluster pour vérifier le changement epsilon :
+
[source, cli]
----
cluster show
----
. Afficher toutes les LIFs du réseau de données :
+
[source, cli]
----
network interface show -role data
----
. Migrer toutes les LIF de données vers le nœud 4 :
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node4> -destination-port <port_name>
----
. Afficher le statut de toutes les LIFs data dans le cluster :
+
[source, cli]
----
network interface show -role data
----
. Si des LIF sont en panne, définissez leur statut administratif sur `up` en entrant la commande suivante une fois pour chaque LIF :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Migrer la LIF cluster management :
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node4> -destination-port <port_name>
----
. Afficher le statut de la LIF cluster management :
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Arrêt du nœud 1 :
+
[source, cli]
----
halt -node <node1> -inhibit-takeover true -ignore-quorum-warnings true
----


.Et la suite ?
link:convert-fas2820-node1-drive-shelf.html["Convertissez le nœud 1 en tiroir disque et connectez-vous au nœud 3"]
