---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: 'Pour terminer la mise à niveau, connectez FAS2820node3 à node4, puis migrez les interfaces logiques de données (LIF) et les agrégats de données sur node4 vers node3.' 
---
= Migrer les LIF et les agrégats de données du nœud 4 vers le nœud 3 de FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour terminer la mise à niveau, connectez le nœud 3 du FAS2820 au nœud 4, puis migrez les interfaces logiques de données (LIF) et les agrégats de données du nœud 4 vers le nœud 3.

.Description de la tâche
Effectuez les étapes suivantes sur node3.

.Étapes
. À l'invite DU CHARGEUR pour le NODE3, démarrez le nœud dans le menu de démarrage :
+
[source, cli]
----
boot_ontap menu
----
. Sélectionnez option `6 Update flash from backup config` pour restaurer le système de fichiers /var sur le node3.
+
Cette opération remplace toute configuration Flash par la dernière sauvegarde sur disque.

. Entrez `y` pour continuer.
. Laissez le nœud démarrer normalement.
+
[NOTE]
====
Le nœud redémarre automatiquement pour charger la nouvelle copie du système de fichiers /var.

Le nœud signale un avertissement de non-concordance de l'ID système. Entrez `y` Pour remplacer l'ID système.

====
. Vérifiez que le cluster et les ports HA sont connectés entre le nœud 3 et le nœud 4.
. Afficher le cluster et les ports HA sur les nœuds 3 et 4 :
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. Modifier le broadcast domain de cluster pour inclure les ports de cluster souhaités :
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: À partir de ONTAP 9.8, les nouveaux IPspaces et un ou plusieurs domaines de diffusion peuvent être désignés sur des ports physiques existants destinés à la connectivité du cluster.

. Modifier le cluster IPspace pour inclure les ports de cluster souhaités et définir l'unité de transmission maximale sur 9000 si ce n'est pas déjà fait :
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. Afficher toutes les LIFs cluster network :
+
[source, cli]
----
network interface show -role cluster
----
. Migrez tous les LIF du réseau de cluster sur les deux nœuds vers leurs ports d'origine prévus :
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. Afficher toutes les LIFs cluster network :
+
[source, cli]
----
network interface show -role cluster
----
. Configurer les ports d’accueil pour les LIF du réseau de cluster :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. Migrer tous les LIF de données destinés au nœud 3 vers le nœud 3 :
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. Afficher toutes les LIFs du réseau de données :
+
[source, cli]
----
network interface show -role data
----
. Configurez le nœud d'origine et le port d'origine pour tous les LIF de données.  Si des LIF sont en panne, définissez leur statut administratif sur `up` en entrant la commande suivante une fois pour chaque LIF :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. Migrer la LIF cluster management :
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. Afficher le statut de la LIF cluster management :
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Afficher l'état de tous les agrégats de données du cluster :
+
[source, cli]
----
storage aggregate show
----
. Activer la haute disponibilité du cluster dans le cluster à deux nœuds :
+
[source, cli]
----
cluster ha modify -configured true
----
. Activer et vérifier le basculement de stockage pour les nœuds 3 et 4 :
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. Migrer les agrégats de données appartenant à node4 qui devraient appartenir à node3 :
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. Afficher l'état de tous les agrégats de données du cluster :
+
[source, cli]
----
storage aggregate show
----
. Activer la restauration automatique des LIFs réseau sur les nœuds :
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. Activer le rétablissement automatique du basculement du stockage :
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. Afficher l'état du cluster :
+
[source, cli]
----
cluster show
----
. Afficher l'éligibilité au basculement :
+
[source, cli]
----
storage failover show
----
+

NOTE: Dans la sortie du rapport de cluster, un nœud peut posséder par erreur des agrégats appartenant à un autre nœud.  Si cela se produit, effectuez une prise de contrôle et une restitution des deux côtés du cluster.

. Afficher l'état de tous les agrégats de données du cluster :
+
[source, cli]
----
storage aggregate show
----

