---
permalink: upgrade/reassign-node1-drives.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: 'Après avoir converti node1 en une baie de disques et l"avoir connecté à node3, vous réaffectez les disques qui appartenaient auparavant à node1 à node3.' 
---
= Réaffectez des lecteurs du nœud 1 au nœud 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Réaffectez les disques qui étaient précédemment affectés à node1 à node3.

.Étapes
Effectuez ces étapes sur le nœud3.

. À l'invite DU CHARGEUR, démarrez le nœud 3 en mode maintenance :
+
[source, cli]
----
boot_ontap maint
----
+
L'invite du mode de maintenance s'affiche.

. Afficher tous les disques connectés :
+
[source, cli]
----
disk show -v
----
. Enregistrez la valeur de l’ID du système local ; il s’agit de l’ID système du nœud 3.  Enregistrez également les ID système de node1 et node4 dans la colonne « PROPRIÉTAIRE ».
. Réaffectez tous les disques du nœud 1 au nœud 3 :
+
[role="tabbed-block"]
====
.Si vous utilisez des disques entiers
--
Exécutez la commande suivante :

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID>
----
--
.Si vous utilisez des disques partitionnés
--
Exécutez la commande suivante :

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID> -p <node4_system_ID>
----
--
====
. Vérifiez que tous les disques réaffectés sont visibles pour le nouvel ID système :
+
[source, cli]
----
disk show -s <node3_system_ID>
----
+

CAUTION: Si les lecteurs ne sont pas visibles, *arrêtez* et contactez le support technique pour obtenir de l'aide.

. Quitter le mode Maintenance :
+
[source, cli]
----
halt
----


.Et la suite ?
link:migrate-node4-lifs-aggregates.html["Migration des LIF et des agrégats de données du nœud 4 vers le nœud 3"]
