---
permalink: upgrade/upgrade-optional-move-internal-storage.html 
sidebar: sidebar 
keywords: node, support, model, internal, sata, drive, ssd, moving, move, upgrading, upgrade, convert, move internal storage or convert the system to a drive shelf 
summary: 'Si votre nœud d"origine est l"un des modèles pris en charge, vous pouvez déplacer vos disques SATA, SSD ou SAS internes vers un tiroir disque relié aux nouveaux nœuds lors de la mise à niveau du stockage. Vous pouvez également convertir le système en tiroir disque et le connecter aux nouveaux nœuds.' 
---
= Présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre nœud d'origine est l'un des modèles pris en charge, vous pouvez déplacer vos disques SATA, SSD ou SAS internes vers un tiroir disque relié aux nouveaux nœuds lors de la mise à niveau du stockage. Vous pouvez également convertir le système en tiroir disque et le connecter aux nouveaux nœuds.

Vous pouvez déplacer des disques ou des tiroirs disques uniquement au sein du même cluster.

.Choix
* link:upgrade-move-internal-drives.html["Déplacez les disques internes d'un nœud d'origine"]
+
Si votre nœud d'origine est l'un des modèles pris en charge, pendant la mise à niveau en déplaçant le stockage, vous pouvez déplacer les disques SATA, SSD ou SAS internes du nœud vers un tiroir disque connecté au nouveau nœud du même cluster.

* link:upgrade-convert-node-to-shelf.html["Convertir un nœud d'origine en tiroir disque"]
+
Si votre nœud d'origine est l'un des modèles pris en charge, pendant le processus de mise à niveau en déplaçant le stockage, vous pouvez convertir le nœud en tiroir disque, puis le connecter aux nouveaux nœuds du même cluster.


