---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 'Ce contenu explique comment mettre à niveau le matériel du contrôleur d"un système AFF ou d"un système FAS dans un cluster en déplaçant le stockage ou les volumes.' 
---
= Décidez de mettre à niveau en déplaçant des volumes ou du stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce contenu explique comment mettre à niveau le matériel du contrôleur d'un système AFF, FAS ou ASA dans un cluster en déplaçant le stockage ou les volumes.

Suivez cette procédure pour mettre à niveau le matériel du contrôleur dans les situations suivantes :


NOTE: Les procédures de mise à niveau matérielle ont été simplifiées dans ONTAP 9.8 grâce à l'introduction de la fonction de positionnement automatique des ports.

* Vos nœuds d'origine et nouveaux sont compatibles et pris en charge.
* Les nœuds d'origine et nouveaux exécutent ONTAP 9.0 ou version ultérieure. NetApp recommande, si possible, que la même version de ONTAP s'exécute sur les nœuds d'origine et les nouveaux nœuds.
+
Si la mise à niveau de votre contrôleur inclut des versions ONTAP mixtes, reportez-vous à la section https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["Clusters ONTAP à version mixte"^] pour en savoir plus.

* Vous réutilisez les adresses IP, les masques de réseau et les passerelles des nœuds d'origine sur les nouveaux nœuds.
* Vous prévoyez de mettre à niveau le matériel des contrôleurs en déplaçant le stockage ou les volumes,
* Vous êtes prêt à effectuer une procédure perturbateur si vous mettez à niveau en déplaçant le stockage.
+
La mise à niveau en déplaçant des volumes s'effectue sans interruption.

* Vous prévoyez de convertir un nœud d'un modèle pris en charge en tiroir disque, puis de le connecter aux nouveaux nœuds.


Si vous mettez à niveau une configuration MetroCluster, reportez-vous à la section https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Mettez à niveau, actualisez ou développez la configuration MetroCluster"^].

.Informations associées
* xref:upgrade-considerations.adoc[Considérations relatives à la mise à niveau du matériel du contrôleur]
* xref:choose_controller_upgrade_procedure.adoc[Choisissez des méthodes de mise à niveau du matériel du contrôleur]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Où trouver les procédures pour les tâches de maintenance MetroCluster"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

