---
permalink: upgrade/upgrade-unjoin-original-nodes-move-volumes.html 
sidebar: sidebar 
keywords: volume, move, node, unjoin, original, cluster, configuration, disk, initialize, unjoin the original nodes from the cluster 
summary: 'Une fois les volumes déplacés vers les nouveaux nœuds, déjoignez les nœuds d"origine du cluster. Lorsque vous annulez le rattachement d"un nœud, la configuration du nœud est effacée et tous les disques sont initialisés.' 
---
= Dissocier les nœuds d'origine du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois les volumes déplacés vers les nouveaux nœuds, déjoignez les nœuds d'origine du cluster. Lorsque vous annulez l'assemblage d'un nœud, la configuration du nœud est effacée et tous les disques sont initialisés.

.Étapes
. Désactiver la configuration haute disponibilité sur les nœuds d'origine : `storage failover modify -node _original_node_name_ -enabled false`
. Accéder au niveau de privilège avancé :
+
`set -privilege advanced`

. Identifier le nœud qui possède epsilon :
+
`cluster show`

+
Dans l'exemple suivant, « node0 » contient actuellement epsilon :

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. Si l'un des nœuds d'origine contient epsilon, déplacement d'epsilon vers un nœud différent :
+
.. Retirer epsilon du nœud d'origine : +
`cluster modify -node _original_node_name_ -epsilon false`
.. Assigner epsilon à un nœud différent : +
`cluster modify -node _new_node_name_ -epsilon true`


. Depuis un nœud qui restera dans le cluster, unjoin chaque nœud d'origine du cluster (niveau de privilège avancé) :
+
`cluster unjoin -node _original_node_name_`

+
Un message similaire au message suivant s'affiche :

+
[listing]
----
Warning: This command will unjoin node node_name from the cluster. You
         must unjoin the failover partner as well. After the node is
         successfully unjoined, erase its configuration and initialize all
         disks by using the "Clean configuration and initialize all disks (4)"
         option from the boot menu.
         Do you want to continue? {y|n}: y
----
. Entrez `y` pour continuer.
+
Le nœud non joint est automatiquement redémarré et s'arrête dans le menu de démarrage.

. Dans le menu d'amorçage du nœud non joint, sélectionnez l'option *(4) nettoyer la configuration et initialisez tous les disques* pour effacer la configuration du nœud et initialiser tous les disques.
+
Un message similaire au message suivant s'affiche :

+
[listing]
----
Zero disks, reset config and install a new file system?:
This will erase all the data on the disks, are you sure?:
----
. Entrez `y` à ces deux invites.
. Si le cluster ne comporte que deux nœuds, configurez la haute disponibilité pour le cluster à deux nœuds :
+
`cluster ha modify -configured true`


