---
permalink: upgrade/upgrade-map-network-ports-ontap-9-8.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, correct, configure, setting, data, map network ports using ontap 9.8 
summary: 'Pour permettre aux noeuds 3 et nœud4 de communiquer entre eux au sein du cluster et avec le réseau après la mise à niveau, vous devez vous assurer que les ports physiques sont correctement configurés avec les paramètres de l"utilisation prévue, tels que le cluster, les données, etc.' 
---
= Mappe les ports réseau avec ONTAP 9.8 ou version ultérieure
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour permettre aux nœuds 3 et Node4 de communiquer entre eux dans le cluster et avec le réseau après la mise à niveau, vous devez confirmer que les ports physiques sont correctement configurés avec les paramètres requis pour l'utilisation prévue, tels que le cluster, les données, etc.

.Avant de commencer
Ces étapes s'appliquent aux systèmes exécutant ONTAP 9.8 ou version ultérieure. Si vous exécutez ONTAP 9.7 ou une version antérieure, vous devez suivre la procédure de la section xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[Mappez les ports réseau avec ONTAP 9.7 ou version antérieure].

.Description de la tâche
Vous devez effectuer ces étapes sur les noeuds 3 et 4.


NOTE: Les exemples de commandes suivants font référence au nœud 1, car à ce stade de la procédure, les nœuds de remplacement « node3 » et « node4 » sont nommés « node1 » et « node2 ».

.Étapes
. Si votre système exécute ONTAP 9.7 ou une version antérieure, *STOP*. Vous devez utiliser la procédure dans xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[Mappez les ports réseau avec ONTAP 9.7 ou version antérieure].
. Recherchez les informations de configuration des ports et LIF pour les nœuds 1 et 2 que vous avez enregistrées dans _prepare for Upgrade lors du déplacement du stockage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Étape 3"].
. Localisez les informations sur les ports, les domaines de diffusion et les IPspaces que vous avez enregistrées dans _prepare for Upgrade lors du déplacement du stockage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["Étape 3"].
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. Effectuez les modifications suivantes :
+
.. Démarrez et connectez-vous aux nœuds 3 et 4 si vous ne l'avez pas déjà fait.
.. Modifier les ports qui feront partie du Cluster broadcast domain :
+
`network port modify -node _node_name_ -port _port_name_ -mtu 9000 -ipspace Cluster`

+
Cet exemple ajoute `Cluster` port e1b sur « node1 » :

+
`network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. Migrer les LIFs du cluster sur les nouveaux ports, une seule fois pour chaque LIF :
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -source-node node1 -destination-node node1 -destination-port _port_name_`

+
Lorsque toutes les LIFs du cluster sont migrées et que la communication du cluster est établie, le cluster doit se trouver au quorum.

.. Modifier le home port des LIFs du Cluster :
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Retirer les anciens ports du `Cluster` broadcast domain :
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports _node1:port_`

.. Afficher l'état de santé des nœuds 3 et 4 :
+
`cluster show -node _node1_ -fields health`

.. Chaque LIF de cluster doit écouter sur le port 7700. Vérifiez que les LIFs de cluster écoutent sur le port 7700 :
+
`::> network connections listening show -vserver Cluster`

+
Le port 7700 en écoute sur les ports de cluster est le résultat attendu, comme illustré dans l'exemple suivant pour un cluster à deux nœuds :

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. Si nécessaire, pour chaque LIF de cluster qui ne écoute pas sur le port 7700, mettre le statut administratif de la LIF sur `down` puis `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Répétez la sous-étape (g) pour vérifier que la LIF de cluster écoute désormais sur le port 7700.



. [[map_9.8_5]]Modifier les adhésions à un domaine de diffusion de ports physiques hébergeant des LIFs de données. Vous pouvez effectuer cette opération manuellement, comme indiqué dans la link:upgrade-map-network-ports-ontap-9-7-or-earlier.html#map_9.7_7["Mapper les ports réseau à l'aide de ONTAP 9.7 ou version antérieure, étape 7"]. L'approche recommandée consiste à utiliser la procédure d'acquisition et de réparation améliorée de la capacité d'amélioration du réseau introduite dans ONTAP 9.8, comme indiqué à l'étape 5, sous-étapes (a) à (g).
+
.. Lister l'état de la capacité d'accessibilité de tous les ports :
+
`network port reachability show`

.. Réparez la capacité d'accessibilité des ports physiques, suivie de ports VLAN, en exécutant la commande suivante sur chaque port, un port à la fois :
+
`reachability repair -node _node_name_ -port _port_name_`

+
Un avertissement comme celui ci-dessous est attendu. Vérifier et entrer `y` ou `n` selon les besoins :

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a
different broadcast domain, which can cause LIFs to be re-homed away
from the port. Are you sure you want to continue? {y|n}:
----
.. Pour activer ONTAP pour terminer la réparation, attendez environ une minute après l'exécution du `reachability repair` commande sur le dernier port.
.. Lister tous les broadcast domain sur le cluster :
+
`broadcast-domain show`

.. Au fur et à mesure que la réparation de l'accessibilité est effectuée, ONTAP tente de placer les ports dans les domaines de diffusion appropriés. Cependant, si la capacité d'un port ne peut pas être déterminée et ne correspond à aucun des domaines de diffusion existants, ONTAP crée de nouveaux domaines de diffusion pour ces ports. Si nécessaire, vous pouvez supprimer les nouveaux domaines de diffusion si tous leurs ports membres deviennent des ports membres des groupes d'interfaces. Supprimer les domaines de diffusion :
+
`broadcast-domain delete -broadcast-domain _broadcast_domain_`

.. Vérifiez la configuration des groupes d'interfaces et, le cas échéant, ajoutez ou supprimez des ports membres. Ajouter des ports membres aux ports du groupe d'interfaces :
+
`ifgrp add-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

+
Supprimer les ports membres des ports d'interface group :

+
`ifgrp remove-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

.. Supprimez et recréez les ports VLAN si nécessaire. Supprimer les ports VLAN :
+
`vlan delete -node _node_name_ -vlan-name _vlan_port_`

+
Créez des ports VLAN :

+
`vlan create -node _node_name_ -vlan-name _vlan_port_`

+

NOTE: En fonction de la complexité de la configuration réseau du système mis à niveau, vous devrez peut-être répéter l'étape 5, les sous-étapes (a) à (g) pour indiquer que tous les ports sont correctement placés si nécessaire.



. Si aucun VLAN n'est configuré sur le système, passez à l' <<map_98_7,Étape 7>>. Si des VLAN sont configurés, restaurez des VLAN déplacés qui étaient précédemment configurés sur des ports qui n'existent plus ou qui étaient configurés sur des ports déplacés vers un autre domaine de diffusion.
+
.. Afficher les réseaux locaux virtuels déplacés :
+
`cluster controller-replacement network displaced-vlans show`

.. Restaurez les VLAN déplacés vers le port de destination souhaité :
+
`displaced-vlans restore -node _node_name_ -port _port_name_ -destination-port _destination_port_`

.. Vérifier que tous les VLAN déplacés ont été restaurés :
+
`cluster controller-replacement network displaced-vlans show`

.. Les VLAN sont automatiquement placés dans les domaines de diffusion appropriés environ une minute après leur création. Vérifiez que les VLAN restaurés ont été placés dans les domaines de diffusion appropriés :
+
`network port reachability show`



. [[map_98_7]]depuis ONTAP 9.8, ONTAP modifie automatiquement les ports home des LIFs si les ports sont déplacés entre les broadcast domain pendant la procédure de réparation de la accessibilité des ports réseau. Si le port de rattachement d'une LIF a été déplacé dans un autre nœud ou s'il est non attribué, cette LIF sera présentée comme une LIF déplacée. Restaurer les ports de rattachement des LIFs déplacées dont les ports de rattachement n'existent plus ou ont été déplacés sur un autre nœud.
+
.. Afficher les LIFs dont les ports home port auraient pu être déplacés vers un autre nœud ou qui n'existent plus :
+
`displaced-interface show`

.. Restaurer le home port de chaque LIF :
+
`displaced-interface restore -vserver _vserver_name_ -lif-name _lif_name_`

.. Vérifier que tous les ports de base LIF ont été restaurés :
+
`displaced-interface show`

+
Lorsque tous les ports sont correctement configurés et ajoutés aux domaines de diffusion corrects, la commande network port reachable show doit indiquer que l'état de la capacité d'accessibilité est ok pour tous les ports connectés et que l'état n'est pas de capacité d'accès pour les ports sans connectivité physique. Si des ports indiquent un état autre que ces deux, réparez la capacité d'accessibilité comme indiqué dans la section <<map_98_5,Étape 5>>.



. Vérifier que toutes les LIFs sont administrativement présentes sur les ports appartenant aux domaines de diffusion appropriés.
+
.. Vérifiez si toutes les LIF sont administrativement arrêtées :
+
`network interface show -vserver _vserver_name_ -status-admin down`

.. Vérifier si les LIF ne sont pas opérationnelles : `network interface show -vserver _vserver_name_ -status-oper down`
.. Modifier toutes les LIFs qui doivent être modifiées pour avoir un autre port de home port :
+
`network interface modify -vserver _vserver_name_ -lif _lif_ -home-port _home_port_`

+

NOTE: Pour les LIF iSCSI, la modification du port de home port nécessite la mise hors service administrative de la LIF.

.. Revert les LIF qui ne home pas leurs ports respectifs :
+
`network interface revert *`





Le mappage des ports physiques est terminé. Pour terminer la mise à niveau, rendez-vous sur xref:upgrade-final-upgrade-steps-in-ontap-9-8.adoc[Effectuez les dernières étapes de mise à niveau dans ONTAP 9.8 ou version ultérieure].
