---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 'Ce contenu explique comment mettre à niveau le matériel du contrôleur d"un système AFF ou d"un système FAS dans un cluster en déplaçant le stockage ou les volumes.' 
---
= Décidez de mettre à niveau en déplaçant des volumes ou du stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce contenu explique comment mettre à niveau le matériel du contrôleur d'un système AFF, FAS ou ASA dans un cluster en déplaçant le stockage ou les volumes.

Suivez cette procédure pour mettre à niveau le matériel du contrôleur dans les situations suivantes :

[NOTE]
====
* Les mises à niveau ASA vers un système de remplacement ASA r2 ne sont pas prises en charge. Pour plus d'informations sur la migration des données d'un système ASA vers un système ASA r2, reportez-vous à la section link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Activez l'accès aux données depuis des hôtes SAN vers votre système de stockage ASA r2"^].
* Lorsque vous effectuez une mise à niveau vers un système introduit dans ONTAP 9.15.1 ou version ultérieure, ONTAP convertit l'efficacité du stockage des volumes existants et applique les nouvelles fonctionnalités d'efficacité du stockage qui utilisent la fonctionnalité de déchargement matériel. Il s'agit d'un processus automatique en arrière-plan, sans impact visible sur les performances du système.
+
** Pour AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 et AFF C80, ONTAP convertit l'efficacité du stockage de tous les volumes à provisionnement fin existants, y compris ceux qui n'utilisent pas l'efficacité du stockage.
** Pour les systèmes FAS70 et FAS90, ONTAP ne convertit que l'efficacité du stockage des volumes existants à provisionnement fin pour lesquels l'efficacité du stockage est activée avant la mise à niveau.
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["En savoir plus sur l'efficacité du stockage"^].



* Les procédures de mise à niveau matérielle ont été simplifiées dans ONTAP 9.8 grâce à l'introduction de la fonction de positionnement automatique des ports.


====
* Vos nœuds d'origine et nouveaux sont compatibles et pris en charge.
* Les nœuds d'origine et nouveaux exécutent ONTAP 9.0 ou version ultérieure. NetApp recommande, si possible, que la même version de ONTAP s'exécute sur les nœuds d'origine et les nouveaux nœuds.
+
Si la mise à niveau de votre contrôleur inclut des versions ONTAP mixtes, reportez-vous à la section https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["Clusters ONTAP à version mixte"^] pour en savoir plus.

* Vous réutilisez les adresses IP, les masques de réseau et les passerelles des nœuds d'origine sur les nouveaux nœuds.
* Vous prévoyez de mettre à niveau le matériel des contrôleurs en déplaçant le stockage ou les volumes,
* Vous êtes prêt à effectuer une procédure perturbateur si vous mettez à niveau en déplaçant le stockage.
+
La mise à niveau en déplaçant des volumes s'effectue sans interruption.

* Vous prévoyez de convertir un nœud d'un modèle pris en charge en tiroir disque, puis de le connecter aux nouveaux nœuds.


Si vous mettez à niveau une configuration MetroCluster, reportez-vous à la section https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Mettez à niveau, actualisez ou développez la configuration MetroCluster"^].

.Informations associées
* link:upgrade_aff_a250_to_aff_a400_ndu_upgrade_workflow.html["Convertissez AFF A250 en lecteur de plateau et effectuez une mise à niveau vers AFF A400"](procédure non perturbatrice)
* link:convert-fas2820-to-drive-shelf.html["Mise à niveau du FAS2820 en le convertissant en étagère de lecteur"](procédure non perturbatrice)
* link:upgrade-considerations.html["Considérations relatives à la mise à niveau du matériel du contrôleur"]
* link:../choose_controller_upgrade_procedure.html["Choisissez des méthodes de mise à niveau du matériel du contrôleur"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Où trouver les procédures pour les tâches de maintenance MetroCluster"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

