---
permalink: upgrade/upgrade-set-up-new-nodes.html 
sidebar: sidebar 
keywords: upgrade, nodes, moving, storage, port, original, new 
summary: 'Lors de la mise à niveau en déplaçant le stockage, vous mettez les nœuds 3 et 4 sous tension, démarrez l"image logicielle et configurez les nœuds.' 
---
= Configurez les nouveaux nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la mise à niveau en déplaçant le stockage, vous mettez les nœuds 3 et 4 sous tension, démarrez l'image logicielle et configurez les nœuds. L'organisation des ports physiques entre les nœuds d'origine et les nouveaux peut être différente. Le mappage des ports entre les nœuds d'origine et de remplacement doit être réalisé afin d'identifier le schéma approprié des ports et des connexions.

Si la version de ONTAP exécutée sur les nouveaux nœuds est différente de celle des nœuds d'origine, vous devez avoir téléchargé la version correcte `<ontap_version>_image.tgz` Fichier du site de support NetApp vers un répertoire accessible via le Web (voir _préparer la mise à niveau lors du déplacement du stockage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_5["STEP5"]). Vous avez besoin de la `<ontap_version>_image.tgz` fichier pour effectuer un démarrage sur le réseau de votre système.

.Étapes
. Mettez le nœud 3 sous tension, puis appuyez immédiatement sur Ctrl-C sur le terminal de la console pour accéder à l'invite DU CHARGEUR.
+
Si les nœuds 3 et 4 se trouvent dans le même châssis, passez à l'étape 2. Sinon, passer à l'étape 3.

. Si les nœuds 3 et 4 se trouvent dans une configuration de châssis unique (avec des contrôleurs dans le même châssis) :
+
.. Reliez une console série au nœud 4.
.. Mettez le nœud 4 sous tension, s'il n'est pas déjà ALLUMÉ, puis interrompez le processus de démarrage en appuyant sur Ctrl-C au niveau du terminal de la console pour accéder à l'invite DU CHARGEUR.
+
Si les deux contrôleurs se trouvent dans le même châssis, l'alimentation doit déjà ÊTRE MISE SOUS tension.

+
Quittez NODE4 à l'invite DU CHARGEUR ; vous revenez à cette procédure et répétez ces étapes après l'installation du nœud 3.



. À l'invite DU CHARGEUR, entrez la commande suivante :
+
`set-defaults`

. À l'invite DU CHARGEUR, configurez la connexion netboot pour les LIF de gestion :
+
[cols="25,75"]
|===
| Si l'adressage IP est... | Alors... 


| DHCP | Configurer la connexion automatique :
`ifconfig e0M -auto` 


| Statique | Configurer la connexion manuelle :
`ifconfig e0M -addr=ip_addr -mask=netmask -gw=gateway` 
|===
. À l'invite DU CHARGEUR, exécutez netboot sur le nœud 3 :
+
[cols="25,75"]
|===
| Pour... | Alors... 


| GAMMES FAS2200, FAS2500, FAS3200, FAS6200, FAS/AFF8000 | `netboot \http://web_server_ip/path_to_webaccessible_directory/netboot/kernel` 


| Tous les autres systèmes | `netboot \http://web_server_ip/path_to_webaccessible_directory/ontap_version_image.tgz` 
|===
+
Le `path_to_the_web-accessible_directory` est l'emplacement du téléchargé
`<ontap_version>_image.tgz` fichier.

+

NOTE: Si vous ne pouvez pas netboot sur les nouveaux contrôleurs, contactez le support technique.

. Dans le menu de démarrage, sélectionnez l'option *(7) installer le nouveau logiciel en premier* pour télécharger et installer la nouvelle image logicielle sur le périphérique d'amorçage.
+
Ne tenez pas compte du message suivant : `"This procedure is not supported for NonDisruptive Upgrade on an HA pair"`. Il s'applique aux mises à niveau logicielles sans interruption et non aux mises à niveau des contrôleurs.

. Si vous êtes invité à continuer la procédure, saisissez y et à indiquer l'URL du fichier image :
+
`/http://web_server_ip/path_to_web-accessible_directory/<ontap_version>_image.tgz`

+
Saisissez le nom d'utilisateur/mot de passe, le cas échéant, ou appuyez sur entrée pour continuer.

. Entrez `n` pour ignorer la restauration de la sauvegarde lorsque vous voyez une invite similaire à la suivante :
+
[listing]
----
`Do you want to restore the backup configuration now? {y|n}`
----
. Redémarrez en entrant `y` lorsque vous voyez une invite similaire à la suivante :
+
[listing]
----
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`
----
. Interrompez le processus de redémarrage en appuyant sur Ctrl-C pour afficher le menu de démarrage lorsque le système vous invite à le faire.
. Dans le menu de démarrage, sélectionnez *(5) Maintenance mode boot* pour accéder au mode Maintenance.
. Si nécessaire, modifiez les ports FC ou CNA sur le nœud, puis redémarrez le nœud en mode maintenance.
+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["Gestion SAN avec l'interface de ligne de commandes"^]

. Vous devez vérifier que la sortie de la commande affiche `ha`:
+
[listing]
----
*> ha-config show
 Chassis HA configuration: ha
 Controller HA configuration: ha
----
+
Les systèmes enregistrent dans une PROM, qu'ils soient dans une paire HA ou une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité

+
Le `ha-config modify controller ha` commande configure `ha` pour le réglage du contrôleur. Le `ha-config modify chassis ha` commande configure `ha` pour le réglage du châssis.

. Quitter le mode Maintenance :
+
`halt`

+
Le système s'arrête à l'invite DU CHARGEUR


