---
permalink: upgrade/upgrade-final-upgrade-steps-in-ontap-9-8.html 
sidebar: sidebar 
keywords: complete, procedure, upgrading, upgrade, moving, move, storage, delete, unused, port, lif, re-enable, failover, availability, service, processor, sp, autosupport, volume, encryption, fc, cna, perform final upgrade steps in ontap 9.8 
summary: 'Pour terminer la procédure de mise à niveau en déplaçant le stockage, vous devez supprimer les ports et LIF inutilisés des nouveaux nœuds, réactiver le basculement du stockage ou la haute disponibilité, configurer le processeur de service \(SP\), installer de nouvelles licences et configurer AutoSupport. Vous devrez également configurer le chiffrement du volume ou du stockage et les ports FC ou CNA.' 
---
= Effectuez les dernières étapes de mise à niveau dans ONTAP 9.8 ou version ultérieure
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour terminer la procédure de mise à niveau en déplaçant le stockage, vous devez supprimer les ports et LIF inutilisés des nouveaux nœuds, réactiver le basculement du stockage ou la haute disponibilité, configurer le processeur de service, installer de nouvelles licences et configurer AutoSupport. Vous devrez également configurer le chiffrement du volume ou du stockage et les ports FC ou CNA.

.Avant de commencer
Ces étapes s'appliquent aux systèmes exécutant ONTAP 9.8 ou version ultérieure. Si vous exécutez ONTAP 9.7 ou une version antérieure, vous devez suivre la procédure de la section link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["Exécution des étapes finales de mise à niveau sous ONTAP 9.7 ou version antérieure"].

.Étapes
. Si votre système exécute ONTAP 9.7 ou une version antérieure, *STOP*. Vous devez utiliser la procédure dans link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["Exécution des étapes finales de mise à niveau sous ONTAP 9.7 ou version antérieure"].
. Dans l'invite du système de stockage, affiche des informations sur les LIFs :
+
`network interface show`

. Si vous vous trouvez dans un environnement SAN, supprimez les LIF inutilisées du jeu de ports afin de pouvoir les supprimer :
+
.. Afficher la liste des ensembles de ports :
+
`lun portset show`

.. Supprimez toutes les LIFs inutilisées du jeu de ports :
+
`lun portset remove`



. Supprimez chaque LIF inutilisée des nouveaux nœuds :
+
`network interface delete`

. Réactiver le basculement du stockage ou la haute disponibilité sur la nouvelle paire de nœuds, selon les besoins :
+
[cols="1,2"]
|===
| Si vous avez un... | Alors... 


 a| 
Cluster à deux nœuds
 a| 
Réactiver la haute disponibilité : `cluster ha modify -configured true`



 a| 
Un cluster comprenant plus de deux nœuds
 a| 
Réactivation du basculement du stockage : `storage failover modify -node node_name -enabled true`

|===
. Configurez le processeur de service sur les nouveaux nœuds si nécessaire :
+
`system service-processor network modify`

. Installez les nouvelles licences sur les nouveaux nœuds, le cas échéant :
+
`system license add`

. Configurez AutoSupport sur les nouveaux nœuds :
+
`system node autosupport modify`

. Depuis chaque nouveau nœud, envoyez un message AutoSupport post-mise à niveau au support technique :
+
`system node autosupport invoke -node node_name -type all -message "MAINT=END node_name successfully upgraded from platform_old to platform_new"`

. Restaurez la fonctionnalité de cryptage de stockage ou de volume en suivant la procédure appropriée dans https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Gestion du chiffrement via l'interface de ligne de commandes"^] le contenu.
+
Choisissez l'une des procédures suivantes selon que vous utilisez la gestion intégrée ou externe des clés :

+
** « Restauration des clés de cryptage intégrées »
** « Restauration des clés de cryptage externes »


. Si les nouveaux nœuds disposent de ports FC (intégrés ou sur adaptateurs FC), de ports CNA intégrés ou d'une carte CNA, configurez les ports FC ou CNA en entrant la commande suivante à l'invite du système de stockage :
+
`system node hardware unified-connect modify -node node-name -adapter adapter-name -mode {fc|cna} -type {target|initiator}`

+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["Gestion SAN avec l'interface de ligne de commandes"^]

+
Vous ne pouvez modifier la configuration CNA que lorsque les adaptateurs CNA sont hors ligne.

. Le cas échéant, configurez un cluster sans commutateur sur les nouveaux nœuds.
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["Migration vers un cluster à deux nœuds avec commutateur avec commutateurs de cluster Cisco"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["Migration vers un cluster à deux nœuds avec commutateurs de cluster NetApp CN1610"^]

. Selon les besoins, désaffectez les systèmes d'origine via le site de support NetApp pour informer NetApp que les systèmes ne sont plus opérationnels et peuvent être supprimés des bases de données de support :
+
.. Connectez-vous au https://mysupport.netapp.com/site/global/dashboard["Support NetApp"^] le site.
.. Cliquez sur le lien *Mes systèmes installés*.
.. Sur la page systèmes installés, saisissez le numéro de série de l'ancien système dans le formulaire, puis cliquez sur *Go!*
.. Sur la page formulaire de mise hors service, remplissez le formulaire et cliquez sur *Envoyer*.




.Une fois que vous avez terminé
Vous avez terminé la procédure de mise à niveau.
