---
permalink: upgrade/upgrade_considerations_move_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, lif, original, node, unjoin, original, move san lifs 
summary: 'Vous n"avez besoin de déplacer que les LIF SAN si vous modifiez le contenu de votre cluster.' 
---
= Considérations relatives à la migration des LIF SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il vous suffit de déplacer les LIF SAN si vous modifiez le contenu du cluster, par exemple en ajoutant des nœuds au cluster ou en supprimant des nœuds. Lorsque vous déplacez une LIF, vous n'avez pas besoin de rezones de votre structure FC ou de créer de nouvelles sessions iSCSI entre les hôtes connectés de votre cluster et la nouvelle interface cible.

Vous pouvez déplacer une LIF SAN à l'aide du `network interface modify` commande. Pour déplacer une LIF SAN, vous devez mettre cette LIF hors ligne, déplacer cette LIF vers un autre nœud ou port d'origine, puis la remettre en ligne à son nouvel emplacement. L'ALUA (Asymmetric Logical Unit Access) offre des chemins redondants et une sélection de chemin automatique dans le cadre de n'importe quelle solution SAN de ONTAP. Par conséquent, lorsque la LIF est mise hors ligne pour le déplacement, il n'y a pas d'interruption d'E/S. L'hôte tente simplement de retraiter et déplace les E/S vers un autre LIF.

Durant les mouvements de la LIF, vous pouvez effectuer les tâches suivantes sans interruption :

* Remplacement d'une paire haute disponibilité d'un cluster par une paire haute disponibilité mise à niveau de manière transparente pour les hôtes qui accèdent aux données de la LUN
* Mettre à niveau une carte d'interface cible
* Transfert des ressources d'un SVM (Storage Virtual machine) d'un ensemble de nœuds d'un cluster vers un autre ensemble de nœuds du même cluster
* Lorsque le serveur hôte est en ligne, vous pouvez déplacer un LUN SAN vers une nouvelle paire haute disponibilité sans interrompre l'accès du serveur hôte aux données de la LUN


Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["Mouvement San LIF"^] Procédure de la documentation _SAN Storage Management_.
