---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: Vous devez réattribuer les disques qui appartenaient aux nœuds 1 et 2 respectivement aux nœuds 3 et 4. 
---
= Ajout de tiroirs de stockage et réaffectation de la propriété des disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez réattribuer les disques qui appartenaient aux nœuds 1 et 2 respectivement aux nœuds 3 et 4.

.Description de la tâche
Vous effectuez les étapes de cette section sur node3 et node4. Réalisez chaque étape sur node3 puis sur node4 avant de passer à l'étape suivante.

[[reassign-spare-disks-step1]]
.Étapes
. Raccordez les câbles des tiroirs disques qui étaient précédemment attachés :
+
** Connectez les câbles du nœud 1 au nœud 3
** Connectez les câbles du nœud 2 au nœud 4.
+

CAUTION: Ne connectez pas de nouveaux tiroirs disques à node3 ou node4 pendant cette procédure de mise à niveau. Vous pouvez connecter de nouveaux tiroirs disques au système sans interruption après avoir terminé la mise à niveau du contrôleur.



. Vérification de l'alimentation électrique et de la connectivité physique des tiroirs
. Dans l'invite DU CHARGEUR du nœud 3, démarrez en mode maintenance :
+
`boot_ontap maint`

. Afficher l'ID système du noeud 3 :
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Enregistrez l'identifiant système du nœud 3 pour l'utiliser dans <<reassign-disks-and-aggregates,Étape 5>>.



[[reassign-disks-and-aggregates]]
. Réaffectez les disques et les agrégats de données :
+
[role="tabbed-block"]
====
.Réaffecter au nœud 3
--
Réaffectez les disques de rechange du nœud 1, les disques appartenant à l'agrégat racine et tous les agrégats de données au nœud 3 :

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** Le paramètre  `node1_sysid` est la valeur que vous avez enregistrée dans _Arrêt des nœuds d'origine_ link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Étape 5"].
** Spécifiez le paramètre `-p <node2_sysid>` uniquement lorsque des disques partagés sont présents.


--
.Réaffecter au nœud 4
--
Réaffectez les disques de rechange du nœud 2, les disques appartenant à l'agrégat racine et tous les agrégats de données au nœud 4 :

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** Le paramètre  `node2_sysid` est la valeur que vous avez enregistrée dans _Arrêt des nœuds d'origine_ link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Étape 5"].
** Spécifiez le paramètre  `-p <node3_sysid>`uniquement lorsque des disques partagés sont présents.


--
====
+
Un message similaire au message suivant s'affiche :

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Entrez `y` pour continuer.
+
Un message similaire au message suivant s'affiche :

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Entrez `y` pour continuer.
. Confirmer que l'agrégat racine du nœud 1 est défini sur `root` dans le champ options et que les autres agrégats sont en ligne :
+
`aggr status`

+
Vous devez voir les résultats similaires à ce qui suit :

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]Quittez le mode maintenance :
+
`halt`

. Répétez <<reassign-spare-disks-step1,Étape 1>> à <<reassign-spare-disks-step9,Étape 9>> sur le nœud 4.


.Et la suite ?
Après avoir installé les étagères de stockage et réattribué la propriété des disques, link:upgrade-restore-root-volume-config.html["restaurer la configuration du volume racine"].
