---
permalink: upgrade/upgrade-remove-disk-ownership-new-nodes.html 
sidebar: sidebar 
keywords: node, internal, disk, add-on, shelves, attach, system, interfere, controller, upgrade, remove, ownership, node3, node4, node, remove ownership of disks attached to the new nodes 
summary: 'Si les nouveaux nœuds disposent de disques internes ou de tiroirs d"extension connectés au système, ces derniers peuvent interférer avec la mise à niveau du contrôleur. Procédez comme suit pour supprimer la propriété de tout nouveau disque fourni avec le noeud 3/node4.' 
---
= Supprime la propriété des disques connectés aux nouveaux nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si les nouveaux nœuds disposent de disques internes ou de tiroirs d'extension connectés au système, ces derniers peuvent interférer avec la mise à niveau du contrôleur. Procédez comme suit pour supprimer la propriété de tout nouveau disque fourni avec le noeud 3/node4.

.Description de la tâche
Ces étapes sont effectuées l'une après l'autre sur les noeuds 3 et 4. La séquence de nœuds n'a pas d'importance.

[NOTE]
====
* À ce stade, les tiroirs des nœuds 1 et 2 ne sont pas connectés physiquement aux nœuds 3 et 4.
* Vous n'êtes tenu d'enlever la propriété des disques et tiroirs livrés avec les nouveaux contrôleurs.
* Vous n'êtes pas tenu de retirer la propriété des disques si vous mettez à niveau le matériel en remplaçant un ancien contrôleur par un nouveau contrôleur sur une plate-forme de disque interne tout en conservant le châssis et les disques de l'ancien contrôleur.
+
Par exemple, si vous mettez à niveau votre système de A200 vers A220 en remplaçant uniquement l'ancien module de contrôleur A200 par le nouveau module de contrôleur A220 tout en conservant le châssis et les disques de l'ancien système A200 en place, Vous ne devez pas supprimer la propriété des disques du nouveau module de contrôleur A220 comme indiqué dans cette section _Suppression de la propriété des disques connectés aux nouveaux nœuds_.

+
Contactez le support technique NetApp si vous avez des questions sur le retrait de la propriété du disque lors de la mise à niveau du contrôleur.

+
Voici la liste des systèmes de stockage interne : FAS2520, FAS2552, FAS2554, FAS2620, FAS2650 ou FAS2650 FAS2720, FAS2750, AFF A200, AFF A220, AFF A700S, AFF A800, AFF A250.

+
Si votre système n'est pas répertorié ci-dessus, reportez-vous à la section https://hwu.netapp.com["NetApp Hardware Universe"^] pour vérifier s'il dispose de disques internes.



====
.Étapes
. À l'invite DU CHARGEUR du nœud, entrez la commande :
+
`boot_ontap menu`

. À l'invite du menu de démarrage, entrez `9a` Puis appuyez sur entrée.
+
L'écran suivant affiche l'invite du menu de démarrage.

+
[listing]
----
Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  9a
----
. Supprimez la propriété de disque en saisissant `y` lorsque vous voyez une invite similaire à la suivante :
+
[listing]
----

########## WARNING ##########

This is a disruptive operation and will result in the
    loss of all filesystem data. Before proceeding further,
    make sure that:
    1) This option (9a) has been executed or will be executed
    on the HA partner node, prior to reinitializing either
    system in the HA-pair.
    2) The HA partner node is currently in a halted state or
    at the LOADER prompt.


    Do you still want to continue (yes/no)? yes
----
+
Le système supprime la propriété du disque et revient au menu de démarrage.

. Au menu de démarrage, entrez `5` pour passer en mode maintenance.
. En mode maintenance, exécutez le `disk show` commande.
+
Aucun disque ne doit être répertorié.

. Exécutez la commande : `
+
`disk show -a`

+
Tous les disques répertoriés doivent être non assignés.

. Quitter le mode maintenance :
+
`halt`


