---
permalink: upgrade/upgrade-delete-san-lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lid, original, node, unjoin, original, delete san lifs from the original nodes 
summary: 'Si le cluster se trouve dans un environnement SAN, vous devez supprimer toute LIF SAN des nœuds d"origine avant de pouvoir dissocier les nœuds d"origine du cluster.' 
---
= Supprimez les LIFs SAN qui ne sont plus nécessaires des nœuds d'origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le cluster se trouve dans un environnement SAN, vous devez supprimer toutes les LIFs SAN dont vous n'avez plus besoin des nœuds initiaux avant de pouvoir dissocier les nœuds d'origine du cluster.

.Étapes
. Si vous avez des initiateurs iSCSI, procédez comme suit :
+
.. Afficher la liste des initiateurs actifs actuellement connectés à un SVM sur les nœuds d'origine, une fois pour chacune des anciennes LIFs : +
`iscsi connection show -vserver _Vserver_name_ -lif _old_lif_`
+
L'exemple suivant montre la sortie de la commande avec un initiateur actif connecté au SVM vs1 :

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. Si des initiateurs sont toujours connectés à un nœud d'origine, déconnectez-vous des sessions de votre ordinateur hôte.


. Afficher la liste de jeux de ports pour déterminer si des LIF iSCSI ou FC des nœuds d'origine appartiennent à un ensemble de ports :
+
`lun portset show`

+
L'exemple suivant montre la sortie du `lun portset show` commande :

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. Si des iSCSI ou des LIF FC d'un nœud d'origine sont membres d'un ensemble de ports, supprimez-les du jeu de ports :
+
`lun portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _lif_name_`

. Supprimez les LIFs sur les nœuds d'origine :
+
`network interface delete -vserver _vserver_name_ -lif _lif_name_`


