---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configurez et gérez Storage Encryption, gérez les clés d"authentification et mettez fin à la relation SnapMirror lors de la mise à niveau des contrôleurs exécutant ONTAP 9.15.1 ou version ultérieure à l"aide de la `system controller replace` commande.' 
---
= Finalisez la préparation de la mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les licences ONTAP et la gestion du chiffrement du stockage à l'aide du gestionnaire de clés intégré (OKM). Vous pouvez également mettre en veille les relations SnapMirror.



== Découvrez les licences ONTAP

Pour plus d'informations sur les licences ONTAP, reportez-vous à https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gestion des licences"^]la section .


NOTE: L'utilisation de fonctionnalités sans licence sur le contrôleur peut vous mettre hors conformité avec votre contrat de licence.



== Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré

Utilisez le Gestionnaire de clés intégré (OKM) pour gérer les clés de chiffrement. Si l'OKM est configuré, vous devez enregistrer la phrase de passe et les données de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Notez la phrase de passe à l'échelle du cluster.
+
Il s'agit de la phrase secrète saisie lorsque le gestionnaire de clés intégré OKM a été configuré ou mis à jour via l'interface de ligne de commandes ou l'API REST.

. Vérifiez la phrase de passe et le fonctionnement du key-manager :
+
`security key-manager onboard sync`

+
Lorsque vous y êtes invité, saisissez la phrase secrète OKM à l'échelle du cluster que vous avez enregistrée à l'étape précédente.

. Vérifiez que cc-mode est activé en consultant le résultat de la commande suivante :
+
`security key-manager config show`

. Sauvegardez les informations du key-manager :
+
`security key-manager onboard show-backup`





== Facultativement, mettre en pause les relations SnapMirror

Avant de poursuivre l'opération, vous devez confirmer que toutes les relations SnapMirror sont suspendues. Lorsqu'une relation SnapMirror est mise en veille, elle reste suspension sur l'ensemble des redémarrages et basculements.

.Étapes
. Vérifier l'état de la relation SnapMirror sur le cluster destination :
+
`snapmirror show`

+
[NOTE]
====
Si l'état est « transfert », vous devez annuler ces transferts :
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'annulation échoue si la relation SnapMirror n'est pas à l'état « Transferring ».

. Arrêter toutes les relations entre le cluster :
+
`snapmirror quiesce -destination-vserver *`



.Et la suite ?
Après avoir préparé la mise à niveau, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["déplacer les agrégats non racines et les LIF de données NAS appartenant au nœud1 vers le nœud2"].
