---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Vous pouvez choisir d"utiliser le transfert d"agrégats pour mettre à niveau les contrôleurs exécutant ONTAP 9.15.1 ou une version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Décider d'utiliser ou non cette procédure de relocalisation globale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs méthodes de relocalisation d'agrégats (ARL) pour mettre à niveau le matériel du contrôleur. Cette procédure ARL décrit comment mettre à niveau une paire de contrôleurs HA dans les systèmes de stockage AFF et FAS introduits dans ONTAP 9.15.1 ou version ultérieure avec de nouveaux contrôleurs tout en conservant les données et les disques existants. Cette procédure complexe est réservée aux administrateurs ONTAP expérimentés.

Pour vous aider à décider si cette procédure ARL est adaptée à la mise à niveau du matériel de votre contrôleur, vous devez examiner toutes les circonstances suivantes pour les mises à niveau prises en charge et non prises en charge.



== Mises à niveau prises en charge pour cette procédure ARL

Vous pouvez utiliser cette procédure ARL pour mettre à niveau une paire de nœuds dans les circonstances suivantes :

* Vous utilisez ONTAP 9.15.1 ou une version ultérieure.
* Vous ne souhaitez pas ajouter de nouveaux contrôleurs au cluster en tant que nouvelle paire haute disponibilité et migrer les données à l'aide de la procédure de déplacement de volumes.
* Vous êtes expérimenté dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilège de diagnostic.
* Votre combinaison de mise à niveau matérielle est répertoriée dans le <<sys_commands_9151_supported_systems,matrice de modèle prise en charge>> .



NOTE: Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).



== Mises à niveau non prises en charge pour cette procédure ARL

Vous ne pouvez pas utiliser cette procédure ARL pour mettre à niveau une paire de nœuds dans les circonstances suivantes :

* Vous effectuez l'une des mises à niveau suivantes :
+
|===
| Contrôleur existant | Remplacement du contrôleur 


| AFF A250 | AFF A50, AFF A30 


| AFF A800 | AFF A70, AFF A90 


| AFF C250 | AFF C30, AFF C60 


| AFF C800 | AFF C80 
|===
+
Pour effectuer une mise à niveau d'une mise à niveau répertoriée dans le tableau ci-dessus, reportez-vous à  la section  pour créer un link:other_references.html["Références"]lien vers _utiliser les commandes « System Controller replace » pour mettre à niveau les modèles de contrôleur dans le même châssis_.

* Vous mettez à niveau un système de stockage V-Series ou un système de virtualisation FlexArray à l'aide d'une baie externe pour le stockage interne. Pour savoir comment mettre à niveau un système V-Series ou FlexArray, contactez le support technique.
* Vous mettez à niveau une configuration MetroCluster FC ou IP. Pour mettre à niveau une configuration MetroCluster, reportez-vous à la section link:other_references.html["Références"] pour accéder à la _documentation de mise à niveau et d'extension MetroCluster_.




== Combinaisons de mise à niveau du système prises en charge

Le tableau suivant présente les combinaisons de mises à niveau de contrôleur prises en charge par ARL pour les systèmes AFF et FAS introduits dans ONTAP 9.15.1 ou version ultérieure. Si votre combinaison de mise à niveau de contrôleur n'est pas répertoriée, contactez le support technique.

|===
| Contrôleur existant | Remplacement du contrôleur | Pris en charge à partir de ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220, AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1 P3 pour FAS70, FAS90 9.16,1 P2 pour FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ pour effectuer la mise à niveau vers une baie AFF A20, vous devez d'abord convertir un AFF A150 ou un AFF A220 en tiroir DS224C en remplaçant le module de contrôleur par un module IOM12. Voir link:../upgrade/upgrade-convert-node-to-shelf.html["Convertir un nœud d'origine en tiroir disque"].

^2^ les systèmes AFF A20, AFF A50, AFF A70 et AFF A90 sont intégrés avec deux contrôleurs dans une configuration haute disponibilité et des disques intégrés dans un seul châssis :

* Si vous effectuez une mise à niveau vers un AFF A20, AFF A50, AFF A70 ou AFF A90 avec disques internes, vous devez supprimer la propriété de ces disques internes avant de procéder à la mise à niveau. Une fois la mise à niveau terminée, vous pouvez attribuer les disques internes aux nœuds AFF A20, AFF A50, AFF A70 ou AFF A90 et les utiliser pour créer des agrégats de données. Vous n'avez pas besoin de migrer les agrégats racine ou de données vers des disques internes.
* Si vous effectuez une mise à niveau vers un AFF A20, un AFF A50, un AFF A70 ou un AFF A90 sans lecteur interne, vous n'avez pas besoin d'affecter des lecteurs internes après avoir terminé la mise à niveau.




== Choisissez une autre procédure de mise à niveau matérielle

* link:../upgrade-arl/index.html["Passez en revue les méthodes ARL alternatives disponibles pour la mise à niveau du matériel du contrôleur"].
* Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.


.Informations associées
Se référer à link:other_references.html["Références"] pour créer un lien vers la _Documentation ONTAP 9_.
