---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Déterminez si vous pouvez effectuer une mise à niveau vers les contrôleurs introduits dans ONTAP 9.15.1 ou une version ultérieure en utilisant  `system controller replace` des commandes.' 
---
= Instructions de mise à niveau des contrôleurs avec l'ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour savoir si vous pouvez utiliser ARL pour mettre à niveau vers une paire de contrôleurs introduite dans ONTAP 9.15.1 ou une version ultérieure, cela dépend de la plateforme et de la configuration des contrôleurs d'origine et de remplacement.



[[supported-upgrades-for-arl]]
== Mises à niveau prises en charge pour l'ARL

Avant de mettre à niveau une paire de nœuds à l'aide de cette procédure ARL, vérifiez les conditions suivantes pour vous assurer que votre configuration est prise en charge :

* Vérifiez que le transfert d'agrégats peut être effectué sur les contrôleurs d'origine et de remplacement.
* Vérifiez la taille de tous les agrégats définis et le nombre de disques pris en charge par le système d'origine. Vous comparez ensuite la taille des agrégats et le nombre de disques pris en charge à la taille de l'agrégat et au nombre de disques pris en charge par le nouveau système. Reportez-vous à link:other-references.html["Références"] pour accéder à _Hardware Universe_ où ces informations sont disponibles. La taille de l'agrégat et le nombre de disques pris en charge par le nouveau système doivent être égaux ou supérieurs à la taille de l'agrégat et au nombre de disques pris en charge par le système d'origine.
* Vérifiez, dans les règles de mixage de clusters, si de nouveaux nœuds peuvent être intégrés au cluster avec les nœuds existants lors du remplacement du contrôleur d'origine. Pour plus d'informations sur les règles de mixage de clusters, reportez-vous à link:other-references.html["Références"] pour accéder à _Hardware Universe_.
* Migrez et réHome les LIF du cluster sur deux ports de cluster par nœud si vous disposez d'un système, tel qu'un AFF 700, avec la configuration suivante :
* Plus de deux ports de cluster par nœud
* Une carte d'interconnexion de cluster en slot4 en mode écorché pour créer les ports e4a, e4b, e4c et e4d et les ports e4e, e4f, e4g et e4h
+

NOTE: Une mise à niveau de contrôleur avec plus de deux ports de cluster par nœud peut entraîner l'absence de LIF de cluster sur le nouveau contrôleur après la mise à niveau.

+
Pour plus d'informations, consultez l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Comment supprimer des LIF de cluster inutiles ou indésirables"^].



La mise à niveau du contrôleur avec l'ARL est prise en charge sur les systèmes configurés avec les volumes SnapLock Enterprise et SnapLock Compliance.



[[two-node-switchless-clusters]]
== Clusters à 2 nœuds sans commutateur

Si vous mettez à niveau des nœuds dans un cluster sans commutateur à 2 nœuds, vous pouvez quitter le cluster sans commutateur tout en effectuant la mise à niveau. Il n'est pas nécessaire de les convertir en cluster commuté.



[[upgrades-not-supported-for-arl]]
== Mises à niveau non prises en charge pour l'ARL

Vous ne pouvez pas mettre à niveau des contrôleurs de remplacement qui ne prennent pas en charge les tiroirs disques connectés aux contrôleurs d'origine.

Consultez link:other-references.html["Références"] pour accéder à _Hardware Universe_ et obtenir des informations sur la prise en charge des disques.

Si vous souhaitez mettre à niveau des contrôleurs d'entrée de gamme avec disques internes, reportez-vous à link:other-references.html["Références"]_Mise à niveau par déplacement de volumes ou de stockage_ et accédez à la procédure _Mise à niveau d'une paire de nœuds exécutant Data ONTAP par déplacement de volumes_.



[[troubleshoot]]
== Résoudre les problèmes

En cas de problème lors de la mise à jour des manettes, consultezlink:aggregate_relocation_failures.html["Résoudre les problèmes"] pour plus d'informations et des solutions possibles.

Si vous ne trouvez pas de solution au problème que vous rencontrez, contactez le support technique.

.Et la suite ?
Après avoir examiné les directives de mise à niveau des contrôleurs avec ARL,link:overview_of_the_arl_upgrade.html["Découvrez la séquence de mise à niveau ARL"].
