---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'Vous pouvez mettre à niveau le matériel du contrôleur exécutant ONTAP 9.15.1 ou une version ultérieure à l"aide de `system controller replace` commandes et déplacer la propriété d"agrégats non racines.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette procédure décrit la procédure de mise à niveau du matériel du contrôleur à l'aide du transfert d'agrégats (ARL) pour les configurations système suivantes :

[cols="40,20,40"]
|===
| Méthode | Version ONTAP | Systèmes pris en charge 


| À l'aide de `system controller replace` commandes | 9.15.1 ou ultérieure | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_9151_supported_systems["Lien vers la matrice des systèmes pris en charge"] 
|===

NOTE: Vous ne pouvez pas utiliser cette procédure pour mettre à niveau une configuration MetroCluster FC ou IP. Pour mettre à niveau une configuration MetroCluster, reportez-vous à la section link:other_references.html["Références"] pour accéder à la _documentation de mise à niveau et d'extension MetroCluster_.

Pendant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, délocalisant ainsi la propriété des agrégats non racines. Vous migrez plusieurs fois des agrégats entre nœuds et nœuds pour confirmer qu'au moins un nœud transmet des données depuis les agrégats tout au long de la procédure de mise à niveau. Vous migrez également les interfaces de données logiques (LIF) et vous affectez les ports réseau sur le nouveau contrôleur aux groupes d'interface.

.Terminologie utilisée dans ces informations
Dans ces informations, les nœuds d'origine sont appelés « nœud1 » et « nœud2 », ainsi que « nœud3 » et « nœud4 ». Au cours de la procédure décrite, le noeud 1 est remplacé par le noeud 3 et le noeud 2 est remplacé par le noeud 4.

Les termes « node1 », « node2 », « node3 » et « node4 » servent uniquement à la distinction entre les nœuds d'origine et les nouveaux. Lorsque vous suivez la procédure, vous devez remplacer les véritables noms de vos nœuds d'origine et de vos nouveaux nœuds. Toutefois, en réalité, les noms des nœuds ne changent pas : le nœud 3 porte le nom node1 et le nœud 4 porte le nom node2 une fois le contrôleur mis à niveau.

.Information importante :
* Cette procédure est complexe et suppose que vous avez des compétences avancées en administration de ONTAP. Vous devez également lire et comprendre le link:guidelines_for_upgrading_controllers_with_arl.html["Instructions de mise à niveau des contrôleurs avec l'ARL"] et le link:overview_of_the_arl_upgrade.html["Présentation de la mise à niveau ARL"] avant de commencer la mise à niveau.
* Cette procédure suppose que le matériel de remplacement du contrôleur est nouveau et qu'il n'a pas été utilisé. Les étapes requises pour préparer les contrôleurs utilisés avec la `wipeconfig` commande ne sont pas incluses dans cette procédure. Vous devez contacter le support technique si vous avez déjà utilisé le matériel de remplacement du contrôleur.
* Vous pouvez suivre cette procédure pour mettre à niveau le matériel du contrôleur dans des clusters de plus de deux nœuds. Toutefois, vous devez effectuer la procédure séparément pour chaque paire haute disponibilité du cluster.
* Lorsque vous effectuez une mise à niveau vers un système introduit dans ONTAP 9.15.1 ou version ultérieure, ONTAP convertit l'efficacité du stockage des volumes existants et applique les nouvelles fonctionnalités d'efficacité du stockage qui utilisent la fonctionnalité de déchargement matériel. Il s'agit d'un processus automatique en arrière-plan, sans impact visible sur les performances du système.
+
** Pour les systèmes AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 et AFF C80, ONTAP convertit l'efficacité du stockage de tous les volumes à provisionnement fin existants, y compris ceux qui n'utilisent pas l'efficacité du stockage.
** Pour les systèmes FAS70 et FAS90, ONTAP ne convertit que l'efficacité du stockage des volumes existants à provisionnement fin pour lesquels l'efficacité du stockage est activée avant la mise à niveau.


+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["En savoir plus sur l'efficacité du stockage"^].

* Les systèmes AFF A20, AFF A50, AFF A70, AFF A90, AFF A1K, FAS70 et FAS90 partagent des ports réseau de 100 GbE pour les connexions en cluster et haute disponibilité. Ces systèmes peuvent prendre en charge des connexions de cluster 10 GbE ou 25 GbE avec les anciens switchs de cluster. Cependant, NetApp recommande de mettre à jour les vitesses de cluster 100 GbE lorsque les switchs 10 GbE et 25 GbE ne sont plus nécessaires. Pour plus d'informations, consultez les articles suivants de la base de connaissances :
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Comment configurer les ports de cluster 10G ou 25G sur une nouvelle configuration de cluster sur AFF/ASA A1K, A90, A70, FAS90, FAS70"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Comment convertir un cluster existant de ports de type 10 ou 25 Gbit/s en ports de cluster 40 Gbit/s ou 100 Gbit/s sur un système AFF/ASA A1K, A90, A70, FAS90, FAS70"^]


--
+
Le système AFF A20 partage des ports réseau 10 GbE et 25 GbE pour les connexions en cluster et haute disponibilité. Il s'agit des seules connexions de cluster de ports réseau prises en charge par un système AFF A20.

+
Si vous ne pouvez pas relier les ports e0a ou e0b du nœud existant aux ports de cluster du nouveau nœud, reportez-vous à la section link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["Bugs NetApp ID de bug en ligne CONTAP-166978"^].


