---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: 'Installez et amorcez Node3 et installez le logiciel ONTAP lors de la mise à niveau de contrôleurs exécutant ONTAP 9.15.1 ou version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Installez et démarrez le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous installez le nœud 3 dans le rack, transférez les connexions du nœud 1 vers le nœud 3, amorcez le nœud 3 et installez ONTAP. Vous réaffectez ensuite l'un des disques de spare du nœud 1, tous les disques appartenant au volume racine et tous les agrégats non racines qui n'ont pas été déplacés vers le nœud 2 plus tôt dans le processus, comme indiqué dans cette section.

.Description de la tâche
L'opération de déplacement est mise en pause au début de cette étape. Ce processus est largement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. En outre, vous devez vérifier que les LIFs SAN sont bien mises en ligne et attribuées aux ports physiques FC appropriés sur le NODE3.

Vous avez besoin de netboot nœud3 si cette version de ONTAP 9 n'est pas installée sur le nœud 1. Une fois le noeud 3 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers corrects sur le périphérique de démarrage pour les démarrages suivants du système, en suivant les instructions de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

.Étapes
. [[auto_install3_step1]]Assurez-vous que vous disposez d'un espace rack pour node3.
+
Les besoins en espace et en hauteur des nouveaux nœuds peuvent être différents des nœuds existants. Planifiez l'espace requis pour votre scénario de mise à niveau.

. [[auto_install3_step2]]installez le noeud 3 dans le rack, en suivant les instructions _installation and Setup_ de votre modèle de nœud.
. [[auto_install3_step3]]Cable node3, déplaçant les connexions du node1 vers le node3.
+
À partir de ONTAP 9.15.1, les nouveaux modèles de contrôleurs ne disposent que d'un seul port « clé » pour le contrôleur BMC (Baseboard Management Controller) et les connexions de gestion. Planifiez les modifications de câblage en conséquence.

+
** Console (port de gestion à distance)
** De clusters et de ports haute disponibilité
** Ports de données
** Ports de gestion de clusters et de nœuds
** Ports de stockage SAS (Serial-Attached SCSI) et Ethernet
** Configurations SAN : ports de switch Ethernet iSCSI, FC et NVMe/FC
+
[NOTE]
====
Vous devrez peut-être modifier les câbles d'interconnexion entre l'ancien et le nouveau contrôleur pour assurer l'interopérabilité entre les différents modèles de contrôleur et de carte. Pour obtenir un schéma de câblage des tiroirs de stockage Ethernet de vos systèmes, reportez-vous au link:https://docs.netapp.com/us-en/ontap-systems/index.html["procédures d'installation du système"^] .

Pour les contrôleurs introduits dans ONTAP 9.15.1 et versions ultérieures, les interconnexions de cluster et haute disponibilité utilisent les mêmes ports. Pour les configurations connectées par commutateur, il est nécessaire de connecter des ports similaires aux mêmes commutateurs du cluster. Par exemple, lors de la mise à niveau vers un AFF A1K à partir d'un contrôleur existant, vous devez connecter les ports e1a des deux nœuds à un commutateur et les ports e7a des deux nœuds au second commutateur.

====


. [[auto_install3_step4]]mettez le système sous tension vers le noeud 3, puis interrompez le processus d'amorçage en appuyant sur Ctrl-C sur le terminal de la console pour accéder à l'invite de l'environnement d'amorçage.
+

NOTE: Lorsque vous démarrez le nœud 3, le message d'avertissement suivant peut s'afficher :

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]si vous voyez le message d'avertissement dans <<auto_install3_step4,Étape 4>>, procédez comme suit :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage s'achever.
+

WARNING: *Attention : ne pas outrepasser le délai; si la batterie n'est pas chargée, cela pourrait entraîner une perte de données.*

+

NOTE: Reportez-vous à la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].





. [[step6]]configurez la connexion netboot en choisissant l'une des actions suivantes.
+

NOTE: Vous devez utiliser le port de gestion et l'IP comme connexion netboot. N'utilisez pas d'IP de la LIF de données et ne subit aucune panne pendant l'exécution de la mise à niveau.

+
[cols="30,70"]
|===
| Si le protocole DHCP (Dynamic Host Configuration Protocol) est... | Alors... 


| Exécution | Configurez la connexion automatiquement à l'aide de la commande suivante à l'invite de l'environnement d'initialisation :
`ifconfig e0M -auto` 


| Non en cours d'exécution  a| 
Configurez manuellement la connexion à l'aide de la commande suivante à l'invite de l'environnement d'initialisation :
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Est l'adresse IP du système de stockage (obligatoire).
`_netmask_` est le masque de réseau du système de stockage (obligatoire).
`_gateway_` est la passerelle du système de stockage (obligatoire).
`_dns_addr_` Est l'adresse IP d'un serveur de noms sur votre réseau (facultatif).
`_dns_domain_` Est le nom de domaine DNS (Domain Name Service) (facultatif).


NOTE: D'autres paramètres peuvent être nécessaires pour votre interface. Entrez `help ifconfig` à l'invite du micrologiciel pour plus de détails.

|===
. [[step7]]exécutez sur le nœud 3 :
+
`netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

+
Le `<path_to_the_web-accessible_directory>` vous devez indiquer où vous avez téléchargé le `<ontap_version>_image.tgz` dans la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

+

NOTE: N'interrompez pas l'amorçage.

. [[step8]]] dans le menu de démarrage, sélectionnez option `(7) Install new software first`.
+
Cette option de menu permet de télécharger et d'installer la nouvelle image ONTAP sur le périphérique d'amorçage.

+
Ne tenez pas compte du message suivant :

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Cette remarque s'applique aux mises à niveau de ONTAP sans interruption et non aux mises à niveau des contrôleurs.

+

NOTE: Utilisez toujours netboot pour mettre à jour le nouveau nœud vers l'image souhaitée. Si vous utilisez une autre méthode pour installer l'image sur le nouveau contrôleur, il est possible que l'image incorrecte soit installée. Ce problème s'applique à toutes les versions de ONTAP. Procédure netboot combinée avec l'option `(7) Install new software` Efface le support de démarrage et place la même version de ONTAP sur les deux partitions d'image.

. [[step9]]si vous êtes invité à poursuivre la procédure, entrez `y`, Et lorsque vous êtes invité à saisir l'URL du pack :
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]]effectuez les sous-étapes suivantes pour redémarrer le module de contrôleur :
+
.. Entrez `n` pour ignorer la récupération de sauvegarde lorsque l'invite suivante s'affiche :
+
`Do you want to restore the backup configuration now? {y|n}`

.. Entrez `y` pour redémarrer lorsque vous voyez l'invite suivante :
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
Le module de contrôleur redémarre mais s'arrête au menu d'amorçage car le périphérique d'amorçage a été reformaté et les données de configuration doivent être restaurées.



. [[step11]]sélectionnez le mode de maintenance `5` dans le menu de démarrage et entrez `y` lorsque vous êtes invité à poursuivre le démarrage.
. [[step12]]vérifier que le contrôleur et le châssis sont configurés comme haute disponibilité :
+
`ha-config show`

+
L'exemple suivant montre la sortie du `ha-config show` commande :

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Le système enregistre dans une PROM, qu'il soit dans une paire HA ou dans une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité.

. Si le contrôleur et le châssis ne sont pas configurés comme HA, utilisez les commandes suivantes pour corriger la configuration :
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

. Vérifiez que tous les ports Ethernet utilisés pour la connexion aux tiroirs Ethernet sont configurés comme stockage :
+
`storage port show`

+
Le résultat affiché dépend de la configuration du système. L'exemple de sortie suivant concerne un nœud avec une seule carte de stockage dans slot11. La sortie de votre système peut être différente :

+
[listing]
----
*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e11a ENET storage 100 Gb/s    enabled  online  30
e11b ENET storage 100 Gb/s    enabled  online  30
----
. Modifiez les ports qui ne sont pas définis sur Storage :
+
`storage port modify -p <port> -m storage`

+
Tous les ports Ethernet connectés aux tiroirs de stockage doivent être configurés en tant que stockage pour permettre l'accès aux disques et aux tiroirs.

. Quitter le mode maintenance :
+
`halt`

+
Interrompez l'AUTOBOOT en appuyant sur `Ctrl-C` à l'invite de l'environnement de démarrage.

. Sur le node2, vérifiez la date, l'heure et le fuseau horaire du système :
+
`date`

. Sur le node3, vérifiez la date à l'aide de la commande suivante à l'invite de l'environnement de démarrage :
+
`show date`

. Si nécessaire, définissez la date sur le nœud 3 :
+
`set date <mm/dd/yyyy>`

. Sur le node3, vérifiez l'heure en utilisant la commande suivante à l'invite de l'environnement de démarrage :
+
`show time`

. Si nécessaire, définissez l'heure sur le nœud 3 :
+
`set time <hh:mm:ss>`

. Dans le chargeur de démarrage, définissez l'ID système du partenaire sur le nœud 3 :
+
`setenv partner-sysid <node2_sysid>`

+
Pour le nœud 3, `partner-sysid` doit être celui du node2.

+
.. Enregistrer les paramètres :
+
`saveenv`



. [[auto_install3_step21]]Vérifiez l' `partner-sysid` pour le nœud 3 :
+
`printenv partner-sysid`

. Si des disques NetApp Storage Encryption (NSE) sont installés, effectuez les opérations suivantes.
+

NOTE: Si ce n'est déjà fait, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Comment savoir si un disque est certifié FIPS"^] déterminer le type de disques à autocryptage utilisés.

+
.. Réglez `bootarg.storageencryption.support` à `true` ou `false`:
+
[cols="35,65"]
|===
| Si les lecteurs suivants sont utilisés… | Puis… 


| Disques NSE conformes aux exigences de chiffrement automatique FIPS 140-2 de niveau 2 | `setenv bootarg.storageencryption.support *true*` 


| NetApp non-SED FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
.. Accédez au menu de démarrage spécial et sélectionnez option `(10) Set Onboard Key Manager recovery secrets`.
+
Saisissez la phrase de passe et les informations de sauvegarde que vous avez enregistrées lors de la procédure précédente. Voir link:manage_storage_encryption_using_okm.html["Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré"].



. Démarrez le nœud dans le menu de démarrage :
+
`boot_ontap menu`

. Sur le node3, accédez au menu de démarrage et, à l'aide de 22/7, sélectionnez l'option cachée `boot_after_controller_replacement`. À l'invite, entrez node1 pour réaffecter les disques du nœud1 au nœud3, comme dans l'exemple suivant.
+
.Développez l'exemple de sortie de la console
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: Dans l'exemple de sortie de la console ci-dessus, ONTAP vous invite à entrer le nom du nœud partenaire si le système utilise des disques du partitionnement de disque avancé.

. Si le système passe en boucle de redémarrage avec le message `no disks found`, il indique qu'il y a eu un problème avec la réaffectation de disque. Voir link:aggregate_relocation_failures.html["Résoudre les problèmes"] pour résoudre le problème.
. Appuyez sur `Ctrl-C` pendant l'AUTOBOOT pour arrêter le nœud à `LOADER>` l'invite.
. À l'invite du CHARGEUR, entrer en mode maintenance :
+
`boot_ontap maint`

. Vérifiez la connectivité du disque, le modèle de contrôleur, la configuration haute disponibilité et d'autres informations relatives à la connectivité du matériel.
. Quitter le mode maintenance :
+
`halt`

. [[auto_check3_step32]]à l'invite du CHARGEUR, démarrez :
+
`boot_ontap menu`

+
Maintenant, au démarrage, le nœud peut détecter tous les disques qui lui étaient précédemment affectés et peut démarrer comme prévu.

+
Lorsque les nœuds de cluster que vous remplacez utilisent le chiffrement de volume racine, ONTAP ne peut pas lire les informations de volume à partir des disques. Restaurer les clés du volume root.

+

NOTE: Cela s'applique uniquement lorsque le volume racine utilise le chiffrement de volume NetApp.

+
.. Revenir au menu de démarrage spécial :
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Sélectionnez *(10) définir les secrets de récupération du gestionnaire de clés intégré*
.. Entrez `y` à l'invite suivante :
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. À l'invite, entrez la phrase de passe du gestionnaire de clés.
.. Entrez les données de sauvegarde lorsque vous y êtes invité.
+

NOTE: Vous devez avoir obtenu la phrase de passe et les données de sauvegarde dans le link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"] section de cette procédure.

.. Une fois que le système a de nouveau démarré dans le menu de démarrage spécial, exécutez l'option *(1) démarrage normal*
+

NOTE: Il se peut que vous rencontriez une erreur à ce stade. Si une erreur se produit, répétez les sous-étapes de la section <<auto_check3_step32,Étape 32>> jusqu'à ce que le système démarre normalement.




