---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/manage-authentication-using-kmip-servers.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configurez et gérez le chiffrement du stockage, gérez les clés d"authentification et mettez au repos les relations SnapMirror lors de la mise à niveau vers les contrôleurs introduits dans ONTAP 9.15.1 ou ultérieur à l"aide de la commande  `system controller replace`.' 
---
= Gérez l'authentification à l'aide de serveurs KMIP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les serveurs KMIP (Key Management Interoperability Protocol) pour gérer les clés d'authentification.

.Étapes
. Ajout d'un nouveau contrôleur :
+
`security key-manager external enable`

. Ajouter le gestionnaire de clés :
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vérifier que les serveurs de gestion des clés sont configurés et disponibles pour tous les nœuds du cluster :
+
`security key-manager external show-status`

. Restaurez les clés d'authentification de tous les serveurs de gestion de clés liés vers le nouveau nœud :
+
`security key-manager external restore -node _new_controller_name_`



.Et la suite ?
Après avoir géré l'authentification à l'aide des serveurs KMIP, link:ensure_new_controllers_are_set_up_correctly.html["vérifier que les nouveaux contrôleurs sont correctement configurés"].
