---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 'Comprendre le fonctionnement de la procédure de mise à niveau des contrôleurs exécutant ONTAP 9.15.1 ou une version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Présentation de la mise à niveau ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau les nœuds à l'aide de l'ARL, il est important de connaître son fonctionnement. Dans ce contenu, la procédure est divisée en plusieurs étapes.



== Mettre à niveau la paire de nœuds

Pour mettre à niveau la paire de nœuds, vous devez préparer les nœuds d'origine, puis effectuer une série d'étapes sur les nœuds d'origine et nouveaux. Vous pouvez ensuite désaffecter les nœuds d'origine.



== Présentation de la séquence de mise à niveau ARL

Durant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, un contrôleur à la fois, en tirant parti de la configuration de paires haute disponibilité pour transférer la propriété d'agrégats non racines. Tous les agrégats non racines doivent être reloisés afin d'atteindre leur destination finale, qui est le nœud mis à niveau correct.

Chaque agrégat possède un propriétaire d'origine et un propriétaire actuel. Le propriétaire de la maison est le propriétaire réel de l'agrégat, et le propriétaire actuel est le propriétaire temporaire.

Le tableau ci-après décrit les tâches générales que vous effectuez à chaque étape ainsi que l'état de propriété de l'agrégat à la fin de cette étape. Les étapes détaillées sont fournies ultérieurement dans la procédure :

[cols="35,65"]
|===
| Étape | Description 


| link:stage_1_index.html["Étape 1. Préparation de la mise à niveau"]  a| 
Lors de l'étape 1, vous exécutez des contrôles préalables et, le cas échéant, vous devez corriger la propriété globale. Vous devez enregistrer certaines informations si vous gérez le chiffrement du stockage à l'aide de OKM et si vous pouvez choisir de suspendre les relations SnapMirror.

Propriété d'un agrégat à la fin de la phase 1 :

* NODE1 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 1.
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2.




| link:stage_2_index.html["Étape 2. Transférez et retirez le nœud 1"]  a| 
Lors de la phase 2, vous transférez les agrégats non racines et les LIF de données du nœud 1 vers le nœud 2. Ce processus est largement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. Si nécessaire, vous transférez des agrégats défaillants ou vetotés. Vous enregistrez les informations sur le noeud 1 pour les utiliser ultérieurement dans la procédure avant de retirer le noeud 1. Vous pouvez également préparer votre infrastructure sur le nœud 3 et sur le nœud 4 plus tard dans la procédure.

Propriété d'un agrégat à la fin de la phase 2 :

* NODE2 est le propriétaire actuel des agrégats du nœud 1.
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2.




| link:stage_3_index.html["Étape 3. Installez et démarrez le nœud 3"]  a| 
Lors de la phase 3, vous installez et démarrez le nœud 3, vérifiez que le cluster et les ports de gestion des nœuds du nœud 1 sont connectés sur le nœud 3 et vérifiez l'installation du nœud 3. Si vous utilisez NetApp Volume Encryption (NVE), vous restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer les LIF de données NAS du nœud 1 et les agrégats non racine du nœud 2 vers le nœud 3, puis vérifier que les LIF SAN existent sur le nœud 3.

Propriété globale à la fin de la phase 3 :

* NODE3 est le propriétaire et propriétaire actuel des agrégats du nœud 1.
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2.




| link:stage_4_index.html["Étape 4. Transférez et retirez le nœud 2"]  a| 
Lors de la phase 4, vous transférez les agrégats non racines et les LIF de données NAS du nœud 2 vers le nœud 3. Vous enregistrez également les informations du node2 pour les utiliser ultérieurement dans la procédure avant de retirer le node2.

Propriété globale à la fin de la phase 4 :

* NODE3 est le propriétaire et propriétaire actuel des agrégats qui appartenaient initialement au noeud 1.
* Node4 est le propriétaire accueil des agrégats du nœud 2.
* NODE3 est le propriétaire actuel des agrégats du nœud 2.




| link:stage_5_index.html["Étape 5. Installez et démarrez Node4"]  a| 
Lors de la phase 5, vous installez et démarrez le nœud 4, vérifiez que le cluster et les ports de gestion des nœuds du nœud 2 sont connectés sur le nœud 4, puis vérifiez l'installation du nœud 4. Si vous utilisez NVE, restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer les LIF de données NAS du nœud 2 et les agrégats non racine du nœud 3 vers le nœud 4, puis vérifier que les LIF SAN existent sur le nœud 4.

Propriété globale à la fin de la phase 5 :

* NODE3 est le propriétaire et propriétaire actuel des agrégats qui appartenaient initialement au noeud 1.
* NODE4 est le propriétaire et propriétaire actuel des agrégats qui appartenaient initialement au nœud2.




| link:stage_6_index.html["Étape 6. Terminez la mise à niveau"]  a| 
Lors de la phase 6, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NVE. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

|===