---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 'Préparez les nœuds et exécutez une série de vérifications préalables lors de la mise à niveau vers des contrôleurs introduits dans ONTAP 9.15.1 ou une version ultérieure en utilisant les commandes  `system controller replace`.' 
---
= Préparer les nœuds pour une mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le processus de remplacement du contrôleur commence par une série de vérifications préalables. Vous collectez également des informations sur les nœuds d'origine pour les utiliser ultérieurement dans la procédure. Si l'une de ces vérifications échoue, vous devez corriger la propriété des agrégats avant de poursuivre la mise à niveau.



[[step-1-prepare-node1-and-node2]]
== Étape 1 : Préparez le nœud1 et le nœud2

Démarrez la procédure de remplacement du contrôleur et effectuez des vérifications préalables sur node1 et node2. Si nécessaire, déterminez le type de disques à chiffrement automatique utilisés.

.Étapes
. Lancer le processus de remplacement du contrôleur en entrant la commande suivante dans la ligne de commande ONTAP :
+
[source, cli]
----
system controller replace start -nodes <node_names>
----
+
[NOTE]
====
Vous ne pouvez exécuter la commande qu' `system controller replace start`au niveau de privilège avancé :

[source, cli]
----
set -privilege advanced
----
====
+
Vous obtenez un résultat similaire à l'exemple suivant. Le résultat affiche la version d'ONTAP en cours d'exécution sur votre cluster :

+
....
Warning: 1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedure.
Do you want to continue? {y|n}: y
....
. Sélectionnez `y`, vous voyez la sortie suivante :
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
Le système exécute les contrôles préalables suivants ; notez le résultat de chaque contrôle préalable pour utilisation ultérieure de la procédure :

+
[cols="35,65"]
|===
| Contrôle préalable | Description 


| Vérification de l'état du cluster | Vérifie que tous les nœuds du cluster sont défectueux. 


| Vérification de l'état du transfert d'agrégat | Vérifie si un transfert d'agrégat est déjà en cours. Si un autre transfert d'agrégat est en cours, le contrôle échoue. 


| Vérification du nom du modèle | Vérifie si les modèles de contrôleur sont pris en charge pour cette procédure. Si les modèles ne sont pas pris en charge, la tâche échoue. 


| Vérification du quorum du cluster | Vérifie que les nœuds remplacés se trouvent au quorum. Si les nœuds ne sont pas dans le quorum, la tâche échoue. 


| Vérification de la version de l'image | Vérifie que les nœuds remplacés exécutent la même version de ONTAP. Si les versions des images ONTAP sont différentes, la tâche échoue. La même version de ONTAP 9.x doit être installée sur les nouveaux nœuds. Si une autre version de ONTAP est installée sur les nouveaux nœuds, vous devez netboot les nouveaux contrôleurs après les avoir installés. Pour obtenir des instructions sur la mise à niveau de ONTAP, reportez-vous à la section link:other_references.html["Références"] Pour accéder à _Upgrade ONTAP_. 


| Vérification de l'état DE LA HAUTE DISPONIBILITÉ | Vérifie si les deux nœuds remplacés se trouvent dans une configuration de paires haute disponibilité. Si le basculement du stockage n'est pas activé pour les contrôleurs, la tâche échoue. 


| Vérification de l'état de l'agrégat | Si les nœuds remplacés incluent des agrégats dont ils ne sont pas le propriétaire du site, la tâche échoue. Les nœuds ne doivent pas posséder d'agrégats non locaux. 


| Vérification de l'état du disque | Si l'un des nœuds remplacés contient des disques manquants ou en panne, la tâche échoue. Si des disques sont manquants, reportez-vous à la section link:other_references.html["Références"] pour établir un lien vers la gestion des disques et des agrégats avec l'interface de ligne de commande_, _gestion logique du stockage avec l'interface de ligne de commande_ et _gestion des paires HA_ pour configurer le stockage de la paire HA. 


| Vérification de l'état de la LIF de données | Vérifie si l'un des nœuds remplacés dispose de LIF de données non locales. Les nœuds ne doivent pas contenir de LIFs de données pour lesquelles ils ne sont pas le propriétaire. Si l'un des nœuds contient des LIFs de données non locales, la tâche échoue. 


| État de la LIF de cluster | Vérifie si les LIFs de cluster sont active pour les deux nœuds. Si les LIFs de cluster sont arrêtées, la tâche échoue. 


| AutoSupport Vérification de l'état | Si les notifications AutoSupport ne sont pas configurées, la tâche échoue. Vous devez activer AutoSupport avant de lancer la procédure de remplacement du contrôleur. 


| Vérification de l'utilisation du processeur | Vérifie si le taux d'utilisation du CPU est supérieur à 50 % pour l'un des nœuds remplacés. Si l'utilisation du processeur est supérieure à 50 % pendant une période de temps considérable, la tâche échoue. 


| Contrôle de reconstruction d'agrégats | Vérifie si la reconstruction a lieu sur l'un des agrégats de données. Si la reconstruction d'agrégat est en cours, la tâche échoue. 


| Vérification du travail d'affinité du nœud | Vérifie si des travaux d'affinité de nœud sont en cours d'exécution. Si des tâches d'affinité de nœud sont en cours d'exécution, la vérification échoue. 
|===
. Une fois l'opération de remplacement du contrôleur démarrée et les contrôles préalables terminés, l'opération s'interrompt pour vous permettre de collecter les informations de sortie dont vous aurez peut-être besoin ultérieurement lors de la configuration du noeud 3.
+
[NOTE]
====
Avant de commencer la mise à niveau, vous migrez et réamorcez les LIF du cluster sur deux ports de cluster par nœud si vous disposez d'un système, tel qu'un AFF 700, avec la configuration suivante :

** Plus de deux ports de cluster par nœud
** Une carte d'interconnexion de cluster en slot4 en mode écorché pour créer les ports e4a, e4b, e4c et e4d et les ports e4e, e4f, e4g et e4h


Une mise à niveau de contrôleur avec plus de deux ports de cluster par nœud peut entraîner l'absence de LIF de cluster sur le nouveau contrôleur après la mise à niveau.

Pour plus d'informations, consultez l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Comment supprimer des LIF de cluster inutiles ou indésirables"^].

====
. Exécuter le jeu de commandes ci-dessous comme indiqué par la procédure de remplacement du contrôleur sur la console du système.
+
Depuis le port série connecté à chaque nœud, exécutez et enregistrez les valeurs de sortie des commandes suivantes individuellement :

+
[source, cli]
----
vserver services name-service dns show
----
+
[source, cli]
----
network interface show -curr-node <local> -role cluster,intercluster,node-mgmt,cluster-mgmt,data
----
+
[source, cli]
----
network port show -node <local> -type physical
----
+
[source, cli]
----
service-processor show -node <local> -instance
----
+
[source, cli]
----
network fcp adapter show -node <local>
----
+
[source, cli]
----
network port ifgrp show -node <local>
----
+
[source, cli]
----
system node show -instance -node <local>
----
+
[source, cli]
----
run -node <local> sysconfig
----
+
[source, cli]
----
storage aggregate show -r
----
+
[source, cli]
----
storage aggregate show -node <local>
----
+
[source, cli]
----
volume show -node <local>
----
+
[source, cli]
----
system license show -owner <local>
----
+
[source, cli]
----
storage encryption disk show
----
+
[source, cli]
----
security key-manager onboard show-backup
----
+
[source, cli]
----
security key-manager external show
----
+
[source, cli]
----
security key-manager external show-status
----
+
[source, cli]
----
network port reachability show -detail -node <local>
----
+

NOTE: Si vous utilisez NetApp Volume Encryption (NVE) ou NetApp Aggregate Encryption (NAE) avec le gestionnaire de clés intégré (OKM), conservez la phrase de passe du gestionnaire de clés prête pour effectuer la resynchronisation du gestionnaire de clés plus tard dans la procédure.

. Si votre système utilise des lecteurs auto-cryptés, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Comment savoir si un disque est certifié FIPS"^] Pour déterminer le type de disques à autocryptage utilisés sur la paire haute disponibilité que vous mettez à niveau. Le logiciel ONTAP prend en charge deux types de disques avec autocryptage :
+
--
** Disques SAS ou NVMe NetApp Storage Encryption (NSE) certifiés FIPS
** Disques NVMe non-FIPS à autochiffrement (SED)


https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["En savoir plus sur les disques à autochiffrement pris en charge"^].

--




[[step-2-correct-aggregate-ownership-if-an-arl-precheck-fails]]
== Étape 2 : Corriger la propriété de l'agrégat si une vérification préalable ARL échoue

En cas d'échec de la vérification de l'état de l'agrégat, vous devez renvoyer les agrégats qui appartiennent au nœud partenaire au nœud propriétaire du nœud de rattachement et relancer le processus de vérification préalable.

.Étapes
. Renvoyez les agrégats actuellement détenus par le nœud partenaire au nœud propriétaire de rattachement :
+
[source, cli]
----
storage aggregate relocation start -node <source_node> -destination <destination_node> -aggregate-list *
----
. Vérifiez que ni le nœud1 ni le nœud2 ne possède toujours des agrégats pour lesquels il s'agit du propriétaire actuel (mais pas le propriétaire du domicile) :
+
[source, cli]
----
storage aggregate show -nodes <node_name> -is-home false -fields owner-name, home-name, state
----
+
L'exemple suivant montre la sortie de la commande lorsqu'un nœud est à la fois le propriétaire actuel et le propriétaire du domicile des agrégats :

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----
. Redémarrez le processus de remplacement du contrôleur :
+
[source, cli]
----
system controller replace start -nodes <node_names>
----




[[step-3-prepare-node3-and-node4]]
== Étape 3 : Préparez les nœuds 3 et 4

Vérifiez si la build sur node3 et node4 est une image NODAR (sans chiffrement des données au repos). Si la build est une image NODAR, vous devez installer une image DARE (chiffrement des données au repos).

.Description de la tâche
Effectuez les étapes suivantes sur node3 et node4.

.Étapes
. Démarrez le nœud dans le menu de démarrage :
+
[source, cli]
----
LOADER> boot_ontap menu
----
. Entrez dans systemshell :
+
[source, cli]
----
systemshell
----
. [[check-build]]Vérifiez si la version est une image NODAR :
+
[source, cli]
----
cat /BUILD
----
+
Dans la sortie de la commande, vérifiez si  `build-type` est une image NODAR, par exemple,  `DEBUG SIM NODAR`.

+

NOTE: Si  `build-type` n'est pas une image NODAR, la version est une image DARE.

. Si la version est une image NODAR, installez une image DARE.
+
.. Quittez l'interface système et le menu de démarrage :
+
[source, cli]
----
halt
----
.. Installez une image DARE. Pour plus d'informations, consultez l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/Netbooting_a_FAS_and_AFF_Controller_in_ONTAP_9["Démarrage réseau d’un contrôleur FAS et AFF dans ONTAP 9"^].




.Et la suite ?
Après avoir préparé les nœuds, link:complete-preparation-for-upgrade.html["achever la préparation de la mise à niveau"].
