---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: 'Séquence de processus de l"étape 3 pour une mise à niveau ARL à l"aide des `system controller replace` commandes des contrôleurs exécutant ONTAP 9.15.1 ou version ultérieure.' 
---
= Présentation de la phase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 3, vous installez et démarrez le nœud 3, vérifiez que le cluster et les ports de gestion des nœuds du nœud 1 sont connectés sur le nœud 3 et vérifiez l'installation du nœud 3. Si vous utilisez NetApp Volume Encryption (NVE), vous restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer les LIF de données NAS du nœud 1 et les agrégats non racine du nœud 2 vers le nœud 3, puis vérifier que les LIF SAN existent sur le nœud 3.

.Étapes
. link:install_boot_node3.html["Installez et démarrez le nœud 3"]
. link:verify_node3_installation.html["Vérifiez l'installation du noeud 3"]
. link:restore_key-manager_configuration_node3.html["Restaurez la configuration du gestionnaire de clés sur le noeud 3"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 1 du nœud 2 vers le nœud 3"]

