---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Séquence de processus de l"étape 5 pour une mise à niveau ARL à l"aide des `system controller replace` commandes des contrôleurs exécutant ONTAP 9.15.1 ou version ultérieure.' 
---
= Présentation de la phase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la phase 5, vous installez et démarrez le nœud 4, vérifiez que le cluster et les ports de gestion des nœuds du nœud 2 sont connectés sur le nœud 4, puis vérifiez l'installation du nœud 4. Si vous utilisez NVE, restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer les LIF de données NAS du nœud 2 et les agrégats non racine du nœud 3 vers le nœud 4, puis vérifier que les LIF SAN existent sur le nœud 4.

.Étapes
. link:install_boot_node4.html["Installez et démarrez Node4"]
. link:verify_node4_installation.html["Vérifiez l'installation du node4"]
. link:restore_key-manager_config_node4.html["Restaurez la configuration du gestionnaire de clés sur le nœud 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4"]

