---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 'Choisissez si vous souhaitez utiliser l"ARL pour mettre à niveau les contrôleurs sous ONTAP 9.5 vers 9.7 à l"aide de `system controller replace` commandes.' 
---
= Décider d'utiliser ou non cette procédure de relocalisation globale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs méthodes de relocalisation d'agrégats (ARL) pour mettre à niveau le matériel du contrôleur. Cette procédure décrit comment mettre à niveau le matériel du contrôleur à l'aide de l'ARL et des commandes de remplacement du contrôleur système sur les systèmes exécutant ONTAP 9.7, 9.6 ou 9.5. Cette procédure complexe est réservée aux administrateurs ONTAP expérimentés.

Pour vous aider à décider si cette procédure ARL est adaptée à la mise à niveau du matériel de votre contrôleur, vous devez examiner toutes les circonstances suivantes pour les mises à niveau prises en charge :

* Vous mettez à niveau des contrôleurs NetApp exécutant ONTAP 9.5, 9.6 ou 9.7. Ce document ne s'applique pas aux mises à niveau vers ONTAP 9.8.
* Vous ne souhaitez pas ajouter de nouveaux contrôleurs comme nouvelle paire haute disponibilité au cluster et migrer les données à l'aide des déplacements de volumes.
* Vous avez de l'expérience dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilèges de diagnostic.
* Votre combinaison de mise à niveau matérielle est répertoriée dans le <<sys_commands_95_97_supported_systems,matrice de modèle prise en charge>> .
* Si vous mettez à niveau une configuration MetroCluster, il s'agit d'une configuration FC à 4 nœuds ou supérieure et tous les nœuds exécutent ONTAP 9.6 ou 9.7.


[NOTE]
====
* . Cette procédure ARL inclut les étapes qui garantissent que les disques internes restent sécurisés dans le châssis lorsque vous retirez et installez les contrôleurs pendant la procédure de mise à niveau
+
link:../upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["Découvrez les combinaisons de mise à niveau système prises en charge à l'aide d'ARL, en conservant le châssis et les disques système existants"].

* Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).


====


== Combinaisons de mise à niveau du système prises en charge

Les tableaux suivants présentent la matrice de modèles pris en charge pour la mise à niveau du contrôleur à l'aide de cette procédure ARL.

[cols="50,50"]
|===
| Ancien contrôleur | Remplacement du contrôleur 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700^1^, AFF A800^2^ 


| FAS8200 | FAS8700, FAS9000, FAS8300^4^,^^5^ 


| AFF A300 | AFF A700^1^, AFF A800^2^,^^3^, AFF A400^4^,^^5^ 
|===

NOTE: Si la combinaison de modèle de mise à niveau du contrôleur ne se trouve pas dans le tableau ci-dessus, contactez l'assistance technique.

^1^la mise à niveau automatisée du ARL pour le système AFF A700 est prise en charge à partir de ONTAP 9.7P2.

^2^si vous effectuez une mise à jour vers un AFF A800 ou un système prenant en charge des disques internes et externes, vous devez suivre les instructions spécifiques relatives à l'agrégat racine sur des disques NVMe internes. Voir link:set_fc_or_uta_uta2_config_on_node3.html#step14["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3, étape 14"] et link:set_fc_or_uta_uta2_config_node4.html#step14["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4, étape 14"].

^3^la mise à niveau automatisée d'un AFF A300 vers un système AFF A800 est prise en charge par ONTAP 9.7P5.

^4^la mise à niveau automatisée d'un AFF A300 vers un système AFF A400 et un système FAS8200 vers FAS8300 est prise en charge par ONTAP 9.7P8.

^5^si vous effectuez une mise à niveau depuis un AFF A300 vers un système AFF A400 ou FAS8200 vers un système FAS8300 dans une configuration de cluster sans commutateur à deux nœuds, vous devez choisir les ports de cluster temporaires pour la mise à niveau du contrôleur. Les systèmes AFF A400 et FAS8300 se présentent dans deux configurations sous la forme d'un bundle Ethernet où les ports de carte mezzanine sont de type Ethernet et sous la forme d'un bundle FC où les ports mezzanine sont de type FC.

* Dans le cas d'un système AFF A400 ou FAS8300 avec une configuration de type Ethernet, vous pouvez utiliser n'importe lequel des deux ports mezzanine comme ports de cluster temporaires.
* Pour un système AFF A400 ou FAS8300 avec une configuration de type FC, vous devez ajouter une carte d'interface réseau 10GbE à quatre ports (référence X1147A) pour fournir les ports de cluster temporaires.
* Après avoir effectué la mise à niveau du contrôleur en utilisant des ports de cluster temporaires, vous pouvez migrer les LIF de cluster vers les ports e3a et e3b, 100 GbE sur un système AFF A400 et e0c et e0d, 100 GbE sur un système FAS8300 sans interruption.




== Choisissez une autre procédure de mise à niveau matérielle

* link:../upgrade-arl/index.html["Passez en revue les méthodes ARL alternatives disponibles pour la mise à niveau du matériel du contrôleur"].
* Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.


.Informations associées
Se référer à link:other_references.html["Références"] pour créer un lien vers la _Documentation ONTAP 9_.
