---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: 'Installez et démarrez le nœud 4 et installez le logiciel ONTAP lors de la mise à niveau des contrôleurs exécutant ONTAP 9.5 vers 9.7 à l"aide de l"outil `system controller replace` commandes.' 
---
= Installez et démarrez Node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez installer NODE4 dans le rack, transférer les connexions NODE2 vers node4, démarrer node4 et installer ONTAP. Vous devez ensuite réaffecter tout disque de spare sur le nœud2, tout disque appartenant au volume racine, ainsi que tout agrégat non racine qui n'a pas été déplacé vers le nœud3 plus tôt dans le processus, comme indiqué dans cette section.

.Description de la tâche
L'opération de déplacement est mise en pause au début de cette étape. Ce processus est principalement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. En outre, vous devez vérifier que les LIF de données NAS ont bien été déplacées vers le nœud 4.

Vous devez netboot nœud4 si cette version de ONTAP 9 n'est pas installée sur le nœud 2. Une fois le noeud 4 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers corrects sur le périphérique de démarrage pour les démarrages suivants du système, en suivant les instructions de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

[IMPORTANT]
====
* Pour une mise à niveau du contrôleur AFF A800 ou AFF C800 , vous devez vous assurer que tous les lecteurs du châssis sont fermement fixés contre le plan médian avant de retirer le nœud 2. Pour plus d'informations, voir link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Remplacez les modules de contrôleur AFF A800 ou AFF C800"].
* Si vous mettez à niveau un système avec des disques de stockage, vous devez compléter toute cette section, puis passer à link:set_fc_or_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"] , en entrant des commandes à l'invite du cluster.


====
.Étapes
. [[auto_install4_step1]]Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant.
+
Si le noeud 4 se trouve dans un châssis distinct du noeud 2, vous pouvez placer le noeud 4 au même emplacement que le noeud 3. Si les nœuds 2 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.

. Installez le node4 dans le rack en suivant les instructions de _instructions d'installation et de configuration_ pour le modèle de nœud.
. Reliez le nœud 4, puis déplacez les connexions du nœud 2 vers le nœud 4.
+
Effectuez les connexions suivantes en utilisant les _Instructions d'installation et de configuration_ pour la plate-forme node4, le document d'étagère de disque approprié et la documentation de _gestion des paires HA_.

+
Se référer àlink:other_references.html["Références"] pour créer un lien vers la _gestion des paires HA_.

+
** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC
+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion/carte FC-VI ou la connexion de câble d'interconnexion/FC-VI du node2 au node4 car la plupart des modèles de plateforme disposent de modèles de cartes d'interconnexion uniques. Pour la configuration MetroCluster, vous devez déplacer les connexions des câbles FC-VI du nœud2 au nœud4. Si le nouvel hôte ne dispose pas de carte FC-VI, il vous faudra peut-être déplacer la carte FC-VI.



. Mettez le nœud 4 sous tension, puis interrompez le processus de démarrage en appuyant sur Ctrl-C au niveau du terminal de la console pour accéder à l'invite de l'environnement de démarrage.
+

NOTE: Lors du démarrage du nœud 4, le message d'avertissement suivant peut s'afficher :

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Si le message d'avertissement s'affiche à l'étape 4, effectuez les actions suivantes :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage s'achever.
+

WARNING: *Ne dépassez pas le délai ; ne pas laisser la batterie se charger pourrait entraîner une perte de données.*

+

NOTE: Reportez-vous à la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].





. [[step6]]configurez la connexion netboot en choisissant l'une des actions suivantes.
+

NOTE: Vous devez utiliser le port de gestion et l'IP comme connexion netboot. N'utilisez pas d'IP de la LIF de données et ne subit aucune panne pendant l'exécution de la mise à niveau.

+
[cols="30,70"]
|===
| Si le protocole DHCP (Dynamic Host Configuration Protocol) est... | Alors... 


| Exécution | Configurez la connexion automatiquement en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -auto` 


| Non en cours d'exécution | Configurez manuellement la connexion en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Est l'adresse IP du système de stockage (obligatoire).
`_netmask_` est le masque de réseau du système de stockage (obligatoire).
`_gateway_` est la passerelle du système de stockage (obligatoire).
`_dns_addr_` Est l'adresse IP d'un serveur de noms sur votre réseau (facultatif).
`_dns_domain_` Est le nom de domaine DNS (Domain Name Service). Si vous utilisez ce paramètre facultatif, vous n'avez pas besoin d'un nom de domaine complet dans l'URL du serveur netboot ; vous n'avez besoin que du nom d'hôte du serveur. REMARQUE : d'autres paramètres peuvent être nécessaires pour votre interface. Entrez `help ifconfig` à l'invite du micrologiciel pour plus de détails. 
|===
. Démarrage sur le nœud 4 :
+
[cols="30,70"]
|===
| Pour... | Alors... 


| Systèmes de la gamme FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Tous les autres systèmes | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
Le `<path_to_the_web-accessible_directory>` vous devez indiquer où vous avez téléchargé le `<ontap_version>_image.tgz` À l'étape 1 de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

+

NOTE: N'interrompez pas l'amorçage.

. Dans le menu de démarrage, sélectionnez option `(7) Install new software first`.
+
Cette option de menu permet de télécharger et d'installer la nouvelle image ONTAP sur le périphérique d'amorçage.

+
Ne tenez pas compte du message suivant :

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Cette remarque s'applique aux mises à niveau de ONTAP sans interruption et non aux mises à niveau des contrôleurs.

+

NOTE: Utilisez toujours netboot pour mettre à jour le nouveau nœud vers l'image souhaitée. Si vous utilisez une autre méthode pour installer l'image sur le nouveau contrôleur, il est possible que l'image incorrecte soit installée. Ce problème s'applique à toutes les versions de ONTAP. Procédure netboot combinée avec l'option `(7) Install new software` Efface le support de démarrage et place la même version de ONTAP sur les deux partitions d'image.

. Si vous êtes invité à poursuivre la procédure, entrez `y`, Et lorsque vous êtes invité à saisir l'URL du pack :
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. Procédez comme suit pour redémarrer le module de contrôleur :
+
.. Entrez `n` pour ignorer la récupération de sauvegarde lorsque l'invite suivante s'affiche :
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. Redémarrez en entrant `y` lorsque vous voyez l'invite suivante :
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
Le module de contrôleur redémarre mais s'arrête au menu d'amorçage car le périphérique d'amorçage a été reformaté et les données de configuration doivent être restaurées.



. Sélectionnez le mode maintenance `5` dans le menu de démarrage et entrez `y` lorsque vous êtes invité à poursuivre le démarrage.
. Vérifiez que le contrôleur et le châssis sont configurés en tant que haute disponibilité :
+
`ha-config show`

+
L'exemple suivant montre la sortie du `ha-config show` commande :

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Le système enregistre dans une PROM, qu'il soit dans une paire HA ou dans une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité.

. Si le contrôleur et le châssis ne sont pas configurés comme HA, utilisez les commandes suivantes pour corriger la configuration :
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si vous disposez d'une configuration MetroCluster, utilisez les commandes suivantes pour modifier le contrôleur et le châssis :

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. Quitter le mode maintenance :
+
`halt`

+
Interrompez l'AUTOBOOT en appuyant sur Ctrl-C à l'invite de l'environnement de démarrage.

. [[auto_install4_step15]]sur le noeud 3, vérifiez la date, l'heure et le fuseau horaire du système :
+
`date`

. Sur le nœud 4, vérifiez la date à l'aide de la commande suivante à l'invite de l'environnement d'initialisation :
+
`show date`

. Si nécessaire, définissez la date sur le node4 :
+
`set date _mm/dd/yyyy_`

. Sur le nœud 4, vérifiez l'heure à l'aide de la commande suivante à l'invite de l'environnement d'amorçage :
+
`show time`

. Si nécessaire, définissez l'heure sur le node4 :
+
`set time _hh:mm:ss_`

. Dans le chargeur de démarrage, définissez l'ID système partenaire sur le nœud 4 :
+
`setenv partner-sysid _node3_sysid_`

+
Pour node4, `partner-sysid` doit être celui du noeud 3.

+
Enregistrer les paramètres :

+
`saveenv`

. [[auto_install4_step21]] Vérifiez l' `partner-sysid` pour le nœud 4 :
+
`printenv partner-sysid`



. [[auto_install4_step22]]Si vous avez installé des lecteurs NetApp Storage Encryption (NSE), procédez comme suit :
+

NOTE: Si ce n'est déjà fait, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Comment savoir si un disque est certifié FIPS"^] déterminer le type de disques à autocryptage utilisés.

+
.. Réglez `bootarg.storageencryption.support` à `true` ou `false`:
+
[cols="35,65"]
|===
| Si les lecteurs suivants sont utilisés… | Puis… 


| Disques NSE conformes aux exigences de chiffrement automatique FIPS 140-2 de niveau 2 | `setenv bootarg.storageencryption.support *true*` 


| NetApp non-SED FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Vous ne pouvez pas combiner des disques FIPS avec d'autres types de disques sur le même nœud ou la même paire HA. Vous pouvez utiliser les disques SED avec des disques sans cryptage sur le même nœud ou une paire haute disponibilité.

====
.. Pour obtenir de l'aide sur la restauration des informations de gestion intégrée des clés, contactez le support NetApp.


. Démarrez le nœud dans le menu de démarrage :
+
`boot_ontap menu`



.Et la suite ?
* Si vous avez un système avec une configuration FC ou UTA/UTA2,link:set_fc_or_uta_uta2_config_node4.html["définir la configuration FC ou UTA/UTA2 sur node4"] .
* Si vous n'avez pas de configuration FC ou UTA/UTA2,link:reassign-node2-disks-to-node4.html#reassign-node2-node4-step1["réaffecter les disques du nœud 2 au nœud 4, étape 1"] afin que node4 puisse reconnaître les disques de node2.
* Si vous avez une configuration MetroCluster ,link:set_fc_or_uta_uta2_config_node4.html["définir la configuration FC ou UTA/UTA2 sur node4"] pour détecter les disques attachés au nœud.

