---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node3.html 
keywords: install, boot, node3 relocation, nodes, V-series, storage disks 
summary: 'Installez et démarrez le nœud 3 et installez le logiciel ONTAP lors de la mise à niveau des contrôleurs exécutant ONTAP 9.5 vers 9.7 à l"aide de `system controller replace` commandes.' 
---
= Installez et démarrez le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez installer NODE3 dans le rack, transférer les connexions du noeud 1 vers le noeud 3, démarrer le noeud 3 et installer ONTAP. Vous devez ensuite réaffecter l'un des disques de spare du nœud1, tous les disques appartenant au volume racine et tous les agrégats non racines qui n'ont pas été transférés vers le nœud2 plus tôt dans le processus, comme indiqué dans cette section.

.Description de la tâche
L'opération de déplacement est mise en pause au début de cette étape. Ce processus est largement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. En outre, vous devez vérifier que les LIF SAN ont bien été déplacées vers le nœud 3.

Vous avez besoin de netboot nœud3 si cette version de ONTAP 9 n'est pas installée sur le nœud 1. Une fois le noeud 3 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers corrects sur le périphérique de démarrage pour les démarrages suivants du système, en suivant les instructions de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

.Important :
* Si vous mettez à niveau un système V-Series connecté à des baies de stockage ou à un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous devez le faire <<auto_install3_step1,Étape 1>> à <<auto_install3_step21,Étape 21>>, quittez ensuite cette section et suivez les instructions de la section link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurez les ports FC sur le nœud 3"] et link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3"] Sections si nécessaire, en saisissant des commandes en mode maintenance. Vous devez ensuite revenir à cette section et reprendre avec <<auto_install3_step23,Étape 23>>.
* Si vous mettez à niveau un système avec des disques de stockage, vous devez remplir cette section entière, puis aller à link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurez les ports FC sur le nœud 3"] et link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3"] sections, saisie de commandes à l'invite du cluster.


.Étapes
. [[auto_install3_step1]]Assurez-vous que vous disposez d'un espace rack pour node3.
+
Si les nœuds 1 et 2 se trouvent dans un châssis distinct, vous pouvez placer le nœud 3 au même emplacement de rack que le nœud 1. Toutefois, si le nœud 1 se trouvait dans le même châssis avec le nœud 2, il faut placer le nœud 3 dans son propre espace rack, de préférence à proximité de l'emplacement du nœud 1.

. [[auto_install3_step2]]installez le noeud 3 dans le rack, en suivant les instructions _installation and Setup_ de votre modèle de nœud.
+

NOTE: Si vous effectuez une mise à niveau vers un système contenant les deux nœuds du même châssis, installez le nœud 4 dans le châssis et sur le nœud 3. Si ce n'est pas le cas, lors du démarrage du nœud 3, le nœud se comporte comme s'il se trouvaient dans une configuration à double châssis et lors du démarrage du nœud 4, l'interconnexion entre les nœuds n'apparaît pas.

. [[auto_install3_step3]]Cable node3, déplaçant les connexions du node1 vers le node3.
+
Reliez les connexions suivantes à l'aide des instructions _installation and Setup_ ou des instructions _FlexArray Virtualization installation conditions requises et Reference_ pour la plateforme node3, du document du tiroir disque approprié et de _High Availability Management_.

+
Reportez-vous à la section link:other_references.html["Références"] Pour établir un lien vers les spécifications d'installation de la virtualisation et les références_ et _gestion de la haute disponibilité_ de FlexArray.

+
** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC
+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion ou la connexion du câble d'interconnexion de cluster du nœud 1 vers le nœud 3, car la plupart des modèles de plateforme possèdent un modèle de carte d'interconnexion unique. Pour la configuration MetroCluster, vous devez déplacer les connexions des câbles FC-VI du nœud 1 vers le nœud 3. Si le nouvel hôte ne dispose pas de carte FC-VI, il vous faudra peut-être déplacer la carte FC-VI.



. [[auto_install3_step4]]mettez le système sous tension vers le noeud 3, puis interrompez le processus d'amorçage en appuyant sur Ctrl-C sur le terminal de la console pour accéder à l'invite de l'environnement d'amorçage.
+
Si vous effectuez la mise à niveau vers un système avec les deux nœuds du même châssis, le nœud 4 redémarre également. Vous pouvez toutefois ignorer le démarrage du nœud 4 jusqu'à ce qu'il soit ultérieur.

+

NOTE: Lorsque vous démarrez le nœud 3, le message d'avertissement suivant peut s'afficher :

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]si vous voyez le message d'avertissement dans <<auto_install3_step4,Étape 4>>, procédez comme suit :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage s'achever.
+

WARNING: *Attention : ne pas outrepasser le délai; si la batterie n'est pas chargée, cela pourrait entraîner une perte de données.*

+

NOTE: Reportez-vous à la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].





. [[auto9597_istall3_step6]]configurez la connexion netboot en choisissant l'une des actions suivantes.
+

NOTE: Vous devez utiliser le port de gestion et l'IP comme connexion netboot. N'utilisez pas d'IP de la LIF de données et ne subit aucune panne pendant l'exécution de la mise à niveau.

+
[cols="30,70"]
|===
| Si le protocole DHCP (Dynamic Host Configuration Protocol) est... | Alors... 


| Exécution | Configurez la connexion automatiquement en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -auto` 


| Non en cours d'exécution  a| 
Configurez manuellement la connexion en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Est l'adresse IP du système de stockage (obligatoire).
`_netmask_` est le masque de réseau du système de stockage (obligatoire).
`_gateway_` est la passerelle du système de stockage. (obligatoire).
`_dns_addr_` Est l'adresse IP d'un serveur de noms sur votre réseau (facultatif).
`_dns_domain_` Est le nom de domaine DNS (Domain Name Service). Si vous utilisez ce paramètre facultatif, vous n'avez pas besoin d'un nom de domaine complet dans l'URL du serveur netboot ; vous n'avez besoin que du nom d'hôte du serveur.


NOTE: D'autres paramètres peuvent être nécessaires pour votre interface. Entrez `help ifconfig` à l'invite du micrologiciel pour plus de détails.

|===
. [[step7]]exécutez sur le nœud 3 :
+
[cols="30,70"]
|===
| Pour... | Alors... 


| Systèmes de la gamme FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Tous les autres systèmes | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
Le `<path_to_the_web-accessible_directory>` vous devez indiquer où vous avez téléchargé le `<ontap_version>_image.tgz` dans la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

+

NOTE: N'interrompez pas l'amorçage.

. [[step8]]] dans le menu de démarrage, sélectionnez option `(7) Install new software first`.
+
Cette option de menu permet de télécharger et d'installer la nouvelle image ONTAP sur le périphérique d'amorçage.

+
Ne tenez pas compte du message suivant :

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Cette remarque s'applique aux mises à niveau de ONTAP sans interruption et non aux mises à niveau des contrôleurs.

+

NOTE: Utilisez toujours netboot pour mettre à jour le nouveau nœud vers l'image souhaitée. Si vous utilisez une autre méthode pour installer l'image sur le nouveau contrôleur, il est possible que l'image incorrecte soit installée. Ce problème s'applique à toutes les versions de ONTAP. Procédure netboot combinée avec l'option `(7) Install new software` Efface le support de démarrage et place la même version de ONTAP sur les deux partitions d'image.

. [[step9]]si vous êtes invité à poursuivre la procédure, entrez `y`, Et lorsque vous êtes invité à saisir l'URL du pack :
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]]effectuez les sous-étapes suivantes pour redémarrer le module de contrôleur :
+
.. Entrez `n` pour ignorer la récupération de sauvegarde lorsque l'invite suivante s'affiche :
+
`Do you want to restore the backup configuration now? {y|n}`

.. Entrez `y` pour redémarrer lorsque vous voyez l'invite suivante :
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
Le module de contrôleur redémarre mais s'arrête au menu d'amorçage car le périphérique d'amorçage a été reformaté et les données de configuration doivent être restaurées.



. [[step11]]sélectionnez le mode de maintenance `5` dans le menu de démarrage et entrez `y` lorsque vous êtes invité à poursuivre le démarrage.
. [[step12]]vérifier que le contrôleur et le châssis sont configurés comme haute disponibilité :
+
`ha-config show`

+
L'exemple suivant montre la sortie du `ha-config show` commande :

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: Le système enregistre dans une PROM, qu'il soit dans une paire HA ou dans une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité.

. [[step13]]si le contrôleur et le châssis ne sont pas configurés comme HA, utilisez les commandes suivantes pour corriger la configuration :
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si vous disposez d'une configuration MetroCluster, utilisez les commandes suivantes pour modifier le contrôleur et le châssis :

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[step14]]quitter le mode maintenance :
+
`halt`

+
Interrompez l'AUTOBOOT en appuyant sur Ctrl-C à l'invite de l'environnement de démarrage.

. [[step15]]sur le noeud 2, vérifiez la date, l'heure et le fuseau horaire du système :
+
`date`

. [[step16]]sur le noeud 3, vérifiez la date à l'aide de la commande suivante à l'invite de l'environnement d'initialisation :
+
`show date`

. [[step17]]si nécessaire, définissez la date sur le noeud 3 :
+
`set date _mm/dd/yyyy_`

. [[step18]]sur le noeud 3, vérifiez l'heure à l'aide de la commande suivante à l'invite de l'environnement d'initialisation :
+
`show time`

. [[step19]]si nécessaire, définissez l'heure sur le noeud 3 :
+
`set time _hh:mm:ss_`

. [[step20]]dans le chargeur de démarrage, définissez l'ID système partenaire sur le noeud 3 :
+
`setenv partner-sysid _node2_sysid_`

+
Pour le nœud 3, `partner-sysid` doit être celui du node2.

+
.. Enregistrer les paramètres :
+
`saveenv`



. [[auto_install3_step21]]Vérifiez l' `partner-sysid` pour le nœud 3 :
+
`printenv partner-sysid`

. [[step22]]effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si votre système... | Description 


| Possède des disques et aucun stockage interne | Accédez à <<auto_install3_step23,Étape 23>> 


| Est un système V-Series ou un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage  a| 
.. Passez à la section link:set_fc_or_uta_uta2_config_on_node3.html["Configuration FC ou UTA/UTA2 sur le nœud 3"] complétez les sous-sections de cette section.
.. Revenez à cette section et suivez les étapes restantes, en commençant par <<auto_install3_step23,Étape 23>>.



IMPORTANT: Vous devez reconfigurer les ports intégrés FC, les ports intégrés CNA et les cartes CNA avant de démarrer ONTAP sur le système V-Series ou sur le système avec le logiciel de virtualisation FlexArray.

|===
. [[auto_install3_step23]]Ajoutez les ports d'initiateur FC du nouveau nœud aux zones de commutation.
+
Si votre système dispose d'un SAN sur bandes, vous devez segmentation pour les initiateurs. Si nécessaire, modifiez les ports intégrés sur l'initiateur en consultant le link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configuration des ports FC sur le nœud3"]. Reportez-vous à la documentation relative à votre matrice de stockage et à la segmentation pour plus d'instructions sur le zonage.

. [[step24]]Ajouter les ports d'initiateur FC à la baie de stockage en tant que nouveaux hôtes, en mappant les LUN de la baie aux nouveaux hôtes.
+
Reportez-vous à la documentation relative à votre matrice de stockage et au zoning pour obtenir des instructions.

. [[step25]]Modifier les valeurs du nom de port mondial (WWPN) dans les groupes d'hôtes ou de volumes associés aux LUN de baie de stockage.
+
L'installation d'un nouveau module de contrôleur modifie les valeurs WWPN associées à chaque port FC intégré.

. [[step26]]si votre configuration utilise un zoning basé sur des commutateurs, ajustez le zoning pour refléter les nouvelles valeurs WWPN.


. Si des disques NetApp Storage Encryption (NSE) sont installés, effectuez les opérations suivantes.
+

NOTE: Si ce n'est déjà fait, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Comment savoir si un disque est certifié FIPS"^] déterminer le type de disques à autocryptage utilisés.

+
.. Réglez `bootarg.storageencryption.support` à `true` ou `false`:
+
[cols="35,65"]
|===
| Si les lecteurs suivants sont utilisés… | Puis… 


| Disques NSE conformes aux exigences de chiffrement automatique FIPS 140-2 de niveau 2 | `setenv bootarg.storageencryption.support *true*` 


| NetApp non-SED FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Vous ne pouvez pas combiner des disques FIPS avec d'autres types de disques sur le même nœud ou la même paire HA. Vous pouvez utiliser les disques SED avec des disques sans cryptage sur le même nœud ou une paire haute disponibilité.

====
.. Pour obtenir de l'aide sur la restauration des informations de gestion intégrée des clés, contactez le support NetApp.


. Nœud de démarrage dans le menu de démarrage :
+
`boot_ontap menu`

+
Si vous ne disposez pas de configuration FC ou UTA/UTA2, effectuez les opérations suivantes link:set_fc_or_uta_uta2_config_node4.html#auto_check_4_step15["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4, étape 15"] afin que le nœud4 puisse reconnaître les disques du nœud2.

. [[auto9597_istall3_step29]]]pour une configuration MetroCluster, les systèmes V-Series et les systèmes avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, allez à l'adresse link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3, étape 15"].

