---
sidebar: sidebar 
permalink: upgrade-arl-auto/manage_storage_encryption_using_okm.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: 'Configurez et gérez le cryptage du stockage, gérez les clés d"authentification et mettez au repos les relations SnapMirror lors de la mise à niveau des contrôleurs exécutant ONTAP 9.5 vers 9.7 à l"aide de `system controller replace` commandes.' 
---
= Finalisez la préparation de la mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




== Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré

Utilisez le Gestionnaire de clés intégré (OKM) pour gérer les clés de chiffrement. Si l'OKM est configuré, vous devez enregistrer la phrase de passe et les données de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Notez la phrase de passe à l'échelle du cluster.
+
Il s'agit de la phrase secrète saisie lorsque le gestionnaire de clés intégré OKM a été configuré ou mis à jour via l'interface de ligne de commandes ou l'API REST.

. Vérifiez la phrase de passe et le fonctionnement du key-manager :
+
`security key-manager onboard sync`

+
Lorsque vous y êtes invité, saisissez la phrase secrète OKM à l'échelle du cluster que vous avez enregistrée à l'étape précédente.

. Vérifiez que cc-mode est activé en consultant le résultat de la commande suivante :
+
`security key-manager config show`

. Sauvegardez les informations du key-manager :
+
`security key-manager onboard show-backup`





== Facultativement, mettre en pause les relations SnapMirror

Avant de poursuivre l'opération, vous devez confirmer que toutes les relations SnapMirror sont suspendues. Lorsqu'une relation SnapMirror est mise en veille, elle reste suspension sur l'ensemble des redémarrages et basculements.

.Étapes
. Vérifier l'état de la relation SnapMirror sur le cluster destination :
+
`snapmirror show`

+
[NOTE]
====
Si l'état est « transfert », vous devez annuler ces transferts :
`snapmirror abort -destination-vserver _vserver_name_`

====
+
L'annulation échoue si la relation SnapMirror n'est pas à l'état « Transferring ».

. Arrêter toutes les relations entre le cluster :
+
`snapmirror quiesce -destination-vserver *`


