---
sidebar: sidebar 
permalink: upgrade-arl-auto/reassign-node1-disks-to-node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: 'Vous pouvez configurer les ports FC intégrés des nœuds 3, les ports UTA/UTA2 ou la carte UTA/UTA2 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.5 vers 9.7 à l"aide de `system controller replace` commandes.' 
---
= Réaffectez les disques du nœud 1 au nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez réaffecter les disques appartenant au nœud 1 au nœud 3 avant de vérifier l'installation du nœud 3.

.Étapes
. [[reassign-node1-node3-step1]]Vérifiez que le nœud 1 s'est arrêté au menu de démarrage et réaffectez les disques du nœud 1 au nœud 3 :
+
`boot_after_controller_replacement`

+
Après un bref délai, vous êtes invité à saisir le nom du nœud en cours de remplacement. S'il existe des disques partagés (également appelés partitionnement de disque avancé ou des disques partitionnés), vous êtes invité à saisir le nom de nœud du partenaire haute disponibilité.

+
Ces invites peuvent être enfouies dans les messages de la console. Si vous ne saisissez pas de nom de nœud ou si vous saisissez un nom incorrect, vous êtes invité à saisir de nouveau le nom.

+
.Développez l'exemple de sortie de la console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement)   Boot after controller upgrade
(9a)                                  Unpartition all disks and remove their ownership information.
(9b)                                  Clean configuration and initialize node with partitioned disks.
(9c)                                  Clean configuration and initialize node with whole disks.
(9d)                                  Reboot the node.
(9e)                                  Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to
disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login:
...
----
====
. Si le système entre dans une boucle de redémarrage avec le message `no disks found` , c'est parce qu'il a réinitialisé les ports au mode cible et qu'il est donc incapable de voir aucun disque.  Effectuer<<auto_check3_step3,Étape 3>> à<<auto_check3_step8,Étape 8>> sur le nœud 3 pour résoudre ce problème.
. [[auto_check3_step3]]appuyez sur Ctrl-C pendant l'AUTOBOOT pour arrêter le nœud à l'invite du CHARGEUR>.
. [[step18]]à l'invite du CHARGEUR, entrer en mode maintenance :
+
`boot_ontap maint`

. [[step19]]en mode maintenance, affichez tous les ports initiateurs précédemment définis qui sont maintenant en mode cible :
+
`ucadmin show`

+
Modifier les ports en mode initiateur :

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[step20]]Vérifiez que les ports ont été modifiés en mode initiateur :
+
`ucadmin show`

. [[step21]]Quitter le mode maintenance :
+
`halt`

+
[NOTE]
====
Si vous effectuez une mise à niveau à partir d'un système qui prend en charge des disques externes vers un système qui prend également en charge <<auto_check3_step8,Étape 8>>des disques externes, passez à l' .

Si vous effectuez une mise à niveau à partir d'un système prenant en charge des disques externes vers un système prenant en charge des disques internes et externes, par exemple, un système AFF A800, passez à <<auto_check3_step9,Étape 9>>l' .

====
. [[auto_check3_step8]]à l'invite du CHARGEUR, démarrez :
+
`boot_ontap menu`

+
Maintenant, au démarrage, le nœud peut détecter tous les disques qui lui étaient précédemment affectés et peut démarrer comme prévu.

+
Lorsque les nœuds de cluster que vous remplacez utilisent le chiffrement de volume racine, ONTAP ne peut pas lire les informations de volume à partir des disques. Restaurer les clés du volume root:

+
.. Revenir au menu de démarrage spécial :
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Sélectionnez *(10) définir les secrets de récupération du gestionnaire de clés intégré*
.. Entrez `y` à l'invite suivante :
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. À l'invite, entrez la phrase de passe du gestionnaire de clés.
.. Entrez les données de sauvegarde lorsque vous y êtes invité.
+

NOTE: Vous devez avoir obtenu la phrase de passe et les données de sauvegarde dans le link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"] section de cette procédure.

.. Une fois que le système a de nouveau démarré dans le menu de démarrage spécial, exécutez l'option *(1) démarrage normal*
+

NOTE: Il se peut que vous rencontriez une erreur à ce stade. Si une erreur se produit, répétez les sous-étapes de la section <<auto_check3_step8,Étape 8>> jusqu'à ce que le système démarre normalement.



. [[auto_check3_step9]]Si vous effectuez une mise à niveau d'un système avec des disques externes vers un système prenant en charge les disques internes et externes (systèmes AFF A800 , par exemple), définissez l'agrégat node1 comme agrégat racine pour confirmer que node3 démarre à partir de l'agrégat racine de node1.  Pour définir l'agrégat racine, accédez au menu de démarrage sur le nœud 3 et sélectionnez l'option `5` pour entrer en mode maintenance.
+

CAUTION: *Vous devez exécuter les sous-étapes suivantes dans l'ordre exact indiqué ; le non-respect de cette consigne peut entraîner une panne ou même une perte de données.*

+
La procédure suivante définit le nœud 3 pour démarrer à partir de l'agrégat racine du nœud 1 :

+
.. Passer en mode maintenance :
+
`boot_ontap maint`

.. Vérifier les informations RAID, plex et checksum du noeud 1 :
+
`aggr status -r`

.. Vérifier le statut de l'agrégat du nœud 1 :
+
`aggr status`

.. Si nécessaire, mettre l'agrégat du nœud 1 en ligne :
+
`aggr_online root_aggr_from___node1__`

.. Empêcher le démarrage du nœud 3 à partir de son agrégat racine d'origine :
+
`aggr offline _root_aggr_on_node3_`

.. Définir l'agrégat racine du nœud 1 en tant que nouvel agrégat racine pour le nœud 3 :
+
`aggr options aggr_from___node1__ root`

.. Vérifier que l'agrégat racine du nœud 3 est hors ligne et que l'agrégat racine des disques transférées depuis le nœud 1 est en ligne et défini à la racine :
+
`aggr status`

+

NOTE: Si vous ne procédez pas à la sous-étape précédente, le noeud 3 risque de démarrer à partir de l'agrégat racine interne, ou le système peut supposer qu'une nouvelle configuration de cluster existe ou vous inviter à en identifier une.

+
Voici un exemple de sortie de la commande :

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



