---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html 
keywords: node4, interface group, VLANs, broadcast domains, re-create 
summary: 'Créez à nouveau les VLAN, les groupes d"interface et les domaines de diffusion du nœud 2 sur le nœud 4 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.5 vers 9.7 à l"aide de `system controller replace` commandes.' 
---
= Recréez des VLAN, des groupes d'interface et des domaines de diffusion sur le node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Une fois que vous avez confirmé que le nœud4 est quorum et que vous pouvez communiquer avec le nœud3, vous devez recréer les VLAN, les groupes d'interface et les domaines de diffusion du nœud2 sur le nœud4. Vous devez également ajouter les ports node3 aux domaines de diffusion nouvellement créés.

.Description de la tâche
Pour plus d'informations sur la création et la recrércréation de VLAN, de groupes d'interfaces et de domaines de diffusion, accédez à link:other_references.html["Références"] Et lien vers _Network Management_.

.Étapes
. Recréez les réseaux locaux virtuels sur le nœud 4 à l'aide des informations du nœud 2 enregistrées dans le système link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Transférez des agrégats non racines et des LIF de données NAS du nœud 2 vers le nœud 3"] section :
+
`network port vlan create -node _node4_ -vlan _vlan-names_`

. Recréez les groupes d'interface sur le node4 à l'aide des informations du node2 enregistrées dans le link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Transférez des agrégats non racines et des LIF de données NAS du nœud 2 vers le nœud 3"] section :
+
`network port ifgrp create -node _node4_ -ifgrp _port_ifgrp_names_-distr-func`

. Recréez les domaines de diffusion sur le node4 à l'aide des informations node2 enregistrées dans le link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Transférez des agrégats non racines et des LIF de données NAS du nœud 2 vers le nœud 3"] section :
+
`network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names_ -mtu _mtu_size_ -ports _node_name:port_name,node_name:port_name_`

. Ajoutez les ports node4 aux domaines de diffusion nouvellement créés :
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_names_ -ports _node_name:port_name,node_name:port_name_`


