---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_5_index.html 
keywords: install, boot, node4, node2, node-management,  stage 5 
summary: 'Étape 5 : séquence de processus pour la mise à niveau d"ARL à l"aide de `system controller replace` Commandes des contrôleurs exécutant ONTAP 9.5 à 9.7.' 
---
= Présentation de la phase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Au cours de l'étape 5, vous installez et amorcez le nœud 4, mappez les ports de gestion de cluster et de nœud du nœud 2 au nœud 4, réaffectez les disques du nœud 2 au nœud 4 et vérifiez l'installation du nœud 4. Si nécessaire, définissez la configuration FC ou UTA/UTA2 sur le nœud 4 et vérifiez que le quorum du nœud 4 est atteint. Vous pouvez également transférer les LIF de données NAS du nœud 2 et les agrégats non racine du nœud 3 vers le nœud 4, puis vérifier que les LIF SAN existent sur le nœud 4.

.Étapes
. link:install_boot_node4.html["Installez et démarrez Node4"]
. link:set_fc_or_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"]
. link:reassign-node2-disks-to-node4.html["Réaffectez les disques du nœud 2 au nœud 4"]
. link:map_ports_node2_node4.html["Mappage des ports du node2 au node4"]
. link:join_quorum_node_has_different_ports_stage5.html["Joignez le quorum lorsqu'un nœud dispose d'un ensemble différent de ports réseau"]
. link:verify_node4_installation.html["Vérifiez l'installation du node4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4"]

