---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_3_index.html 
keywords: stage 3, install node3, non-SAN data LIFs, non-root aggregates 
summary: 'Étape 3 : séquence de processus pour la mise à niveau d"ARL à l"aide de `system controller replace` Commandes des contrôleurs exécutant ONTAP 9.5 à 9.7.' 
---
= Présentation de la phase 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Au cours de l'étape 3, vous installez et amorcez le nœud 3, mappez les ports de gestion de cluster et de nœud du nœud 1 au nœud 3, réaffectez les disques du nœud 1 au nœud 3 et vérifiez l'installation du nœud 3. Si nécessaire, définissez la configuration FC ou UTA/UTA2 sur le nœud 3 et vérifiez que le nœud 3 a rejoint le quorum. Vous pouvez également transférer les LIF de données NAS du nœud 1 et les agrégats non racine du nœud 2 vers le nœud 3, puis vérifier que les LIF SAN existent sur le nœud 3.

.Étapes
. link:install_boot_node3.html["Installez et démarrez le nœud 3"]
. link:set_fc_or_uta_uta2_config_on_node3.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 3"]
. link:reassign-node1-disks-to-node3.html["Réaffectez les disques du nœud 1 au nœud 3"]
. link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"]
. link:join_quorum_node_has_different_ports_stage3.html["Jonction du quorum lorsqu'un nœud dispose d'un ensemble différent de ports réseau"]
. link:verify_node3_installation.html["Vérifiez l'installation du noeud 3"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 1 du nœud 2 vers le nœud 3"]

