= 
:allow-uri-read: 



NOTE: Le propriétaire du home-home pour les agrégats et les LIFs n'est pas modifié ; seul le propriétaire actuel est modifié.

.Étapes
. Reprendre les opérations de transfert d'agrégats et de déplacement de LIF de données NAS :
+
`system controller replace resume`

+
Tous les agrégats non racine et les LIF de données NAS sont migrés du nœud 1 vers le nœud 2.

+
L'opération s'interrompt pour vous permettre de vérifier si tous les agrégats non-racine du nœud 1 et les LIF de données non-SAN ont été migrés vers le nœud 2.

. Vérifier le statut du transfert d'agrégats et du déplacement des LIF de données NAS :
+
`system controller replace show-details`

. Lorsque l'opération est toujours en pause, vérifiez que tous les agrégats non racines sont en ligne pour leur état sur le nœud 2 :
+
`storage aggregate show -node _node2_ -state online -root false`

+
L'exemple suivant montre que les agrégats non-root du noeud 2 sont en ligne :

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Si les agrégats ont été mis hors ligne ou sont devenus étrangers sur le nœud 2, les mettre en ligne en utilisant la commande suivante sur le nœud 2, une fois pour chaque agrégat :

+
`storage aggregate online -aggregate _aggr_name_`

. Vérifier que tous les volumes sont en ligne sur le nœud 2 à l'aide de la commande suivante sur le nœud 2 et en examinant la sortie correspondante :
+
`volume show -node _node2_ -state offline`

+
Si un volume est hors ligne sur le nœud 2, mettez-le en ligne à l'aide de la commande suivante sur le nœud 2, une fois pour chaque volume :

+
`volume online -vserver _vserver_name_ -volume _volume_name_`

+
Le `_vserver_name_` pour utiliser cette commande avec cette commande, figure dans la sortie du précédent `volume show` commande.


