= Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3
:allow-uri-read: 




== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3

Si le nœud 3 est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez vérifier la configuration des ports et éventuellement les reconfigurer, en fonction du mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Si vous souhaitez utiliser un port UTA/UTA2 (Unified Target adapter) pour FC, vous devez d'abord vérifier la configuration du port.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Vous pouvez utiliser le `ucadmin show` commande pour afficher ou vérifier la configuration actuelle du port, comme indiqué dans l'exemple de sortie suivant :

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Les ports UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément le trafic NIC et FCoE sur la même interface SFP+ 10 GbE et prend en charge les cibles FC.

Les ports UTA/UTA2 peuvent être trouvés sur un adaptateur complémentaire ou sur la carte mère du contrôleur et avoir les configurations suivantes, mais vous devez vérifier la configuration des ports UTA/UTA2 sur le node3 et la modifier, si nécessaire :

* Les cartes UTA/UTA2 commandées lors de la commande du contrôleur sont configurées avant l'expédition pour avoir la personnalité que vous demandez.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés avant l'expédition pour personnaliser votre demande.
+

WARNING: Vous devez être en mode Maintenance pour configurer les ports UTA/UTA2.  Saisissez les commandes de cette section à l’invite du shell en mode Maintenance.



.Étapes
. Si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. Vérifiez les paramètres du port UTA/UTA2 :
+
`ucadmin show`

+
Examinez la sortie et déterminez si les ports UTA/UTA2 ont la personnalité souhaitée.

+
La sortie dans l'exemple suivant montre que le type d'adaptateur « 1b » passe à l'initiateur et que le mode des adaptateurs « 2a » et « 2b » passe à « cna ».  Le mode CNA vous permet d'utiliser la carte comme adaptateur réseau.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si les ports UTA/UTA2... | Puis… 


| N'avez pas la personnalité que vous voulez | Aller à<<auto_check3_step4,Étape 4>> . 


| Avoir la personnalité que vous voulez | Sautez les étapes 4 à 8 et passez à<<auto_check3_step9,Étape 9>> . 
|===
. [[auto_check3_step4]]Effectuez l’une des actions suivantes :
+
[cols="30,70"]
|===
| Si vous configurez... | Puis… 


| Ports sur carte UTA/UTA2 | Aller à<<auto_check3_step5,Étape 5>> 


| Ports UTA/UTA2 intégrés | Sautez l'étape 5 et accédez à<<auto_check3_step6,Étape 6>> . 
|===
. [[auto_check3_step5]]Si l'adaptateur est en mode initiateur et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter <adapter_name>`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode maintenance.

. [[auto_check3_step6]]Si la configuration actuelle ne correspond pas à l'utilisation souhaitée, modifiez la configuration selon vos besoins :
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` est le mode personnalité, `fc` ou `cna`.
** `-t` Est de type FC4, `target` ou `initiator`.
+

NOTE: Vous devez utiliser l'initiateur FC pour les lecteurs de bande et les configurations MetroCluster .  Vous devez utiliser la cible FC pour les clients SAN.



. Placez tous les ports cibles en ligne en entrant la commande suivante une fois pour chaque port :
+
`storage enable adapter <adapter_name>`

. Reliez le port.

