= 
:allow-uri-read: 


. [[auto_check_4_step17]]appuyez sur `Ctrl-C` dans le cas de l'autoboot, cette variable permet d'arrêter le nœud sur le `LOADER>` à l'invite.
. À l'invite du chargeur, passez en mode maintenance :
+
`boot_ontap maint`

. En mode maintenance, afficher tous les ports initiateurs précédemment définis qui sont maintenant en mode cible :
+
`ucadmin show`

+
Modifier les ports en mode initiateur :

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Vérifiez que les ports ont été modifiés en mode initiateur :
+
`ucadmin show`

. Quitter le mode maintenance :
+
`halt`

+
[NOTE]
====
Si vous effectuez une mise à niveau à partir d'un système prenant en charge des disques externes vers un système qui prend également en charge des disques externes, accédez à <<auto_check_4_step22,Étape 22>>.

Si vous effectuez une mise à niveau à partir d'un système qui utilise des disques externes vers un système prenant en charge des disques internes et externes, par exemple un système AFF A800, rendez-vous sur <<auto_check_4_step23,Étape 23>>.

====
. [[auto_check_4_step22]]à l'invite du chargeur, démarrez :
+
`boot_ontap menu`

+
Maintenant, au démarrage, le nœud peut détecter tous les disques qui lui étaient précédemment affectés et peut démarrer comme prévu.

+
Lorsque les nœuds de cluster que vous remplacez utilisent le chiffrement de volume root, le logiciel ONTAP ne peut pas lire les informations de volume des disques. Restaurer les clés du volume root:

+
.. Revenir au menu de démarrage spécial :
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Sélectionnez *(10) définir les secrets de récupération du gestionnaire de clés intégré*
.. Entrez `y` à l'invite suivante :
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. À l'invite, entrez la phrase de passe du gestionnaire de clés.
.. Entrez les données de sauvegarde lorsque vous y êtes invité.
+

NOTE: Vous devez avoir obtenu la phrase de passe et les données de sauvegarde dans le link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"] section de cette procédure.

.. Une fois que le système a de nouveau démarré dans le menu de démarrage spécial, exécutez l'option *(1) démarrage normal*
+

NOTE: Il se peut que vous rencontriez une erreur à ce stade. Si une erreur se produit, répétez les sous-étapes de la section <<auto_check_4_step22,Étape 22>> jusqu'à ce que le système démarre normalement.




