= Configurez les ports FC sur le nœud 4
:allow-uri-read: 




== Configurez les ports FC sur le nœud 4

Si le nœud 4 dispose de ports FC, intégrés ou sur un adaptateur FC complémentaire, vous devez définir les configurations de port sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés lors de l'expédition des systèmes.  Si vous ne configurez pas les ports comme requis, vous risquez de subir une interruption de service.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 2 que vous avez enregistrées dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'un adaptateur UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>>.


IMPORTANT: Saisissez les commandes de cette section à l’invite du shell en mode Maintenance.

.Étapes
. Afficher des informations sur tous les adaptateurs réseau FC et convergés du système :
+
`system node hardware unified-connect show`

. Comparez les paramètres FC sur le nœud4 avec ceux que vous avez capturés précédemment à partir du nœud1.
. Modifier les ports FC sur le nœud 4 si nécessaire :
+
** Pour programmer comme ports cibles :
+
`ucadmin modify -m fc -t target _adapter_`

+
Par exemple: `ucadmin modify -m fc -t target 2a`

** Pour programmer les ports initiateurs :
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` Est le type FC4 : cible ou initiateur.

+
Par exemple: `ucadmin modify -m fc -t initator 2b`



. Arrêter le nœud :
+
`halt`

. Démarrez le système à partir de l'invite du CHARGEUR :
+
`boot_ontap menu`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Sélectionnez option `5` dans le menu de démarrage pour le mode maintenance.

