= Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré
:allow-uri-read: 




== Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré

Utilisez le Gestionnaire de clés intégré (OKM) pour gérer les clés de chiffrement. Si l'OKM est configuré, vous devez enregistrer la phrase de passe et les données de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Notez la phrase de passe à l'échelle du cluster.
+
Il s'agit de la phrase secrète saisie lorsque le gestionnaire de clés intégré OKM a été configuré ou mis à jour via l'interface de ligne de commandes ou l'API REST.

. Vérifiez la phrase de passe et le fonctionnement du key-manager :
+
`security key-manager onboard sync`

+
Lorsque vous y êtes invité, saisissez la phrase secrète OKM à l'échelle du cluster que vous avez enregistrée à l'étape précédente.

. Vérifiez que cc-mode est activé en consultant le résultat de la commande suivante :
+
`security key-manager config show`

. Sauvegardez les informations du key-manager :
+
`security key-manager onboard show-backup`


