= 
:allow-uri-read: 


. [[auto_check3_step17]]appuyez sur `Ctrl-C` dans le cas de l'autoboot, cette variable permet d'arrêter le nœud sur le `LOADER>` à l'invite.
. [[step18]]à l'invite du chargeur, entrer en mode maintenance :
+
`boot_ontap maint`

. [[step19]]en mode maintenance, affichez tous les ports initiateurs précédemment définis qui sont maintenant en mode cible :
+
`ucadmin show`

+
Modifier les ports en mode initiateur :

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[step20]]Vérifiez que les ports ont été modifiés en mode initiateur :
+
`ucadmin show`

. [[step21]]Quitter le mode maintenance :
+
`halt`

+
[NOTE]
====
Si vous effectuez une mise à niveau à partir d'un système prenant en charge des disques externes vers un système qui prend également en charge des disques externes, accédez à <<auto_check3_step22,Étape 22>>.

Si vous mettez à niveau à partir d'un système prenant en charge des disques externes vers un système prenant en charge des disques internes et externes, par exemple un système AFF A800, rendez-vous sur <<auto_check3_step23,Étape 23>>.

====
. [[auto_check3_step22]]à l'invite du chargeur, démarrez :
+
`boot_ontap`

+
Maintenant, au démarrage, le nœud peut détecter tous les disques qui lui étaient précédemment affectés et peut démarrer comme prévu.

. [[auto_check3_step23]]si vous effectuez une mise à niveau depuis un système avec des disques externes vers un système qui prend en charge des disques internes et externes (systèmes AFF A800, par exemple), définissez l'agrégat node1 comme agrégat racine pour confirmer que ce dernier démarre depuis l'agrégat racine du nœud1. Pour définir l'agrégat root, aller au menu de boot et faire une sélection `5` pour passer en mode maintenance.
+

CAUTION: *Vous devez exécuter les sous-étapes suivantes dans l'ordre exact indiqué ; le non-respect de cette consigne peut entraîner une panne ou même une perte de données.*

+
La procédure suivante définit le nœud 3 pour démarrer à partir de l'agrégat racine du nœud 1 :

+
.. Passer en mode maintenance :
+
`boot_ontap maint`

.. Vérifier les informations RAID, plex et checksum du noeud 1 :
+
`aggr status -r`

.. Vérifier le statut de l'agrégat du nœud 1 :
+
`aggr status`

.. Si nécessaire, mettre l'agrégat du nœud 1 en ligne :
+
`aggr_online root_aggr_from___node1__`

.. Empêcher le démarrage du nœud 3 à partir de son agrégat racine d'origine :
+
`aggr offline _root_aggr_on_node3_`

.. Définir l'agrégat racine du nœud 1 en tant que nouvel agrégat racine pour le nœud 3 :
+
`aggr options aggr_from___node1__ root`

.. Vérifier que l'agrégat racine du nœud 3 est hors ligne et que l'agrégat racine des disques transférées depuis le nœud 1 est en ligne et défini à la racine :
+
`aggr status`

+

NOTE: Si vous ne procédez pas à la sous-étape précédente, le noeud 3 risque de démarrer à partir de l'agrégat racine interne, ou le système peut supposer qu'une nouvelle configuration de cluster existe ou vous inviter à en identifier une.

+
Voici un exemple de sortie de la commande :

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



