= 
:allow-uri-read: 


Vous devez redémarrer le nœud 4 sur le réseau si la version ONTAP sur le nœud 4 est différente de la version ONTAP sur le nœud 2. Après avoir installé node4, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur web. Vous pouvez ensuite télécharger les fichiers appropriés sur le périphérique de démarrage pour les démarrages système ultérieurs en suivant les instructions du link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

[IMPORTANT]
====
* Pour une mise à niveau du contrôleur AFF A800 ou AFF C800 , vous devez vous assurer que tous les lecteurs du châssis sont fermement fixés contre le plan médian avant de retirer le nœud 2. Pour plus d'informations, voir link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Remplacez les modules de contrôleur AFF A800 ou AFF C800"].
* Si vous mettez à niveau un système avec des disques de stockage, vous devez compléter toute cette section, puis passer à link:set_fc_or_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"] , en entrant des commandes à l'invite du cluster.


====
.Étapes
. [[auto_install4_step1]]Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant.
+
Si le noeud 4 se trouve dans un châssis distinct du noeud 2, vous pouvez placer le noeud 4 au même emplacement que le noeud 3. Si les nœuds 2 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.

. Installez le node4 dans le rack en suivant les instructions de _instructions d'installation et de configuration_ pour le modèle de nœud.
. Reliez le nœud 4, puis déplacez les connexions du nœud 2 vers le nœud 4.
+
Effectuez les connexions suivantes en utilisant les _Instructions d'installation et de configuration_ pour la plate-forme node4, le document d'étagère de disque approprié et la documentation de _gestion des paires HA_.

+
Se référer àlink:other_references.html["Références"] pour créer un lien vers la _gestion des paires HA_.

+
** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC
+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion/carte FC-VI ou la connexion de câble d'interconnexion/FC-VI du node2 au node4 car la plupart des modèles de plateforme disposent de modèles de cartes d'interconnexion uniques. Pour la configuration MetroCluster, vous devez déplacer les connexions des câbles FC-VI du nœud2 au nœud4. Si le nouvel hôte ne dispose pas de carte FC-VI, il vous faudra peut-être déplacer la carte FC-VI.



. Mettez le nœud 4 sous tension, puis interrompez le processus de démarrage en appuyant sur Ctrl-C au niveau du terminal de la console pour accéder à l'invite de l'environnement de démarrage.
+

NOTE: Lors du démarrage du nœud 4, le message d'avertissement suivant peut s'afficher :

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Si le message d'avertissement s'affiche à l'étape 4, effectuez les actions suivantes :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage s'achever.
+

WARNING: *Ne dépassez pas le délai ; ne pas laisser la batterie se charger pourrait entraîner une perte de données.*

+

NOTE: Reportez-vous à la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].




