= Étape 2 : Corriger la propriété de l'agrégat si une vérification préalable ARL échoue
:allow-uri-read: 




[[step-2-correct-aggregate-ownership-if-an-arl-precheck-fails]]
== Étape 2 : Corriger la propriété de l'agrégat si une vérification préalable ARL échoue

En cas d'échec de la vérification de l'état de l'agrégat, vous devez renvoyer les agrégats qui appartiennent au nœud partenaire au nœud propriétaire du nœud de rattachement et relancer le processus de vérification préalable.

.Étapes
. Renvoyez les agrégats actuellement détenus par le nœud partenaire au nœud propriétaire de rattachement :
+
[source, cli]
----
storage aggregate relocation start -node <source_node> -destination <destination_node> -aggregate-list *
----
. Vérifiez que ni le nœud1 ni le nœud2 ne possède toujours des agrégats pour lesquels il s'agit du propriétaire actuel (mais pas le propriétaire du domicile) :
+
[source, cli]
----
storage aggregate show -nodes <node_name> -is-home false -fields owner-name, home-name, state
----
+
L'exemple suivant montre la sortie de la commande lorsqu'un nœud est à la fois le propriétaire actuel et le propriétaire du domicile des agrégats :

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----
. Redémarrez le processus de remplacement du contrôleur :
+
[source, cli]
----
system controller replace start -nodes <node_names>
----

