= Configurez les ports FC sur le nœud 4
:allow-uri-read: 




== Configurez les ports FC sur le nœud 4

Si le nœud 4 possède des ports FC intégrés ou sur un adaptateur FC, vous devez définir des configurations de ports sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés. Si les ports ne sont pas configurés, le service peut subir une interruption.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 2 que vous avez enregistrées dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'un adaptateur UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>>.


IMPORTANT: Entrez les commandes de cette section à l’invite du cluster.

.Étapes
. Afficher des informations sur tous les adaptateurs réseau FC et convergés du système :
+
`system node hardware unified-connect show`

. Comparez les paramètres FC des nouveaux nœuds avec les paramètres que vous avez précédemment définis à partir du nœud d'origine.
. Modifier les ports FC sur le nœud 4 si nécessaire :
+
** Pour programmer les ports cibles :
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Pour programmer les ports initiateurs :
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` Est le type, la cible ou l'initiateur FC4.



. Vérifiez les nouveaux paramètres en entrant la commande suivante et en examinant la sortie :
+
`system node unified-connect show`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les paramètres FC par défaut sont définis sur les nouveaux nœuds... | Puis… 


| Identique à ceux que vous avez capturés sur les noeuds d'origine | Aller à<<man_config_4_Step9,Étape 9>> . 


| Différent de ceux que vous avez capturés sur les nœuds d'origine | Aller à<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Quitter le mode Maintenance :
+
`halt`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Démarrez node4 en entrant la commande suivante à l’invite de l’environnement de démarrage :
+
`boot_ontap`

. [[man_config_4_Step9]]Effectuez l’une des actions suivantes :
+
** Accédez à <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>> Si le nœud 4 est doté d'une carte UTA/UTA2A ou de ports intégrés UTA/UTA2.
** Ignorez la section et accédez à link:map_ports_node2_node4.html["Mappage des ports du node2 au node4"] Si le nœud Node4 ne est pas doté d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2.



