= 
:allow-uri-read: 


Vous devez installer NODE4 dans le rack, transférer les connexions node2 vers node4 et démarrer node4. Vous devez également réaffecter toutes les unités de rechange du nœud 2, tous les disques appartenant à la racine et tous les agrégats non racines qui n'ont pas été transférés auparavant sur le nœud 3.

.Description de la tâche
Vous devez netboot Node4 si cette version de ONTAP 9 n'est pas installée sur le nœud 2. Une fois le noeud 4 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers corrects sur le périphérique de démarrage pour les démarrages suivants du système en suivant les instructions de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"]

Cependant, vous n'êtes pas obligé de netboot node4 s'il possède la même version ou une version ultérieure de ONTAP 9 installée sur le node2.

*Information importante:*

* Si vous mettez à niveau un système V-Series ou un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous devez le faire <<man_install4_Step1,Étape 1>> à <<man_install4_Step7,Étape 7>>, laissez cette section à <<man_install4_Step8,Étape 8>> et suivez les instructions de la section link:set_fc_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"] Si nécessaire, saisir les commandes en mode maintenance. Vous devez ensuite revenir à cette section et reprendre la procédure à <<man_install4_Step9,Étape 9>>.
* Toutefois, si vous mettez à niveau un système avec des disques de stockage, vous devez remplir cette section entière et passer à la section link:set_fc_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"], saisie de commandes à l'invite du cluster.


.Étapes
. [[man_install4_Step1]]entreprendre l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si node4 sera dans ... | Alors... 


| Châssis séparé du nœud3 | Accédez à <<man_install4_Step2,Étape 2>>. 


| Châssis identique à celui du nœud3 | Ignorez les étapes 2 et 3 et passez à <<man_install4_Step4,Étape 4>>. 
|===
. [[man_install4_Step2]] Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant.
+
Si le noeud 4 se trouve dans un châssis distinct du noeud 3, vous pouvez placer le noeud 4 au même emplacement que le noeud 2. Si les nœuds 3 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.

. Installez le node4 dans le rack en suivant les instructions de _instructions d'installation et de configuration_ pour le modèle de nœud.
. [[man_install4_Step4]]câble node4, en déplaçant les connexions du node2 vers le node4.
+
Les références suivantes vous aident à effectuer les connexions de câble appropriées. Accédez à link:other_references.html["Références"] pour les lier.

+
** _Instructions d'installation et de configuration_ ou _exigences et références d'installation de la virtualisation FlexArray_ pour la plate-forme node4
** Procédure appropriée de tiroir disque
** La documentation _High Availability Management_
+
Reliez les connexions suivantes :

** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC


+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion/carte FC_VI ou la connexion de câble d'interconnexion/FC_VI du node2 au node4 car la plupart des modèles de plateforme disposent de modèles de cartes d'interconnexion uniques.

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le noeud 4 est dans... | Alors... 


| Châssis identique à celui du nœud 3 | Accédez à <<man_install4_Step8,Étape 8>>. 


| Châssis séparé du nœud3 | Accédez à <<man_install4_Step6,Étape 6>>. 
|===
. [[man_install4_Step6]]mettez le noeud 4 sous tension, puis interrompez le démarrage en appuyant sur `Ctrl-C` pour accéder à l'invite de l'environnement de démarrage.
+

NOTE: Lorsque vous démarrez le nœud 4, le message suivant peut s'afficher :

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]si vous voyez le message d'avertissement à l'étape 6, procédez comme suit :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage se terminer.
+

WARNING: *Avertissement : ne pas annuler le délai. Si la batterie n'est pas chargée, cela pourrait entraîner une perte de données.*



. [[man_install4_Step8]]entreprendre l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si votre système... | Alors... 


| Possède des disques et aucun stockage interne | Passez aux étapes 9 à 14 et passez à <<man_install4_Step15,Étape 15>>. 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage  a| 
.. Allez dans la section _définissez la configuration FC ou UTA/UTA2 sur le nœud 4_ et complétez les sections link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Configurez les ports FC sur le nœud 4"] et link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4"], en fonction de votre système.
.. Revenez à cette section et suivez les étapes restantes, en commençant par <<man_install4_Step9,Étape 9>>.



IMPORTANT: Vous devez reconfigurer les ports intégrés FC, les ports intégrés UTA/UTA2 et les cartes UTA/UTA2 avant de démarrer ONTAP sur le système V-Series.

|===
. [[man_install4_Step9]]Ajouter les ports d'initiateur FC du nouveau nœud aux zones de commutation.
+
Reportez-vous à la documentation relative à votre matrice de stockage et au zoning pour obtenir des instructions.

. Ajoutez les ports d'initiateur FC à la baie de stockage en tant que nouveaux hôtes, en mappant les LUN de la baie aux nouveaux hôtes.
+
Reportez-vous à la documentation relative à votre matrice de stockage et au zoning pour obtenir des instructions.

. Modifier les valeurs WWPN (World Wide Port Name) dans les groupes d'hôtes ou de volumes associés aux LUN de baies de la baie de stockage.
+
L'installation d'un nouveau module de contrôleur modifie les valeurs WWPN associées à chaque port FC intégré.

. Si votre configuration utilise un zoning basé sur des commutateurs, ajustez le zoning en fonction des nouvelles valeurs WWPN.
. Vérifiez que les LUN de baie sont désormais visibles pour le nœud 4 en saisissant la commande suivante et en examinant la sortie correspondante :
+
`sysconfig -v`

+
Le système affiche toutes les LUN de baie visibles pour chacun des ports de l'initiateur FC. Si les LUN de la matrice ne sont pas visibles, vous ne pouvez pas réaffecter de disques du node2 au node4 ultérieurement dans cette section.

. Appuyez sur `Ctrl-C` Pour afficher le menu de démarrage et sélectionner Maintenance mode.
. [[man_install4_Step15]]à l'invite du mode Maintenance, entrez la commande suivante :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. Configuration du nœud 4 pour ONTAP :
+
`set-defaults`


