= 
:allow-uri-read: 


Vous devez installer NODE3 dans le rack, transférer les connexions du noeud 1 vers le noeud 3, démarrer le noeud 3 et installer ONTAP. Vous devez également réaffecter les disques de spare du nœud1, tous les disques appartenant au volume racine et tous les agrégats non racines qui ne sont pas transférés vers le nœud2 plus tôt.

.Description de la tâche
Vous devez démarrer le nœud 3 via le réseau s'il ne possède pas la même version d'ONTAP 9 que celle installée sur le nœud 1. Une fois le noeud 3 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers corrects sur le périphérique de démarrage pour les démarrages suivants du système. Voir link:prepare_for_netboot.html["Préparation à la mise sur le réseau"].

Cependant, vous n'avez pas besoin de démarrer le nœud 3 en réseau s'il possède la même version ou une version ultérieure d'ONTAP 9 installée sur le nœud 1.

[IMPORTANT]
====
* Pour une mise à niveau du contrôleur AFF A800 ou AFF C800, vous devez vous assurer que tous les lecteurs du châssis sont fermement fixés contre le plan médian avant de retirer le nœud 1. Pour plus d'informations, voir link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Remplacez les modules de contrôleur AFF A800 ou AFF C800"].
* Si vous mettez à niveau un système V-Series connecté à des baies de stockage ou à un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous devez le faire <<man_install3_step1,Étape 1>> à <<man_install3_step5,Étape 5>>, laissez cette section à <<man_install3_step6,Étape 6>> et suivez les instructions de la section link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurez les ports FC sur le nœud 3"] et link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3"] si nécessaire, la saisie de commandes en mode maintenance. Vous devez ensuite revenir à cette section et reprendre avec <<man_install3_step7,Étape 7>>.
* Si vous mettez à niveau un système avec des disques de stockage, vous devez compléter toute cette section, puis accéder à link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurez les ports FC sur le nœud 3"] et link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3"] , en entrant des commandes à l'invite du cluster.


====
.Étapes
. [[man_install3_step1]]Assurez-vous que vous disposez d'un espace rack pour node3.
+
Si les nœuds 1 et 2 se trouvent dans un châssis distinct, vous pouvez placer le nœud 3 au même emplacement de rack que le nœud 1. Cependant, si le nœud 1 se trouvait dans le même châssis avec le nœud 2, vous devez placer le nœud 3 dans son propre espace rack, de préférence à proximité de l'emplacement du nœud 1.

. [[step2]]installez le noeud 3 dans le rack, en suivant les instructions _installation and Setup_ pour votre modèle de nœud.
+

NOTE: Si vous effectuez une mise à niveau vers un système contenant les deux nœuds du même châssis, installez le nœud 4 dans le châssis et sur le nœud 3. Si ce n'est pas le cas, lors du démarrage du nœud 3, le nœud se comporte comme s'il se trouvaient dans une configuration à double châssis et lors du démarrage du nœud 4, l'interconnexion entre les nœuds n'apparaît pas.

. [[step3]]câble du noeud 3, en déplaçant les connexions du noeud 1 vers le noeud 3.
+
Les références suivantes vous aident à effectuer les connexions de câble appropriées. Accédez à link:other_references.html["Références"] pour les lier.

+
** _Instructions d'installation et de configuration_ ou _exigences d'installation et de référence de virtualisation FlexArray_ pour la plate-forme node3
** Procédure appropriée de tiroir disque
** La documentation _HA pair Management_


+
Reliez les connexions suivantes :

+
** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC
+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion ou la connexion du câble d'interconnexion de cluster du nœud 1 vers le nœud 3, car la plupart des modèles de plateforme possèdent un modèle de carte d'interconnexion unique. Pour la configuration MetroCluster, vous devez déplacer les connexions de câble FC-VI du nœud 1 vers le nœud 3. Si le nouvel hôte ne dispose pas de carte FC-VI, il vous faudra peut-être déplacer la carte FC-VI.



. [[man_install3_step4]]mettez le système sous tension vers le noeud 3, puis interrompez le processus d'amorçage en appuyant sur Ctrl-C sur le terminal de la console pour accéder à l'invite de l'environnement d'amorçage.
+
Si vous effectuez la mise à niveau vers un système avec les deux nœuds du même châssis, le nœud 4 redémarre également. Vous pouvez toutefois ignorer le démarrage du nœud 4 jusqu'à ce qu'il soit ultérieur.

+

NOTE: Lorsque vous démarrez le nœud 3, le message d'avertissement suivant peut s'afficher :

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]si vous voyez le message d'avertissement dans <<man_install3_step4,Étape 4>>, procédez comme suit :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage s'achever.
+

NOTE: *Attention*: Ne pas neutraliser le délai; si la batterie n'est pas chargée, cela pourrait entraîner une perte de données.



. [[man_install3_step6]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si votre système... | Alors... 


| Possède des disques et aucun stockage interne | Passez aux étapes 7 à 12 et passez à <<man_install3_step13,Étape 13>>. 


| Est un système V-Series ou un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage  a| 
.. Accédez à link:set_fc_uta_uta2_config_node3.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 3"] et complétez les sous-sections link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configurez les ports FC sur le nœud 3"] et link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3"], en fonction de votre système.
.. Revenez à cette section et suivez les étapes restantes, en commençant par <<man_install3_step7,Étape 7>>.



IMPORTANT: Vous devez reconfigurer les ports intégrés FC, les ports intégrés CNA et les cartes CNA avant de démarrer ONTAP sur le système V-Series ou sur le système avec le logiciel de virtualisation FlexArray.

|===
. [[man_install3_step7]]Ajoutez les ports d'initiateur FC du nouveau nœud aux zones de commutation.
+
Si votre système dispose d'un SAN sur bandes, vous devez segmentation pour les initiateurs. Reportez-vous à la documentation relative à votre matrice de stockage et au zoning pour obtenir des instructions.

. [[man_install3_step8]]Ajoutez les ports d'initiateur FC à la matrice de stockage en tant que nouveaux hôtes, mappant les LUN de la baie aux nouveaux hôtes.
+
Reportez-vous à la documentation relative à votre matrice de stockage et au zoning pour obtenir des instructions.

. [[man_install3_step9]]] modifiez les valeurs WWPN (World Wide Port Name) dans les groupes hôte ou de volumes associés aux LUN de tableau de la matrice de stockage.
+
L'installation d'un nouveau module de contrôleur modifie les valeurs WWPN associées à chaque port FC intégré.

. [[man_install3_step10]]si votre configuration utilise un zoning basé sur des commutateurs, ajustez la segmentation pour refléter les nouvelles valeurs WWPN.
. [[man_install3_step11]]Vérifiez que les LUN de tableau sont désormais visibles pour le noeud 3 :
+
`sysconfig -v`

+
Le système affiche toutes les LUN de baie visibles pour chacun des ports FC initiator. Si les LUN de la matrice ne sont pas visibles, vous ne pourrez pas réattribuer des disques du nœud1 au nœud3 ultérieurement dans cette section.

. [[man_install3_step12]]appuyez sur Ctrl-C pour afficher le menu de démarrage et sélectionner le mode de maintenance.
. [[man_install3_step13]]à l'invite du mode Maintenance, entrez la commande suivante :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. [[man_install3_step14]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système auquel vous effectuez la mise à niveau est dans... | Alors... 


| Configuration à châssis double (avec contrôleurs dans un châssis différent) | Accédez à <<man_install3_step15,Étape 15>>. 


| Configuration à châssis unique (avec contrôleurs dans le même châssis)  a| 
.. Basculez le câble de la console du node3 vers le node4.
.. Mettez le nœud 4 sous tension, puis interrompez le processus de démarrage en appuyant sur Ctrl-C au niveau du terminal de la console pour accéder à l'invite de l'environnement de démarrage.
+
Si les deux contrôleurs se trouvent dans le même châssis, l'alimentation doit déjà être mise sous tension.

+

NOTE: Quittez le nœud4 à l'invite de l'environnement de démarrage ; vous revenez au nœud 4 dans link:install_boot_node4.html["Installez et démarrez Node4"].

.. Si le message d'avertissement s'affiche dans <<man_install3_step4,Étape 4>>, suivez les instructions de la section <<man_install3_step5,Étape 5>>
.. Retournez le câble de la console du nœud 4 au nœud 3.
.. Accédez à <<man_install3_step15,Étape 15>>.


|===
. [[man_install3_step15]]configurer le noeud 3 pour ONTAP :
+
`set-defaults`


