= 
:allow-uri-read: 


. Si la version de ONTAP installée sur le nœud 4 est identique ou ultérieure à celle de ONTAP 9 installée sur le nœud 2, entrez la commande suivante :
+
`boot_ontap menu`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Ne dispose pas de la version ONTAP correcte ou actuelle du système node4 | Accédez à <<man_install4_Step20,Étape 20>>. 


| Dispose de la version correcte ou à jour de ONTAP sur le nœud 4 | Accédez à <<man_install4_Step25,Étape 25>>. 
|===
. [[man_install4_Step20]]configurez la connexion netboot en choisissant l'une des actions suivantes.
+

NOTE: Vous devez utiliser le port de gestion et l'adresse IP comme connexion netboot. N'utilisez pas d'adresse IP de la LIF de données et ne subit aucune panne lors de l'exécution de la mise à niveau.

+
[cols="35,75"]
|===
| Si le protocole DHCP (Dynamic Host Configuration Protocol) est... | Alors... 


| Exécution  a| 
Configurez la connexion automatiquement en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -auto`



| Non en cours d'exécution  a| 
Configurez manuellement la connexion en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` Est l'adresse IP du système de stockage (obligatoire).
`_netmask_` est le masque de réseau du système de stockage (obligatoire).
`_gateway_` est la passerelle du système de stockage (obligatoire).
`_dns_addr_` Est l'adresse IP d'un serveur de noms sur votre réseau (facultatif).
`_dns_domain_` Est le nom de domaine DNS (Domain Name Service). Si vous utilisez ce paramètre facultatif, vous n'avez pas besoin d'un nom de domaine complet dans l'URL du serveur netboot ; vous n'avez besoin que du nom d'hôte du serveur.


NOTE: D'autres paramètres peuvent être nécessaires pour votre interface. Entrez `help ifconfig` à l'invite du micrologiciel pour plus de détails.

|===
. Démarrage sur le nœud 4 :
+
[cols="30,70"]
|===
| Pour... | Alors... 


| Systèmes de la gamme FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| Tous les autres systèmes | `netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
Le `<path_to_the_web-accessible_directory>` vous devez indiquer où vous avez téléchargé le
`<ontap_version>_image.tgz` dans link:prepare_for_netboot.html#man_netboot_Step1["Étape 1"] Dans la section _préparer pour netboot_.

+

NOTE: N'interrompez pas l'amorçage.

. Dans le menu de démarrage, sélectionnez `option (7) Install new software first`.
+
Cette option de menu permet de télécharger et d'installer la nouvelle image Data ONTAP sur le périphérique d'amorçage.

+
Ne tenez pas compte du message suivant :

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Cette remarque s'applique aux mises à niveau de Data ONTAP sans interruption et non aux mises à niveau des contrôleurs.

+

NOTE: Utilisez toujours netboot pour mettre à jour le nouveau nœud vers l'image souhaitée. Si vous utilisez une autre méthode pour installer l'image sur le nouveau contrôleur, il est possible que l'image incorrecte soit installée. Ce problème s'applique à toutes les versions d'ONTAP. Procédure netboot combinée avec l'option `(7) Install new software` Efface le support de démarrage et place la même version de ONTAP sur les deux partitions d'image.

. [[man_install4_step23]] si vous êtes invité à poursuivre la procédure, entrez y et, lorsque vous y êtes invité, entrez l'URL :
+
`\http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. Procédez comme suit :
+
.. Entrez `n` pour ignorer la récupération de sauvegarde lorsque l'invite suivante s'affiche :
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Redémarrez en entrant `y` lorsque vous voyez l'invite suivante :
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Le module de contrôleur redémarre mais s'arrête au menu d'amorçage car le périphérique d'amorçage a été reformaté et les données de configuration doivent être restaurées.



. [[man_install4_Step25]]sélectionnez le mode de maintenance `5` dans le menu de démarrage et entrez `y` lorsque vous êtes invité à poursuivre le démarrage.
. [[man_install4_Step26]]avant de continuer, passez à l' link:set_fc_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"] Pour modifier les ports FC ou UTA/UTA2 sur le nœud, Apportez les modifications recommandées dans ces sections, redémarrez le nœud et passez en mode maintenance.
. Entrez la commande suivante et vérifiez la sortie pour rechercher l'ID système du nœud 4 :
+
`disk show -a`

+
Le système affiche l'ID système du nœud et les informations sur les disques correspondantes, comme illustré ci-dessous :

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. Réaffectez les disques de secours du nœud 2, les disques appartenant à la racine et tout agrégat non racine qui n'a pas été déplacé vers le nœud 3 plus tôt dans la section link:relocate_non_root_aggr_node2_node3.html["Transférer des agrégats non racines du nœud 2 vers le nœud 3"]:
+

NOTE: Si vous avez des disques partagés, des agrégats hybrides ou les deux sur votre système, vous devez utiliser le bon `disk reassign` commande du tableau suivant.

+
[cols="35,65"]
|===
| Type de disque... | Lancer la commande... 


| Avec disques partagés | `disk reassign -s`

`_node2_sysid_ -d _node4_sysid_ -p _node3_sysid_` 


| Sans partage | `disks disk reassign -s`

`_node2_sysid_ -d _node4_sysid_` 
|===
+
Pour le `<node2_sysid>` valeur, utilisez les informations capturées dans link:record_node2_information.html#man_record_2_step10["Étape 10"] De la section _Record node2 information_. Pour `_node4_sysid_`, utilisez les informations capturées dans <<man_install4_step23,Étape 23>>.

+

NOTE: Le `-p` cette option n'est requise en mode maintenance que lorsque des disques partagés sont présents.

+
Le `disk reassign` la commande réaffecte uniquement les disques pour lesquels `_node2_sysid_` est le propriétaire actuel.

+
Le système affiche le message suivant :

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
Entrez `n` lorsqu'il est demandé d'annuler la réaffectation du disque.

+
Lorsque vous êtes invité à annuler la réaffectation des disques, vous devez répondre à une série d'invites comme indiqué dans les étapes suivantes :

+
.. Le système affiche le message suivant :
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. Entrez `y` pour continuer.
+
Le système affiche le message suivant :

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. Entrez `y` pour permettre la mise à jour de la propriété de disque.


. Si vous effectuez une mise à niveau à partir d'un système avec des disques externes vers un système prenant en charge des disques internes et externes (systèmes A800, par exemple), définissez le noeud 4 en tant que racine pour confirmer son démarrage à partir de l'agrégat racine du noeud 2.
+

WARNING: *Avertissement : vous devez exécuter les sous-étapes suivantes dans l'ordre exact indiqué ; le non-respect de cette consigne peut entraîner une panne ou même une perte de données.*

+
La procédure suivante définit le nœud 4 pour démarrer à partir de l'agrégat racine du nœud 2 :

+
.. Vérifier les informations RAID, plex et checksum du noeud 2 :
+
`aggr status -r`

.. Vérifier le statut global de l'agrégat du nœud 2 :
+
`aggr status`

.. Si nécessaire, mettre l'agrégat du nœud 2 en ligne :
+
`aggr_online root_aggr_from___node2__`

.. Empêcher le démarrage du nœud 4 à partir de son agrégat racine d'origine :
+
`aggr offline _root_aggr_on_node4_`

.. Définir l'agrégat racine du nœud 2 en tant que nouvel agrégat racine pour le nœud 4 :
+
`aggr options aggr_from___node2__ root`



. Vérifiez que le contrôleur et le châssis sont configurés comme `ha` en entrant la commande suivante et en observant la sortie de :
+
`ha-config show`

+
L'exemple suivant montre la sortie du `ha-config show` commande :

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
Les systèmes enregistrent dans une PROM, qu'ils soient dans une paire HA ou dans une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité.

+
Si le contrôleur et le châssis ne sont pas configurés comme étant `ha`, utilisez les commandes suivantes pour corriger la configuration :

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`.

+
Si vous disposez d'une configuration MetroCluster, utilisez les commandes suivantes pour corriger la configuration :

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`.

. Détruire les boîtes aux lettres sur le nœud4 :
+
`mailbox destroy local`

. Quitter le mode Maintenance :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. Sur le node3, vérifiez la date, l'heure et le fuseau horaire du système :
+
`date`

. Sur le nœud 4, vérifiez la date à l'invite de l'environnement de démarrage :
+
`show date`

. Si nécessaire, définissez la date sur le node4 :
+
`set date _mm/dd/yyyy_`

. Sur le nœud 4, vérifiez l'heure à l'invite de l'environnement de démarrage :
+
`show time`

. Si nécessaire, définissez l'heure sur le node4 :
+
`set time _hh:mm:ss_`

. Vérifiez que l'ID du système partenaire est correctement défini comme indiqué dans la <<man_install4_Step26,Étape 26>> sous option.
+
`printenv partner-sysid`

. Si nécessaire, définissez l'ID système partenaire sur le noeud 4 :
+
`setenv partner-sysid _node3_sysid_`

+
.. Enregistrer les paramètres :
+
`saveenv`



. Entrez le menu de démarrage à l'invite de l'environnement de démarrage :
+
`boot_ontap menu`

. Dans le menu de démarrage, sélectionnez l'option *(6) mettre à jour la mémoire flash à partir de la configuration de sauvegarde* en entrant `6` à l'invite.
+
Le système affiche le message suivant :

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. Entrez `y` à l'invite.
+
Le démarrage se poursuit normalement et le système vous invite à confirmer la non-concordance de l'ID système.

+

NOTE: Il est possible que le système redémarre deux fois avant d'afficher l'avertissement de non-concordance.

. Confirmez la non-concordance. Le nœud peut effectuer un redémarrage complet avant le démarrage normal.
. Connectez-vous au nœud 4.

