= 
:allow-uri-read: 


. [[man_install3_step17]]] si la version de ONTAP installée sur le noeud 3 est identique ou ultérieure à la version de ONTAP 9 installée sur le noeud 1, répertoriez et réaffectez les disques au nouveau noeud 3 :
+
`boot_ontap`

+

WARNING: Si ce nouveau nœud a déjà été utilisé dans un autre cluster ou une paire HA, vous devez exécuter `wipeconfig` avant de continuer. Le non-respect de cette consigne peut entraîner des pannes du service ou des pertes de données. Contactez le support technique si le contrôleur de remplacement était auparavant utilisé, en particulier si les contrôleurs exécutaient ONTAP sous 7-mode.

. Appuyez sur CTRL-C pour afficher le menu de démarrage.
. [[man_install3_step19]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| _NOT_ dispose de la version ONTAP correcte ou actuelle sur le noeud 3 | Aller à<<man_install3_step13,Étape 13>> . 


| Dispose de la version correcte ou à jour de ONTAP sur le noeud 3 | Aller à<<man_install3_step18,Étape 18>> . 
|===
. [[man_install3_step13]]Configurez la connexion netboot en choisissant l’une des actions suivantes.
+

NOTE: Vous devez utiliser le port de gestion et l'IP comme connexion netboot. N'utilisez pas d'IP de la LIF de données et ne provoquer aucune interruption de service pendant l'exécution de la mise à niveau.

+
[cols="35,65"]
|===
| Si le protocole DHCP (Dynamic Host Configuration Protocol) est... | Alors... 


| Exécution | Configurez la connexion automatiquement en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -auto` 


| Non en cours d'exécution  a| 
Configurez manuellement la connexion en entrant la commande suivante à l'invite de l'environnement d'amorçage :
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Est l'adresse IP du système de stockage (obligatoire).
`_netmask_` est le masque de réseau du système de stockage (obligatoire).
`_gateway_` est la passerelle du système de stockage (obligatoire).
`_dns_addr_` Est l'adresse IP d'un serveur de noms sur votre réseau (facultatif).
`_dns_domain_` Est le nom de domaine DNS (Domain Name Service). Si vous utilisez ce paramètre facultatif, vous n'avez pas besoin d'un nom de domaine complet dans l'URL du serveur netboot ; vous n'avez besoin que du nom d'hôte du serveur.


NOTE: D'autres paramètres peuvent être nécessaires pour votre interface. Entrez `help ifconfig` à l'invite du micrologiciel pour plus de détails.

|===
. Exécuter le démarrage réseau sur le nœud 3 :
+
[cols="35,65"]
|===
| Pour... | Alors... 


| Systèmes de la gamme FAS/AFF8000 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| Tous les autres systèmes | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
Le `<path_to_the_web-accessible_directory>` mène à l'emplacement où vous avez téléchargé le `<ontap_version>_image.tgz` dans link:prepare_for_netboot.html#man_netboot_Step1["Étape 1"] Dans la section _préparer pour netboot_.

+

NOTE: N'interrompez pas l'amorçage.

. Dans le menu de démarrage, sélectionnez d’abord l’option *(7) Installer un nouveau logiciel*.
+
Cette option de menu permet de télécharger et d'installer la nouvelle image ONTAP sur le périphérique d'amorçage.

+
Ne tenez pas compte du message suivant :

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
Cette remarque s'applique aux mises à niveau de ONTAP sans interruption et non aux mises à niveau des contrôleurs.

+

NOTE: Utilisez toujours netboot pour mettre à jour le nouveau nœud vers l'image souhaitée. Si vous utilisez une autre méthode pour installer l'image sur le nouveau contrôleur, il est possible que la mauvaise image soit installée. Ce problème s'applique à toutes les versions d'ONTAP. Procédure netboot combinée avec l'option `(7) Install new software` Efface le support de démarrage et place la même version de ONTAP ONTAP sur les deux partitions d'images.

. Si vous êtes invité à continuer la procédure, entrez `y` , et lorsque vous êtes invité à choisir le package, entrez l'URL suivante :
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. Procédez comme suit :
+
.. Entrez `n` pour ignorer la récupération de sauvegarde lorsque l'invite suivante s'affiche :
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Redémarrez en entrant `y` lorsque vous voyez l'invite suivante :
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
Le module de contrôleur redémarre mais s'arrête au menu d'amorçage car le périphérique d'amorçage a été reformaté et les données de configuration doivent être restaurées.



. [[man_install3_step18]]Sélectionnez *(5) Maintenance mode boot* en entrant `5` , puis entrez `y` lorsque vous êtes invité à continuer le démarrage.
. [[man_install3_step26]]avant de continuer, allez à link:set_fc_uta_uta2_config_node3.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 3"] Pour modifier les ports FC ou UTA/UTA2 sur le nœud,
+
Apportez les modifications recommandées dans ces sections, redémarrez le nœud et passez en mode maintenance.

. Trouver l'ID système de node3 :
+
`disk show -a`

+
Le système affiche l'ID système du nœud et les informations sur les disques correspondantes, comme illustré ci-dessous :

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: Le message peut s'afficher `disk show: No disks match option -a.` après avoir saisi la commande. Ce n'est pas un message d'erreur qui vous permet de poursuivre la procédure.

. [[man_install3_step21]]Réaffectez les disques de rechange du nœud 1, tous les disques appartenant à la racine et tous les agrégats non racine qui n'ont pas été déplacés vers le nœud 2 plus tôt danslink:relocate_non_root_aggr_node1_node2.html["Transférer des agrégats non racines du nœud 1 vers le nœud 2"] .
+
Entrez le formulaire approprié du `disk reassign` commande basée sur si votre système possède des disques partagés :

+

NOTE: Si vous avez des disques partagés, des agrégats hybrides ou les deux sur votre système, vous devez utiliser le bon `disk reassign` commande du tableau suivant.

+
[cols="35,65"]
|===
| Si le type de disque est... | Exécutez ensuite la commande... 


| Avec disques partagés | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| Sans disques partagés | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
Pour le `_node1_sysid_` valeur, utilisez les informations capturées dans link:record_node1_information.html["Enregistrer les informations sur le noeud 1"]. Pour obtenir la valeur de `_node3_sysid_`, utilisez l' `sysconfig` commande.

+

NOTE: Le `-p` cette option n'est requise en mode maintenance que lorsque des disques partagés sont présents.

+
Le `disk reassign` la commande réassigne uniquement les disques pour lesquels `_node1_sysid_` est le propriétaire actuel.

+
Le système affiche le message suivant :

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]]entrer `n`.
+
Le système affiche le message suivant :

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]]entrer `y`
+
Le système affiche le message suivant :

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]]entrer `y`.
. [[man_install3_step32]]si vous effectuez une mise à niveau d'un système avec des disques externes vers un système qui prend en charge des disques internes et externes (systèmes AFF A800, par exemple), définissez l'agrégat node1 comme root pour confirmer que node3 démarre à partir de l'agrégat racine du nœud1.
+

WARNING: *Avertissement* : vous devez effectuer les sous-étapes suivantes dans l'ordre indiqué ; le non-respect de cette consigne peut entraîner une panne ou même une perte de données.

+
La procédure suivante définit le nœud 3 pour démarrer à partir de l'agrégat racine du nœud 1 :

+
.. Vérifier les informations RAID, plex et checksum du noeud 1 :
+
`aggr status -r`

.. Vérifier le statut de l'agrégat du nœud 1 :
+
`aggr status`

.. Mettre l'agrégat de nœud 1 en ligne, si nécessaire :
+
`aggr_online _root_aggr_from_node1_`

.. Empêcher le démarrage du nœud 3 à partir de son agrégat racine d'origine :
`aggr offline _root_aggr_on_node3_`
.. Définir l'agrégat racine du nœud 1 en tant que nouvel agrégat racine pour le nœud 3 :
+
`aggr options _aggr_from_node1_ root`

.. Vérifier que l'agrégat racine du nœud 3 est hors ligne et que l'agrégat racine des disques transférées depuis le nœud 1 est en ligne et défini à la racine :
+
`aggr status`

+

NOTE: Si vous ne procédez pas à la sous-étape précédente, le noeud 3 risque de démarrer à partir de l'agrégat racine interne, ou le système peut supposer qu'une nouvelle configuration de cluster existe ou vous inviter à en identifier une.

+
Voici un exemple de sortie de la commande :



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]]Vérifiez que le contrôleur et le châssis sont configurés comme `ha`:
+
`ha-config show`

+
L'exemple suivant montre le résultat de la commande ha-config show :

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
Les systèmes enregistrent dans une ROM programmable (PROM), qu'ils soient dans une paire HA ou une configuration autonome. L'état doit être le même sur tous les composants du système autonome ou de la paire haute disponibilité.

+
Si le contrôleur et le châssis ne sont pas configurés comme « HA », utilisez les commandes suivantes pour corriger la configuration :

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si vous disposez d'une configuration MetroCluster, utilisez les commandes suivantes pour modifier le contrôleur et le châssis :

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]]détruisez les boîtes aux lettres sur le noeud 3 :
+
`mailbox destroy local`

+
La console affiche le message suivant :

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]]entrer `y` à l'invite pour confirmer que vous souhaitez détruire les boîtes aux lettres locales.
. [[man_install3_step36]]Quitter le mode de maintenance :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. [[man_install3_step37]]sur le node2, vérifiez la date, l'heure et le fuseau horaire du système :
+
`date`

. [[man_install3_step38]]sur le noeud 3, vérifiez la date à l'invite de l'environnement d'initialisation :
+
`show date`

. [[man_install3_step39]]si nécessaire, définissez la date sur le noeud 3 :
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]]sur le noeud 3, vérifiez l'heure à l'invite de l'environnement d'initialisation :
+
`show time`

. [[man_install3_step41]]si nécessaire, définissez l'heure sur node3 :
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]Vérifiez que l'ID du système partenaire est correctement défini comme indiqué dans<<man_install3_step21,Étape 21>> sous le commutateur -p :
+
`printenv partner-sysid`

. [[man_install3_step43]]si nécessaire, définissez l'ID système partenaire sur le noeud 3 :
+
`setenv partner-sysid _node2_sysid_`

+
Enregistrer les paramètres :

+
`saveenv`

. [[man_install3_step44]]accédez au menu de démarrage à l'invite de l'environnement d'amorçage :
+
`boot_ontap menu`

. [[man_install3_step45]]dans le menu de démarrage, sélectionnez l'option *(6) mettre à jour Flash à partir de la configuration de sauvegarde* en entrant `6` à l'invite.
+
Le système affiche le message suivant :

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]]entrer `y` à l'invite.
+
Le démarrage se poursuit normalement, et le système vous demande alors de confirmer la non-concordance de l'ID système.

+

NOTE: Il est possible que le système redémarre deux fois avant d'afficher l'avertissement de non-concordance.

. [[man_install3_step47]]confirmer l'incohérence comme indiqué dans l'exemple suivant :
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
Le nœud peut se redémarrer avant de démarrer normalement.

. [[man_install3_step48]]Connectez-vous au node3.

