= Configurez les ports FC sur le nœud 3
:allow-uri-read: 




== Configurez les ports FC sur le nœud 3

Si le nœud 3 dispose de ports FC, intégrés ou sur un adaptateur FC complémentaire, vous devez définir les configurations de port sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés lors de l'expédition des systèmes.  Si vous ne configurez pas les ports, vous risquez de subir une interruption de service.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 1 que vous avez enregistrées dans link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.


IMPORTANT: Entrez les commandes de cette section à l’invite du cluster.

.Étapes
. Affichez des informations sur tous les adaptateurs réseau FC et convergés du système.
+
`system node hardware unified-connect show`

. Comparez les paramètres FC du nœud 3 avec les paramètres que vous avez capturés précédemment à partir du nœud 1.
. [[man_config_3_step3]]Effectuez l’une des actions suivantes :
+
[cols="35,65"]
|===
| Si les paramètres FC par défaut sont définis sur les nouveaux nœuds... | Alors... 


| Identique à ceux que vous avez capturés sur le noeud 1 | Aller à<<man_config_3_step9,Étape 9>> . 


| Différent de ceux que vous avez capturés sur le nœud1 | Aller à<<man_config_3_step4,Étape 4>> . 
|===
. [[man_config_3_step4]]Modifiez les ports FC sur le nœud 3 selon vos besoins en entrant l'une des commandes suivantes :
+
** Pour programmer les ports cibles :
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Pour programmer les ports initiateurs :
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Est le type FC4 : cible ou initiateur.



. Vérifiez les nouveaux paramètres en entrant la commande suivante et en examinant la sortie :
+
`system node hardware unified-connect show`

. Quitter le mode Maintenance :
+
`halt`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Démarrez le nœud 3 à l’invite de l’environnement de démarrage :
+
`boot_ontap`

. [[man_config_3_step9]]Effectuez l’une des actions suivantes :
+
** Si le nœud 3 dispose d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2, rendez-vous sur <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.
** Si le nœud 3 ne dispose pas de carte UTA/UTA2 ou de ports intégrés UTA/UTA2, ignorez-le <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>> et allez à link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"].



