= 
:allow-uri-read: 


Les LIF distantes gèrent le trafic vers des LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour assurer l'intégrité du cluster ou du service pendant la mise à niveau. Les LIF SAN ne sont pas déplacées sauf si elles doivent être mappées sur de nouveaux ports. Vous vérifiez que les LIFs sont saines et situées sur les ports appropriés après avoir mis le nœud4 en ligne.

.Étapes
. Lister toutes les LIFs de données NAS qui ne appartiennent pas au nœud3 en entrant la commande suivante sur l'un des nœuds et en capturant la sortie :
+
`network interface show -role data -curr-node node3 -is-home false`

. [[Worksheet_step2_node2]]si le cluster est configuré pour les LIFs SAN, enregistrez les LIFs SAN et les informations de configuration existantes dans ce link:worksheet_information_before_moving_san_lifs_node4.html["feuille de calcul"] pour une utilisation ultérieure dans la procédure.
+
.. Lister les LIFs SAN sur le nœud3 et examiner le résultat :
+
`network interface show -data-protocol fc*`

+
Le système renvoie une sortie similaire à l'exemple suivant :

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. Dressez la liste des configurations existantes et examinez les résultats :
+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Le système renvoie une sortie similaire à l'exemple suivant :

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le noeud 2... | Description 


| Des groupes d'interface ou des VLAN ont été configurés | Accédez à ,Étape 4. 


| Aucun groupe d'interfaces ou VLAN n'a été configuré | Ignorez l'étape 4 et passez à ,Étape 5. 
|===
. [[man_lif_revérification_4_Step3]]effectuez les étapes suivantes pour migrer toutes les LIF de données NAS hébergées sur des groupes d'interface et des VLAN qui se trouvaient au départ sur le nœud 2, du nœud 3 vers le nœud 4.
+
.. [[man_lif_verify_4_sub-pa]]migrer toutes les LIF hébergées sur le nœud 3 qui étaient auparavant appartenant au nœud 2 sur un groupe d'interface vers un port du nœud 4 capable d'héberger les LIF sur le même réseau en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node node4 –destination-port _netport|ifgrp_`

.. Modifier le home port et le home node des LIFs dans ,Sous-étape a Au port et au nœud qui hébergent actuellement les LIFs en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-node node4 home-port _netport|ifgrp_`

.. [[man_lif_verify_4_sub-epc]]] migrer toutes les LIF hébergées sur le nœud 3 qui appartenaient précédemment au nœud 2 sur un port VLAN vers un port du nœud 4 capable d'héberger les LIFs sur le même réseau en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface migrate -vserver _vserver_name_ -lif _datalif_name_ -destination-node node4 –destination-port _netport|ifgrp_`

.. Modifier le home port et le home node des LIFs dans ,Sous-étape c Au port et au nœud qui hébergent actuellement les LIFs en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-node _node4_ home-port _netport|ifgrp_`



. [[man_lif_verify_4_Step4]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le cluster est configuré pour... | Alors... 


| NAS | Terminé ,Étape 6 à ,Étape 9, Ignorez l'étape 10 et terminez ,Étape 11 à ,Étape 14. 


| SAN | Passez les étapes 6 à 9 et terminez ,Étape 10 à ,Étape 14. 


| NAS et SAN | Terminé ,Étape 6 à ,Étape 14. 
|===
. [[man_lif_verify_4_Step5]]si vous disposez de ports de données qui ne sont pas les mêmes sur vos plates-formes, entrez la commande suivante pour ajouter les ports au broadcast domain :
+
`network port broadcast-domain add-ports -ipspace _IPspace_name_ -broadcast-domain mgmt ports _node:port_`

+
L'exemple suivant ajoute le port « e0a » sur le nœud « 6280-1 » et le port « e0i » du nœud « 8060-1 » à la gestion de domaine de diffusion dans l'IPspace par défaut :

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. Migrer chaque LIF de données NAS vers le nœud 4 en saisissant la commande suivante, une fois pour chaque LIF :
+
`network interface migrate -vserver _vserver-name_ -lif _datalif-name_ -destination-node _node4_ -destination-port _netport|ifgrp_ -home-node _node4_`

. Assurez-vous que la migration des données est persistante :
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-port _netport|ifgrp_`

. [[man_lif_verify_4_Step8]]Vérifiez l'état de tous les liens comme `up` en entrant la commande suivante pour lister tous les ports réseau et examiner sa sortie :
+
`network port show`

+
L'exemple suivant montre la sortie du `network port show` Commande avec quelques LIF hausse ou baisse :

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. [[man_lif_verify_4_Step9]]si la sortie de l' `network port show` commande affiche les ports réseau qui ne sont pas disponibles dans le nouveau nœud et qui sont présents dans les anciens nœuds. pour ce faire, supprimez les anciens ports réseau en effectuant les sous-étapes suivantes :
+
.. Entrez le niveau de privilège avancé en entrant la commande suivante :
+
`set -privilege advanced`

.. Entrez la commande suivante, une fois pour chaque ancien port réseau :
+
`network port delete -node _node_name_ -port _port_name_`

.. Revenir au niveau admin en entrant la commande suivante :
+
`set -privilege admin`



. [[man_lif_verify_4_Step10]]Confirmez que les LIFs SAN se trouvent sur les ports corrects sur le nœud 4 en effectuant les sous-étapes suivantes :
+
.. Entrez la commande suivante et examinez son résultat :
+
`network interface show -data-protocol iscsi|fcp -home-node node4`

+
Le système renvoie une sortie similaire à l'exemple suivant :

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node4         a0a     true
            data1        up/up    10.63.0.50/18      node4         e0c     true
            rads1        up/up    10.63.0.51/18      node4         e1a     true
            rads2        up/down  10.63.0.52/24      node4         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node4         e0c     true
            lif2         up/up    172.17.176.121/24  node4
----
.. Vérifiez que le nouveau `adapter` et `switch-port` les configurations sont correctes en comparant la sortie du `fcp adapter show` commande avec les nouvelles informations de configuration que vous avez enregistrées dans la fiche technique du ,Étape 2.
+
Lister les nouvelles configurations LIF SAN sur le nœud4 :

+
`fcp adapter show -fields switch-port,fc-wwpn`

+
Le système renvoie une sortie similaire à l'exemple suivant :

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----
+

NOTE: Si une LIF SAN dans la nouvelle configuration ne se trouve pas sur un adaptateur toujours connecté à la même configuration `switch-port`, cela peut provoquer une panne du système lorsque vous redémarrez le nœud.

.. Si le nœud4 possède des LIFs SAN ou des groupes de LIFs SAN qui se trouvent sur un port n'existant pas sur le nœud2, déplacez-les vers un port approprié du nœud4 en entrant l'une des commandes suivantes :
+
... Définir le statut LIF sur « down » :
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin down`

... Supprimer le LIF du port set :
+
`portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

... Entrez l'une des commandes suivantes :
+
**** Déplacement d'un seul LIF :
+
`network interface modify -lif _lif_name_ -home-port _new_home_port_`

**** Déplacer toutes les LIF sur un port unique inexistant ou incorrect vers un nouveau port :
+
`network interface modify {-home-port _port_on_node2_ -home-node _node2_ -role data} -home-port _new_home_port_on_node4_`

**** Reajoutez les LIFs au port set :
+
`portset add -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`







+

NOTE: Vous devez déplacer les LIFs SAN sur un port dont la vitesse de liaison est identique à celle du port d'origine.

. Modifiez le statut de toutes les LIFs à `up` Pour que les LIFs acceptent et envoient le trafic sur le nœud en entrant la commande suivante :
+
`network interface modify -vserver _vserver_name_ -home-port _port_name_ -home-node _node4_ lif _lif_name_ -status-admin up`

. Vérifier que toutes les LIFs SAN ont été déplacées vers les ports appropriés et que celles-ci sont à l'état `up` en saisissant la commande suivante sur l'un ou l'autre des nœuds et en examinant la sortie :
+
`network interface show -home-node _node4_ -role data`

. [[man_lif_verify_4_Step13]]si l'une des LIFs est hors service, définissez le statut administratif des LIFs sur `up` En saisissant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`


