= 
:allow-uri-read: 


Vous devez installer NODE4 dans le rack, transférer les connexions node2 vers node4 et démarrer node4. Vous devez également réaffecter toutes les unités de rechange du nœud 2, tous les disques appartenant à la racine et tous les agrégats non racines qui n'ont pas été transférés auparavant sur le nœud 3.

.Description de la tâche
Vous devez démarrer le nœud 4 via le réseau si la version d'ONTAP 9 n'est pas identique à celle installée sur le nœud 2. Une fois le noeud 4 installé, démarrez-le à partir de l'image ONTAP 9 stockée sur le serveur Web. Vous pouvez ensuite télécharger les fichiers appropriés sur le support de démarrage pour les démarrages ultérieurs du système en suivant les instructions de la section link:prepare_for_netboot.html["Préparation à la mise sur le réseau"] .

Cependant, vous n'êtes pas obligé de démarrer le nœud 4 en réseau s'il possède la même version ou une version ultérieure d'ONTAP 9 installée sur le nœud 2.

[IMPORTANT]
====
* Pour une mise à niveau du contrôleur AFF A800 ou AFF C800, vous devez vous assurer que tous les lecteurs du châssis sont fermement fixés contre le plan médian avant de retirer le nœud 2. Pour plus d'informations, voir link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Remplacez les modules de contrôleur AFF A800 ou AFF C800"].
* Si vous mettez à niveau un système avec des disques de stockage, vous devez compléter toute cette section, puis passer à la section link:set_fc_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"] , en entrant des commandes à l'invite du cluster.


====
.Étapes
. [[man_install4_Step1]]entreprendre l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si node4 sera dans ... | Alors... 


| Châssis séparé du nœud3 | Accédez à <<man_install4_Step2,Étape 2>>. 


| Châssis identique à celui du nœud3 | Ignorez les étapes 2 et 3 et passez à <<man_install4_Step4,Étape 4>>. 
|===
. [[man_install4_Step2]] Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant.
+
Si le noeud 4 se trouve dans un châssis distinct du noeud 3, vous pouvez placer le noeud 4 au même emplacement que le noeud 2. Si les nœuds 3 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.

. Installez le node4 dans le rack en suivant les instructions de _instructions d'installation et de configuration_ pour le modèle de nœud.
. [[man_install4_Step4]]câble node4, en déplaçant les connexions du node2 vers le node4.
+
Les références suivantes vous aident à effectuer les connexions de câble appropriées. Accédez à link:other_references.html["Références"] pour les lier.

+
** _Instructions d'installation et de configuration_ pour la plateforme node4
** Procédure appropriée de tiroir disque
** La documentation _HA pair Management_
+
Reliez les connexions suivantes :

** Console (port de gestion à distance)
** Ports de cluster
** Ports de données
** Ports de gestion de clusters et de nœuds
** Stockage
** Configurations SAN : ports de switch iSCSI Ethernet et FC


+

NOTE: Il n'est pas nécessaire de déplacer la carte d'interconnexion/carte FC_VI ou la connexion de câble d'interconnexion/FC_VI du node2 au node4 car la plupart des modèles de plateforme disposent de modèles de cartes d'interconnexion uniques.

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le noeud 4 est dans... | Alors... 


| Châssis identique à celui du nœud 3 | Accédez à <<man_install4_Step8,Étape 8>>. 


| Châssis séparé du nœud3 | Accédez à <<man_install4_Step6,Étape 6>>. 
|===
. [[man_install4_Step6]]mettez le node4 sous tension, puis interrompez le démarrage en appuyant sur Ctrl-C pour accéder à l'invite de l'environnement de démarrage.
+

NOTE: Lorsque vous démarrez le nœud 4, le message suivant peut s'afficher :

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]si vous voyez le message d'avertissement à l'étape 6, procédez comme suit :
+
.. Vérifiez s'il y a un message de console susceptible d'indiquer un problème autre que celui d'une batterie NVRAM faible et, le cas échéant, effectuez les actions correctives nécessaires.
.. Laissez la batterie se charger et le processus de démarrage se terminer.
+

WARNING: *Ne pas outrepasser le délai.  Ne pas laisser la batterie se charger peut entraîner une perte de données.*



. [[man_install4_Step8]]À l'invite du mode Maintenance, entrez la commande suivante :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. Configuration du nœud 4 pour ONTAP :
+
`set-defaults`


