= 
:allow-uri-read: 


Avant de pouvoir remplacer le nœud 2 par le nœud 4, vous devez envoyer un message AutoSupport pour le nœud 2, puis déplacer les agrégats non-racine qui appartiennent au nœud 2 vers le nœud 3.


CAUTION: Au cours de cette procédure, ne déplacez pas les agrégats du nœud 3 vers le nœud 2. Les agrégats sont alors mis hors ligne et les agrégats déplacés sont affectés par une panne de données.

[[verify-partner-sys-id]]
.Étapes
. Vérifiez que l'ID du système partenaire est correctement défini sur le nœud 3 :
+
.. Saisissez le niveau de privilège avancé :
+
`set -privilege advanced`

.. Afficher l'ID du système partenaire sur le nœud 3 :
+
`ha interconnect config show -node <node3-node1>`

+
Un résultat similaire à l'exemple suivant s'affiche :

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. Si l'ID du système partenaire est incorrect pour le nœud 3 :
+
.. Nœud d'arrêt 3 :
+
`halt`

.. À l'invite Loader, définissez la valeur « Partner-sysid » correcte.
+
Le node3 "Partner-sysid" est l'ID système du node2, que vous pouvez trouver dans la `ha interconnect config show` sortie dans <<verify-partner-sys-id,Étape 1>>.

.. Enregistrer les paramètres :
+
`saveenv`

.. À l'invite Loader, démarrez node3 dans le menu de démarrage :
+
`boot_ontap menu`

.. Connectez-vous au nœud 3.


. Envoyer un message AutoSupport à NetApp pour node2 :
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. Vérifiez que le message AutoSupport a été envoyé :
+
`system node autosupport show -node <node2> -instance`

+
Les champs « dernier objet envoyé : » et « dernière envoi : » contiennent le titre du message du dernier message envoyé et l'heure à laquelle le message a été envoyé.

. Transfert des agrégats non racine :
+
.. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

.. Lister les agrégats qui sont détenus par le nœud2 :
+
`storage aggregate show -owner-name <node2>`

.. Démarrer le transfert d'agrégats :
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: La commande ne localise que des agrégats non-racines.

.. Entrez-le lorsque vous y êtes invité `y`.
+
La réinstallation a lieu en arrière-plan. Le transfert d'un agrégat peut prendre quelques secondes ou quelques minutes, Cette durée inclut à la fois les parties en cas d'interruption du client et les parties en cas d'interruption de service. La commande ne déplace pas d'agrégats hors ligne ou restreints.

.. Retour au niveau de privilège admin :
+
`set -privilege admin`



. Vérifiez l'état de la réinstallation du noeud 2 :
+
`storage aggregate relocation show -node <node2>`

+
Le résultat affiche « Done » pour un agrégat après son transfert.

+

NOTE: Vous devez patienter jusqu'à ce que tous les agrégats qui appartiennent au nœud 2 aient été transférés vers le nœud 3 avant de passer à l'étape suivante.

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| En cas de déménagement de... | Alors... 


| Tous les agrégats ont réussi | Allez à <<man_relocate_2_3_step8,Étape 8>>. 


| Tout agrégat a échoué ou a été vetoté  a| 
.. Afficher un message d'état détaillé :
+
`storage aggregate show -instance`

+
Vous pouvez également vérifier les journaux EMS pour voir l'action corrective requise.

+

NOTE: Le `event log show` la commande répertorie les erreurs qui se sont produites.

.. Effectuez l'action corrective.
.. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

.. Transfert d'agrégats défaillants ou vetotés :
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. Entrez-le lorsque vous y êtes invité `y`.
.. Retour au niveau de privilège admin :
+
`set -privilege admin`



Si nécessaire, vous pouvez forcer la relocalisation en utilisant l'une des méthodes suivantes :

** En remplaçant les contrôles de veto :
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** En remplaçant les vérifications de destination :
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Pour plus d'informations sur les commandes de transfert d'agrégats de stockage, rendez-vous sur link:other_references.html["Références"] Pour établir un lien vers la gestion des _disques et des agrégats à l'aide de la CLI_ et des commandes _ONTAP 9 : manuel page Reference_.

|===
. [[man_relocaliser_2_3_step8]]Vérifiez que tous les agrégats non racine sont en ligne sur le node3 :
+
`storage aggregate show -node <node3> -state offline -root false`

+
Si un agrégat est mis hors ligne ou est devenu étranger, vous devez les mettre en ligne une fois pour chaque agrégat :

+
`storage aggregate online -aggregate <aggregate_name>`

. Vérifiez que tous les volumes sont en ligne sur le noeud 3 :
+
`volume show -node <node3> -state offline`

+
Si des volumes sont hors ligne sur le nœud 3, vous devez les mettre en ligne une fois pour chaque volume :

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. Vérifiez que le nœud 2 ne possède aucun agrégat non racine en ligne :
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
Le résultat de la commande ne doit pas afficher d'agrégats en ligne non-racine, car tous les agrégats en ligne non-racine ont déjà été déplacés vers le nœud 3.


