= Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4
:allow-uri-read: 




== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4

Si le NODE4 dispose de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2A, vous devez vérifier la configuration des ports et les configurer, en fonction de votre mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Les ports UTA/UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2A. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément les cartes réseau et le trafic FCoE pour partager la même interface SFP+ 10 GbE et prend en charge la cible FC.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Les ports UTA/UTA2 peuvent être situés sur un adaptateur ou sur le contrôleur dans les configurations suivantes :

* Les cartes UTA/UTA2 commandées en même temps que le contrôleur sont configurées avant l'expédition pour obtenir la personnalité demandée.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés (avant l'expédition) pour utiliser le profil demandé.


Toutefois, vous pouvez vérifier la configuration des ports UTA/UTA2 sur le nœud 4 et la modifier si nécessaire.

*Attention* : si votre système dispose de disques de stockage, entrez les commandes de cette section à l'invite du cluster, sauf si vous êtes invité à passer en mode Maintenance. Si vous utilisez un système FC MetroCluster, un système V-Series ou un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous devez être en mode de maintenance pour configurer les ports UTA/UTA2.

.Étapes
. Vérifiez la configuration actuelle des ports à l'aide de l'une des commandes suivantes sur le nœud4 :
+
[cols="35,65"]
|===
| Si le système... | Puis… 


| Possède des disques de stockage | `system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `ucadmin show` 
|===
+
Un résultat similaire à l'exemple suivant s'affiche :

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. Examiner la sortie du `system node hardware unified-connect show` ou `ucadmin show` Déterminez si les ports UTA/UTA2 ont le profil souhaité.
. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les ports CNA... | Alors... 


| N'avez pas la personnalité que vous voulez | Accédez à <<man_check_4_Step5,Étape 5>>. 


| Avoir la personnalité que vous voulez | Passez aux étapes 5 à 12 et passez à <<man_check_4_Step13,Étape 13>>. 
|===
. [[man_check_4_Step5]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage et exécute Data ONTAP 8.3 | Démarrage du nœud 4 et passage en mode maintenance :
`boot_ontap maint` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Accédez à <<man_check_4_Step6,Étape 6>>. Vous devez déjà être en mode Maintenance. 
|===
. [[man_check_4_Step6]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si vous configurez... | Alors... 


| Ports sur une carte UTA/UTA2A | Accédez à <<man_check_4_Step7,Étape 7>>. 


| Ports UTA/UTA2 intégrés | Ignorez l'étape 7 et passez à <<man_check_4_Step8,Étape 8>>. 
|===
. [[man_check_4_Step7]]si l'adaptateur est en mode initiateur, et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter _adapter_name_`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode maintenance.

. [[man_check_4_Step8]]si la configuration actuelle ne correspond pas à l'utilisation souhaitée, entrez la commande suivante pour modifier la configuration selon les besoins :
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Est le mode Personality : carte UTA FC ou 10GbE
** `-t` Est le type FC4 : cible ou initiateur.


+

NOTE: Vous devez utiliser l'initiateur FC pour les disques sur bande et les systèmes de virtualisation FlexArray. Vous devez utiliser la cible FC pour les clients SAN.

. Vérifiez les paramètres en saisissant la commande suivante et en examinant la sortie correspondante :
+
`ucadmin show`

. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage  a| 
.. Saisissez la commande suivante :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

.. Saisissez la commande suivante :
+
`boot_ontap`





| Est un système V-Series ou un logiciel de virtualisation FlexArray. Il est connecté aux baies de stockage et exécute Data ONTAP 8.3 | Redémarrer en mode maintenance :
`boot_ontap maint` 
|===
. Vérifiez les paramètres :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | Saisissez la commande suivante :
`system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Saisissez la commande suivante :
`ucadmin show` 
|===
+
Le résultat des exemples suivants montre que le type FC4 d'adaptateur « 1b » passe à `initiator` et que le mode des adaptateurs « 2a » et « 2b » passe à `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. Placez n'importe quel port cible en ligne en entrant l'une des commandes suivantes, une fois pour chaque port :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `fcp config _adapter_name_ up` 
|===
. [[man_check_4_Step13]]câble du port.
. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | Accédez à link:map_ports_node2_node4.html["Mappage des ports du node2 au node4"]. 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Retournez à la section _Install and boot node4_, puis reprenez la section à l'adresse link:install_boot_node4.html#man_install4_Step9["Étape 9"]. 
|===

