---
sidebar: sidebar 
permalink: upgrade-arl-manual/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: Décidez si vous souhaitez utiliser la procédure ARL manuelle pour mettre à niveau les contrôleurs de stockage dans une paire HA avec de nouveaux contrôleurs exécutant ONTAP 9.7 ou une version antérieure. 
---
= Décider d'utiliser ou non cette procédure de relocalisation globale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette procédure décrit comment mettre à niveau le matériel du contrôleur à l'aide de la relocalisation manuelle des agrégats (ARL) sur les systèmes exécutant ONTAP 9.7 ou une version antérieure. Cette procédure complexe est réservée aux administrateurs ONTAP expérimentés.

Utilisez ce contenu dans les circonstances suivantes :

* Vous ne souhaitez pas ajouter de nouveaux contrôleurs comme nouvelle paire haute disponibilité au cluster et migrer les données à l'aide des déplacements de volumes.
* Vous avez de l'expérience dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilèges de diagnostic.
* Vos contrôleurs exécutent ONTAP 9.7 ou une version antérieure.
* Le système repose sur des configurations Fabric MetroCluster à 4 et 8 nœuds qui exécutent ONTAP 9.5 ou une version antérieure.


[NOTE]
====
* Si vous mettez à niveau un système en échangeant des modules de contrôleur dans le même châssis, comme AFF A800 ou AFF C800, NetApp recommande fortement d'utiliser la procédure de mise à niveau quilink:../upgrade-arl-auto-in-chassis/index.html["met à niveau les modèles de contrôleurs à l'aide d'ARL, en conservant le châssis et les disques du système existant"] .  Cette procédure ARL inclut les étapes qui garantissent que les disques internes restent sécurisés dans le châssis lorsque vous retirez et installez les contrôleurs pendant la procédure de mise à niveau.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Découvrez les combinaisons de mise à niveau système prises en charge à l'aide d'ARL, en conservant le châssis et les disques système existants"].

* Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).


====
Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.

Reportez-vous à la section link:other_references.html["Références"] Lien vers le Centre de documentation _ONTAP 9_ où vous pouvez accéder à la documentation produit ONTAP 9.



== Choisissez une autre procédure de mise à niveau matérielle

* link:../upgrade-arl/index.html["Passez en revue les méthodes ARL alternatives disponibles pour la mise à niveau du matériel du contrôleur"].
* Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.


.Informations associées
Se référer à link:other_references.html["Références"] pour créer un lien vers la _Documentation ONTAP 9_.
