---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 'Utilisez la procédure manuelle de mise à niveau d"ARL pour mettre à niveau le matériel des contrôleurs exécutant ONTAP 9.7 ou une version antérieure, délocalisant ainsi la propriété des agrégats non racines.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette procédure décrit la procédure de mise à niveau du matériel du contrôleur à l'aide du transfert d'agrégats (ARL) pour les configurations système suivantes :

[cols="20,20,60"]
|===
| Méthode | Version ONTAP | Systèmes pris en charge 


| Mise à niveau manuelle avec l'ARL | 9.7 ou antérieure  a| 
* Du système FAS au système FAS
* Du système FAS à un système doté du logiciel de virtualisation FlexArray ou d'un système V-Series
* Du système AFF au système AFF
* Système avec le logiciel de virtualisation FlexArray ou un système V-Series vers un système FAS, à condition que le système doté du logiciel de virtualisation FlexArray ou d'un système V-Series ne dispose pas de LUN de baie.
* Système V-Series à un système avec le logiciel de virtualisation FlexArray ou un système V-Series


|===
Pendant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, délocalisant ainsi la propriété des agrégats non racines. Vous migrez plusieurs fois des agrégats entre nœuds et nœuds pour confirmer qu'au moins un nœud transmet des données depuis les agrégats tout au long de la procédure de mise à niveau. Vous migrez également les interfaces de données logiques (LIF) et vous affectez les ports réseau sur le nouveau contrôleur aux groupes d'interface.


NOTE: Dans ce document, les nœuds d'origine sont appelés _node1_ et _node2_, et les nouveaux nœuds sont appelés _node3_ et _node4_. Au cours de la procédure décrite, le noeud 1 est remplacé par le noeud 3 et le noeud 2 est remplacé par le noeud 4. Les termes _node1_, _node2_, _node3_ et _node4_ sont utilisés uniquement pour distinguer les nœuds d'origine et les nouveaux. Lorsque vous suivez la procédure, vous devez remplacer les véritables noms de vos nœuds d'origine et de vos nouveaux nœuds. Toutefois, en réalité, les noms des nœuds ne changent pas : le nœud 3 porte le nom node1 et le nœud 4 porte le nom node2 une fois le contrôleur mis à niveau. Ce document utilise le terme _systèmes avec le logiciel de virtualisation FlexArray_ pour faire référence aux systèmes qui appartiennent à ces nouvelles plateformes. Il utilise le terme _V-Series system_ pour se référer aux systèmes matériels distincts pouvant être connectés aux baies de stockage

.Information importante :
* Cette procédure est complexe et suppose que vous avez des compétences avancées en administration de ONTAP. Vous devez également lire et comprendre le link:guidelines_upgrade_with_arl.html["Instructions de mise à niveau des contrôleurs avec l'ARL"] et le link:arl_upgrade_workflow.html["Workflow de mise à niveau ARL"] avant de commencer la mise à niveau.
* Cette procédure suppose que le matériel de remplacement du contrôleur est nouveau et qu'il n'a pas été utilisé. Étapes requises pour préparer les contrôleurs utilisés avec le `wipeconfig` la commande n'est pas incluse dans cette procédure. Vous devez contacter le support technique si le matériel de remplacement du contrôleur était précédemment utilisé, en particulier si les contrôleurs exécutaient Data ONTAP sous 7-mode.
* Vous pouvez suivre cette procédure pour mettre à niveau le matériel du contrôleur dans des clusters de plus de deux nœuds. Toutefois, vous devez effectuer la procédure séparément pour chaque paire haute disponibilité du cluster.
* Cette procédure s'applique aux systèmes FAS, aux systèmes V-Series, aux systèmes AFF et aux systèmes équipés du logiciel de virtualisation FlexArray. Les systèmes FAS commercialisés après ONTAP 9 peuvent se connecter aux baies de stockage si la licence requise est installée. Les systèmes V-Series existants sont pris en charge par ONTAP 9. Pour plus d'informations sur la baie de stockage et les modèles V-Series, reportez-vous au link:other_references.html["Références"] Pour accéder à _Hardware Universe_ et voir _V-Series support Matrix_.


* Cette procédure s'applique aux configurations MetroCluster à quatre et huit nœuds qui exécutent ONTAP 9.5 et versions antérieures. Pour les configurations MetroCluster exécutant ONTAP 9.6 ou version ultérieure, rendez-vous sur link:other_references.html["Références"] Pour établir un lien vers _utilisation des commandes de remplacement du contrôleur système pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.5 vers ONTAP 9.7_.

