---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_node2.html 
keywords: node1, node3, nas, lifs, cluster, san 
summary: 'Déplacez les LIF de données NAS du nœud 1 vers le nœud 2 si vous disposez d"un cluster à deux nœuds ou vers un troisième nœud si votre cluster possède plus de deux nœuds, au cours d"une mise à niveau manuelle du transfert d"agrégats, ARL, sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Déplacez les LIF de données NAS qui appartiennent au nœud 1 vers le nœud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de remplacer le nœud 1 par le nœud 3, vous devez déplacer les LIF de données NAS qui appartiennent au nœud 1 vers le nœud 2 si vous disposez d'un cluster à deux nœuds ou vers un troisième nœud si votre cluster possède plus de deux nœuds. La méthode que vous utilisez varie selon que le cluster est configuré pour NAS ou SAN.

.Description de la tâche
Les LIF distantes gèrent le trafic vers des LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour assurer l'intégrité du cluster ou du service pendant la mise à niveau. Vous devez vérifier que les LIFs sont bonnes et situées sur les ports appropriés une fois que vous avez mis le nœud3 en ligne.

.Étapes
. Lister toutes les LIFs de données NAS hébergées sur le nœud1 en saisissant la commande suivante et en capturant la sortie :
+
`network interface show -data-protocol nfs|cifs -curr-node _node1_`

+
Le système affiche les LIFs de données NAS sur le nœud 1, comme illustré ci-dessous :

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. Effectuer l'une des actions suivantes :
+
[cols="40,60"]
|===
| Si le noeud 1... | Alors... 


| Dispose de groupes d'interfaces de réseaux VLAN configurés | Accédez à <<man_move_lif_1_2_step3,Étape 3>>. 


| Aucun groupe d'interface ou VLAN n'est configuré | Ignorez l'étape 3 et passez à <<man_move_lif_1_2_step4,Étape 4>>. 
|===
+
Utilisez le `network port vlan show` Commande pour afficher des informations sur les ports réseau connectés aux VLAN, et utilisez le `network port ifgrp show` commande permettant d'afficher des informations sur les groupes d'interfaces de port.

. [[man_Move_lif_1_2_step3]]effectuez les opérations suivantes pour migrer des LIF de données NAS hébergées sur des groupes d'interfaces et des VLAN sur le nœud 1 :
+
.. [[man_Move_lif_1_2_deepa]]migrer les LIF hébergées sur n'importe quel groupe d'interface et les VLAN du nœud 1 vers un port du nœud 2 qui est capable d'héberger les LIF sur le même réseau que les groupes d'interface en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node2_ –destination-port _netport|ifgrp_`

.. Modifier le port de rattachement et le nœud de rattachement des LIFs et des VLAN dans <<man_move_lif_1_2_substepa,Sous-étape a>> Au port et au nœud qui hébergent actuellement les LIFs en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node2_ - home-port _netport|ifgrp_`



. [[man_Move_lif_1_2_step4]]effectuer l'une des actions suivantes :
+
[cols="20,80"]
|===
| Si le cluster est configuré pour... | Alors... 


| NAS | Terminé <<man_move_lif_1_2_step5,Étape 5>> à <<man_move_lif_1_2_step8,Étape 8>>. 


| SAN | Désactiver toutes les LIFs SAN du nœud pour les désactiver pour la mise à niveau :
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_Move_lif_1_2_step5]]migrer les LIF de données NAS du nœud 1 vers le nœud 2 en saisissant la commande suivante, une fois pour chaque LIF de données :
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination-node _node2_ -destination-port _data_port_`

. [[step6]]Entrez la commande suivante et examinez ses valeurs de sortie pour vérifier que les LIF ont été déplacées vers les ports corrects et que celles-ci ont le statut de up en entrant la commande suivante sur l'un des nœuds et en examinant la sortie :
+
`network interface show -curr-node _node2_ -data-protocol nfs|cifs`

. [[step7]]Entrez la commande suivante pour modifier le nœud de rattachement des LIFs migrées :
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node2_ -home-port _port_name_`

. [[man_Move_lif_1_2_step8]]Vérifiez si la LIF utilise le port comme port de base ou actuel. Si le port n'est pas à la maison ou le port actuel, allez à <<man_move_lif_1_2_step9,Étape 9>>:
+
`network interface show -home-node _node2_ -home-port _port_name_`

+
`network interface show -curr-node _node_name_ -curr-port _port_name_`

. [[man_Move_lif_1_2_ste9]]si les LIFs utilisent le port en tant que port de base ou port actuel, modifiez-les pour utiliser un autre port :
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination–node _node_name_ -destination-port _port_name_`

+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home–node _node_name_ -home-port _port_name_`

. [[step10]]si les ports qui hébergent actuellement des LIFs de données ne vont pas exister sur le nouveau matériel, supprimez-les du broadcast domain maintenant :
+
`network port broadcast-domain remove-ports -ipspace Default -broadcast-domain Default -ports _node:port_`

. [[step11]]si des LIF sont arrêtées, définissez le statut d'administration des LIFs à « up » en entrant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _nodename_ -status-admin up`

+

NOTE: Pour les configurations MetroCluster, il se peut que vous ne puissiez pas modifier le broadcast domain d'un port, car il est associé à un port hébergeant la LIF d'un SVM (Storage Virtual machine) de destination. Taper la commande suivante du SVM source correspondant sur le site distant pour réaffecter le LIF de destination à un port approprié :
`metrocluster vserver resync -vserver _Vserver_name_`

. [[step12]]Entrez la commande suivante et examinez ses valeurs de sortie pour vérifier qu'aucune LIF de données n'est restante sur le nœud 1 :
+
`network interface show -curr-node _node1_ -role data`

. [[step13]]si vous avez configuré des groupes d'interfaces ou des VLAN, procédez comme suit :
+
.. Supprimez les VLAN des groupes d'interface en entrant la commande suivante :
+
`network port vlan delete -node _nodename_ -port _ifgrp_name_ -vlan-id _VLAN_ID_`

.. Entrez la commande suivante et examinez son résultat pour vérifier la présence d'un groupe d'interfaces configuré sur le nœud :
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
Le système affiche les informations sur les groupes d'interfaces pour le nœud, comme illustré ci-dessous :

+
[listing]
----
  cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                   Node: node1
   Interface Group Name: a0a
  Distribution Function: ip
          Create Policy: multimode_lacp
            MAC Address: 02:a0:98:17:dc:d4
     Port Participation: partial
          Network Ports: e2c, e2d
               Up Ports: e2c
             Down Ports: e2d
----
.. Si des groupes d'interface sont configurés sur le nœud, notez les noms de ces groupes et des ports qui leur sont affectés, puis supprimez les ports en entrant la commande suivante, une fois pour chaque port :
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




