---
sidebar: sidebar 
permalink: upgrade-arl-manual/reconfig_index.html 
keywords: reconfigure, fc, switch, layout, RCF, metrocluster 
summary: 'Pour ONTAP 9.1 ou version ultérieure, reconfigurez la disposition des ports et appliquez les protocoles RFC les plus récents lors d"une mise à niveau manuelle du transfert d"agrégats sur des contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Reconfigurer la disposition des commutateurs FC pour ONTAP 9.1 ou version ultérieure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si votre disposition de commutateur FC existante a été configurée avant ONTAP 9.1, vous devez reconfigurer la disposition des ports et appliquer les derniers fichiers RCF (Reference Configuration Files). Cette procédure s'applique uniquement aux configurations MetroCluster FC.

.Avant de commencer
Vous devez identifier les commutateurs FC présents dans le domaine de la structure.

Vous avez besoin du mot de passe d'administration et de l'accès à un serveur FTP ou SCP.

.Description de la tâche
Vous devez effectuer cette tâche si votre configuration de commutateur FC existante a été configurée avant ONTAP 9.1 et que vous effectuez une mise à niveau vers un modèle de plateforme pris en charge par ONTAP 9.1 ou version ultérieure. Il est _NOT_ nécessaire si vous effectuez une mise à niveau à partir d'une configuration de commutateur existante configurée pour ONTAP 9.1 ou version ultérieure.

Cette procédure ne génère aucune interruption et prend environ quatre heures (à l'exception du rack et de la pile) lorsque les disques sont mis à zéro.

.Étapes
. link:send_custom_asup_message_prior_reconfig_switches.html["Envoyer un message AutoSupport personnalisé avant de reconfigurer les commutateurs"]
. link:verify_health_mcc_config.html["Vérifier l'état de santé de la configuration MetroCluster"]
. link:check_mcc_config_errors.html["Recherchez les erreurs de configuration MetroCluster"]
. link:persist_disable_switches.html["Désactivez les commutateurs de manière persistante"]
. link:determine_new_cabling_layout.html["Identification de la nouvelle disposition de câblage"]
. link:apply_RCF_files_recable_switches.html["Appliquer les fichiers RCF et recâblage des commutateurs"]
. link:persist_enable_switches.html["Activer de manière persistante les commutateurs"]
. link:verify_swtichover_healing_switchback.html["Vérification du basculement, de la résolution et du rétablissement"]

