---
sidebar: sidebar 
permalink: upgrade-arl-manual/send_custom_asup_message_prior_reconfig_switches.html 
keywords: autosupport, reconfigure, send message, maintenance, netapp support 
summary: 'Informez le support technique de NetApp que la maintenance est en cours lors d"une mise à niveau manuelle du transfert d"agrégats sur des contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Envoyer un message AutoSupport personnalisé avant de reconfigurer les commutateurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de reconfigurer vos commutateurs, vous devez émettre un message AutoSupport pour informer le support technique de NetApp que la maintenance est en cours. Informer le support technique que la maintenance est en cours empêche l'ouverture d'un dossier en supposant une interruption de l'activité.

Cette tâche doit être effectuée sur chaque site MetroCluster.

.Étapes
. Connectez-vous au cluster.
. Appelez un message AutoSupport indiquant le début de la maintenance :
+
`system node autosupport invoke -node * -type all -message MAINT=_maintenance-window-in-hours_`

+
Le `maintenance-window-in-hours` valeur spécifie la longueur de la fenêtre de maintenance, avec un maximum de 72 heures. Si la maintenance est terminée avant le temps écoulé, vous pouvez appeler un message AutoSupport indiquant la fin de la période de maintenance :

+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Répétez cette procédure sur le site du partenaire.

