---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: 'Si nécessaire, configurez le nouveau module de contrôleur pour NVE ou NAE lors d"une mise à niveau manuelle des agrégats ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Configurez NetApp Volume Encryption ou Aggregate Encryption sur le nouveau module de contrôleur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si le remplacement du contrôleur ou le partenaire HA (haute disponibilité) du nouveau contrôleur utilise NetApp Volume Encryption (NVE) ou NetApp Aggregate Encryption (NAE), il faut configurer le nouveau module de contrôleur pour NVE ou NAE.

.Description de la tâche
Cette procédure comprend les étapes réalisées sur le nouveau module de contrôleur. Vous devez saisir la commande sur le nœud approprié.

.Étapes
. Vérifier que les serveurs de gestion des clés sont toujours disponibles, leur état et leurs informations de clé d'authentification :
+
[cols="35,65"]
|===
| Pour cette version de ONTAP… | Utilisez cette commande... 


| ONTAP 9.6 ou 9.7 | `security key-manager key query -node node` 


| ONTAP 9.5 ou version antérieure | `security key-manager key show` 
|===
. Ajoutez les serveurs de gestion des clés répertoriés à l'étape précédente à la liste des serveurs de gestion des clés du nouveau contrôleur :
+
.. Ajoutez le serveur de gestion des clés à l'aide de la commande suivante :
+
`security key-manager -add _key_management_server_ip_address_`

.. Répétez l'étape précédente pour chaque serveur de gestion des clés répertorié. Vous pouvez lier jusqu'à quatre serveurs de gestion des clés.
.. Vérifiez que les serveurs de gestion des clés ont été correctement ajoutés à l'aide de la commande suivante :
+
`security key-manager show`



. Sur le nouveau module de contrôleur, exécutez l'assistant de configuration de la gestion des clés pour configurer et installer les serveurs de gestion des clés.
+
Vous devez installer les mêmes serveurs de gestion des clés que ceux installés sur le module de contrôleur existant.

+
.. Lancez l'assistant de configuration du serveur de gestion des clés sur le nouveau nœud à l'aide de la commande suivante :
+
`security key-manager setup -node _new_controller_name_`

.. Suivez les étapes de l'assistant pour configurer les serveurs de gestion des clés.


. Restaurez les clés d'authentification de tous les serveurs de gestion de clés liés vers le nouveau nœud.
+
** Restauration de l'authentification pour le gestionnaire de clés externe :
+
`security key-manager external restore`

+
Cette commande nécessite la phrase secrète Onboard Key Manager (OKM)

+
Pour plus d'informations, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["Restauration de la configuration du serveur de gestionnaire de clés externe à partir du menu de démarrage ONTAP"^].

** Restaurer l'authentification pour OKM :
+
[cols="35,65"]
|===
| Pour cette version de ONTAP… | Utilisez cette commande... 


| Toutes les autres versions de ONTAP | `security key-manager onboard sync` 


| ONTAP 9.5 | `security key-manager setup -node _node_name_` 
|===




.Une fois que vous avez terminé
Vérifiez si des volumes ont été mis hors ligne, car les clés d'authentification ne sont pas disponibles ou si les serveurs de gestion des clés externes n'ont pas pu être atteints. Remettre ces volumes en ligne à l'aide du `volume online` commande.
