---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: 'Configurez les ports FC intégrés des nœuds 3, les ports UTA/UTA2 ou la carte UTA/UTA2 lors d"une mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Définissez la configuration FC ou UTA/UTA2 sur le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si le système Node4 est doté de ports FC intégrés, de ports UTA/UTA2 (ou d'une carte UTA/UTA2), vous devez configurer les paramètres avant de suivre la procédure.

.Description de la tâche
Vous devrez peut-être le faire <<Configurez les ports FC sur le nœud 3>>, ou <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>, ou les deux sections.


NOTE: Les documents marketing NetApp peuvent utiliser le terme « UTA2 » pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme « CNA ».

* Si le nœud 3 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2 et que vous mettez à niveau le système avec des disques de stockage, vous pouvez ignorer la link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"].
* Cependant, si vous disposez d'un système V-Series ou d'un système doté du logiciel de virtualisation FlexArray avec des baies de stockage, et que le nœud 3 ne dispose pas de ports FC intégrés, de ports UTA/UTA intégrés ou d'une carte UTA/UTA2, retournez à l'installation et au démarrage sur le nœud 3_, puis reprenez le contrôle link:install_boot_node3.html#man_install3_step22["Étape 22"].


.Choix :
* <<Configurez les ports FC sur le nœud 3>>
* <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>




== Configurez les ports FC sur le nœud 3

Si le nœud 3 dispose de ports FC intégrés ou d'un adaptateur FC, vous devez définir des configurations de ports sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés. Si les ports ne sont pas configurés, le service peut subir une interruption.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 1 que vous avez enregistrées dans link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.


IMPORTANT: Si votre système dispose de disques de stockage, entrez les commandes dans cette section à l'invite du cluster. Si vous disposez d'un système V-Series ou d'un logiciel de virtualisation FlexArray et êtes connecté aux baies de stockage, entrez les commandes de cette section en mode maintenance.

.Étapes
. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Possède des disques de stockage | Accédez à <<man_config_3_step5,Étape 5>> 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Accédez à <<man_config_3_step2,Étape 2>> 
|===
. [[man_config_3_step2]]démarrez le nœud 3 et accédez au mode de maintenance :
+
`boot_ontap maint`

. [[step3]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Possède des disques de stockage | Saisissez la commande suivante :
`system node hardware unified-connect show` 


| Est un système V-Series ou est doté du logiciel de virtualisation FlexArray et est connecté aux baies de stockage. | Saisissez la commande suivante
`ucadmin show` 
|===
+
Le système affiche des informations sur la totalité des adaptateurs réseau convergés et FC sur le système.

. [[step4]]Comparez les paramètres FC du noeud 3 avec les paramètres que vous avez précédemment capturés à partir du noeud 1.
. [[man_config_3_step5]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les paramètres FC par défaut sont définis sur les nouveaux nœuds... | Alors... 


| Identique à ceux que vous avez capturés sur le noeud 1 | Accédez à <<man_config_3_step11,Étape 11>>. 


| Différent de ceux que vous avez capturés sur le nœud1 | Accédez à <<man_config_3_step6,Étape 6>>. 
|===
. [[man_config_3_step6]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Possède des disques de stockage  a| 
Modifiez les ports FC sur le nœud 3 en saisissant l'une des commandes suivantes :

** Pour programmer les ports cibles :
`system node hardware unified-connect modify -type | -t target -adapter _port_name_`
** Pour programmer les ports initiateurs :
`system node hardware unified-connect modify -type | -t initiator -adapter _port_name_`


`-t` Est le type FC4 : cible ou initiateur.



| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage  a| 
Modifiez les ports FC sur le nœud 3 si nécessaire en entrant la commande suivante :

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` Est le type, la cible ou l'initiateur FC4.


NOTE: Les ports FC doivent être programmés comme initiateurs.

|===
. [[step7]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Possède des disques de stockage | Vérifiez les nouveaux paramètres en saisissant la commande suivante et en examinant la sortie :
`system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Vérifiez les nouveaux paramètres en saisissant la commande suivante et en examinant la sortie :
`ucadmin show` 
|===
. [[step8]]quittez le mode de maintenance en entrant la commande suivante :
+
`halt`

. [[step9]]après avoir saisi la commande, attendez que le système s'arrête à l'invite de l'environnement d'amorçage.
. [[step10]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Est un système V-Series ou un logiciel de virtualisation FlexArray exécutant clustered Data ONTAP 8.3 | Démarrez le nœud 3 et accédez à la maintenance au niveau de l'invite de l'environnement de démarrage :
`boot_ontap maint` 


| N'est pas un système V-Series ou ne possède pas le logiciel de virtualisation FlexArray | Démarrez le nœud 3 à l'invite de l'environnement de démarrage :
`boot_ontap` 
|===
. [[man_config_3_step11]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système que vous mettez à niveau... | Alors... 


| Possède des disques de stockage  a| 
** Si le nœud 3 dispose d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2, rendez-vous sur <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.
** Si le nœud 3 ne dispose pas de carte UTA/UTA2 ou de ports intégrés UTA/UTA2, ignorez-le <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>> et allez à link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"].




| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage  a| 
** Si le nœud3 possède une carte ou des ports intégrés, rendez-vous à <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.
** Si le nœud3 ne possède pas de carte ni de ports intégrés, ignorez-le <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>, Puis revenez à _Install and boot node3_ et reprenez à link:install_boot_node3.html#man_install3_step7["Étape 7"].


|===




== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3

Si le nœud 3 est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez vérifier la configuration des ports et éventuellement les reconfigurer, en fonction du mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Si vous souhaitez utiliser un port UTA/UTA2 (Unified Target adapter) pour FC, vous devez d'abord vérifier la configuration du port.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Vous pouvez utiliser le `ucadmin show` commande pour vérifier la configuration actuelle du port :

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
Les ports UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément le trafic NIC et FCoE sur la même interface SFP+ 10 GbE et prend en charge les cibles FC.

Il est possible de trouver des ports UTA2 sur un adaptateur ou un contrôleur et de bénéficier des configurations suivantes, mais vous devez vérifier la configuration des ports UTA/UTA2 sur le nœud 3 et la modifier si nécessaire :

* Les cartes UTA/UTA2 commandées lors de la commande du contrôleur sont configurées avant l'expédition pour avoir la personnalité que vous demandez.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés avant l'expédition pour personnaliser votre demande.
+

NOTE: *Attention* : si votre système dispose de disques de stockage, vous devez saisir les commandes de cette section à l'invite du cluster sauf si vous êtes invité à passer en mode maintenance. Si vous possédez un système VSeries ou un logiciel de virtualisation FlexArray et que vous êtes connecté à des baies de stockage, vous devez entrer des commandes dans cette section à l'invite du mode maintenance. Vous devez être en mode de maintenance pour configurer les ports UTA/UTA2.



.Étapes
. Vérifier la configuration actuelle des ports et l'entrée sur les commandes suivantes sur le nœud3 :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | `system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `ucadmin show` 
|===
+
Un résultat similaire aux exemples suivants s'affiche :

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending  Admin
Adapter  Mode     Type       Mode     Type     Status
-------  -------  ---------  -------  -------  ------
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
*>
----
. [[step2]]si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. [[step3]]examiner la sortie du `system node hardware unified-connect show` ou `ucadmin show` Commande pour déterminer si les ports UTA/UTA2 ont le profil souhaité.
. [[step4]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les ports UTA/UTA2... | Alors... 


| N'avez pas la personnalité que vous voulez | Accédez à <<man_check_3_step5,Étape 5>>. 


| Avoir la personnalité que vous voulez | Passez aux étapes 5 à 12 et passez à <<man_check_3_step13,Étape 13>>. 
|===
. [[man_check_3_step5]]effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage et exécute clustered Data ONTAP 8.3 | Démarrage du nœud 3 et passage en mode maintenance :
`boot_ontap maint` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Accédez à <<man_check_3_step6,Étape 6>>. Vous devez déjà être en mode de maintenance. 
|===
. [[man_check_3_step6]]effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===
| Si vous configurez... | Alors... 


| Ports sur carte UTA/UTA2 | Accédez à <<man_check_3_step7,Étape 7>>. 


| Ports UTA/UTA2 intégrés | Ignorez l'étape 7 et passez à <<man_check_3_step8,Étape 8>>. 
|===
. [[man_check_3_step7]]si l'adaptateur est en mode initiateur, et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter _adapter_name_`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode de maintenance.

. [[man_check_3_step8]]si la configuration actuelle ne correspond pas à l'utilisation souhaitée, modifiez la configuration selon les besoins :
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` est le mode personnalité, `fc` ou `cna`.
** `-t` Est de type FC4, `target` ou `initiator`.
+

NOTE: Vous devez utiliser l'initiateur FC pour les lecteurs de bande, les systèmes de virtualisation FlexArray et les configurations MetroCluster. Vous devez utiliser la cible FC pour les clients SAN.



. Vérifiez les paramètres :
+
`ucadmin show`

. Vérifiez les paramètres :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage  a| 
.. Arrêter le système :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

.. Saisissez la commande suivante :
+
`boot_ontap`





| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Redémarrer en mode maintenance :
`boot_netapp maint` 
|===
. [[step11]]Vérifiez les paramètres :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | `system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray, et il est connecté aux baies de stockage | `ucadmin show` 
|===
+
Les résultats dans les exemples suivants montrent que le type FC4 d'adaptateur « 1b » passe à `initiator` et que le mode des adaptateurs « 2a » et « 2b » passe à `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending    Admin
Adapter  Mode     Type       Mode     Type       Status
-------  -------  ---------  -------  ---------  ------
1a       fc       initiator  -        -          online
1b       fc       target     -        initiator  online
2a       fc       target     cna      -          online
2b       fc       target     cna      -          online
*>
----
. [[step12a]]placez n'importe quel port cible en ligne en entrant l'une des commandes suivantes, une fois pour chaque port :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `fcp config _adapter_name_ up` 
|===
. [[man_check_3_step13]]Connectez le câble au port.
. [[step14]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le système... | Alors... 


| Possède des disques de stockage | Accédez à link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"]. 


| Est un système V-Series ou est doté du logiciel de virtualisation FlexArray et est connecté aux baies de stockage | Retournez à _Install and boot node3_ et reprenez à link:install_boot_node3.html#man_install3_step7["Étape 7"]. 
|===

