---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: 'Configurez les ports FC intégrés des nœuds 3, les ports UTA/UTA2 ou la carte UTA/UTA2 lors d"une mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Définissez la configuration FC ou UTA/UTA2 sur le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si le système Node4 est doté de ports FC intégrés, de ports UTA/UTA2 (ou d'une carte UTA/UTA2), vous devez configurer les paramètres avant de suivre la procédure.

.Description de la tâche
Vous devrez peut-être compléter<<Configurez les ports FC sur le nœud 3>> ou<<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>> , ou les deux sections.


NOTE: Les documents marketing NetApp peuvent utiliser le terme « UTA2 » pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme « CNA ».

Si le nœud 3 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2 et que vous mettez à niveau un système avec des disques de stockage, vous pouvez passer àlink:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"] .



== Configurez les ports FC sur le nœud 3

Si le nœud 3 dispose de ports FC, intégrés ou sur un adaptateur FC complémentaire, vous devez définir les configurations de port sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés lors de l'expédition des systèmes.  Si vous ne configurez pas les ports, vous risquez de subir une interruption de service.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 1 que vous avez enregistrées dans link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.


IMPORTANT: Entrez les commandes de cette section à l’invite du cluster.

.Étapes
. Affichez des informations sur tous les adaptateurs réseau FC et convergés du système.
+
`system node hardware unified-connect show`

. Comparez les paramètres FC du nœud 3 avec les paramètres que vous avez capturés précédemment à partir du nœud 1.
. [[man_config_3_step3]]Effectuez l’une des actions suivantes :
+
[cols="35,65"]
|===
| Si les paramètres FC par défaut sont définis sur les nouveaux nœuds... | Alors... 


| Identique à ceux que vous avez capturés sur le noeud 1 | Aller à<<man_config_3_step9,Étape 9>> . 


| Différent de ceux que vous avez capturés sur le nœud1 | Aller à<<man_config_3_step4,Étape 4>> . 
|===
. [[man_config_3_step4]]Modifiez les ports FC sur le nœud 3 selon vos besoins en entrant l'une des commandes suivantes :
+
** Pour programmer les ports cibles :
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Pour programmer les ports initiateurs :
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Est le type FC4 : cible ou initiateur.



. Vérifiez les nouveaux paramètres en entrant la commande suivante et en examinant la sortie :
+
`system node hardware unified-connect show`

. Quitter le mode Maintenance :
+
`halt`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Démarrez le nœud 3 à l’invite de l’environnement de démarrage :
+
`boot_ontap`

. [[man_config_3_step9]]Effectuez l’une des actions suivantes :
+
** Si le nœud 3 dispose d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2, rendez-vous sur <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.
** Si le nœud 3 ne dispose pas de carte UTA/UTA2 ou de ports intégrés UTA/UTA2, ignorez-le <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>> et allez à link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"].






== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3

Si le nœud 3 est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez vérifier la configuration des ports et éventuellement les reconfigurer, en fonction du mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Si vous souhaitez utiliser un port UTA/UTA2 (Unified Target adapter) pour FC, vous devez d'abord vérifier la configuration du port.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Vous pouvez utiliser le `ucadmin show` commande pour vérifier la configuration actuelle du port :

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
Les ports UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément le trafic NIC et FCoE sur la même interface SFP+ 10 GbE et prend en charge les cibles FC.

Il est possible de trouver des ports UTA2 sur un adaptateur ou un contrôleur et de bénéficier des configurations suivantes, mais vous devez vérifier la configuration des ports UTA/UTA2 sur le nœud 3 et la modifier si nécessaire :

* Les cartes UTA/UTA2 commandées lors de la commande du contrôleur sont configurées avant l'expédition pour avoir la personnalité que vous demandez.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés avant l'expédition pour personnaliser votre demande.
+

NOTE: Saisissez les commandes de cette section à l’invite du cluster, sauf si vous êtes invité à entrer en mode Maintenance.



.Étapes
. Vérifiez la configuration actuelle du port en entrant la commande suivante sur node3 :
+
`system node hardware unified-connect show`

+
Un résultat similaire à l'exemple suivant s'affiche :

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[step2]]si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. [[step3]]examiner la sortie du `system node hardware unified-connect show` ou `ucadmin show` Commande pour déterminer si les ports UTA/UTA2 ont le profil souhaité.
. [[step4]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les ports UTA/UTA2... | Alors... 


| N'avez pas la personnalité que vous voulez | Accédez à <<man_check_3_step5,Étape 5>>. 


| Avoir la personnalité que vous voulez | Sautez les étapes 5 à 13 et passez à<<man_check_3_step14,Étape 14>> . 
|===
. [[man_check_3_step5]]Si le système dispose de disques de stockage et exécute clustered Data ONTAP 8.3, démarrez node3 et entrez en mode maintenance :
+
`boot_ontap maint`

. Vérifiez les paramètres :
+
`ucadmin show`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si vous configurez... | Alors... 


| Ports sur carte UTA/UTA2 | Aller à<<man_check_3_step8,Étape 8>> . 


| Ports UTA/UTA2 intégrés | Sautez l'étape 8 et passez à<<man_check_3_step9,Étape 9>> . 
|===
. [[man_check_3_step8]]Si l'adaptateur est en mode initiateur et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter _adapter_name_`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode de maintenance.

. [[man_check_3_step9]]Si la configuration actuelle ne correspond pas à l'utilisation souhaitée, modifiez la configuration selon vos besoins :
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` est le mode personnalité, `fc` ou `cna`.
** `-t` Est de type FC4, `target` ou `initiator`.
+

NOTE: Vous devez utiliser l'initiateur FC pour les lecteurs de bande et les configurations MetroCluster .  Vous devez utiliser la cible FC pour les clients SAN.



. Arrêter le système :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

. Saisissez la commande suivante :
+
`boot_ontap`

. [[step11]]Vérifiez les paramètres :
+
`system node hardware unified-connect show`

+
Les résultats dans les exemples suivants montrent que le type FC4 d'adaptateur « 1b » passe à `initiator` et que le mode des adaptateurs « 2a » et « 2b » passe à `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]Placez tous les ports cibles en ligne en entrant la commande suivante, une fois pour chaque port :
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step14]]Câblez le port.

