---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_1_index.html 
keywords: stage 1, prepare, upgrade, steps 
summary: 'Étape 1 : processus de mise à niveau manuelle d"agrégats ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Présentation de la phase 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la phase 1, le cas échéant, vérifiez que les disques internes ne contiennent pas d'agrégats racines ou d'agrégats de données, préparez les nœuds pour la mise à niveau et exécutez une série de contrôles préalables. Vous pouvez également avoir besoin de clés à main pour le chiffrement du stockage et préparer le démarrage sur le réseau des nouveaux contrôleurs.

.Étapes
. link:determine_aggregates_on_internal_drives.html["Déterminez si le contrôleur possède des agrégats sur des disques internes"]
. link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"]
. link:manage_authentication_okm.html["Gérez les clés d'authentification à l'aide du gestionnaire de clés intégré"]
. link:quiesce_snapmirror_relationships.html["Suspendre les relations SnapMirror"]
. link:prepare_for_netboot.html["Préparation à la mise sur le réseau"]

