---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_5_index.html 
keywords: stage 5, install, boot, node3, node4, relocate, aggregates 
summary: 'Étape 5 : processus de mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Présentation de la phase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la phase 5, vous installez et démarrez le nœud 4, mappez les ports de cluster et de gestion des nœuds du nœud 2 vers le nœud 4, vérifiez l'installation du nœud 4 et déplacez les LIF de données et les LIF SAN appartenant au nœud 2, du nœud 3 vers le nœud 4. Vous pouvez également transférer les agrégats du nœud 2 du nœud 3 vers le nœud 4.

.Étapes
. link:install_boot_node4.html["Installez et démarrez Node4"]
. link:set_fc_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"]
. link:map_ports_node2_node4.html["Mappage des ports du node2 au node4"]
. link:verify_node4_installation.html["Vérifiez l'installation du node4"]
. link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["Déplacez les LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4, puis vérifiez les LIF SAN sur le nœud 4"]
. link:relocate_node2_non_root_aggr_node3_node4.html["Déplacez les agrégats non racines nœud2 du nœud 3 vers le nœud 4"]

