---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_6_index.html 
keywords: stage 6, complete, upgrade, set up, setup, controller, storage encryption, netapp encryption, decommission, resume snapmirror 
summary: 'Étape 6 : processus de mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 6, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NetApp Volume Encryption. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

. link:manage_authentication_kmip.html["Gérez l'authentification à l'aide de serveurs KMIP"]
. link:ensure_controllers_set_up_correctly.html["Vérifiez que les nouveaux contrôleurs sont correctement configurés"]
. link:set_up_storage_encryption_new_controller.html["Configurez Storage Encryption sur le nouveau module de contrôleur"]
. link:set_up_netapp_encryption_on_new_controller.html["Configurez NetApp Volume Encryption ou Aggregate Encryption sur le nouveau module de contrôleur"]
. link:decommission_old_system.html["Désaffectation de l'ancien système"]
. link:resume_snapmirror_ops.html["Reprendre les opérations SnapMirror"]

