---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_2_index.html 
keywords: relocate, retire, node1, steps,  stage 2 
summary: 'Étape 2 : processus de mise à niveau manuelle d"agrégats ARL sur les contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 2, vous transférez des agrégats non-racines du nœud 1 vers le nœud 2, et déplacez les LIF de données non-SAN qui appartiennent au nœud 1 vers le nœud 2, y compris les agrégats défaillants ou vetotés. Vous enregistrez également les informations nécessaires sur le nœud1 pour une utilisation ultérieure dans la procédure, puis retirez le nœud1.

.Étapes
. link:relocate_non_root_aggr_node1_node2.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 1 vers le nœud 2"]
. link:move_nas_lifs_node1_node2.html["Déplacement des LIF de données NAS qui appartiennent au nœud 1 vers le nœud 2"]
. link:record_node1_information.html["Enregistrement des informations sur le noeud 1"]
. link:retire_node1.html["Retirer le nœud 1"]

