---
sidebar: sidebar 
permalink: upgrade-arl-manual/verify_node4_installation.html 
keywords: install, node4, node3, verify, communicate 
summary: 'Vérifiez l"installation du nœud 4 et la communication avec le nœud 3 lors d"une mise à niveau manuelle du transfert d"agrégats sur des contrôleurs exécutant ONTAP 9.7 ou une version antérieure.' 
---
= Vérifiez l'installation du node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois que vous avez installé et installé le nœud 4, vous devez vérifier qu'il est installé correctement, qu'il fait partie du cluster et qu'il peut communiquer avec le nœud 3.

.Étapes
. À l'invite du système, connectez-vous au nœud 4.
. Vérifiez que le noeud 4 fait partie du même cluster que le noeud 3 et qu'il est en bon état :
+
`cluster show`

. Vérifier que le nœud 4 peut communiquer avec le nœud 3 et que toutes les LIFs sont en service :
+
`network interface show -curr-node _node4_`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le noeud 4 est... | Alors... 


| Dans un châssis séparé du nœud3  a| 
Connectez l'interconnexion haute disponibilité entre les nœuds en procédant comme suit :

.. Connectez le port d'interconnexion supérieur du nœud3 au port d'interconnexion supérieur du nœud4.
.. Connectez le port d'interconnexion inférieur du nœud3 au port d'interconnexion inférieur du nœud4.
.. Accédez à ,Étape 5.




| Dans le même châssis que le nœud 3 | Accédez à ,Étape 5. Inutile de connecter manuellement l'interconnexion haute disponibilité entre les nœuds. Dans les configurations de même châssis, l'interconnexion haute disponibilité est connectée automatiquement via le fond de panier. 
|===
. [[étape 5]]effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si le cluster est... | Alors... 


| Dans un environnement SAN | Terminé ,Étape 6 et allez à la section link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["Déplacez les LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4, puis vérifiez les LIF SAN sur le nœud 4"]. 


| Pas dans un environnement SAN | Passez à l'étape 6. Passez à la section link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["Déplacez les LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4, puis vérifiez les LIF SAN sur le nœud 4"]. 
|===
. [[Step6]]Vérifiez que les noeuds 3 et 4 sont dans le quorum en entrant la commande suivante sur l'un des noeuds :
+
`event log show -messagename scsiblade.*`

+
L'exemple suivant montre la sortie lorsque les nœuds du cluster sont au quorum :

+
[listing]
----
cluster::> event log show -messagename scsiblade.*
Time                Node   Severity      Event
------------------- ------ ------------- --------------------------
8/13/2012 14:03:51  node1  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:51  node2  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:48  node3  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:43  node4  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
----

