---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Vous pouvez décider de mettre à niveau les contrôleurs exécutant ONTAP 9.8 ou version ultérieure à l"aide du transfert d"agrégats `system controller replace` commandes.' 
---
= Décider d'utiliser ou non cette procédure de relocalisation globale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs méthodes de relocalisation d'agrégats (ARL) pour mettre à niveau le matériel du contrôleur. Cette procédure décrit comment mettre à niveau le matériel du contrôleur à l'aide de la relocalisation d'agrégats (ARL) avec les commandes de remplacement du contrôleur système sur les systèmes exécutant ONTAP 9.8 ou version ultérieure. Cette procédure complexe est réservée aux administrateurs ONTAP expérimentés.

Pour vous aider à décider si cette procédure ARL est adaptée à la mise à niveau du matériel de votre contrôleur, vous devez examiner toutes les circonstances suivantes pour les mises à niveau prises en charge :

* Vous utilisez ONTAP 9.8 ou une version ultérieure.
* Vous ne souhaitez pas ajouter de nouveaux contrôleurs comme nouvelle paire haute disponibilité au cluster et migrer les données à l'aide des déplacements de volumes.
* Vous êtes expérimenté dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilège de diagnostic.
* Si vous mettez à niveau une configuration MetroCluster, il s'agit d'une configuration FC à quatre nœuds ou plus, et tous les nœuds exécutent ONTAP 9.8 ou version ultérieure.
+
Pour mettre à niveau les configurations IP de MetroCluster, reportez-vous au link:other_references.html["Références"]lien vers _mise à niveau et extension MetroCluster_.



[NOTE]
====
* Si vous mettez à niveau un système en échangeant des modules de contrôleur dans le même châssis, comme AFF A800 ou AFF C800, NetApp recommande fortement d'utiliser la procédure de mise à niveau quilink:../upgrade-arl-auto-in-chassis/index.html["met à niveau les modèles de contrôleurs à l'aide d'ARL, en conservant le châssis et les disques du système existant"] .  Cette procédure ARL inclut les étapes qui garantissent que les disques internes restent sécurisés dans le châssis lorsque vous retirez et installez les contrôleurs pendant la procédure de mise à niveau.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Découvrez les combinaisons de mise à niveau système prises en charge à l'aide d'ARL, en conservant le châssis et les disques système existants"].

* Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).


====


== Combinaisons de mise à niveau du système prises en charge

Le tableau suivant présente la matrice des systèmes pris en charge pour effectuer une mise à niveau du contrôleur à l'aide de cette procédure ARL.

|===
| Ancien contrôleur | Remplacement du contrôleur 


| FAS8020^3^, FAS8040^3^, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| FAS8060^4^, FAS8080^4^ | FAS9500 


| AFF8020^3^, AFF8040^3^, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800^1^ 


| AFF8060^4^, AFF8080^4^ | AFF A900 


| FAS8200 | FAS8300^2^, FAS8700, FAS9000, FAS9500 


| FAS8300, FAS8700, FAS9000 | FAS9500 


| AFF A300 | AFF A400^2^, AFF A700, AFF A800^1^, AFF A900 


| AFF A320^4^ | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===

NOTE: Si votre combinaison de modèles de mise à niveau de contrôleurs ne figure pas dans le tableau ci-dessus, contactez le support technique.

^1^pour les étapes supplémentaires requises pour les systèmes AFF A800, passez à l'étape qui fait référence à A800 dans la section link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Réaffectez les disques du nœud 1 au nœud 3, étape 9"], ou link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["Réaffectez les disques du nœud 2 au nœud 4, étape 9"].

^2^si vous effectuez une mise à niveau d'un système AFF A300 vers un système AFF A400 ou FAS8200 vers un système FAS8300 dans une configuration en cluster sans commutateur à deux nœuds, vous devez choisir des ports de cluster temporaires pour la mise à niveau du contrôleur. Les systèmes AFF A400 et FAS8300 se présentent dans deux configurations sous la forme d'un bundle Ethernet où les ports de carte mezzanine sont de type Ethernet et sous la forme d'un bundle FC où les ports mezzanine sont de type FC.

* Dans le cas d'un système AFF A400 ou FAS8300 avec une configuration de type Ethernet, vous pouvez utiliser n'importe lequel des deux ports mezzanine comme ports de cluster temporaires.
* Pour un système AFF A400 ou FAS8300 avec une configuration de type FC, vous devez ajouter une carte d'interface réseau 10GbE à quatre ports (référence X1147A) pour fournir les ports de cluster temporaires.
* Après avoir effectué la mise à niveau du contrôleur en utilisant des ports de cluster temporaires, vous pouvez migrer les LIF de cluster vers les ports e3a et e3b, 100 GbE sur un système AFF A400 et e0c et e0d, 100 GbE sur un système FAS8300 sans interruption.


^3^pour les mises à niveau des systèmes FAS8020, FAS8040, AFF8020 et AFF8040 vers les contrôleurs de remplacement cibles répertoriés dans le tableau ci-dessus, les contrôleurs de remplacement doivent exécuter la même version ONTAP que l'ancien contrôleur. Notez que les systèmes FAS8020, FAS8040, AFF8020 et AFF8040 ne prennent pas en charge les versions ONTAP ultérieures à ONTAP 9.8.

^4^le tableau suivant indique les versions ONTAP minimum et ultérieures prises en charge pour ces combinaisons de mise à niveau de contrôleur.

[cols="20,30,20,30"]
|===
2+| Ancien contrôleur 2+| Remplacement du contrôleur 


| Système | Version ONTAP | Système | Version ONTAP 


| AFF A320 | 9.9.1 ou ultérieure | AFF A400 | 9.9.1 ou ultérieure 


| AFF 8060 | Correctifs 9.8P13 ou version ultérieure | AFF A900 | 9.10.1 à 9.12.1 


| AFF 8080 | Correctifs 9.8P10 ou version ultérieure | AFF A900 | 9.10.1 à 9.12.1 


| FAS8060 | Correctifs 9.8P13 ou version ultérieure | FAS9500 | 9.10.1P3 à 9.12.1 


| FAS8080 | Correctifs 9.8P12 ou version ultérieure | FAS9500 | 9.10.1P3 à 9.12.1 
|===
[NOTE]
====
Pour les combinaisons de mise à niveau indiquées dans le tableau précédent :

* Il n'est pas nécessaire d'utiliser la même version de ONTAP sur les contrôleurs existants et de remplacement. La mise à niveau logicielle de ONTAP est effectuée lors de la mise à niveau du contrôleur.
* Lors de la mise à niveau, vous devez installer un contrôleur de remplacement avec une version ONTAP et un niveau de patch pris en charge.
* Il n'est pas possible d'annuler ou de retirer une mise à niveau du contrôleur après le démarrage de la procédure et la mise à niveau du premier nœud.


====


== Choisissez une autre procédure de mise à niveau matérielle

* link:../upgrade-arl/index.html["Passez en revue les méthodes ARL alternatives disponibles pour la mise à niveau du matériel du contrôleur"].
* Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.


.Informations associées
Se référer à link:other_references.html["Références"] pour créer un lien vers la _Documentation ONTAP 9_.
