---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decommission_old_system.html 
keywords: decommission, old system, upgrade, databases, netapp, support, site, serial, number, cluster 
summary: 'Faites savoir à NetApp que l"ancien système n"est plus opérationnel après la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou version ultérieure en utilisant `system controller replace` commandes.' 
---
= Désaffectation de l'ancien système
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Une fois la mise à niveau effectuée, vous pouvez désaffecter l'ancien système via le site de support NetApp. Hors fonctionnement du système dit à NetApp que le système n'est plus opérationnel et qu'il l'supprime des bases de données de prise en charge.

.Étapes
. Reportez-vous à la section link:other_references.html["Références"] Pour accéder au _site de support NetApp_ et connectez-vous.
. Sélectionnez *produits > Mes produits* dans le menu.
. Sur la page *Afficher les systèmes installés*, choisissez les *critères de sélection* que vous souhaitez utiliser pour afficher des informations sur votre système.
+
Vous pouvez choisir l'une des options suivantes pour localiser votre système :

+
** Numéro de série (situé à l'arrière de l'appareil)
** Numéros de série pour mon emplacement


. Sélectionnez *Go!*
+
Un tableau affiche les informations sur le cluster, y compris les numéros de série.

. Localisez le cluster dans le tableau et sélectionnez *Decommission This system* dans le menu déroulant Product Tool Set.

