---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/ensure_new_controllers_are_set_up_correctly.html 
keywords: confirm, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: 'Activation de la paire haute disponibilité, vérification de l"accès au stockage des nœuds 3 et 4, et confirmation de la propriété de l"agrégat après la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou une version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Vérifiez que les nouveaux contrôleurs sont correctement configurés
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour confirmer la configuration correcte, vous devez activer la paire HA. Vous devez également vérifier que les nœuds 3 et Node4 ne sont pas en mesure d'accéder aux systèmes de stockage des autres et que les LIF de données ne sont pas membres du cluster. Vous devez également confirmer que le nœud 3 est propriétaire des agrégats du nœud 1 et que le nœud 4 est propriétaire des agrégats du nœud 2, et que les volumes des deux nœuds sont en ligne.

.Étapes
. Après la vérification du post-nœud 2, le basculement du stockage et la paire HA du cluster pour le cluster node 2 sont activés. Lorsque l'opération est effectuée, les deux nœuds indiquent que l'opération est terminée et le système effectue certaines opérations de nettoyage.
. Vérifiez que le basculement du stockage est activé :
+
`storage failover show`

+
L'exemple suivant montre la sortie de la commande lorsque le basculement du stockage est activé :

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. Vérifiez que les nœuds 3 et 4 appartiennent au même cluster à l'aide de la commande suivante et en examinant le résultat :
+
`cluster show`

. Vérifiez que les nœuds 3 et Node4 peuvent accéder mutuellement au stockage, à l'aide de la commande suivante et en examinant le résultat :
+
`storage failover show -fields local-missing-disks, partner-missing-disks`

. Vérifiez que les nœuds 3 et NODE4 ne possèdent pas de LIF de données détenues par d'autres nœuds du cluster à l'aide de la commande suivante et en examinant la sortie.
+
`network interface show`

+
Si les LIF de données des nœuds 3 ou 4 ne sont pas propriétaires de LIF de données détenues par d'autres nœuds du cluster, restaurez-les au propriétaire de leur domicile :

+
`network interface revert`

. Vérifiez que le nœud 3 possède les agrégats du nœud 1 et que le nœud 4 est propriétaire des agrégats du nœud 2 :
+
`storage aggregate show -owner-name _node3_`

+
`storage aggregate show -owner-name _node4_`

. Déterminez si des volumes sont hors ligne :
+
`volume show -node _node3_ -state offline`

+
`volume show -node _node4_ -state offline`

. Si des volumes sont hors ligne, comparez-les avec la liste des volumes hors ligne que vous avez capturés dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"], et de mettre en ligne l'un des volumes hors ligne, si nécessaire, à l'aide de la commande suivante, une fois pour chaque volume :
+
`volume online -vserver _vserver_name_ -volume _volume_name_`

. Installez les nouvelles licences pour les nouveaux nœuds à l'aide de la commande suivante pour chaque nœud :
+
`system license add -license-code _license_code,license_code,license_code…_`

+
Le paramètre License-code accepte une liste de 28 clés de caractères alphabétiques majuscules. Vous pouvez ajouter une licence à la fois ou ajouter plusieurs licences à la fois, en séparant chaque clé de licence par une virgule.

. Supprimez toutes les anciennes licences des nœuds d'origine à l'aide de l'une des commandes suivantes :
+
`system license clean-up -unused -expired`

+
`system license delete -serial-number _node_serial_number_ -package _licensable_package_`

+
--
** Supprimer toutes les licences expirées :
+
`system license clean-up -expired`

** Supprimer toutes les licences inutilisées :
+
`system license clean-up -unused`

** Supprimez une licence spécifique d'un cluster à l'aide des commandes suivantes sur les nœuds :
+
`system license delete -serial-number _node1_serial_number_ -package *`

+
`system license delete -serial-number _node2_serial_number_ -package *`



--
+
Les valeurs de sortie suivantes sont affichées :

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
Entrez `y` pour supprimer tous les paquets.

. Vérifiez que les licences sont correctement installées à l'aide de la commande suivante et en examinant le résultat :
+
`system license show`

+
Vous pouvez comparer la sortie avec la sortie capturée dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

. Si vous utilisez des disques à chiffrement automatique dans la configuration, et que vous avez défini le `kmip.init.maxwait` variable à `off` (par exemple, dans link:install_boot_node4.html#step27["Installez et démarrez node4, étape 27"]), vous devez annuler la variable :
+
`set diag; systemshell -node _node_name_ -command sudo kenv -u -p kmip.init.maxwait`



. [[étape 13]]configurez les SP à l'aide de la commande suivante sur les deux nœuds :
+
`system service-processor network modify -node _node_name_`

+
Reportez-vous à la section link:other_references.html["Références"] Pour accéder à _System Administration Reference_ pour obtenir des informations sur les processeurs de stockage et les _ONTAP 9.8 Commands: Manual page Reference_ pour obtenir des informations détaillées sur le système `service-processor network modify` commande.

. Pour configurer un cluster sans commutateur sur les nouveaux nœuds, reportez-vous à la section link:other_references.html["Références"] Pour établir un lien vers le site de support _NetApp_ et suivre les instructions de la section _transition vers un cluster_ sans commutateur à deux nœuds_.


.Une fois que vous avez terminé
Si le cryptage du stockage est activé sur les nœuds 3 et 4, complétez la section link:set_up_storage_encryption_new_module.html["Configurez Storage Encryption sur le nouveau module de contrôleur"]. Sinon, complétez la section link:decommission_old_system.html["Désaffectation de l'ancien système"].
