---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Vous pouvez savoir si vous pouvez mettre à niveau les contrôleurs exécutant ONTAP 9.8 ou version ultérieure en utilisant `system controller replace` commandes.' 
---
= Instructions de mise à niveau des contrôleurs avec l'ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour savoir si vous pouvez utiliser la fonctionnalité ARL pour mettre à niveau une paire de contrôleurs exécutant ONTAP 9.8 ou version ultérieure, vous devez également connaître la plateforme et la configuration des contrôleurs d'origine et de remplacement.



[[supported-upgrades-for-arl]]
== Mises à niveau prises en charge pour l'ARL

Lorsque vous mettez à niveau une paire de nœuds à l'aide de cette procédure d'ARL pour ONTAP 9.8 ou version ultérieure, vous devez vérifier que l'ARL peut être réalisé sur les contrôleurs d'origine et de remplacement.

Vous devez vérifier la taille de tous les agrégats définis et le nombre de disques pris en charge par le système d'origine. Vous devez ensuite comparer la taille de l'agrégat et le nombre de disques pris en charge à la taille de l'agrégat et au nombre de disques pris en charge par le nouveau système. Consultez link:other-references.html["Références"] pour accéder à _Hardware Universe_ où ces informations sont disponibles. La taille de l'agrégat et le nombre de disques pris en charge par le nouveau système doivent être égaux ou supérieurs à la taille de l'agrégat et au nombre de disques pris en charge par le système d'origine.

Vous devez valider dans les règles de mixage de clusters si de nouveaux nœuds peuvent être intégrés au cluster avec les nœuds existants lors du remplacement du contrôleur d'origine. Pour plus d'informations sur les règles de mixage de clusters, reportez-vous à link:other-references.html["Références"] pour accéder à _Hardware Universe_.


NOTE: Si vous mettez à niveau un système qui prend en charge les disques internes (par exemple, un FAS2700 ou AFF A250) mais qui ne possède PAS de disques internes, reportez-vous à link:other-references.html["Références"] et utilisez la procédure du contenu _Aggregate Relocation to Manually Upgrade Controller Hardware_ qui correspond à votre version de ONTAP.

Si vous possédez un système doté de plus de deux ports de cluster par nœud, par exemple un système FAS8080 ou AFF8080, avant de démarrer la mise à niveau, vous devez migrer et ré-home les LIF de cluster sur deux ports de cluster par nœud. Si vous effectuez la mise à niveau du contrôleur avec plus de deux ports de cluster par nœud, des LIF de cluster risquent d'être manquantes sur le nouveau contrôleur après la mise à niveau.

La mise à niveau du contrôleur avec l'ARL est prise en charge sur les systèmes configurés avec les volumes SnapLock Enterprise et SnapLock Compliance.



[[two-node-switchless-clusters]]
== Clusters à 2 nœuds sans commutateur

Si vous mettez à niveau des nœuds dans un cluster sans commutateur à 2 nœuds, vous pouvez quitter le cluster sans commutateur tout en effectuant la mise à niveau. Il n'est pas nécessaire de les convertir en cluster commuté.



[[upgrades-not-supported-for-arl]]
== Mises à niveau non prises en charge pour l'ARL

Vous ne pouvez pas effectuer les mises à niveau suivantes :

* Remplacement des contrôleurs qui ne prennent pas en charge les tiroirs disques connectés aux contrôleurs d'origine
+
Consultez link:other-references.html["Références"] pour accéder à _Hardware Universe_ et obtenir des informations sur la prise en charge des disques.

* Aux contrôleurs d'entrée de gamme avec disques internes, par exemple : un FAS2750.
+
Si vous souhaitez mettre à niveau des contrôleurs d'entrée de gamme avec disques internes, reportez-vous à link:other-references.html["Références"]_Mise à niveau par déplacement de volumes ou de stockage_ et accédez à la procédure _Mise à niveau d'une paire de nœuds exécutant Data ONTAP par déplacement de volumes_.





[[metrocluster-fc-configuration]]
== Configuration MetroCluster FC

En configuration MetroCluster FC, vous devez remplacer les nœuds du site de reprise après incident/basculement dans les plus brefs délais. Les différences entre les modèles de contrôleur et MetroCluster ne sont pas prises en charge, car une non-concordance de modèle de contrôleur peut entraîner la mise en miroir de la reprise après incident. Utilisez `-skip-metrocluster-check true` la commande pour contourner les vérifications MetroCluster lorsque vous remplacez des nœuds sur le second site.



[[troubleshoot]]
== Résoudre les problèmes

Vous pouvez être confronté à une défaillance lors de la mise à niveau de la paire de nœuds. Il est possible que le nœud tombe en panne, mais que les agrégats ne soient pas transférés ou que les LIF ne migrent pas. La cause de l'échec et sa solution dépendent du moment où l'échec s'est produit pendant la procédure de mise à niveau.

Si des problèmes surviennent, reportez-vous à la link:aggregate_relocation_failures.html["Résoudre les problèmes"] Consultez la section à la fin de la procédure pour plus d'informations et les solutions possibles. Les informations sur les défaillances possibles sont répertoriées par phase de la procédure dans la section link:overview_of_the_arl_upgrade.html["Séquence de mise à niveau ARL"] .

Si vous ne trouvez pas de solution au problème que vous rencontrez, contactez le support technique.

.Et la suite ?
Après avoir examiné les directives de mise à niveau des contrôleurs avec ARL, link:verify_health_of_metrocluster_config.html["vérifier l'état de la configuration MetroCluster"].
