---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: 'Vérifiez que les LIF de données NAS du nœud 1 sur le nœud 2 sont transférées du nœud 2 vers le nœud 3 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 1 du nœud 2 vers le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Après avoir vérifié la configuration réseau sur le nœud 3 et avant de transférer les agrégats du nœud 2 vers le nœud 3, vous devez vérifier que les LIF de données NAS appartenant au nœud 1 actuellement sur le nœud 2 sont transférées du nœud 2 vers le nœud 3. Vous devez également vérifier que des LIFs SAN existent sur le noeud 3.

.Description de la tâche
Les LIF distantes gèrent le trafic vers des LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour assurer l'intégrité du cluster ou du service pendant la mise à niveau. Les LIF SAN ne sont pas déplacées sauf si elles doivent être mappées sur de nouveaux ports. Vous vérifierez que les LIFs sont saines et situées sur les ports appropriés après avoir mis le nœud3 en ligne.


NOTE: Si vous modifiez la vitesse de port des cartes d'interface réseau Ethernet T6 ou des ports de carte mère, vous pouvez constater que des paquets mal formés sont reçus après la conversion de vitesse. Voir https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["Code de bogue en ligne de NetApp Bugs 1570339"^] et l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["Erreurs CRC sur les ports T6 après la conversion de 40 GbE à 100 GbE"^] pour obtenir des conseils.

.Étapes
. Reprendre l'opération de relocalisation :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les tâches suivantes :

+
** Vérification du quorum du cluster
** Vérification de l'ID système
** Vérification de la version d'image
** Vérification de la plate-forme cible
** Vérification de l'accessibilité du réseau


+
L'opération s'interrompt à cette étape de la vérification de la capacité d'accessibilité du réseau.

. Reprendre l'opération de relocalisation :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
** Vérification de l'état du cluster
** Vérification de l'état de la LIF de cluster


+
Après ces vérifications, le système relocalise les agrégats non-racine et les LIF de données NAS qui appartiennent au nœud1 vers le nouveau contrôleur, node3. L'opération de remplacement du contrôleur s'interrompt une fois le transfert de ressources terminé.

. Vérifier le statut du transfert d'agrégats et du déplacement des LIF de données NAS :
+
[source, cli]
----
system controller replace show-details
----
+
Si la procédure de remplacement du contrôleur est suspendue, vérifiez et corrigez l'erreur, le cas échéant, puis faites-la `resume` pour poursuivre l'opération.

. Si nécessaire, restaurez et rétablissez les LIF déplacées ou migrez et modifiez manuellement les LIF du nœud 1 qui n'ont pas pu être déplacées automatiquement vers le nœud 3.
+
[role="tabbed-block"]
====
.Restaurez et rétablissez les LIF déplacés
--
.. Veuillez indiquer les LIF déplacés :
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Si des LIF sont déplacées, restaurer le nœud de rattachement vers le nœud3 :
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migration et modification manuelles des LIF
--
.. Migrer vers le nœud 3 les LIF qui n'ont pas pu être déplacés automatiquement :
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. Modifiez le nœud d'origine et le port d'origine pour les LIF migrées :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. Reprenez l'opération pour demander au système d'effectuer les vérifications post-requises :
+
[source, cli]
----
system controller replace resume
----
+
Le système effectue les vérifications suivantes :

+
** Vérification du quorum du cluster
** Vérification de l'état du cluster
** Vérification de la reconstruction d'agrégats
** Vérification de l'état de l'agrégat
** Vérification de l'état du disque
** Vérification de l'état de la LIF de cluster
** Vérification du volume



