---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 'Préparez les nœuds et exécutez une série de contrôles préalables lors de la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou version ultérieure en utilisant `system controller replace` commandes.' 
---
= Préparer les nœuds pour une mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La procédure suivante permet de préparer les nœuds à la mise à niveau.

.Étapes
. Lancer le processus de remplacement du contrôleur en entrant la commande suivante dans la ligne de commande ONTAP :
+
`system controller replace start -nodes _node_names_`

+
[NOTE]
====
** Depuis ONTAP 9.10.1, la procédure de mise à niveau NSO (Automated Negotiated switchover) est la procédure par défaut pour une configuration FC MetroCluster à quatre nœuds. Si vous mettez à niveau une configuration FC MetroCluster à quatre nœuds, lorsque vous rencontrez un problème sur le `system controller replace start` Vous devez empêcher le lancement de la procédure basée sur NSO en définissant le `-nso` paramètre à `false`:
+
`system controller replace start -nodes _node_names_ -nso false`

** Le `system controller replace start` la commande ne peut être exécutée qu'au niveau de privilège avancé :
+
`set -privilege advanced`



====
+
Vous verrez le résultat suivant :

+
....
Warning:
1. Current ONTAP version is 9.x
Before starting controller replacement operation, ensure that the new controllers are running the version 9.x

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

Do you want to continue? {y|n}: y
....
. Appuyez sur `y`, vous verrez le résultat suivant :
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
Le système exécute les contrôles préalables suivants ; notez le résultat de chaque contrôle préalable pour utilisation ultérieure de la procédure :

+
[cols="35,65"]
|===
| Contrôle préalable | Description 


| Vérification de l'état du cluster | Vérifie que tous les nœuds du cluster sont défectueux. 


| Vérification du cluster MCC | Vérifie si le système est une configuration MetroCluster. L'opération détecte automatiquement si elle correspond à une configuration MetroCluster ou non et effectue les contrôles préalables et de vérification spécifiques. Seule la configuration FC MetroCluster à 4 nœuds est prise en charge. Dans le cas de la configuration MetroCluster à 2 nœuds et de la configuration IP MetroCluster à 4 nœuds, la vérification échoue. Si la configuration MetroCluster est à l'état de commutation, la vérification échoue. 


| Vérification de l'état du transfert d'agrégat | Vérifie si un transfert d'agrégat est déjà en cours. Si un autre transfert d'agrégat est en cours, le contrôle échoue. 


| Vérification du nom du modèle | Vérifie si les modèles de contrôleur sont pris en charge pour cette procédure. Si les modèles ne sont pas pris en charge, la tâche échoue. 


| Vérification du quorum du cluster | Vérifie que les nœuds remplacés se trouvent au quorum. Si les nœuds ne sont pas dans le quorum, la tâche échoue. 


| Vérification de la version de l'image | Vérifie que les nœuds remplacés exécutent la même version de ONTAP. Si les versions des images ONTAP sont différentes, la tâche échoue. La même version de ONTAP 9.x doit être installée sur les nouveaux nœuds. Si une autre version de ONTAP est installée sur les nouveaux nœuds, vous devez netboot les nouveaux contrôleurs après les avoir installés. Pour obtenir des instructions sur la mise à niveau de ONTAP, reportez-vous à la section link:other_references.html["Références"] Pour accéder à _Upgrade ONTAP_. 


| Vérification de l'état DE LA HAUTE DISPONIBILITÉ | Vérifie si les deux nœuds remplacés se trouvent dans une configuration de paires haute disponibilité. Si le basculement du stockage n'est pas activé pour les contrôleurs, la tâche échoue. 


| Vérification de l'état de l'agrégat | Si les nœuds remplacés incluent des agrégats dont ils ne sont pas le propriétaire du site, la tâche échoue. Les nœuds ne doivent pas posséder d'agrégats non locaux. 


| Vérification de l'état du disque | Si l'un des nœuds remplacés contient des disques manquants ou en panne, la tâche échoue. Si des disques sont manquants, reportez-vous à la section link:other_references.html["Références"] Pour lier la gestion des _disques et des agrégats à la CLI_, _gestion du stockage logique avec CLI_ et _High Availability management_ afin de configurer le stockage pour la paire HA. 


| Vérification de l'état de la LIF de données | Vérifie si l'un des nœuds remplacés dispose de LIF de données non locales. Les nœuds ne doivent pas contenir de LIFs de données pour lesquelles ils ne sont pas le propriétaire. Si l'un des nœuds contient des LIFs de données non locales, la tâche échoue. 


| État de la LIF de cluster | Vérifie si les LIFs de cluster sont active pour les deux nœuds. Si les LIFs de cluster sont arrêtées, la tâche échoue. 


| Contrôle d'état ASUP | Si les notifications ASUP ne sont pas configurées, la tâche échoue. Vous devez activer ASUP avant de commencer la procédure de remplacement du contrôleur. 


| Vérification de l'utilisation du processeur | Vérifie si le taux d'utilisation du CPU est supérieur à 50 % pour l'un des nœuds remplacés. Si l'utilisation du processeur est supérieure à 50 % pendant une période de temps considérable, la tâche échoue. 


| Contrôle de reconstruction d'agrégats | Vérifie si la reconstruction a lieu sur l'un des agrégats de données. Si la reconstruction d'agrégat est en cours, la tâche échoue. 


| Vérification du travail d'affinité du nœud | Vérifie si des travaux d'affinité de nœud sont en cours d'exécution. Si des tâches d'affinité de nœud sont en cours d'exécution, la vérification échoue. 
|===
. Une fois l'opération de remplacement du contrôleur démarrée et les contrôles préalables terminés, l'opération s'interrompt pour vous permettre de collecter les informations de sortie dont vous aurez peut-être besoin ultérieurement lors de la configuration du noeud 3.
+

NOTE: Si vous possédez un système doté de plus de deux ports de cluster par nœud, par exemple un système FAS8080 ou AFF8080, avant de démarrer la mise à niveau, vous devez migrer et ré-home les LIF de cluster sur deux ports de cluster par nœud. Si vous effectuez la mise à niveau du contrôleur avec plus de deux ports de cluster par nœud, des LIF de cluster risquent d'être manquantes sur le nouveau contrôleur après la mise à niveau.

. Exécuter le jeu de commandes ci-dessous comme indiqué par la procédure de remplacement du contrôleur sur la console du système.
+
Vous devez exécuter et enregistrer séparément les valeurs de sortie des commandes suivantes :

+
** `vserver services name-service dns show`
** `network interface show -curr-node _nodename_ -role _cluster,intercluster,node-mgmt,cluster-mgmt,data_`
** `network port show -node _node_name_ -type physical`
** `service-processor show -node * -instance`
** `network fcp adapter show -node _node_name_`
** `network port ifgrp show`
** `system node show -instance -node _node_name_`
** `run -node _node_name_ sysconfig`
** `storage aggregate show -node _node_name_`
** `volume show -node _node_name_`
** `storage array config show -switch _switch_name_`
** `system license show -owner _node_name_`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `reachability show -detail`


+

NOTE: Si NetApp Volume Encryption utilisant Onboard Key Manager (OKM) est en cours d'utilisation, conservez la phrase secrète du gestionnaire de clés pour terminer la resynchronisation du gestionnaire de clés plus tard dans la procédure.

. Si votre système utilise des lecteurs auto-cryptés, consultez l'article de la base de connaissances https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["Comment savoir si des lecteurs FIPS sont installés"^] Pour déterminer le type de disques à autocryptage utilisés sur la paire haute disponibilité que vous mettez à niveau. Le logiciel ONTAP prend en charge deux types de disques avec autocryptage :
+
--
** Disques SAS ou NVMe NetApp Storage Encryption (NSE) certifiés FIPS
** Disques NVMe non-FIPS à autochiffrement (SED)


[NOTE]
====
** Vous ne pouvez pas combiner des disques FIPS avec d'autres types de disques sur le même nœud ou la même paire HA.
** Vous pouvez utiliser les disques SED avec des disques sans cryptage sur le même nœud ou une paire haute disponibilité.


====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["En savoir plus sur les disques à autochiffrement pris en charge"^].

--




== Corriger la propriété de l'agrégat en cas d'échec d'une vérification préalable du transfert d'agrégats

En cas d'échec de la vérification de l'état de l'agrégat, vous devez renvoyer les agrégats qui appartiennent au nœud partenaire au nœud propriétaire du nœud de rattachement et relancer le processus de vérification préalable.

.Étapes
. Renvoyez les agrégats actuellement détenus par le nœud partenaire au nœud propriétaire de rattachement :
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Vérifiez que ni le nœud1 ni le nœud2 ne possède toujours des agrégats pour lesquels il s'agit du propriétaire actuel (mais pas le propriétaire du domicile) :
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
L'exemple suivant montre la sortie de la commande lorsqu'un nœud est à la fois le propriétaire actuel et le propriétaire du domicile des agrégats :

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== Une fois que vous avez terminé

Vous devez redémarrer la procédure de remplacement des contrôleurs :

`system controller replace start -nodes _node_names_`



== Licence

Lorsque vous configurez un cluster, l'assistant d'installation vous demande d'entrer la clé de licence de base du cluster. Cependant, certaines fonctionnalités nécessitent des licences supplémentaires, qui sont émises sous la forme de _packages_ qui incluent une ou plusieurs fonctionnalités. Chaque nœud du cluster doit disposer de sa propre clé pour que chaque fonctionnalité soit utilisée dans le cluster.

Si vous ne disposez pas de nouvelles clés de licence, les fonctionnalités actuellement sous licence dans le cluster sont disponibles pour le nouveau contrôleur. Toutefois, l'utilisation de fonctions sans licence sur le contrôleur peut vous mettre hors conformité avec votre contrat de licence. Vous devez donc installer la ou les nouvelles clés de licence pour le nouveau contrôleur une fois la mise à niveau terminée.

Reportez-vous à la section link:other_references.html["Références"] Lien vers le site de support _NetApp_ où vous pouvez obtenir de nouvelles clés de licence de deux caractères pour ONTAP. Les clés sont disponibles dans la section _mon support_ sous _licences logicielles_. Si le site ne dispose pas de clés de licence, vous pouvez contacter votre ingénieur commercial NetApp.

Pour plus d'informations sur les licences, reportez-vous à la section link:other_references.html["Références"] Pour établir un lien vers _System Administration Reference_.
