---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reassign-node2-disks-to-node4.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Vous devez réaffecter les disques appartenant au nœud 1 au nœud 3 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou une version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Réaffectez les disques du nœud 2 au nœud 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez réaffecter les disques appartenant au nœud 2 au nœud 4 avant de vérifier l'installation du nœud 4.

.Description de la tâche
Vous effectuez les étapes de cette section sur le node4.

.Étapes
. [[reassigner-node2-node4-app-stepe1]]allez au menu de démarrage et, à l'aide de 22/7, sélectionnez l'option cachée `boot_after_controller_replacement` . À l'invite, entrez node2 pour réaffecter les disques du nœud2 au nœud4, comme dans l'exemple suivant.
+
.Développez l'exemple de sortie de la console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to
restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure
you want to continue?: yes
.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:
<nodename of the node being replaced>
Changing sysid of node node2 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote
    key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a
boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+

NOTE: Dans l'exemple de sortie de la console ci-dessus, ONTAP vous invite à entrer le nom du nœud partenaire si le système utilise des disques du partitionnement de disque avancé.

. Si le système passe en boucle de redémarrage avec le message `no disks found`, il indique que le système a réinitialisé les ports FC ou UTA/UTA2 en mode cible et qu'il n'est donc pas en mesure de voir les disques. Pour résoudre ce problème, passez <<reassign-node2-node4-app-step3,Étape 3>> à  ou passez à <<reassign-node2-node4-app-step8,Étape 8>>la section link:verify_node4_installation.html["Vérifiez l'installation du node4"].
. [[reassigner-node2-node4-app-step3]]appuyez sur Ctrl-C pendant l'AUTOBOOT pour arrêter le nœud à l'invite Loader>.
. À l'invite du CHARGEUR, entrer en mode maintenance :
+
`boot_ontap maint`

. En mode maintenance, afficher tous les ports initiateurs précédemment définis qui sont maintenant en mode cible :
+
`ucadmin show`

+
Modifier les ports en mode initiateur :

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Vérifiez que les ports ont été modifiés en mode initiateur :
+
`ucadmin show`

. Quitter le mode maintenance :
+
`halt`

+
[NOTE]
====
Si vous effectuez une mise à niveau à partir d'un système qui prend en charge des disques externes vers un système qui prend également en charge <<reassign-node2-node4-app-step8,Étape 8>>des disques externes, passez à l' .

Si vous effectuez une mise à niveau à partir d'un système utilisant des disques externes vers un système prenant en charge les disques internes et externes, par exemple, un système AFF A800, passez à <<reassign-node2-node4-app-step9,Étape 9>>l' .

====
. [[reassigner-node2-node4-app-stepe8]]à l'invite Loader, démarrez :
+
`boot_ontap menu`

+
Maintenant, au démarrage, le nœud peut détecter tous les disques qui lui étaient précédemment affectés et peut démarrer comme prévu.

+
Lorsque les nœuds de cluster que vous remplacez utilisent le chiffrement de volume racine, ONTAP ne peut pas lire les informations de volume à partir des disques. Restaurer les clés du volume root.

+

NOTE: Cela s'applique uniquement lorsque le volume racine utilise le chiffrement de volume NetApp.

+
.. Revenir au menu de démarrage spécial :
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Sélectionnez *(10) définir les secrets de récupération du gestionnaire de clés intégré*
.. Entrez `y` à l'invite suivante :
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. À l'invite, entrez la phrase de passe du gestionnaire de clés.
.. Entrez les données de sauvegarde lorsque vous y êtes invité.
+

NOTE: Vous devez avoir obtenu la phrase de passe et les données de sauvegarde dans le link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"] section de cette procédure.

.. Une fois que le système a de nouveau démarré dans le menu de démarrage spécial, exécutez l'option *(1) démarrage normal*
+

NOTE: Il se peut que vous rencontriez une erreur à ce stade. Si une erreur se produit, répétez les sous-étapes de la section <<reassign-node2-node4-app-step8,Étape 8>> jusqu'à ce que le système démarre normalement.



. [[realse-node2-node4-app-step9]] si vous effectuez une mise à niveau d'un système avec des disques externes vers un système qui prend en charge les disques internes et externes (systèmes AFF A800, par exemple), définissez l'agrégat node2 comme agrégat racine pour garantir que le nœud 4 démarre depuis l'agrégat racine du node2. Pour définir l'agrégat racine, accédez au menu de boot et sélectionnez option `5` pour passer en mode de maintenance.
+

WARNING: *Vous devez exécuter les sous-étapes suivantes dans l'ordre exact indiqué ; le non-respect de cette consigne peut entraîner une panne ou même une perte de données.*

+
La procédure suivante définit le nœud 4 pour démarrer à partir de l'agrégat racine du nœud 2 :

+
.. Passer en mode maintenance :
+
`boot_ontap maint`

.. Vérifier les informations RAID, plex et checksum du noeud 2 :
+
`aggr status -r`

.. Vérifier le statut de l'agrégat du nœud 2 :
+
`aggr status`

.. Si nécessaire, mettre l'agrégat du nœud 2 en ligne :
+
`aggr_online root_aggr_from___node2__`

.. Empêcher le démarrage du nœud 4 à partir de son agrégat racine d'origine :
+
`aggr offline _root_aggr_on_node4_`

.. Définir l'agrégat racine du nœud 2 en tant que nouvel agrégat racine pour le nœud 4 :
+
`aggr options aggr_from___node2__ root`

.. Vérifier que l'agrégat racine du nœud 4 est hors ligne et que l'agrégat racine des disques transférées depuis le nœud 2 est en ligne et défini à la racine :
+
`aggr status`

+

NOTE: Si vous ne procédez pas à la sous-étape précédente, le nœud 4 risque de démarrer à partir de l'agrégat racine interne, ou le système peut supposer qu'une nouvelle configuration de cluster existe ou vous inviter à en identifier une.

+
Voici un exemple de sortie de la commande :



+
....
---------------------------------------------------------------------
Aggr State                       Status               Options
aggr 0_nst_fas8080_15 online     raid_dp, aggr        root, nosnap=on
                                 fast zeroed
                                 64-bit
aggr0 offline                    raid_dp, aggr        diskroot
                                 fast zeroed`
                                 64-bit
---------------------------------------------------------------------
....

