---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'Vous pouvez configurer les ports FC intégrés des nœuds node4, les ports UTA/UTA2 ou la carte UTA/UTA2 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Définissez la configuration FC ou UTA/UTA2 sur le nœud 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si le système Node4 est doté de ports FC intégrés, de ports UTA/UTA2 (ou d'une carte UTA/UTA2), vous devez configurer les paramètres avant de suivre la procédure.

.Description de la tâche
Vous devrez peut-être remplir la <<Configurez les ports FC sur le nœud 4>> section ou <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>> , ou les deux sections.

[NOTE]
====
Si le nœud 4 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2 et que vous mettez à niveau un système avec des disques de stockage, vous pouvez passer à link:reassign-node2-disks-to-node4.html["Réaffectez les disques du nœud 2 au nœud 4"].

Cependant, si vous disposez d'un système V-Series ou si vous disposez d'un logiciel de virtualisation FlexArray et que le nœud 4 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez revenir à _Install and boot Node4_ et reprendre la procédure à link:install_boot_node4.html#step22["Étape 22"]l' .

Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant. Si le noeud 4 se trouve dans un châssis distinct du noeud 2, vous pouvez placer le noeud 4 au même emplacement que le noeud 3. Si les nœuds 2 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.

====


== Configurez les ports FC sur le nœud 4

Si le nœud 4 possède des ports FC intégrés ou sur un adaptateur FC, vous devez définir des configurations de ports sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés. Si les ports ne sont pas configurés, le service peut subir une interruption.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 2 que vous avez enregistrées dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'un adaptateur UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>>.


IMPORTANT: Si votre système est doté de disques de stockage, vous devez saisir les commandes de cette section à l'invite du cluster. Si vous disposez d'un système V-Series ou d'un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous pouvez saisir les commandes décrites dans cette section en mode Maintenance.

.Étapes
. Effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si le système que vous mettez à niveau... | Puis… 


| Possède des disques de stockage | `system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `ucadmin show` 
|===
+
Le système affiche des informations sur la totalité des adaptateurs réseau convergés et FC sur le système.

. Comparez les paramètres FC sur le nœud4 avec ceux que vous avez capturés précédemment à partir du nœud1.
. Effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si le système que vous mettez à niveau... | Puis… 


| Possède des disques de stockage  a| 
Modifier les ports FC sur le nœud 4 si nécessaire :

** Pour programmer les ports cibles :
+
`ucadmin modify -m fc -t target _adapter_`

** Pour programmer les ports initiateurs :
+
`ucadmin modify -m fc -t initiator _adapter_`



`-t` Est le type FC4 : cible ou initiateur.



| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage  a| 
Modifier les ports FC sur le nœud 4 si nécessaire :

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` Est le type, la cible ou l'initiateur FC4.


NOTE: Les ports FC doivent être programmés comme initiateurs.

|===
. Quitter le mode Maintenance :
+
`halt`

. Démarrez le système à partir de l'invite du CHARGEUR :
+
`boot_ontap menu`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Sélectionnez option `5` dans le menu de démarrage pour le mode maintenance.


. [[step8]]effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si le système que vous mettez à niveau... | Puis… 


| Possède des disques de stockage  a| 
** Ignorez cette section et passez à link:reassign-node2-disks-to-node4.html["Réaffectez les disques du nœud 2 au nœud 4"] si le nœud 4 ne dispose pas de carte UTA/UTA2 ou de ports intégrés UTA/UTA2.




| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage  a| 
** Accédez à <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>> Si le nœud 4 est doté d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2.
** Ignorez _Vérifiez et configurez les ports UTA/UTA2 sur le node4_ si le nœud 4 ne dispose pas de carte UTA/UTA2 ou de ports intégrés UTA/UTA2, retournez à _Install et boot node4_, puis reprenez la procédure à link:install_boot_node4.html#auto_install4_step23["Étape 23"].


|===




== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4

Si le NODE4 dispose de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2A, vous devez vérifier la configuration des ports et les configurer, en fonction de votre mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Les ports UTA/UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2A. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément le trafic FCoE et les cartes réseau sur la même interface SFP+ 10 GbE et prend en charge la cible FC.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Les ports UTA/UTA2 peuvent être situés sur un adaptateur ou sur le contrôleur dans les configurations suivantes :

* Les cartes UTA/UTA2 commandées en même temps que le contrôleur sont configurées avant l'expédition pour obtenir la personnalité demandée.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés (avant l'expédition) pour utiliser le profil demandé.


Toutefois, vous devez vérifier la configuration des ports UTA/UTA2 sur le nœud 4 et la modifier si nécessaire.


WARNING: *Attention* : si votre système dispose de disques de stockage, entrez les commandes de cette section à l'invite du cluster, sauf si vous êtes invité à passer en mode Maintenance. Si vous utilisez un système FC MetroCluster, un système V-Series ou un système avec le logiciel de virtualisation FlexArray connecté aux baies de stockage, vous devez être en mode de maintenance pour configurer les ports UTA/UTA2.

.Étapes
. Vérifiez la configuration actuelle des ports à l'aide de l'une des commandes suivantes sur le nœud4 :
+
[cols="30,70"]
|===
| Si le système... | Puis… 


| Possède des disques de stockage | `system node hardware unified-connect show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `ucadmin show` 
|===
+
Un résultat similaire à l'exemple suivant s'affiche :

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. Examiner la sortie du `ucadmin show` Déterminez si les ports UTA/UTA2 ont le profil souhaité.
. Effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si les ports CNA... | Puis… 


| N'avez pas la personnalité que vous voulez | Accédez à <<auto_check_4_step5,Étape 5>>. 


| Avoir la personnalité que vous voulez | Passez aux étapes 5 à 12 et passez à <<auto_check_4_step13,Étape 13>>. 
|===
. [[auto_check_4_step5]]effectuez l'une des opérations suivantes :
+
[cols="30,70"]
|===
| Si vous configurez... | Puis… 


| Ports sur carte UTA/UTA2 | Accédez à <<auto_check_4_step7,Étape 7>> 


| Ports UTA/UTA2 intégrés | Ignorez l'étape 7 et passez à <<auto_check_4_step8,Étape 8>>. 
|===
. Si l'adaptateur est en mode initiateur et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter _adapter_name_`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode maintenance.

. [[auto_check_4_step7]]si la configuration actuelle ne correspond pas à l'utilisation souhaitée, modifiez la configuration comme nécessaire :
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Est le mode Personality, FC ou UTA 10 GbE.
** `-t` Est de type FC4, `target` ou `initiator`.
+

NOTE: Vous devez utiliser un initiateur FC pour les lecteurs de bande, les systèmes de virtualisation FlexArray et les configurations MetroCluster. Vous devez utiliser la cible FC pour les clients SAN.



. [[auto_check_4_step8]]Vérifiez les paramètres à l'aide de la commande suivante et en examinant la sortie :
+
`ucadmin show`

. Vérifiez les paramètres :
+
[cols="40,60"]
|===
| Si le système... | Puis… 


| Possède des disques de stockage | `ucadmin show` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `ucadmin show` 
|===
+
Le résultat des exemples suivants montre que le type FC4 d'adaptateur « 1b » passe à `initiator` et que le mode des adaptateurs « 2a » et « 2b » passe à `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Placez n'importe quel port cible en ligne en entrant l'une des commandes suivantes, une fois pour chaque port :
+
[cols="30,70"]
|===
| Si le système... | Puis… 


| Possède des disques de stockage | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | `fcp config _adapter_name_ up` 
|===
. Reliez le port.


. [[step12]]effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si le système... | Puis… 


| Possède des disques de stockage | Allez à link:reassign-node2-disks-to-node4.html["Réaffectez les disques du nœud 2 au nœud 4"]. 


| Est un système V-Series ou un logiciel de virtualisation FlexArray qui est connecté aux baies de stockage | Retournez à _Install et boot node4_, puis reprenez à link:install_boot_node4.html#auto_install4_step23["Étape 23"]. 
|===
. [[auto_check_4_step13]]Quitter le mode Maintenance :
+
`halt`

. [[step14]]démarrez le nœud dans le menu de démarrage :
+
`boot_ontap menu`.

+
Si vous effectuez une mise à niveau vers un système AFF A800, rendez-vous sur link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["Réaffectez les disques du nœud 2 au nœud 4, étape 9"].


