---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Vous pouvez configurer les ports FC intégrés des nœuds 3, les ports UTA/UTA2 ou la carte UTA/UTA2 lors de la mise à niveau des contrôleurs exécutant ONTAP 9.8 ou version ultérieure à l"aide de `system controller replace` commandes.' 
---
= Définissez la configuration FC ou UTA/UTA2 sur le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si le système Node4 est doté de ports FC intégrés, de ports UTA/UTA2 (ou d'une carte UTA/UTA2), vous devez configurer les paramètres avant de suivre la procédure.

.Description de la tâche
Vous devrez peut-être compléter cette section <<Configurez les ports FC sur le nœud 3>>, la section <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>, ou les deux sections.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA (Converged Network adapter). Cependant, l'interface de ligne de commandes utilise le terme CNA.

Si le nœud 3 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2 (par exemple, les systèmes AFF et FAS introduits à partir d' ONTAP 9.15.1) et que vous mettez à niveau un système avec des disques de stockage, vous pouvez passer àlink:reassign-node1-disks-to-node3.html["Réaffectez les disques du nœud 1 au nœud 3"] .



== Configurez les ports FC sur le nœud 3

Si le nœud 3 dispose de ports FC, intégrés ou sur un adaptateur FC complémentaire, vous devez définir les configurations de port sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés lors de l'expédition des systèmes.  Si vous ne configurez pas les ports, vous risquez de subir une interruption de service.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 1 que vous avez enregistrées dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>>.


IMPORTANT: Saisissez les commandes de cette section à l’invite du shell en mode Maintenance.

.Étapes
. Comparez les paramètres FC sur le nœud 3 avec les paramètres que vous avez capturés précédemment à partir du nœud 1.
. Effectuez l’une des actions suivantes pour modifier les ports FC sur le nœud 3, selon vos besoins :
+
En mode Maintenance (option 5 du menu de démarrage) :

+
** Pour programmer comme ports cibles :
+
`ucadmin modify -m fc -t target <adapter>`

+
Par exemple: `ucadmin modify -m fc -t target 2a`

** Pour programmer les ports initiateurs :
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Par exemple: `ucadmin modify -m fc -t initator 2b`



. Vérifiez les nouveaux paramètres en utilisant la commande suivante et en examinant la sortie :
+
`ucadmin show`

. Arrêter le nœud :
+
`halt`

. Démarrez le système à partir de l'invite du CHARGEUR :
+
`boot_ontap menu`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Sélectionnez option `5` dans le menu de démarrage pour le mode maintenance.


. [[auto_check3_step8]]effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si le nœud 3... | Alors... 


| Dispose d'une carte UTA/UTA2 ou de ports UTA/UTA2 intégrés | Aller à<<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3>> 


| Ne possède pas de carte UTA/UTA2 ni de ports UTA/UTA2 intégrés | Ignorez _Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3_ et accédez àlink:reassign-node1-disks-to-node3.html["Réaffectez les disques du nœud 1 au nœud 3"] . 
|===




== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 3

Si le nœud 3 est équipé de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez vérifier la configuration des ports et éventuellement les reconfigurer, en fonction du mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Si vous souhaitez utiliser un port UTA/UTA2 (Unified Target adapter) pour FC, vous devez d'abord vérifier la configuration du port.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Vous pouvez utiliser le `ucadmin show` commande pour afficher ou vérifier la configuration actuelle du port, comme indiqué dans l'exemple de sortie suivant :

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Les ports UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément le trafic NIC et FCoE sur la même interface SFP+ 10 GbE et prend en charge les cibles FC.

Vous pourriez trouver des ports UTA/UTA2 sur un adaptateur supplémentaire ou sur la carte mère du contrôleur, et avoir les configurations suivantes, mais vous devriez vérifier la configuration des ports UTA/UTA2 sur le nœud 3 et la modifier, si nécessaire :

* Les cartes UTA/UTA2 commandées lors de la commande du contrôleur sont configurées avant l'expédition pour avoir la personnalité que vous demandez.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés avant l'expédition pour personnaliser votre demande.
+

WARNING: Vous devez être en mode Maintenance pour configurer les ports UTA/UTA2.  Saisissez les commandes de cette section à l’invite du shell en mode Maintenance.



.Étapes
. Si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. Vérifiez les paramètres du port UTA/UTA2 :
+
`ucadmin show`

+
Examinez la sortie et déterminez si les ports UTA/UTA2 ont la personnalité souhaitée.

+
La sortie dans l'exemple suivant montre que le type d'adaptateur « 1b » passe à l'initiateur et que le mode des adaptateurs « 2a » et « 2b » passe à « cna ».  Le mode CNA vous permet d'utiliser la carte comme adaptateur réseau.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Effectuer l'une des actions suivantes :
+
[cols="30,70"]
|===
| Si les ports UTA/UTA2... | Puis… 


| N'avez pas la personnalité que vous voulez | Aller à<<auto_check3_step4,Étape 4>> . 


| Avoir la personnalité que vous voulez | Sautez les étapes 4 à 8 et passez à<<auto_check3_step9,Étape 9>> . 
|===
. [[auto_check3_step4]]Effectuez l’une des actions suivantes :
+
[cols="30,70"]
|===
| Si vous configurez... | Puis… 


| Ports sur carte UTA/UTA2 | Aller à<<auto_check3_step5,Étape 5>> 


| Ports UTA/UTA2 intégrés | Sautez l'étape 5 et accédez à<<auto_check3_step6,Étape 6>> . 
|===
. [[auto_check3_step5]]Si l'adaptateur est en mode initiateur et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter <adapter_name>`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode maintenance.

. [[auto_check3_step6]]Si la configuration actuelle ne correspond pas à l'utilisation souhaitée, modifiez la configuration selon vos besoins :
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` est le mode personnalité, `fc` ou `cna`.
** `-t` Est de type FC4, `target` ou `initiator`.
+

NOTE: Vous devez utiliser l'initiateur FC pour les lecteurs de bande et les configurations MetroCluster .  Vous devez utiliser la cible FC pour les clients SAN.



. Placez tous les ports cibles en ligne en entrant la commande suivante une fois pour chaque port :
+
`storage enable adapter <adapter_name>`

. Reliez le port.


[[auto_check3_step9]]
. Quitter le mode maintenance :
+
`halt`

. [[step14]]démarrez le nœud dans le menu de démarrage :
+
`boot_ontap menu`



.Et la suite ?
* Si vous effectuez une mise à niveau vers un système AFF A800 , accédez àlink:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["Réaffectez les disques du nœud 1 au nœud 3, étape 9"] .
* Pour toutes les autres mises à niveau du système, accédez àlink:reassign-node1-disks-to-node3.html["Réaffectez les disques du nœud 1 au nœud 3, étape 1"] .

