---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Étape 5 : séquence de processus pour la mise à niveau d"ARL à l"aide de `system controller replace` Commandes sur les contrôleurs exécutant ONTAP 9.8 ou version ultérieure.' 
---
= Présentation de la phase 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Au cours de l'étape 5, vous installez et amorcez node4, vérifiez que le cluster et les ports de gestion des nœuds du node2 sont mis en ligne sur le node4, réaffectez les disques du node2 au node4 et vérifiez l'installation du node4. Si vous utilisez NVE, restaurez la configuration du gestionnaire de clés. Si nécessaire, définissez la configuration FC ou UTA/UTA2 sur le nœud 4. Vous pouvez également transférer les LIF de données NAS du nœud 2 et les agrégats non racine du nœud 3 vers le nœud 4, puis vérifier que les LIF SAN existent sur le nœud 4.

.Étapes
. link:install_boot_node4.html["Installez et démarrez Node4"]
. link:set_fc_or_uta_uta2_config_node4.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 4"]
. link:reassign-node2-disks-to-node4.html["Réaffectez les disques du nœud 2 au nœud 4"]
. link:verify_node4_installation.html["Vérifiez l'installation du node4"]
. link:restore_key-manager_config_node4.html["Restaurez la configuration du gestionnaire de clés sur le nœud 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 2 du nœud 3 vers le nœud 4"]

