---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_2_index.html 
keywords: relocating, retiring, node1, lif, stage 2 
summary: 'Processus de la phase 2 pour une mise à niveau d"ARL à l"aide de `system controller replace` Commandes sur les contrôleurs exécutant ONTAP 9.8 ou version ultérieure.' 
---
= Présentation de la phase 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la phase 2, vous transférez les agrégats non racines et les LIF de données du nœud 1 vers le nœud 2. Ce processus est largement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. Si nécessaire, vous transférez des agrégats défaillants ou vetotés. Vous enregistrez également les informations nécessaires sur le nœud 1, vous retirez le nœud 1 et vous préparez à netboot node3 et node4 plus tard dans la procédure.

.Étapes
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Transférez les agrégats non racine et les LIF de données NAS qui appartiennent au nœud1 vers le nœud2"]
. link:relocate_failed_or_vetoed_aggr.html["Le transfert d'agrégats a échoué ou a été veto"]
. link:retire_node1.html["Retirer le nœud 1"]
. link:prepare_for_netboot.html["Préparation à la mise sur le réseau"]

