---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: 'Étape 6 : séquence de processus pour la mise à niveau d"ARL à l"aide de `system controller replace` Commandes sur les contrôleurs exécutant ONTAP 9.8 ou version ultérieure.' 
---
= Étape 6. Terminez la mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 6, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NetApp Volume Encryption. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

.Étapes
. link:manage-authentication-using-kmip-servers.html["Gérez l'authentification à l'aide de serveurs KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Vérifiez que les nouveaux contrôleurs sont correctement configurés"]
. link:set_up_storage_encryption_new_module.html["Configurez Storage Encryption sur le nouveau module de contrôleur"]
. link:set_up_netapp_volume_encryption_new_module.html["Configurez NetApp Volume Encryption ou Aggregate Encryption sur le nouveau module de contrôleur"]
. link:decommission_old_system.html["Désaffectation de l'ancien système"]
. link:resume_snapmirror_operations.html["Reprendre les opérations SnapMirror"]


.Pour la configuration MetroCluster FC
Pour la configuration MetroCluster FC, il est nécessaire de remplacer les nœuds de site de reprise après incident/basculement le plus rapidement possible. Les différences entre les modèles de contrôleur et MetroCluster ne sont pas prises en charge, car une non-concordance de modèle de contrôleur peut entraîner la mise en miroir de la reprise après incident. Utiliser la commande -`skip-metrocluster-check true` Option permettant de contourner les vérifications MetroCluster lorsque vous remplacez des nœuds sur un second site.
