---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/boot_node1_with_a900_controller_and_nvs.html 
keywords: boot, NVRAM, controller, module, node1, replacement 
summary: 'Démarrez le nœud 1 avec les modules de contrôleur de remplacement lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Démarrez le nœud 1 avec les modules système de remplacement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le nœud 1 avec les modules de remplacement est maintenant prêt à démarrer. Cette section fournit les étapes requises pour démarrer node1 avec les modules de remplacement pour les configurations de mise à niveau suivantes :

[cols="35,65"]
|===
| Ancien contrôleur du nœud 1 | Remplacement des modules système du nœud 1 


| AVEC AFF A220
Solution AFF A200
Baie AFF C190 | Module contrôleur AFF A150 ^1^ 


| FAS2620
FAS2720 | Module contrôleur FAS2820 ^1^ 


| AFF A700 | Contrôleur AFF A900 et modules NVRAM ^2^ 


| FAS9000 | Contrôleur FAS9500 et modules NVRAM ^2^ 
|===
^1^ lors du remplacement des modules de contrôleur, vous déplacez toutes les connexions de l'ancien vers le module de contrôleur de remplacement.
^2^ lors du remplacement du contrôleur et des modules NVRAM, vous déplacez uniquement les connexions de console et de gestion.

.Étapes
. Si des disques NetApp Storage Encryption (NSE) sont installés, effectuez les opérations suivantes.
+

NOTE: Si ce n'est déjà fait, consultez l'article de la base de connaissances https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Comment savoir si un disque est certifié FIPS"^] déterminer le type de disques à autocryptage utilisés.

+
.. Réglez `bootarg.storageencryption.support` à `true` ou `false`:
+
[cols="35,65"]
|===
| Si les lecteurs suivants sont utilisés… | Puis… 


| Disques NSE conformes aux exigences de chiffrement automatique FIPS 140-2 de niveau 2 | `setenv bootarg.storageencryption.support *true*` 


| NetApp non-SED FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
Vous ne pouvez pas combiner des disques FIPS avec d'autres types de disques sur le même nœud ou la même paire HA. Vous pouvez utiliser les disques SED avec des disques sans cryptage sur le même nœud ou une paire haute disponibilité.

====
.. Accédez au menu de démarrage spécial et sélectionnez option `(10) Set Onboard Key Manager recovery secrets`.
+
Saisissez la phrase de passe et les informations de sauvegarde que vous avez enregistrées lors de la procédure précédente. Voir link:manage_storage_encryption_using_okm.html["Gérez le chiffrement du stockage à l'aide du gestionnaire de clés intégré"].



. Démarrez le nœud dans le menu de démarrage :
+
`boot_ontap menu`

. Réaffectez les anciens disques du nœud 1 au nœud de remplacement 1 en entrant « 22/7 » et en sélectionnant l'option cachée `boot_after_controller_replacement` lorsque le nœud s'arrête au menu de démarrage.
+
Après un bref délai, vous êtes invité à saisir le nom du nœud en cours de remplacement. S'il existe des disques partagés (également appelés partitionnement de disque avancé ou des disques partitionnés), vous êtes invité à saisir le nom de nœud du partenaire haute disponibilité.

+
Ces invites peuvent être enfouies dans les messages de la console. Si vous ne saisissez pas de nom de nœud ou si vous saisissez un nom incorrect, vous êtes invité à saisir de nouveau le nom.

+
[NOTE]
====
Si `[localhost:disk.encryptNoSupport:ALERT]: Detected FIPS-certified encrypting drive` et, ou, `[localhost:diskown.errorDuringIO:error]: error 3 (disk failed) on disk` des erreurs se produisent, effectuez les opérations suivantes :

.. Arrêtez le nœud à l'invite DU CHARGEUR.
.. Vérifiez et réinitialisez les bootargs de cryptage de stockage mentionnés dans <<A900_boot_node1,Étape 1>>.
.. À l'invite du chargeur, démarrez :
+
`boot_ontap`



====
+
Vous pouvez utiliser l'exemple suivant comme référence :

+
.Développez l'exemple de sortie de la console
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7

(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.



The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement

This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes

.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>

System rebooting...

.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+
[NOTE]
====
Les ID système affichés dans l'exemple précédent sont des exemples d'ID. Les ID système réels des nœuds que vous mettez à niveau seront différents.

Entre la saisie des noms de nœud à l'invite et à l'invite de connexion, le nœud redémarre plusieurs fois pour restaurer les variables d'environnement, mettre à jour le firmware sur les cartes du système et pour d'autres mises à jour de ONTAP.

====

