---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: Connectez le cluster, la haute disponibilité, le stockage et les connexions de données précédemment connectés au nœud AFF A800 1 au nœud AFF A90 ou AFF A70 nouvellement installé 
---
= Câblage du nœud 1 pour la haute disponibilité et le stockage en cluster partagé
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous effectuez l'une des mises à niveau suivantes, vous devez connecter le cluster, les connexions haute disponibilité, de stockage, de données et de gestion précédemment connectées au nœud 1 du système existant au nœud 1 nouvellement installé sur le système de remplacement.

[cols="35,65"]
|===
| Système existant | Système de remplacement 


| AFF A250 | AFF A30, AFF A50 


| AFF C250 | AFF C30, AFF C60 


| AFF A800 | AFF A70, AFF A90 


| AFF C800 | C80 
|===


== Connectez les ports e0M et BMC

Si le système existant dispose d'un port de gestion (e0M) et d'un port BMC, les ports e0M et BMC sont combinés et accessibles via le port « clé » du système de remplacement. Vous devez vous assurer que les ports e0M et BMC sont connectés au même commutateur et au même sous-réseau sur le système existant avant de vous connecter au système de remplacement.

[cols="35,65"]
|===
| Si... | Alors... 


| Les adresses IP e0M et BMC se trouvent sur le même sous-réseau IP | Connectez le port e0M ou BMC du système existant au port de « clé » du système de remplacement. 


| Les adresses IP e0M et BMC se trouvent sur des sous-réseaux différents  a| 
. Fusionnez les adresses IP e0M et BMC dans un sous-réseau IP.
. Connectez le port e0M ou BMC du système existant au port de « clé » du système de remplacement.


|===


== Connexion à un cluster à 2 nœuds sans commutateur

Les tableaux suivants présentent l'utilisation des ports de commutateur pour les configurations en cluster sans commutateur à 2 nœuds.

|===
| Port | AFF A800, AFF C800 | AFF A90 | AFF A70, AFF C80 


| Cluster | e0a | e1a | e1a 


| Cluster | e1a | E7a (utilisez e1b s'il n'y a pas d'e7a) | e1b 


| HAUTE DISPONIBILITÉ | e0b | Ne pas connecter | Ne pas connecter 


| HAUTE DISPONIBILITÉ | e1b | Ne pas connecter | Ne pas connecter 


| Ports de stockage SAS (si présents et utilisés) | Tout port disponible | Tout port disponible | Tout port disponible 


| Ports de stockage Ethernet pour tiroirs NS224 | Tout port disponible | Reportez-vous à la section mappage de la connectivité du stockage Ethernet | Reportez-vous à la section mappage de la connectivité du stockage Ethernet 
|===
|===
| Port | AFF A250, AFF C250 | AFF A30, AFF C30, AFF C60 | AFF A50 


| Cluster et haute disponibilité | e0c | e4a | e4a 


| Cluster et haute disponibilité | e0d | e2a (utiliser e4b s'il n'y a pas d'e2a) | e2a (utiliser e4b s'il n'y a pas d'e2a) 


| Ports de stockage Ethernet | Tout port disponible | e3a, e3b | e3a, e3b 


| Ports de stockage SAS | Tout port disponible | 3a, 3b | 3a, 3b 
|===


== Se connecter à un cluster relié par un commutateur

Dans le cas d'un cluster relié par commutateur, vérifiez que vous répondez aux exigences suivantes pour les nœuds AFF A30, AFF A50, AFF A70, AFF A90, AFF C30, AFF C60 ou AFF C80 (de remplacement) :

* Les ports de cluster identiques sur le nœud de remplacement sont sur le même commutateur. Par exemple, une fois la mise à niveau terminée, e1a sur le nœud 1 et e1a sur le nœud 2 doivent être connectés à un commutateur de cluster. De même, le second port de cluster des deux nœuds doit être connecté au second commutateur de cluster. La connexion croisée de ports cluster-haute disponibilité partagés, où e1a du nœud 1 est connecté au commutateur a et e1a du nœud 2 est connecté au commutateur B, entraîne des échecs de communication haute disponibilité.
* Le nœud de remplacement utilise des ports Ethernet haute disponibilité et partagés entre les clusters. Vérifiez que les switchs de cluster sont installés avec un fichier de configuration de référence (RCF) qui prend en charge les ports cluster-HA partagés.

