---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Décidez si vous souhaitez utiliser la procédure ARL qui met à niveau les modèles de contrôleurs du même châssis. 
---
= Décider d'utiliser ou non cette procédure de relocalisation globale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs méthodes de relocalisation agrégée (ARL) pour mettre à niveau le matériel du contrôleur. Ce contenu décrit comment mettre à niveau les contrôleurs de stockage d'une paire HA en convertissant le système existant en système de remplacement, tout en conservant le châssis et les disques existants. Cette procédure complexe est réservée aux administrateurs ONTAP expérimentés.

Pour vous aider à décider si cette procédure ARL est adaptée à la mise à niveau du matériel de votre contrôleur, vous devez examiner toutes les circonstances suivantes pour les mises à niveau prises en charge et non prises en charge.



== Prise en charge pour cette mise à niveau ARL

Vous pouvez utiliser cette procédure ARL dans les circonstances suivantes :

* La mise à niveau de votre contrôleur est répertoriée dans le <<supported-systems,matrice des systèmes pris en charge>> .
* Vous avez vérifié auprès de votre ingénieur commercial NetApp que vous avez reçu le matériel nécessaire à la mise à niveau du contrôleur :
+
** Deux contrôleurs AFF A90, AFF A70 ou AFF C80 et tous les modules d'E/S. Longueurs de câbles de 100 GbE requises.
** Deux contrôleurs et modules d'E/S AFF A50, AFF A30, AFF C30 ou AFF C60 et les câbles requis
** Contrôleur ASA A150, AFF A150 ou FAS2820
** Contrôleur ASA A900, AFF A900 ou FAS9500 et modules et pièces NVRAM


* Vous exécutez la version minimale de ONTAP pour votre mise à niveau. Pour plus d'informations, reportez-vous au <<supported-systems,combinaisons de mise à niveau système prises en charge>>.
* Vous êtes expérimenté dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilège de diagnostic.
* Vos systèmes exécutent ONTAP 9.15.1 ou une version ultérieure et ils utilisent des commutateurs Ethernet pour se connecter au stockage connecté Ethernet.



NOTE: Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).



== Non pris en charge pour cette mise à niveau ARL

Vous ne pouvez pas utiliser cette procédure ARL dans les circonstances suivantes :

* Vous souhaitez ajouter les nouveaux contrôleurs au cluster en tant que nouvelle paire haute disponibilité et migrer les données à l'aide des déplacements de volumes.
* Vous utilisez le logiciel de virtualisation FlexArray sur le système existant en cours de mise à niveau.
* Vous mettez à niveau une configuration IP MetroCluster.
+
Pour mettre à niveau une configuration IP MetroCluster, reportez-vous  à la section link:other_references.html["Références"] pour accéder au contenu _MetroCluster Upgrade and expansion_.





== Combinaisons de mise à niveau du système prises en charge

Le tableau suivant présente la matrice des systèmes pris en charge pour effectuer une mise à niveau du contrôleur en convertissant le système existant en système de remplacement, en conservant le châssis et les disques du système existant.


CAUTION: Cette procédure s'applique strictement aux configurations de mise à niveau suivantes. N'utilisez pas cette procédure pour effectuer une mise à niveau entre d'autres combinaisons de systèmes. Pour tous les autres modèles de contrôleurs, reportez-vous à  la section link:other_references.html["Références"]lien vers _utilisation des commandes de remplacement du contrôleur système pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.8 ou version ultérieure_ et _utilisation du déplacement d'agrégat pour mettre à niveau manuellement le matériel du contrôleur exécutant ONTAP 9.8 ou version ultérieure_.

[cols="20,20,40"]
|===
| Système existant | Système de remplacement | Versions de ONTAP prises en charge 


| AFF C250 ^1^ | AFF C30, AFF C60 | 9.16.1 


| AFF A250 ^1^ | AFF A30, AFF A50 | 9.16.1 


| AFF C800 ^1^ | AFF C80 | 9.16.1 


| AFF A800 ^1^ | AFF A90 ou AFF A70 | 9.15.1 et versions ultérieures 


| AFF A220 configuré en tant que baie 100 % SAN (ASA) | ASA A150 | 9.13.1P1 et versions ultérieures 


| AVEC AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 et versions ultérieures 


| Solution AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 et ultérieur ^2^



| Baie AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 et versions ultérieures 


| FAS2620 | FAS2820  a| 
9.11.1P7 ou versions ultérieures (FAS2620) ^2^

9.13.1 et versions ultérieures (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 et versions ultérieures 


| AFF A700 configuré en tant que ASA | ASA A900 | 9.13.1P1 et versions ultérieures 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 et versions ultérieures 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 et versions ultérieures 
|===
^1^ lorsque vous effectuez une mise à niveau vers un système introduit dans ONTAP 9.15.1 ou version ultérieure, ONTAP convertit l'efficacité du stockage de tous les volumes à provisionnement fin existants, y compris ceux qui n'utilisent pas l'efficacité du stockage, et applique les nouvelles fonctionnalités d'efficacité du stockage qui utilisent la fonctionnalité de déchargement matériel. Il s'agit d'un processus automatique en arrière-plan, sans impact visible sur les performances du système. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["En savoir plus >>"^]

^2^ Les systèmes AFF A200 et FAS2620 ne prennent pas en charge les versions ONTAP ultérieures à 9.11.1.

[NOTE]
====
NetApp recommande vivement, dans la mesure du possible, que vous ayez la même version de ONTAP sur les anciens systèmes et sur les systèmes de remplacement.

Les versions ONTAP minimales figurant dans le tableau précédent sont obligatoires. Ces versions de ONTAP sont dotées de la version de firmware du processeur de service ou du contrôleur BMC (Baseboard Management Controller) requise pour prendre en charge l'utilisation de différents types de contrôleurs au sein d'un châssis pendant une mise à niveau.

====


== Choisissez une autre procédure de mise à niveau matérielle

* link:../upgrade-arl/index.html["Passez en revue les méthodes ARL alternatives disponibles pour la mise à niveau du matériel du contrôleur"].
* Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.


.Informations associées
Se référer à link:other_references.html["Références"] pour créer un lien vers la _Documentation ONTAP 9_.
