---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Décidez si vous souhaitez utiliser la procédure ARL qui met à niveau les modèles de contrôleurs du même châssis. 
---
= Décider d'utiliser la procédure de transfert d'agrégats
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce contenu explique comment mettre à niveau les contrôleurs de stockage d'une paire haute disponibilité tout en conservant toutes les données et les disques existants. Il s'agit d'une procédure complexe qui ne doit être utilisée que par des administrateurs expérimentés.



== Pris en charge pour les mises à niveau ARL

Vous pouvez utiliser cette procédure dans les circonstances suivantes :

* La mise à niveau du contrôleur est répertoriée dans le link:index.html#supported-systems,["matrice des systèmes pris en charge"].
* Vous avez vérifié auprès de votre ingénieur commercial NetApp que vous avez reçu le matériel nécessaire à la mise à niveau du contrôleur :
+
** Deux contrôleurs AFF A90, AFF A70 ou AFF C80 et tous les modules d'E/S. Longueurs de câbles de 100 GbE requises.
** Deux contrôleurs et modules d'E/S AFF A50, AFF A30, AFF C30 ou AFF C60 et les câbles requis
** Contrôleur ASA A150, AFF A150 ou FAS2820
** Contrôleur ASA A900, AFF A900 ou FAS9500 et modules et pièces NVRAM


* Vous exécutez la version minimale de ONTAP pour votre mise à niveau. Pour plus d'informations, voir link:index.html["Présentation"].
* Vous êtes expérimenté dans l'administration de ONTAP et vous êtes à l'aise avec les risques de travailler en mode de privilège de diagnostic.
* Vos systèmes exécutent ONTAP 9.15.1 ou une version ultérieure et ils utilisent des commutateurs Ethernet pour se connecter au stockage connecté Ethernet.



NOTE: Cette procédure vous permet d'utiliser NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE) et NetApp Aggregate Encryption (NAE).



== Non pris en charge pour les mises à niveau ARL

Vous ne pouvez pas utiliser cette procédure dans les circonstances suivantes :

* Vous souhaitez ajouter les nouveaux contrôleurs au cluster en tant que nouvelle paire haute disponibilité et migrer les données à l'aide des déplacements de volumes.
* Vous utilisez le logiciel de virtualisation FlexArray sur le système existant en cours de mise à niveau.
* Vous mettez à niveau une configuration IP MetroCluster.
+
Pour mettre à niveau une configuration IP MetroCluster, reportez-vous  à la section link:other_references.html["Références"] pour accéder au contenu _MetroCluster Upgrade and expansion_.



Si vous préférez une autre méthode de mise à niveau du matériel du contrôleur et que vous souhaitez déplacer des volumes, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _Upgrade en déplaçant des volumes ou du stockage_.

Reportez-vous à la section link:other_references.html["Références"] Lien vers le Centre de documentation _ONTAP 9_ où vous pouvez accéder à la documentation produit ONTAP 9.
