---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 'Configurez et gérez le chiffrement du stockage, gérez les clés d"authentification et quiesce les relations SnapMirror lors d"une mise à niveau d"un système AFF A700 vers un système AFF A900.' 
---
= Obtenir l'adresse IP d'un serveur de gestion externe des clés pour Storage Encryption
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois la mise à niveau effectuée, vous devez immédiatement configurer Storage Encryption et établir une clé d'authentification au niveau du cluster pour remplacer les clés d'authentification précédentes au niveau du nœud.

.Étapes
. Installez les certificats SSL (Secure sockets layer) client et serveur nécessaires pour communiquer avec les serveurs de gestion des clés :
+
`security certificate install`

. Configurez Storage Encryption sur tous les nœuds à l'aide de la commande suivante sur chaque nœud :
+
`security key-manager external enable`

. Ajouter l'adresse IP de chaque serveur de gestion des clés :
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vérifiez que les mêmes serveurs de gestion des clés sont configurés et disponibles sur tous les nœuds du cluster :
+
`security key-manager external show-status`

. Créer une nouvelle clé d'authentification au niveau du cluster :
+
`security key-manager key create`

. Notez le nouvel ID de clé d'authentification.
. ReKey tous les disques à autochiffrement grâce à la nouvelle clé d'authentification :
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`





== Gérez l'authentification à l'aide de serveurs KMIP

Depuis ONTAP 9.10.1, vous pouvez utiliser des serveurs KMIP (Key Management Interoperability Protocol) pour gérer les clés d'authentification.

.Étapes
. Ajout d'un nouveau contrôleur :
+
`security key-manager external enable`

. Ajouter le gestionnaire de clés :
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Vérifier que les serveurs de gestion des clés sont configurés et disponibles pour tous les nœuds du cluster :
+
`security key-manager external show-status`

. Restaurez les clés d'authentification de tous les serveurs de gestion de clés liés vers le nouveau nœud :
+
`security key-manager external restore -node _new_controller_name_`

. ReKey tous les disques avec autocryptage à l'aide de la nouvelle clé d'authentification :
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK]`

. Si vous utilisez la norme FIPS (Federal information Processing Standard), ressaisissez tous les disques auto-cryptés à l'aide de la nouvelle clé d'authentification :
+
`storage encryption disk modify -disk * [-fips-key-id nonMSID AK]`


