---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 'Déterminez si vous pouvez utiliser l"ARL, en conservant l"ancien châssis et les anciens disques du système pour la configuration de la mise à niveau.' 
---
= Instructions de mise à niveau des contrôleurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour savoir si vous pouvez utiliser le transfert d'agrégats (ARL), le conservation des anciens châssis et disques du système dépend de la configuration de la mise à niveau du système et de la version de ONTAP.



== Mises à niveau prises en charge pour l'ARL

Des mises à niveau du contrôleur sont prises en charge pour certaines configurations système. Pour afficher la liste des systèmes pris en charge et des versions minimales de ONTAP, reportez-vous à la section link:index.html["Présentation"].

Si vous avez reçu un nouveau système AFF A150, FAS2820, AFF A900 ou FAS9500 en tant que système complet, incluant un nouveau châssis, reportez-vous à la link:other_references.html["Références"] Pour établir un lien vers _utilisez les commandes "System Controller replace" pour mettre à niveau le matériel du contrôleur exécutant ONTAP 9.8 ou version ultérieure_ content.

La mise à niveau du contrôleur avec l'ARL est prise en charge sur les systèmes configurés avec les volumes SnapLock Enterprise et SnapLock Compliance.



== Clusters à 2 nœuds sans commutateur

Si vous mettez à niveau des nœuds dans un cluster sans commutateur à 2 nœuds, vous pouvez quitter le cluster sans commutateur tout en effectuant la mise à niveau. Il n'est pas nécessaire de les convertir en cluster commuté.



== Commutateurs connectés aux clusters

Si vous mettez à niveau des nœuds d'un cluster connecté à un commutateur de cluster, vous devez vérifier que la marque, le modèle, la version du firmware, le fichier RCF et la version de ONTAP exécutés sur le commutateur sont identiques à ceux exécutés sur le contrôleur de remplacement après la mise à niveau. Si nécessaire, vous devez effectuer la mise à niveau du commutateur avant de mettre à niveau les contrôleurs à l'aide de la procédure ARL décrite dans cette documentation.



== Résoudre les problèmes

En cas de problème lors de la mise à niveau des contrôleurs, reportez-vous à la link:troubleshoot_index.html["Résoudre les problèmes"] section à la fin de la procédure pour plus d'informations et des solutions possibles.

Si vous ne trouvez pas de solution au problème que vous rencontrez, contactez le support technique.
