---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 'Vérifiez que les LIF de données NAS du nœud 1 sur le nœud 2 sont déplacées du nœud 2 vers le nœud 1 lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Déplacement des agrégats non racines et des LIF de données NAS qui appartiennent au nœud 1 du nœud 2 vers le nœud mis à niveau 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Après avoir vérifié la configuration réseau sur le nœud 1 et avant de déplacer des agrégats du nœud 2 vers le nœud 1, vérifiez que les LIF de données NAS appartenant au nœud 1 qui se trouvent actuellement sur le nœud 2 sont déplacées du nœud 2 vers le nœud 1. Vous devez également vérifier que les LIFs SAN existent sur le noeud 1.

.Description de la tâche
Les LIF distantes gèrent le trafic vers des LUN SAN pendant la procédure de mise à niveau. Le déplacement des LIF SAN n'est pas nécessaire pour assurer l'intégrité du cluster ou du service pendant la mise à niveau. Les LIF SAN ne sont pas déplacées sauf si elles doivent être mappées sur de nouveaux ports. Une fois le nœud 1 mis en ligne, vous devez vérifier que les LIF sont saines et situées sur les ports appropriés.

.Étapes
. Reprendre l'opération de relocalisation :
+
`system controller replace resume`

+
Le système effectue les tâches suivantes :

+
--
** Vérification du quorum du cluster
** Vérification de l'ID système
** Vérification de la version d'image
** Vérification de la plate-forme cible
** Vérification de l'accessibilité du réseau


--
+
L'opération s'interrompt à cette étape de la vérification de la capacité d'accessibilité du réseau.

. Effectuez une vérification de l'accessibilité du réseau :
+
`network port reachability show -node node1`

+
Vérifiez que tous les ports connectés, y compris le groupe d'interfaces et les ports VLAN, affichent leur état comme `OK`.

. Pour une mise à niveau de AFF A800 vers AFF A70 ou AFF A90, vous devez réaffecter les LIF SAN FCP. Pour toutes les autres mises à niveau du système, passez à <<resume_relocation_step4,Étape 4>>:
+
.. Réaffectez les LIF SAN FCP utilisées pour l'accès aux données FCP ou FC-NVMe aux ports de base appropriés :
+
`network interface show -vserver <vserver_hosting_fcp_lifs>`

.. Pour les LIF avec le nœud actuel comme nœud mis à niveau 1 et le port actuel signale « status oper » comme « - » (car le port existait sur le nœud AFF A800 mais n'existe pas sur le nœud AFF A90), modifiez le port actuel avant de pouvoir le mettre en ligne.
+
Vérifier que la connectivité physique est établie sur le port FC target où le LIF FC doit être déplacé :

+
... Définir le statut de la LIF sur « down » :
+
`network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down`

... Modifier le home port de la LIF :
+
`network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>`

... Régler le statut de la LIF sur « UP » :
+
`network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up`





+
Répétez les sous-étapes a et b pour chaque LIF FC SAN qui est home sur le node1.

. [[resume_relocation_step4]]reprendre l'opération de déplacement :
+
`system controller replace resume`

+
Le système effectue les vérifications suivantes :

+
--
** Vérification de l'état du cluster
** Vérification de l'état de la LIF de cluster


--
+
Après ces vérifications, le système replace les agrégats non-racine et les LIF de données NAS qui appartiennent au nœud1 sur le nouveau nœud 1.

+
L'opération de remplacement du contrôleur s'interrompt une fois le transfert de ressources terminé.

. Vérifier le statut du transfert d'agrégats et du déplacement des LIF de données NAS :
+
`system controller replace show-details`

+
Si la procédure de remplacement du contrôleur est suspendue, vérifiez et corrigez l'erreur, le cas échéant, puis faites-la `resume` pour poursuivre l'opération.

. Si nécessaire, restaurez et restaurez les LIF déplacées. Lister les LIFs déplacées :
+
`cluster controller-replacement network displaced-interface show`

+
Si des LIF sont déplacées, restaurer le nœud de rattachement vers le nœud 1 :

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Reprenez l'opération pour demander au système d'effectuer les vérifications post-requises :
+
`system controller replace resume`

+
Le système effectue les vérifications suivantes :

+
** Vérification du quorum du cluster
** Vérification de l'état du cluster
** Vérification de la reconstruction d'agrégats
** Vérification de l'état de l'agrégat
** Vérification de l'état du disque
** Vérification de l'état de la LIF de cluster
** Vérification du volume



