---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware, old, system, chassis, disk, disks 
summary: 'Comprendre le fonctionnement de la procédure ARL qui permet de mettre à niveau les modèles de contrôleurs d"un même châssis.' 
---
= Présentation de la mise à niveau ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de mettre à niveau les nœuds à l'aide de l'ARL, il est important de connaître son fonctionnement. Dans ce contenu, la procédure est divisée en plusieurs étapes.



== Mettre à niveau la paire de nœuds

Pour mettre à niveau la paire de nœuds, vous devez préparer les nœuds d'origine, puis effectuer une série d'étapes sur les nœuds d'origine et nouveaux. Vous pouvez ensuite désaffecter les nœuds d'origine.



== Présentation de la séquence de mise à niveau ARL

Durant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, un contrôleur à la fois, en tirant parti de la configuration de paires haute disponibilité pour transférer la propriété d'agrégats non racines. Tous les agrégats non racines doivent être reloisés afin d'atteindre leur destination finale, qui est le nœud mis à niveau correct.

Chaque agrégat possède un propriétaire d'origine et un propriétaire actuel. Le propriétaire de la maison est le propriétaire réel de l'agrégat, et le propriétaire actuel est le propriétaire temporaire.

Le tableau ci-après décrit les tâches générales que vous effectuez à chaque étape ainsi que l'état de propriété de l'agrégat à la fin de cette étape. Les étapes détaillées sont fournies ultérieurement dans la procédure :

[cols="35,65"]
|===
| Étape | Étapes 


| link:stage_1_index.html["Étape 1 : préparer la mise à niveau"]  a| 
Au cours de l'étape 1, vous vérifiez que vous disposez du matériel approprié pour votre mise à niveau, exécutez des contrôles préalables et, si nécessaire, corrigez la propriété globale. Vous devez enregistrer certaines informations si vous gérez Storage Encryption à l'aide du gestionnaire de clés intégré et que vous pouvez choisir de suspendre les relations SnapMirror.

Propriété d'un agrégat à la fin de la phase 1 :

* NODE1 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 1
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2




| link:stage_2_index.html["Étape 2 : relocaliser les ressources et retirer le nœud 1"]  a| 
Au cours de la phase 2, vous déplacez les agrégats non racines du nœud 1 et les LIF de données NAS du nœud 1 vers le nœud 2. Ce processus est largement automatisé. L'opération s'interrompt pour vous permettre de vérifier son état. Vous devez reprendre l'opération manuellement. Si nécessaire, vous transférez des agrégats défaillants ou vetotés. Vous enregistrez les informations sur le noeud 1 pour les utiliser ultérieurement dans la procédure avant de retirer le noeud 1. Vous pouvez également préparer le nœud 1 plus tard dans la procédure.

Propriété d'un agrégat à la fin de la phase 2 :

* NODE2 est le propriétaire actuel des agrégats du nœud 1
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2




| link:stage_3_index.html["Etape 3 : démarrez le nœud 1 avec les modules système de remplacement"]  a| 
Au cours de l'étape 3, vous démarrez le nœud 1 avec les modules système mis à niveau et vérifiez l'installation du nœud 1 mis à niveau. Si vous utilisez NetApp Volume Encryption (NVE), vous restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer des agrégats non racines et des LIF de données NAS du nœud 2 vers le nœud mis à niveau 1, puis vérifier que des LIF SAN existent sur le nœud 1.

Propriété globale à la fin de la phase 3 :

* Le node1 mis à niveau est le propriétaire du home et le propriétaire actuel des agrégats node1
* NODE2 est le propriétaire du site et le propriétaire actuel des agrégats du nœud 2




| link:stage_4_index.html["Étape 4 : déplacer les ressources et retirer le nœud 2"]  a| 
Lors de la phase 4, vous transférez les agrégats non racines et les LIF de données NAS du nœud 2 vers le nœud mis à niveau 1, puis retirez le nœud 2.

Propriété globale à la fin de la phase 4 :

* Le nœud mis à niveau 1 est le propriétaire et le propriétaire actuel des agrégats qui appartenaient initialement au nœud 1
* Le nœud mis à niveau est le propriétaire actuel des agrégats du nœud 2




| link:stage_5_index.html["Étape 5 : installez les modules de rechange du système sur le nœud 2"]  a| 
Au cours de l'étape 5, vous installez les nouveaux modules système que vous avez reçus pour le node2 mis à niveau, puis netboot node2.

Propriété globale à la fin de la phase 5 :

* Le nœud mis à niveau 1 est le propriétaire initial et le propriétaire actuel des agrégats qui appartenaient à l'origine du nœud 1.
* Le nœud mis à niveau est le propriétaire du site et le propriétaire actuel des agrégats qui appartenaient initialement au nœud 2.




| link:stage_6_index.html["Etape 6 : démarrez le nœud 2 avec les modules système de remplacement"]  a| 
Au cours de l'étape 6, vous démarrez node2 avec des modules système mis à niveau et vérifiez l'installation du node2 mis à niveau. Si vous utilisez NVE, restaurez la configuration du gestionnaire de clés. Vous pouvez également transférer des agrégats non racines et des LIF de données NAS du nœud 1 vers le nœud 2 mis à niveau, puis vérifier que des LIF SAN existent sur le nœud 2.



| link:stage_7_index.html["Étape 7 : terminez la mise à niveau"]  a| 
Lors de la phase 7, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NVE. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

|===