---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1, NVRAM, controller, module, modules 
summary: 'Transférez les agrégats non racines du nœud 2 vers le nœud 1 lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Transférez des agrégats non racines et des LIF de données NAS du nœud 2 vers le nœud 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de remplacer le nœud 2 par le module système de remplacement, vous devez d'abord déplacer les agrégats non-racine qui appartiennent au nœud 2 vers le nœud 1.

.Avant de commencer
Une fois les post-contrôles effectués à partir de l'étape précédente, la version de ressource pour le noeud 2 démarre automatiquement. Les agrégats non-racines et les LIF de données non-SAN sont migrées depuis le nœud 2 vers le nouveau nœud 1.

.Description de la tâche
Une fois les agrégats et les LIF migrés, l'opération est interrompue à des fins de vérification. À ce stade, vous devez vérifier que tous les agrégats non racine et toutes les LIF de données non-SAN sont migrés vers le nouveau nœud 1.

Le propriétaire home des agrégats et des LIF n'est pas modifié ; seul le propriétaire actuel est modifié.

.Étapes
. Vérifier que tous les agrégats non racines sont en ligne et leur état sur le nœud 1 :
+
`storage aggregate show -node node1 -state online -root false`

+
L'exemple suivant montre que les agrégats non-racines sur le nœud 1 sont en ligne :

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	  #Vols	 Nodes	 RAID	  Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB     744.8GB	  0%	  online	  5	 node1   raid_dp  normal
aggr_2	      825.0GB	  825.0GB	  0%	  online	  1	 node1   raid_dp  normal
2 entries were displayed.
----
+
Si les agrégats ont été mis hors ligne ou sont devenus étrangers sur le nœud 1, les mettre en ligne en utilisant la commande suivante sur le nouveau nœud 1, une fois pour chaque agrégat :

+
`storage aggregate online -aggregate _aggr_name_`

. Vérifiez que tous les volumes sont en ligne sur le nœud 1 à l'aide de la commande suivante sur le nœud 1 et en examinant la sortie correspondante :
+
`volume show -node node1 -state offline`

+
Si un volume est hors ligne sur le nœud 1, mettez-le en ligne à l'aide de la commande suivante sur le nœud 1, une fois pour chaque volume :

+
`volume online -vserver _vserver-name_ -volume _volume-name_`

+
Le `_vserver-name_` pour utiliser cette commande avec cette commande, figure dans la sortie du précédent `volume show` commande.

. Vérifier que les LIFs ont été déplacées vers les ports appropriés et sont à l'état de `up`. Si l'un des LIFs est arrêté, définissez le statut administratif des LIFs sur `up` En saisissant la commande suivante, une fois pour chaque LIF :
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ - status-admin up`

. Vérifier qu'il n'y a pas de LIFs de données restantes sur le nœud2 en utilisant la commande suivante et en examinant le résultat :
+
`network interface show -curr-node _node2_ -role data`


