---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/restore_key_manager_config_upgraded_node1.html 
keywords: restore key-manager, configuration, node1, nve, arl, volume, encryption 
summary: 'Si nécessaire, restaurez la configuration du gestionnaire de clés sur le nœud 1 mis à niveau lors d"une mise à niveau de AFF A700 vers AFF A900.' 
---
= Restaurez la configuration du gestionnaire de clés sur le noeud mis à niveau 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous utilisez NetApp Aggregate Encryption (NAE) ou NetApp Volume Encryption (NVE) pour chiffrer des volumes sur le système que vous mettez à niveau, la configuration de chiffrement doit être synchronisée avec les nouveaux nœuds. Si vous ne resynchroniser pas le gestionnaire de clés, lorsque vous transférez les agrégats du nœud 1 depuis le nœud 2 vers le nœud mis à niveau 1 à l'aide du transfert d'agrégats, des défaillances peuvent se produire, car le nœud 1 ne dispose pas des clés de cryptage requises pour mettre en ligne des volumes et des agrégats chiffrés.

.Description de la tâche
Synchronisez la configuration de cryptage avec les nouveaux nœuds en effectuant les étapes suivantes :

.Étapes
. Exécutez la commande suivante depuis le nœud 1 :
+
`security key-manager onboard sync`

. Vérifier que la clé SVM-KEK est restaurée sur « true » sur le nœud1 avant de transférer les agrégats de données :
+
[listing]
----
::> security key-manager key query -node node1 -fields restored -key-type SVM-KEK
----
+
.Exemple
[listing]
----
::> security key-manager key query -node node1 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node1    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

