---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/restore_key_manager_config_node2.html 
keywords: restore key-manager, configuration, node1, nve, arl, volume, encryption 
summary: 'Si nécessaire, restaurez la configuration du gestionnaire de clés sur le nœud 2 lorsque vous utilisez l"ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Restaurez la configuration du gestionnaire de clés sur le noeud 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous utilisez NetApp Aggregate Encryption (NAE) ou NetApp Volume Encryption (NVE) pour chiffrer les volumes sur le système que vous mettez à niveau, la configuration de chiffrement doit être synchronisée avec les nouveaux nœuds. Si vous ne resynchroniser pas le gestionnaire de clés, lorsque vous transférez les agrégats du nœud 2 depuis le nœud mis à niveau 1 vers le nœud mis à niveau 2 à l'aide du transfert d'agrégats, des pannes peuvent se produire, car le nœud 2 ne dispose pas des clés de cryptage requises pour mettre en ligne les volumes et les agrégats chiffrés.

.Description de la tâche
Synchronisez la configuration de cryptage avec les nouveaux nœuds en effectuant les étapes suivantes :

.Étapes
. Exécutez la commande suivante depuis le nœud 2 :
+
`security key-manager onboard sync`

. Vérifier que la clé SVM-KEK est restaurée sur « true » sur le nœud2 avant de transférer les agrégats de données :
+
[listing]
----
::> security key-manager key query -node node2 -fields restored -key-type SVM-KEK
----
+
.Exemple
[listing]
----
::> security key-manager key query -node node2 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node2    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

