---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_7_index.html 
keywords: upgrade, authentication, storage, volume, aggregate, encryption, overview, stage 7 
summary: 'Séquence de processus de la phase 7 pour une mise à niveau ARL à l"aide de `system controller replace` commandes de mise à niveau des modèles de contrôleur dans le même châssis.' 
---
= Présentation de la phase 7
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la phase 7, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NetApp Volume Encryption. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

.Étapes
. link:manage-authentication-using-kmip-servers.html["Gérez l'authentification à l'aide de serveurs KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Vérifiez que les nouveaux contrôleurs sont correctement configurés"]
. link:set_up_storage_encryption_new_module.html["Configurez Storage Encryption sur le nouveau module de contrôleur"]
. link:set_up_netapp_volume_encryption_new_module.html["Configurez NetApp Volume Encryption ou Aggregate Encryption sur le nouveau module de contrôleur"]
. link:decommission_old_system.html["Désaffectation de l'ancien système"]
. link:resume_snapmirror_operations.html["Reprendre les opérations SnapMirror"]


[NOTE]
====
Les systèmes AFF A70 et AFF A90 partagent des ports réseau de 100 GbE pour les connexions au cluster et haute disponibilité. Ces systèmes peuvent prendre en charge des connexions de cluster 10 GbE ou 25 GbE avec les anciens switchs de cluster. Cependant, NetApp recommande de mettre à jour les vitesses de cluster 100 GbE lorsque les switchs 10 GbE et 25 GbE ne sont plus nécessaires. Pour plus d'informations, consultez les articles suivants de la base de connaissances :

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Comment configurer les ports de cluster 10G ou 25G sur une nouvelle configuration de cluster sur AFF/ASA A1K, A90, A70, FAS90, FAS70"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Comment convertir un cluster existant de ports de type 10 ou 25 Gbit/s en ports de cluster 40 Gbit/s ou 100 Gbit/s sur un système AFF/ASA A1K, A90, A70, FAS90, FAS70"^]


Si vous ne pouvez pas relier les ports e0a ou e0b du nœud existant aux ports de cluster du nouveau nœud, reportez-vous à la section link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["Bugs NetApp ID de bug en ligne CONTAP-166978"^].

====