---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_7_index.html 
keywords: upgrade, authentication, storage, volume, aggregate, encryption, overview, stage 7 
summary: 'Étape 1 : séquence de processus pour une mise à niveau d"ARL à l"aide de `system controller replace` commandes de mise à niveau des modèles de contrôleur dans le même châssis.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 7, vous vérifiez que les nouveaux nœuds sont correctement configurés et que, si les nouveaux nœuds sont activés pour le chiffrement, vous configurez et configurez Storage Encryption ou NetApp Volume Encryption. Vous devez également désaffecter les anciens nœuds et reprendre les opérations SnapMirror.

.Étapes
. link:manage-authentication-using-kmip-servers.html["Gérez l'authentification à l'aide de serveurs KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Vérifiez que les nouveaux contrôleurs sont correctement configurés"]
. link:set_up_storage_encryption_new_module.html["Configurez Storage Encryption sur le nouveau module de contrôleur"]
. link:set_up_netapp_volume_encryption_new_module.html["Configurez NetApp Volume Encryption ou Aggregate Encryption sur le nouveau module de contrôleur"]
. link:decommission_old_system.html["Désaffectation de l'ancien système"]
. link:resume_snapmirror_operations.html["Reprendre les opérations SnapMirror"]

