---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Avant de commencer la mise à niveau, vérifiez que vous disposez du matériel approprié pour mettre à niveau les modèles de contrôleurs dans le même châssis. 
---
= Vérifiez la mise à niveau matérielle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant de commencer la mise à niveau, vérifiez que vous disposez des modules appropriés pour votre système de remplacement. Si certaines pièces sont manquantes, contactez le support technique ou votre ingénieur commercial NetApp pour obtenir de l'aide.

[cols="50,50"]
|===
| Si vous mettez à niveau à partir de ... | Le système de remplacement doit avoir ... 


| AFF A250, AFF C250 | Deux modules de contrôleur et de nouveaux modules d'E/S. 


| AFF A800, AFF C800 | Deux modules de contrôleur, deux NVRAMS et de nouveaux modules d'E/S. 


 a| 
* AFF A220 configuré en tant que ASA
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720

 a| 
Deux modules de contrôleur

Si vous convertissez un système en tiroir de stockage et que vous pouvez le connecter à un autre système, le système de remplacement doit également disposer de deux modules d'E/S.



 a| 
* AFF A700 configuré en tant que ASA
* AFF A700
* FAS9000

| Deux contrôleurs et deux modules NVRAM 
|===