---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Avant de commencer la mise à niveau, vérifiez que vous disposez du matériel approprié pour mettre à niveau les modèles de contrôleurs dans le même châssis. 
---
= Vérifiez la mise à niveau matérielle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de commencer la mise à niveau, vérifiez que vous disposez du matériel approprié pour votre mise à niveau. En fonction de votre mise à niveau, vous devez disposer de deux modules de contrôleur ou de deux modules de contrôleur et de deux modules NVRAM pour chaque paire haute disponibilité mise à niveau. Si certaines pièces sont manquantes, contactez le support technique ou votre ingénieur commercial NetApp pour obtenir de l'aide.

[cols="50,50"]
|===
| Si vous mettez à niveau ... | Vous devez avoir ... 


| AFF A220 configuré en tant que ASA vers ASA A150 | Deux modules de contrôleur 


| AFF A220, AFF A200 ou AFF C190 vers AFF A150 | Deux modules de contrôleur 


| FAS2620 ou FAS2720 à FAS2820 | Deux modules de contrôleur 


| AFF A700 configuré en tant que ASA vers ASA A900 | Deux contrôleurs et deux modules NVRAM 


| DE AFF A700 À AFF A900 | Deux contrôleurs et deux modules NVRAM 


| FAS9000 vers FAS9500 | Deux contrôleurs et deux modules NVRAM 
|===