---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, NVRAM, controller, module, modules 
summary: 'Vérifiez l"installation du nœud 1 avec les modules de remplacement lorsque vous utilisez ARL pour mettre à niveau les modèles de contrôleurs du même châssis.' 
---
= Vérifiez l'installation du noeud 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après avoir initialisé le nœud 1 avec le module de contrôleur de remplacement, vérifiez qu'il est correctement installé.

Pour les mises à niveau de AFF A800 uniquement, vous mappez les ports physiques du nœud 1 existant vers le nœud de remplacement 1, car les ports physiques changent entre le contrôleur AFF A800 et le contrôleur AFF A90 ou AFF A70.

Pour toutes les autres mises à niveau, il n'y a pas de modification des ports physiques, vous n'êtes donc pas tenu de mapper les ports physiques de l'ancien nœud 1 au nœud de remplacement 1.

.Description de la tâche
Vous devez patienter jusqu'à ce que le nœud 1 rejoint le quorum, puis reprendre l'opération de remplacement du contrôleur.

À ce stade de la procédure, l'opération de mise à niveau du contrôleur doit avoir été interrompue au moment où le nœud1 tente de rejoindre automatiquement le quorum.

.Étapes
. Vérifiez que le noeud 1 a rejoint le quorum :
+
`cluster show -node node1 -fields health`

+
La sortie du `health` ce champ doit être de `true`.

. Vérifiez que le noeud 1 fait partie du même cluster que le noeud 2 et qu'il est en bon état :
+
`cluster show`

+
[NOTE]
====
Si le nœud 1 n'a pas rejoint le quorum après le démarrage, attendez cinq minutes et vérifiez à nouveau. Selon la connexion au cluster, l'analyse de l'accessibilité des ports peut prendre un certain temps pour terminer et déplacer les LIF vers leurs ports de base respectifs.

Si le nœud 1 n'est toujours pas au quorum après cinq minutes, vous pouvez modifier le port de cluster du nouveau nœud en le plaçant dans « Cluster ipspace » à l'aide de la commande de privilège de diagnostic `network port modify <port_name> -ipspace Cluster`.

====
. Passer en mode privilège avancé :
+
`set advanced`

. Vérifier l'état de l'opération de remplacement du contrôleur et vérifier qu'elle est en pause et dans le même état qu'avant l'arrêt du nœud 1 pour effectuer les tâches physiques liées à l'installation de nouveaux contrôleurs et au déplacement des câbles :
+
`system controller replace show`

+
`system controller replace show-details`

. Reprendre l'opération de remplacement du contrôleur :
+
`system controller replace resume`

. L'opération de remplacement du contrôleur s'interrompt pour une intervention et affiche le message suivant :
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: Dans cette procédure, la section _Re-création de VLAN, ifgrps et broadcast domain_ a été renommée _Restore network configuration sur node1_.

. Lorsque le remplacement du contrôleur est en pause, passer à <<Restaurez la configuration réseau sur le noeud 1>>.




== Restaurez la configuration réseau sur le noeud 1

Une fois que vous avez confirmé que le nœud1 est dans le quorum et peut communiquer avec le nœud2, vérifiez que les VLAN, les groupes d'interface et les domaines de diffusion du nœud1 sont visibles sur le nœud1. Vérifiez également que tous les ports réseau du nœud1 sont configurés dans leurs domaines de diffusion appropriés.

.Description de la tâche
Pour plus d'informations sur la création et la recrércréation de VLAN, de groupes d'interfaces et de domaines de diffusion, reportez-vous à la section link:other_references.html["Références"] Pour créer un lien vers le contenu _Network Management_.

.Étapes
. Lister tous les ports physiques qui se trouvent sur le nœud mis à niveau 1 :
+
`network port show -node node1`

+
Tous les ports réseau physique, les ports VLAN et les ports de groupe d'interfaces sur le nœud sont affichés. À partir de cette sortie, vous pouvez voir tous les ports physiques qui ont été déplacés dans le `Cluster` Broadcast domain par ONTAP. Vous pouvez utiliser cette sortie pour décider des ports à utiliser comme ports membres de groupe d'interface, ports de base VLAN ou ports physiques autonomes pour l'hébergement des LIFs.

. Lister les rebroadcast domain sur le cluster :
+
`network port broadcast-domain show`

. Lister la possibilité de port réseau de tous les ports du node1 :
+
`network port reachability show -node node1`

+
La sortie doit s'afficher comme dans l'exemple suivant :

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
Dans les exemples précédents, le nœud 1 a démarré après le remplacement du contrôleur. Les ports qui affichent « pas d'accessibilité » n'ont pas de connectivité physique. Vous devez réparer tous les ports dont l'état d'accessibilité est autre que `ok`.

+

NOTE: Pendant la mise à niveau, les ports réseau et leur connectivité ne doivent pas changer. Tous les ports doivent résider dans les domaines de diffusion appropriés et la capacité de port réseau ne doit pas changer. Toutefois, avant de déplacer les LIF du nœud 2 vers le nœud 1, vous devez vérifier l'état d'accessibilité et de santé des ports réseau.

. [[restore_node1_step4]]réparer l'accessibilité pour chacun des ports sur le noeud 1 avec un état de réabilité autre que `ok` en utilisant la commande suivante, dans l'ordre suivant :
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. Ports physiques
.. Ports VLAN


--
+
La sortie doit s'afficher comme dans l'exemple suivant :

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e1b
----
+
[listing]
----
Warning: Repairing port "node1:e1b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
Un message d'avertissement, tel qu'illustré dans l'exemple précédent, est attendu pour les ports dont l'état d'accessibilité peut être différent de l'état d'accessibilité du domaine de diffusion où il se trouve actuellement. Vérifiez la connectivité du port et la réponse `y` ou `n` selon les besoins.

+
Vérifier que tous les ports physiques ont leur capacité d'accessibilité attendue :

+
`network port reachability show`

+
Au fur et à mesure que la réparation de l'accessibilité est effectuée, ONTAP tente de placer les ports dans les domaines de diffusion appropriés. Toutefois, si la capacité de réachbilité d’un port ne peut être déterminée et n’appartient à aucun des domaines de diffusion existants, ONTAP créera de nouveaux domaines de diffusion pour ces ports.

. Vérifiez l'accessibilité des ports :
+
`network port reachability show`

+
Lorsque tous les ports sont correctement configurés et ajoutés aux domaines de diffusion appropriés, le `network port reachability show` la commande doit indiquer l'état de la capacité d'accessibilité `ok` pour tous les ports connectés et l'état en tant que `no-reachability` pour les ports sans connectivité physique. Si un port signale un état autre que ces deux, effectuez la réparation de la capacité d'accès et ajoutez ou supprimez des ports de leurs domaines de diffusion comme indiqué dans <<restore_node1_step4,Étape 4>>.

. Vérifier que tous les ports ont été placés dans des domaines de diffusion :
+
`network port show`

. Vérifiez que l'unité de transmission maximale (MTU) correcte est configurée pour tous les ports des domaines de diffusion :
+
`network port broadcast-domain show`

. Restaurer les ports de base LIF, en précisant les ports de base Vserver et LIF, le cas échéant, à restaurer à l'aide des étapes suivantes :
+
.. Lister les LIFs déplacées :
+
`displaced-interface show`

.. Restaurer les home node LIF et les ports home ports :
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. Vérifier que toutes les LIF disposent d'un port d'origine et sont administrativement en service :
+
`network interface show -fields home-port,status-admin`


