---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/get_address_key_management_server_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 'Configurez le cryptage du stockage lors d"une mise à niveau manuelle du transfert d"agrégats sur des contrôleurs exécutant ONTAP 9.8 ou une version ultérieure.' 
---
= Obtenir l'adresse IP d'un serveur de gestion externe des clés pour Storage Encryption
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Une fois la mise à niveau effectuée, vous devez immédiatement configurer Storage Encryption et établir une clé d'authentification au niveau du cluster pour remplacer les clés d'authentification précédentes au niveau du nœud.

.Étapes
. Installez les certificats SSL (Secure sockets layer) client et serveur nécessaires pour communiquer avec les serveurs de gestion des clés :
+
`security certificate install`

. Configurez Storage Encryption sur tous les nœuds à l'aide de la commande suivante sur chaque nœud :
+
`security key-manager setup`

. Ajouter l'adresse IP de chaque serveur de gestion des clés :
+
`security key-manager add`

. Vérifiez que les mêmes serveurs de gestion des clés sont configurés et disponibles sur tous les nœuds du cluster :
+
`security key-manager show -status`

. Créer une nouvelle clé d'authentification au niveau du cluster :
+
`security key-manager create-key`

. Notez le nouvel ID de clé d'authentification.
. ReKey tous les disques à autochiffrement grâce à la nouvelle clé d'authentification :
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`


