---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: En utilisant la procédure manuelle de mise à niveau du ARL pour mettre à niveau le matériel des contrôleurs sous ONTAP 9.8 ou version ultérieure, relocaliser la propriété des agrégats non racines. 
---
= En savoir plus sur cette procédure de mise à niveau ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette procédure décrit comment mettre à niveau le matériel du contrôleur à l'aide de la relocalisation manuelle des agrégats (ARL) sur les systèmes exécutant ONTAP 9.8 ou version ultérieure.

Vous pouvez utiliser cette procédure ARL si vous effectuez l’une des mises à niveau suivantes :

* Du système FAS au système FAS
* Du système AFF au système AFF
+
Vous pouvez uniquement mettre à niveau vers un système de remplacement de la même série :

+
** Du système AFF A-Series au système AFF A-Series
** Du système AFF C-Series au système AFF C-Series


* Du système ASA au système ASA
+
Les mises à niveau ASA vers un système de remplacement ASA r2 ne sont pas prises en charge. Pour plus d'informations sur la migration des données de ASA vers ASA r2, reportez-vous à link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Activez l'accès aux données depuis des hôtes SAN vers votre système de stockage ASA r2"^]la section .

+
Vous pouvez uniquement mettre à niveau vers un système de remplacement de la même série :

+
** Du système ASA A-Series au système ASA A-Series
** Du système ASA C-Series au système ASA C-Series




Pendant la procédure, vous mettez à niveau le matériel du contrôleur d'origine avec le matériel de remplacement, délocalisant ainsi la propriété des agrégats non racines. Vous migrez plusieurs fois des agrégats entre nœuds et nœuds pour confirmer qu'au moins un nœud transmet des données depuis les agrégats tout au long de la procédure de mise à niveau. Vous migrez également les interfaces de données logiques (LIF) et vous affectez les ports réseau sur le nouveau contrôleur aux groupes d'interface.


NOTE: Dans ce document, les nœuds d'origine sont appelés _node1_ et _node2_, et les nouveaux nœuds sont appelés _node3_ et _node4_.  Au cours de la procédure décrite, le nœud 1 est remplacé par le nœud 3 et le nœud 2 est remplacé par le nœud 4.  Les termes _node1_, _node2_, _node3_ et _node4_ sont utilisés uniquement pour distinguer les nœuds d'origine et les nouveaux nœuds.  Lorsque vous suivez la procédure, vous devez remplacer les vrais noms de vos nœuds d'origine et nouveaux.  Cependant, en réalité, les noms des nœuds ne changent pas : le nœud 3 porte le nom de nœud 1 et le nœud 4 porte le nom de nœud 2 après la mise à niveau du matériel du contrôleur.

.Information importante :
* Cette procédure est complexe et suppose que vous avez des compétences avancées en administration de ONTAP. Vous devez également lire et comprendre le link:guidelines_upgrade_with_arl.html["directives pour la mise à niveau des contrôleurs avec ARL"] et le link:arl_upgrade_workflow.html["Workflow de mise à niveau ARL"] avant de commencer la mise à niveau.
* Cette procédure suppose que le matériel de remplacement du contrôleur est nouveau et qu'il n'a pas été utilisé. Étapes requises pour préparer les contrôleurs utilisés avec le `wipeconfig` la commande n'est pas incluse dans cette procédure. Vous devez contacter le support technique si le matériel de remplacement du contrôleur était précédemment utilisé, en particulier si les contrôleurs exécutaient Data ONTAP sous 7-mode.
* Vous pouvez suivre cette procédure pour mettre à niveau le matériel du contrôleur dans des clusters de plus de deux nœuds. Toutefois, vous devez effectuer la procédure séparément pour chaque paire haute disponibilité du cluster.


* En plus des configurations non MetroCluster, cette procédure s'applique aux configurations Fabric MetroCluster à quatre et huit nœuds qui exécutent ONTAP 9.8 et versions ultérieures.
+
** Pour les configurations MetroCluster exécutant ONTAP 9.7 ou version antérieure, rendez-vous sur link:other_references.html["Références"] Pour établir un lien vers _en utilisant le transfert d'agrégats pour mettre à niveau manuellement le matériel du contrôleur exécutant ONTAP 9.7 ou une version antérieure_.
** Pour les configurations MetroCluster IP et les options de mise à niveau supplémentaires pour les configurations Fabric MetroCluster, rendez-vous sur link:other_references.html["Références"] Pour accéder au contenu _MetroCluster Upgrade and expansion_.



