---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/manage_authentication_okm.html 
keywords: manage, authentication, onboard key manager, okm, key, passphrase, fips 
summary: 'Utilisez un gestionnaire de clés intégré pour gérer les clés d"authentification lors d"une mise à niveau manuelle du transfert d"agrégats (ARL) sur les contrôleurs exécutant ONTAP 9.8 ou une version ultérieure.' 
---
= Gérez l'authentification à l'aide d'un gestionnaire de clés intégré
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser un gestionnaire de clés intégré pour gérer les clés d'authentification. Si vous prévoyez d'utiliser un gestionnaire de clés intégré (OKM), vous devez enregistrer la phrase de passe et les supports de sauvegarde avant de commencer la mise à niveau.

.Étapes
. Vérifiez que les serveurs de gestion des clés sont disponibles pour tous les nœuds du cluster :
+
`security key-manager key show`

. ReKey tous les disques avec autocryptage à l'aide de la nouvelle clé d'authentification :
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK>]`

. Si vous utilisez la norme FIPS (Federal information Processing Standard), ressaisissez tous les disques auto-cryptés à l'aide de la nouvelle clé d'authentification :
+
`storage encryption disk* modify -disk * [-fips-key-id nonMSID AK]`


