---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: 'Vous pouvez configurer les ports FC intégrés des nœuds node4, les ports UTA/UTA2 ou la carte UTA/UTA2 lors d"une mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.8 ou version ultérieure.' 
---
= Définissez la configuration FC ou UTA/UTA2 sur le nœud 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si le système Node4 est doté de ports FC intégrés, de ports UTA/UTA2 (ou d'une carte UTA/UTA2), vous devez configurer les paramètres avant de suivre la procédure.

.Description de la tâche
Vous devrez peut-être compléter<<Configurez les ports FC sur le nœud 4>> ou<<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>> , ou les deux sections.

Si le nœud 4 ne dispose pas de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2 (par exemple, les systèmes AFF et FAS introduits à partir d' ONTAP 9.15.1) et que vous mettez à niveau un système avec des disques de stockage, vous pouvez passer àlink:map_ports_node2_node4.html["Mappage des ports du node2 au node4"] .

Cependant, si vous disposez d'un système V-Series ou d'un logiciel de virtualisation FlexArray et que vous êtes connecté aux baies de stockage, et que le nœud 4 n'est pas équipé de ports FC intégrés, de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2, vous devez revenir à la section _Install and Boot node4_, puis reprendre le processus à l'adresse link:install_boot_node4.html#man_install4_Step9["Étape 9"]. Assurez-vous que le noeud 4 dispose d'un espace de rack suffisant. Si le noeud 4 se trouve dans un châssis distinct du noeud 2, vous pouvez placer le noeud 4 au même emplacement que le noeud 3. Si les nœuds 2 et 4 se trouvent dans le même châssis, le nœud 4 se trouve déjà dans son emplacement de rack approprié.



== Configurez les ports FC sur le nœud 4

Si le nœud 4 possède des ports FC intégrés ou sur un adaptateur FC, vous devez définir des configurations de ports sur le nœud avant de le mettre en service, car les ports ne sont pas préconfigurés. Si les ports ne sont pas configurés, le service peut subir une interruption.

.Avant de commencer
Vous devez avoir les valeurs des paramètres du port FC du noeud 2 que vous avez enregistrées dans la section link:prepare_nodes_for_upgrade.html["Préparer les nœuds pour une mise à niveau"].

.Description de la tâche
Vous pouvez ignorer cette section si votre système ne dispose pas de configurations FC. Si votre système est équipé de ports UTA/UTA2 intégrés ou d'un adaptateur UTA/UTA2, vous devez les configurer dans <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>>.


IMPORTANT: Entrez les commandes de cette section à l’invite du cluster.

.Étapes
. Afficher des informations sur tous les adaptateurs réseau FC et convergés du système :
+
`system node hardware unified-connect show`

. Comparez les paramètres FC des nouveaux nœuds avec les paramètres que vous avez précédemment définis à partir du nœud d'origine.
. Modifier les ports FC sur le nœud 4 si nécessaire :
+
** Pour programmer les ports cibles :
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Pour programmer les ports initiateurs :
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` Est le type, la cible ou l'initiateur FC4.



. Vérifiez les nouveaux paramètres en entrant la commande suivante et en examinant la sortie :
+
`system node unified-connect show`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les paramètres FC par défaut sont définis sur les nouveaux nœuds... | Puis… 


| Identique à ceux que vous avez capturés sur les noeuds d'origine | Aller à<<man_config_4_Step9,Étape 9>> . 


| Différent de ceux que vous avez capturés sur les nœuds d'origine | Aller à<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]Quitter le mode Maintenance :
+
`halt`

. Une fois la commande saisie, attendez que le système s'arrête à l'invite de l'environnement de démarrage.
. Démarrez node4 en entrant la commande suivante à l’invite de l’environnement de démarrage :
+
`boot_ontap`

. [[man_config_4_Step9]]Effectuez l’une des actions suivantes :
+
** Accédez à <<Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4>> Si le nœud 4 est doté d'une carte UTA/UTA2A ou de ports intégrés UTA/UTA2.
** Ignorez la section et accédez à link:map_ports_node2_node4.html["Mappage des ports du node2 au node4"] Si le nœud Node4 ne est pas doté d'une carte UTA/UTA2 ou de ports intégrés UTA/UTA2.






== Vérifiez et configurez les ports UTA/UTA2 sur le nœud 4

Si le NODE4 dispose de ports UTA/UTA2 intégrés ou d'une carte UTA/UTA2A, vous devez vérifier la configuration des ports et les configurer, en fonction de votre mode d'utilisation du système mis à niveau.

.Avant de commencer
Vous devez disposer des modules SFP+ appropriés pour les ports UTA/UTA2.

.Description de la tâche
Les ports UTA/UTA2 peuvent être configurés en mode FC natif ou UTA/UTA2A. Le mode FC prend en charge les initiateurs FC et la cible FC ; le mode UTA/UTA2 permet d'utiliser simultanément les cartes réseau et le trafic FCoE pour partager la même interface SFP+ 10 GbE et prend en charge la cible FC.


NOTE: Les documents marketing NetApp peuvent utiliser le terme UTA2 pour faire référence aux adaptateurs et ports CNA. Cependant, l'interface de ligne de commandes utilise le terme CNA.

Les ports UTA/UTA2 peuvent être situés sur un adaptateur ou sur le contrôleur dans les configurations suivantes :

* Les cartes UTA/UTA2 commandées en même temps que le contrôleur sont configurées avant l'expédition pour obtenir la personnalité demandée.
* Les cartes UTA/UTA2 commandées séparément du contrôleur sont fournies avec la personnalité de la cible FC par défaut.
* Les ports UTA/UTA2 intégrés dans les nouveaux contrôleurs sont configurés (avant l'expédition) pour utiliser le profil demandé.


Toutefois, vous pouvez vérifier la configuration des ports UTA/UTA2 sur le nœud 4 et la modifier si nécessaire.


WARNING: Saisissez les commandes de cette section à l’invite du cluster, sauf si vous êtes invité à entrer en mode Maintenance.  Si vous disposez d'un système MetroCluster FC, vous devez être en mode Maintenance pour configurer les ports UTA/UTA2.

.Étapes
. Vérifiez comment les ports sont actuellement configurés sur node4 :
+
`system node hardware unified-connect show`

. Si le module SFP+ actuel ne correspond pas à l'utilisation souhaitée, remplacez-le par le module SFP+ approprié.
+
Contactez votre ingénieur commercial NetApp pour obtenir le module SFP+ approprié.

. Examiner la sortie du `system node hardware unified-connect show` ou `ucadmin show` Déterminez si les ports UTA/UTA2 ont le profil souhaité.
. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si les ports CNA... | Alors... 


| N'avez pas la personnalité que vous voulez | Accédez à <<man_check_4_Step5,Étape 5>>. 


| Avoir la personnalité que vous voulez | Passez aux étapes 5 à 12 et passez à <<man_check_4_Step13,Étape 13>>. 
|===
. [[man_check_4_Step5]]Si le système dispose de disques de stockage et exécute Data ONTAP 8.3, démarrez node4 et entrez en mode maintenance :
+
`boot_ontap maint`

. Vérifiez les paramètres en saisissant la commande suivante et en examinant la sortie correspondante :
+
`ucadmin show`

. Effectuer l'une des actions suivantes :
+
[cols="35,65"]
|===
| Si vous configurez... | Alors... 


| Ports sur une carte UTA/UTA2A | Aller à<<man_check_4_Step8,Étape 8>> . 


| Ports UTA/UTA2 intégrés | Sautez l'étape 8 et passez à<<man_check_4_Step9,Étape 9>> . 
|===
. [[man_check_4_Step8]]Si l'adaptateur est en mode initiateur et si le port UTA/UTA2 est en ligne, mettez le port UTA/UTA2 hors ligne :
+
`storage disable adapter _adapter_name_`

+
Les adaptateurs en mode cible sont automatiquement hors ligne en mode maintenance.

. [[man_check_4_Step9]]Si la configuration actuelle ne correspond pas à l'utilisation souhaitée, entrez la commande suivante pour modifier la configuration selon vos besoins :
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Est le mode Personality : carte UTA FC ou 10GbE
** `-t` Est le type FC4 : cible ou initiateur.


+

NOTE: Vous devez utiliser l'initiateur FC pour les lecteurs de bande et la cible FC pour les clients SAN.

. Si le système dispose de disques de stockage, entrez la commande suivante :
+
`halt`

+
Le système s'arrête à l'invite de l'environnement d'amorçage.

+
.. Saisissez la commande suivante :
+
`boot_ontap`



. Si le système dispose de disques de stockage, entrez la commande suivante :
+
`system node hardware unified-connect show`

+
Le résultat des exemples suivants montre que le type FC4 d'adaptateur « 1b » passe à `initiator` et que le mode des adaptateurs « 2a » et « 2b » passe à `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. Placez n'importe quel port cible en ligne en entrant l'une des commandes suivantes, une fois pour chaque port :
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_4_Step13]]câble du port.

