---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/stage_3_index.html 
keywords: relocate, retire, node1, steps, stage 3 
summary: 'Étape 3 : processus de mise à niveau manuelle d"ARL sur les contrôleurs exécutant ONTAP 9.8 ou une version ultérieure' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la phase 3, vous installez et démarrez le nœud 3, mappez le cluster et les ports de gestion des nœuds du nœud 1 vers le nœud 3, puis déplacez les LIF de données et les LIF SAN appartenant au nœud 1 du nœud 2 vers le nœud 3. Vous transférez également tous les agrégats du nœud 2 vers le nœud 3, et déplacez les LIF de données et les LIF SAN qui appartiennent au nœud 2 vers le nœud 3.

.Étapes
. link:install_boot_node3.html["Installez et démarrez le nœud 3"]
. link:set_fc_uta_uta2_config_node3.html["Définissez la configuration FC ou UTA/UTA2 sur le nœud 3"]
. link:map_ports_node1_node3.html["Mapper les ports du node1 vers le node3"]
. link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["Déplacez les LIF de données NAS qui appartiennent au nœud 1, du nœud 2 au nœud 3, et vérifiez les LIF SAN sur le nœud 3"]
. link:relocate_non_root_aggr_node2_node3.html["Transférer des agrégats non racines du nœud 2 vers le nœud 3"]
. link:move_nas_lifs_node2_node3.html["Déplacez les LIF de données NAS qui appartiennent au nœud 2 vers le nœud 3"]

