---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/troubleshoot_index.html 
keywords: troubleshoot, failure, aggregate, relocate, lifs 
summary: 'Diagnostiquez les défaillances qui peuvent se produire lors d"une mise à niveau manuelle du transfert d"agrégats qui exécutent ONTAP 9.8 ou une version ultérieure.' 
---
= Résoudre les problèmes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez être confronté à une défaillance lors de la mise à niveau de la paire de nœuds. Il est possible que le nœud tombe en panne, mais que les agrégats ne soient pas transférés ou que les LIF ne migrent pas. La cause de l'échec et sa solution dépendent du moment où l'échec s'est produit pendant la procédure de mise à niveau.

Se référer au tableau décrivant les différentes phases de la procédure dans la section link:arl_upgrade_workflow.html["Workflow de mise à niveau ARL"]. Les informations relatives aux défaillances pouvant survenir sont répertoriées par la phase de la procédure.

* link:aggregate_relocation_failures.html["Défaillance du transfert d'agrégats"]
* link:reboots_panics_power_cycles.html["Redémarre, fonctionne de façon incohérente ou fonctionne tout cycle d'alimentation"]
* link:issues_multiple_stages_of_procedure.html["Problèmes pouvant survenir à plusieurs étapes de la procédure"]
* link:lif_migration_failure.html["Échec de la migration de LIF"]
* link:lifs_invalid_ports_after_upgrade.html["Après la mise à niveau, les LIFs se trouvent sur des ports non valides"]

