---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/worksheet_information_before_moving_san_lifs_node3.html 
keywords: worksheet, information, SAN, LIF, switch, port, adapter 
summary: 'Enregistrez les informations de configuration LIF de données NAS du nœud1 lors d"une mise à niveau manuelle du ARL sur les contrôleurs exécutant ONTAP 9.8 ou une version ultérieure.' 
---
= Fiche : informations à enregistrer avant de déplacer les LIF de données NAS vers le nœud 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour vous aider à vérifier que vous disposez de la configuration correcte après le déplacement des LIF SAN du nœud 2 vers le nœud 3, vous pouvez utiliser la fiche de travail suivante pour enregistrer le `adapter` et `switch-port` Informations pour chaque LIF.

Enregistrer la LIF `adapter` informations du `network interface show -data-protocol fc*` la sortie de la commande et le `switch-port` informations du `fcp adapter show -fields switch-port,fc-wwpn` sortie de la commande pour le nœud 2.

Une fois la migration vers le nœud 3 terminée, enregistrez le LIF `adapter` et `switch-port` Informations relatives aux LIF sur le nœud 3 et vérifier que chaque LIF est toujours connectée à la même `switch-port`.

[cols="6*"]
|===
3+| Nœud 2 3+| Nœud 3 


| LIF | `adapter` | `switch-port` | LIF | `adapter` | `switch-port` 


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  


|  |  |  |  |  |  
|===